### ISSUE TITLE
Firebase cloud message in background

### ISSUE THREAD

**Issue by ProstakovAlexey** [firebase/quickstart-android#1003]
I add in my application example code (https://github.com/firebase/quickstart-android/blob/40f0620d8ef0d47d08c842c4ba362cea32eda53d/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MainActivity.java)  to manifest  and main Activity: 
`if (getIntent().getExtras() != null) {
            for (String key : getIntent().getExtras().keySet()) {
                Object value = getIntent().getExtras().get(key);
                Log.d(TAG, "Key: " + key + " Value: " + value);
            }
        }`
If my application is off, push show in android notification area. I click notification and my application running, this code is work and in catlog I see:
`Key: google.delivered_priority Value: high
 Key: google.sent_time Value: 1574676519718
 Key: google.ttl Value: 2419200
 Key: google.original_priority Value: high
 Key: from Value: 69200725691
 Key: google.message_id Value: 0:1574676519766851%7139185571391855
 Key: collapse_key Value: ru.ittest.freezio_senser
`
Can you add in your example code, how find message bode, titlle and image uri with this keys. Thank you so much, for your  work, example work perfect.

**Comment by kroikie** [comment]
Hi @ProstakovAlexey the title body and image is not available when the user taps on the notification. If you want to get that data you will have to add it to the "data" payload of the message you are sending.

**Comment by ProstakovAlexey** [comment]
Arthur, thank you for answer. Now I use payload (add in firebase console)
![Выделение_072](https://user-images.githubusercontent.com/16253795/69614050-92cd4200-1043-11ea-9342-f7865f6b5420.png) and it work.
