### ISSUE TITLE
Android notification does not contain data when the app is asleep

### ISSUE THREAD

**Issue by NicholasIoanJones** [firebase/quickstart-android#1004]
Android: 9
React-Native-Firebase: 5.5.6
Our server sends messages to our application which of course may or may not be asleep.

If awake the application (onNotification) processes the notification and the data is available in the extras field of the notification.
However, if the app is asleep when the notification is received and we then process notificationsManager.getActiveNotifications() then statusBarNotification.getNotification returns an object with extras, but the fields from the data part of the push notification are not present.

Our application needs to process this data, whether it is awake or asleep when the PN is received. What are we doing wrong?

**Comment by samtstern** [comment]
@kroikie ever heard of something like this?
@NicholasIoanJones this sounds like it might be a react native issue, as far as I know backgrounded RN apps don't behave exactly the same as backgrounded native Android apps.  Have you tried asking the RNFirebase people about this?

**Comment by kroikie** [comment]
@samtstern You are correct.

@NicholasIoanJones I would start by filing an issue with the [RNFirebase repo](https://github.com/invertase/react-native-firebase/issues/new/choose). They will likely have the answer you are looking for.

**Comment by NicholasIoanJones** [comment]
It is not a RN issue as we have extended the RN code to getActiveNotifications (android function) and this does not contain the data from the push notification. At this point in the lifecycle of the push notification, only android has dealt with the message, RN has not even seen it

**Comment by kroikie** [comment]
Hi @NicholasIoanJones `getActiveNotifications` is not a function defined by Firebase SDK. Could you point to the function you are extending?

**Comment by NicholasIoanJones** [comment]
@kroikie So we have an app with chatrooms and when we open the chatroom on the app we want to clear any Android Notifications related to that chatroom. We were struggling so in the end cloned RNFirebaseNotificationManager.removeDeliveredNotificationsByTag and called it removeDeliveredNotificationsByChatroom 
Our expectation was that as we iterated through the statusBarNotifications from notificationManager.getActiveNotification then we could check the extras on the notification to find the ones with the right chatroom and cancel them.
At this point this is all java code running native Android API's - we just happen to be doing it through a RN app, but I don't see why RN would affect this

**Comment by kroikie** [comment]
The notifications you get from `notificationManager.getActiveNotifications` are not managed by Firebase so I can't say what extras would be on those notifications. If you could point me to the RNFirebaseNotificationManager class that you extended I could take a closer look.

**Comment by NicholasIoanJones** [comment]
https://rnfirebase.io/docs/v5.x.x/notifications/ios
https://github.com/invertase/react-native-firebase

**Comment by kroikie** [comment]
@NicholasIoanJones thanks for those links, I've looked but I'm not seeing the `getActiveNotifications` method. If you could point me to that I'll take a look.

**Comment by NicholasIoanJones** [comment]
@kroikie sorry, that is a native android method in https://developer.android.com/reference/android/app/NotificationManager

**Comment by kroikie** [comment]
@NicholasIoanJones I see the method you are asking about.

From your expectation

> Our expectation was that as we iterated through the statusBarNotifications from notificationManager.getActiveNotification then we could check the extras on the notification to find the ones with the right chatroom and cancel them.

The [extras](https://firebase.google.com/docs/cloud-messaging/android/receive#handling_messages) from your FCM message are different from the [extras](https://developer.android.com/reference/android/app/Notification.html#extras) contained in the Notification object. So I don't think you can expect to retrieve data from an FCM message via the Notification class.

**Comment by NicholasIoanJones** [comment]
@kroikie Understand - and that reflects our experience - in that case how can we get the FCM data attributes in the app., if it is asleep when the FCM message arrives?

**Comment by kroikie** [comment]
@NicholasIoanJones Given that you are writing a RN app, this would be a question best answered by the [RN Firebase team](https://github.com/invertase/react-native-firebase).

In the case of native Android apps `Google Play Services` is responsible for handling incoming messages and passing its data to the app. So the developer could handle message data in either the `onMessageReceived` method or via the extras in the launched intent if the user taps a visible notification generated by FCM.

 I'm not sure how this is handled in the `RN Firebase` case, I'm sure [RN Firebase](https://github.com/invertase/react-native-firebase) is the best place to get that question answered.
