### ISSUE TITLE
mlkit vision barcode detection

### ISSUE THREAD

**Issue by cgt1994** [firebase/quickstart-android#1006]
Waiting for the barcode detection model to be downloaded. Please wait.
Can provide default model to downloaded,then we can put it to the assets to use it

**Comment by samtstern** [comment]
@cgt1994 sorry for the slow response here.

If you see the instructions on this page:
https://firebase.google.com/docs/ml-kit/android/detect-faces#before-you-begin

You can add a `meta-data` to your app that will begin the download immediately after your app is installed.  This will get the model to the user as fast as possible.
