### ISSUE TITLE
The provided API key has an IP address restriction.

### ISSUE THREAD

**Issue by msoni-oyo** [firebase/quickstart-android#1008]
I am getting the Remote config error. But the code has been working correctly since last week. But suddenly  the following error is coming :

E/FirebaseRemoteConfig: Fetch failed! Server responded with an error.
    com.google.android.gms.internal.firebase_remote_config.zze: 403 Forbidden
    {
      "code": 403,
      "errors": [
        {
          "domain": "global",
          "message": "The provided API key has an IP address restriction. The originating IP address of the call (2405:204:1308:bc95:b493:506c:3596:86fa) violates this restriction.",
          "reason": "forbidden"
        }
      ],
      "message": "The provided API key has an IP address restriction. The originating IP address of the call (2405:204:1308:bc95:b493:506c:3596:86fa) violates this restriction.",
      "status": "PERMISSION_DENIED"
    }

**Comment by samtstern** [comment]
@msoni-oyo since this is a project-specific issue that will require someone to dig into your API keys, I suggest writing in to Firebase Support:
https://firebase.google.com/support

They have all the tools to look into this!
