### ISSUE TITLE
How to authenticate otp on other device

### ISSUE THREAD

**Issue by hassanrana** [firebase/quickstart-android#1012]
Hi,I have an issue regarding firebase otp.I dont know what is the way to manually authenticate otp.Sometimes the phone number i am providing is on another phone and it cannot autometically detect sms.In that scenario what is the solution?Thanks

**Comment by samtstern** [comment]
@hassanrana in that situation you can simply type in the OTP you received on the other device.  You're right that auto-verification will not occur but that is working as intended.

You just use the code to create a `PhoneAuthCredential` object and then sign in with it:
https://firebase.google.com/docs/auth/android/phone-auth#create-a-phoneauthcredential-object
