### ISSUE TITLE
Crashlytics won't report a crash that is visible in the Google Developer Console

### ISSUE THREAD

**Issue by S0und** [firebase/quickstart-android#1013]
* Android ~~device~~ platform: Android TV
  * Android OS version: _____
  * Google Play Services version: 4.3.3
  * Firebase/Play Services SDK version: crashlytics 2.10.1 
  
Today one of my beta tester reported a crash that was new by the description. So i checked the Firebase console, but the mentioned crash wasn't there. Out of curiosity i checked the developer console, and the crash was there. 

Firebase: https://i.imgur.com/QmSJrl9.png

Google Developer console missing crash: https://i.imgur.com/kWWcf6n.png

This crash showed up in the dev console more then 20 hours now. I don't know how often FB updates the logs, but i think more often then that. 

Pretty much every Arrayindexoutofboundexception happens for the same reason, and i already fixed it in my internal build, but this NullPointException is from a different part of the app. 

Obviously my issue is, i decided to use Crashlytics to have more crash logs not less.

**Comment by samtstern** [comment]
@S0und thanks for reporting this.  Seems like there's an issue either in the Crashlytics SDK or on the Crashyltics backend resulting in not seeing this crash.  However this repo is just for the Android quickstart samples and not for debugging production issues.

I'd suggest filing an issue with Firebase Support who can dig into this.  Feel free to link them to this issue:
https://firebase.google.com/support
