### ISSUE TITLE
A general error occurred.

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/quickstart-android#1014]
No need to use template just a question. Is there a maintenance on going now with Firebase Remote Config we can no longer update value on any Firebase Account?

![image](https://user-images.githubusercontent.com/38008900/70426059-58d15680-1aad-11ea-9823-095570d296ed.png)

![image](https://user-images.githubusercontent.com/38008900/70426115-6dadea00-1aad-11ea-80ba-efc96a85a417.png)

**Comment by samtstern** [comment]
@ArcherEmiya05 looks like you're having an issue in production with the Firebase console. This repo is just for the android quickstart sample apps (hence the tempalte).  Please file an issue with Firebase support who can help you get the console working again:
