### ISSUE TITLE
Analytics LogEvent fails on Sony Xperia Z

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-android#102]
The very same app works on all our devices except for the Sony Xperia Z. The logcat says:

```
W/WindowManager: Force-removing child win Window{3eda4075 u0 SurfaceView} from container Window{1812555f u0 air.com.doitflash.firebaseCore/air.com.doitflash.firebaseCore.AppEntry}
E/Sensors: HAL:write 14 to fd 277 returned 'Device or resource busy' (16)
E/Sensors: HAL:ACCEL update delay error
W/WindowManager: Failed looking up window
       java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@3c4b7bac does not exist
       at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8742)
       at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:8733)
       at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1163)
       at android.os.BinderProxy.sendDeathNotice(Binder.java:551)
I/WindowState: WIN DEATH: null
```

the key part is `HAL:write 14 to fd 277 returned 'Device or resource busy' (16)` I think. Any explanation for this?

**Comment by samtstern** [comment]
I don't see anything to do with `logEvent`here, how are you determining that the `logEvent` method call is failing?

You can view more information about your Firebase Analytics calls by following these instructions:
https://firebase.google.com/docs/analytics/android/events#view_events_in_the_android_studio_debug_log

**Comment by myflashlab** [comment]
> I don't see anything to do with logEventhere

Yep, that's exactly the point and this happens ONLY on Sony Xperia Z. all our other devices are working fine. Because of that, I don't have any more information to provide! But you might probably duplicate the problem if you test with a Sony Xperia Z device?

**Comment by samtstern** [comment]
@myflashlab I don't think those `HAL` logs are related to Firebase Analytics, and unfortunately I don't have access to an Xperia Z device.  Are there any other logs you think might be relevant?  And how does your app behave on that device?

**Comment by samtstern** [comment]
@myflashlab it's been a long time since this issue was active so I am going to close it, please feel free to re-open if you have more information that can help debug this issue (assuming it's still happening).
