### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference

### ISSUE THREAD

**Issue by iBog** [firebase/quickstart-android#1020]
### Step 1: Describe your environment

  * Android device: OnePlus 7 Pro (GM1913)
  * Android OS version: 10
  * Google Play Services version: 19.6.29
  * Firebase/Play Services SDK version: 19.2.0
  
### Step 2: Describe the problem:
Trying to save Object to Firebase DB

```
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
java.lang.NullPointerException: Attempt to invoke interface method 'java.util.Iterator java.util.List.iterator()' on a null object reference
0 = {StackTraceElement@11813} "java.lang.reflect.Method.invoke(Native Method)"
1 = {StackTraceElement@11814} "com.google.firebase.database.core.utilities.encoding.CustomClassMapper$BeanMapper.serialize(com.google.firebase:firebase-database@@19.2.0:657)"
2 = {StackTraceElement@11815} "com.google.firebase.database.core.utilities.encoding.CustomClassMapper.serialize(com.google.firebase:firebase-database@@19.2.0:167)"
3 = {StackTraceElement@11816} "com.google.firebase.database.core.utilities.encoding.CustomClassMapper.convertToPlainJavaTypes(com.google.firebase:firebase-database@@19.2.0:60)"
4 = {StackTraceElement@11817} "com.google.firebase.database.DatabaseReference.setValueInternal(com.google.firebase:firebase-database@@19.2.0:282)"
5 = {StackTraceElement@11818} "com.google.firebase.database.DatabaseReference.setValue(com.google.firebase:firebase-database@@19.2.0:159)"
```

#### Steps to reproduce:

Reproduced on Emulator with Android 10 also 
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
 
#### Relevant Code:

```
DatabaseReference db = FirebaseDatabase.getInstance().getReference();
db.child("profile").child("name@last").setValue(userProfileObj)
```

**Comment by iBog** [comment]
Found the reason, FB InvocationTargetException caused on object method List<Obj> getSomething(), which collect data from inner list of other objects which was null and not checked before calling

**Comment by samtstern** [comment]
@iBog sorry I don't quite understand your solution.  Is there still a bug here or should we close this?

**Comment by plutotechnology** [comment]
you are trying to obtain data yet the data is null

**Comment by iBog** [comment]
> @iBog sorry I don't quite understand your solution. Is there still a bug here or should we close this?
This is definitely the issue as a minus of reflection (errors inside getter methods are not checked (or ignored)).
But fortunately, on dev side, it can be prevented by null checks before return results.

Example:
class Document {
  private List<Objects> records;
  private List<Objects> users;
  public getRecords(){
    return records;
  }
 public getUsers(){
    return users;
  }

//virtual method (getter for calculactions not for exact field), 
//which cause InvocationTargetException error, because fields inside are null
 public getAllObjectsCount() { 
    return records.size() + users.size();
  }

}

**Comment by samtstern** [comment]
I am very late with this response and I apologize but you should make that `getAllObjectsCount` method `private` or exclude it with `@Exclude`.
