### ISSUE TITLE
Firebase Auth with Transaction

### ISSUE THREAD

**Issue by tarektaamali** [firebase/quickstart-android#1022]
Does firebase auth support transactions ? 
for example i want to update user displayname,email and  phone number 
.if any in request i do a rollback .
```
`FirebaseUser user = await FirebaseAuth.instance.currentUser();
  UserUpdateInfo userUpdateInfo = new UserUpdateInfo();
  userUpdateInfo.displayName=firstName+" "+lastName;
  await user.updateProfile(userUpdateInfo);
  await user.updateEmail(email);`
```

**Comment by samtstern** [comment]
@tarektaamali no unfortunately this is not supported, each of those requests is independent and you will have to handle any rollbacks yourself.

**Comment by federicoWax** [comment]
await updateUserAuth(uid!, { email: oldEmail !== email ? email : undefined, password }); Asi lo hago en node ts, las propiedades que pueden ser undefinied no se actualizan, supongo que en flutter se puede hacer algo parecido.

**Comment by federicoWax** [comment]
await updateUserAuth(uid!, { email: oldEmail !== email ? email : undefined, password }); Las propiedades undefines nos e actualizan, es mejor actualizar con un solo metodo los datos de userAuth, es node ts supongo que hay un equivalente en Flutter.
