### ISSUE TITLE
I have some good suggestions for some of the database features!

### ISSUE THREAD

**Issue by ijin1322** [firebase/quickstart-android#1023]
Hi, everyone. I'm writing to suggest some features in the 'database' of the quick-start firebase.

The first is that I want to have the ability to write and delete, as well as the buttons to write on the Android device.

Second, if you use the Google Login button to push this button, you will be more comfortable with the user. In addition, use not only Google but also various e-mail platform login buttons such as the Facebook login button.

What do you think?

### Step 1: Describe your environment

  * Android device: Nexus 5X / Moto G5 Plus
  * Android OS version: 7.1.2 / 7.0.0
  * Google Play Services version: 11.2.0
  * Firebase/Play Services SDK version: 11.2.0

#### Steps to reproduce:

  1. Make a delete button or modify button
  2. Use google Sign In Button UI & API
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
Thanks for submitting #1024, I agree that adding a delete post button is helpful.  I don't think we should add Google Sign In to this app because I want to make it as simple as possible to run, the `auth` sample app shows how to use all of the available sign-in methods.

**Comment by ijin1322** [comment]
@samtstern I really really appreciate your comment. i will do my best! Thank you! have a nice day!
