### ISSUE TITLE
Wrong input datatype of Custom Model  ML Kit

### ISSUE THREAD

**Issue by KhoaN56** [firebase/quickstart-android#1026]
**Environment**

  * Android device: S8+
  * Android OS version: Pie
  * Firebase ML Vision Services SDK version: **24.0.1**
  
**Describe the problem:**
I follow the instruction in the documentation on this site step by step: 
https://firebase.google.com/docs/ml-kit/android/use-custom-models
My model is trained on Google Auto ML Vision Object Detection. I extracted it and downloaded it as .tflite, then upload it to firebase ML Vision project (as a custom model)
When I folow this step:
https://firebase.google.com/docs/ml-kit/android/use-custom-models#specify-the-models-input-and-output
I found that my model's input data type is uint8 just like the picture below:

![get_input_output_data_type(result)](https://user-images.githubusercontent.com/38883688/71098652-a4d67680-21e4-11ea-976e-f2f215e4a66e.png)

So I set the input data type as INT32 because it's the only integer type that FirebaseDataType support (that's all I know). Then, I follow the next step to perform input data type for the interpreter:
https://firebase.google.com/docs/ml-kit/android/use-custom-models#perform-inference-on-input-data
But I changed by just copy the integer value to an int array and return that to put it in the run method of the intepreter. When I run, the exception keep saying that "Internal error has occurred when executing Firebase ML tasks" and I still can't find where the problem is. 
For more information, I read a json file when exported the model of AutoML Vision Object Detection and it said the inference type of the model is: "QUANTIZED_UINT8", and the input tensor is "normalized_input_image_tensor".
Please help me with this. Every answer will be very appreciated.
  
Observed Results:
Logcat:
![image](https://user-images.githubusercontent.com/38883688/71100791-35fb1c80-21e8-11ea-8c34-db38d9cdbb7e.png)

  
Expected Results:

What I expect is it return the result like in this so that I can proccess it to display on screen
  
Relevant Code:

```
Bitmap bitmap = getYourInputImage();
bitmap = Bitmap.createScaledBitmap(bitmap, 224, 224, true);

int batchNum = 0;
float[][][][] input = new float[1][224][224][3];
for (int x = 0; x < 224; x++) {
    for (int y = 0; y < 224; y++) {
        int pixel = bitmap.getPixel(x, y);
        // Normalize channel values to [-1.0, 1.0]. This requirement varies by
        // model. For example, some models might require values to be normalized
        // to the range [0.0, 1.0] instead.
        input[batchNum][x][y][0] = (Color.red(pixel) - 127) / 128.0f;
        input[batchNum][x][y][1] = (Color.green(pixel) - 127) / 128.0f;
        input[batchNum][x][y][2] = (Color.blue(pixel) - 127) / 128.0f;
    }
}
```

**Comment by samtstern** [comment]
@KhoaN56 thanks for the detailed report!  This is a bit over my head, hoping @gkaldev or @ulukaya can take a look.

**Comment by KhoaN56** [comment]
I handled that error. Turns out, it needs byte type input which quantized but I declared it wrong.
But still have another problem when handling the output number. There're all quantized number. I don't know how to change them to normal number which is useable.
@samtstern if you know anything or anyone knows about this, please tell me.
