### ISSUE TITLE
Deprecated in new version

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [firebase/quickstart-android#1035]
Please see how to fix this error. Because I have used the latest dependency version. 
![Screenshot (65)](https://user-images.githubusercontent.com/39325207/71453734-ec479e80-27b2-11ea-956f-0db1a4ca34e8.png)

**Comment by samtstern** [comment]
@KanwarpartapSinghBimrah instead of using `FirebaseInstanceIdService` you should be using `FirebaseMessagingService` which has the functionality you need.

This StackOverflow question has some more information:
https://stackoverflow.com/questions/51123197/firebaseinstanceidservice-is-deprecated
