### ISSUE TITLE
auth-app ----> Emulator API 18 can't sign in

### ISSUE THREAD

**Issue by afaideen** [firebase/quickstart-android#1036]
![image](https://user-images.githubusercontent.com/12533089/71541441-f248a580-2993-11ea-8a5a-3a3a54d358a0.png)

**Comment by afaideen** [comment]
what else info needed to know.

**Comment by samtstern** [comment]
@afaideen the issue template requests information on the type of device you're running, SDK versions, etc.  All of that is useful to help us debug.

Getting the `12500` error code normally means one of the following:

- Your emulator has out of date Google Play services.  You can fix this by using one of the emulator images with the Play Store installed.
- Your SHA1 key has not been correctly entered into the Firebase / Google console online.
- Your app has not properly configured the OAuth consent screen details.
