### ISSUE TITLE
Resources$NotFoundException: String resource ID #0x0

### ISSUE THREAD

**Issue by mehdi-salehi** [firebase/quickstart-android#1037]
### Step 1: Describe your environment

  * Android device: SAMSUNG
  * Android OS version: 9,8
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: 17.2.1-4.3.3
  
### Step 2: Describe the problem:
Crash on push  notification happens
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:
Fatal Exception: android.content.res.Resources$NotFoundException: String resource ID #0x0
       at android.content.res.Resources.getText + 363(Resources.java:363)
       at android.content.res.Resources.getString + 456(Resources.java:456)
       at android.content.Context.getString + 580(Context.java:580)
       at com.google.firebase.messaging.zzb.zzb + 234(zzb.java:234)
       at com.google.firebase.messaging.zzb.zza + 6(zzb.java:6)
       at com.google.firebase.messaging.zzd.zza + 33(zzd.java:33)
       at com.google.firebase.messaging.FirebaseMessagingService.zzc + 69(FirebaseMessagingService.java:69)
       at com.google.firebase.messaging.zze.run + 2(zze.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1167(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 641(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run + 6(zza.java:6)
       at java.lang.Thread.run + 764(Thread.java:764)

**Comment by samtstern** [comment]
@mehdi-salehi there is not enough information here to diagnose this issue.  Can you show the code you're running that causes this and why you think it's an issue with Firebase rather than an issue with your own code?

**Comment by mehdi-salehi** [comment]
it happened after we updated FCM library to latest version and using Androidx.

    implementation 'com.google.android.gms:play-services-location:17.0.0'
    implementation 'com.google.android.gms:play-services-maps:17.0.0'
    implementation 'com.google.android.gms:play-services-auth-api-phone:17.3.0'
    implementation 'com.google.android.gms:play-services-measurement-api:17.2.1'
    implementation 'com.google.android.gms:play-services-measurement-base:17.2.1'
    implementation 'com.google.firebase:firebase-messaging:20.1.0'
    implementation 'com.google.firebase:firebase-iid:20.0.2'
    implementation 'com.google.firebase:firebase-core:17.2.1'
    implementation 'com.google.firebase:firebase-analytics:17.2.1'


public class MyFirebaseMessagingService extends FirebaseMessagingService {

    private static final String NOTIFICATION_CHANNEL_ID = "...";
    private static final String NOTIFICATION_CHANNEL_NAME = "...";
    private static final String NOTIFICATION_CHANNEL_DESC = "...";

    @Override
    public void onNewToken(String token) {
        try {
            saveToken(token);
        } catch (Exception e) {
            e.printStackTrace();
        }

        FirebaseMessaging.getInstance().subscribeToTopic("...");
        FirebaseMessaging.getInstance().subscribeToTopic("version" + Build.VERSION.RELEASE);
    }

    private void saveToken(String token) throws Exception {
      ...
    }

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        try {
            showNotification(remoteMessage);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void showNotification(RemoteMessage remoteMessage) throws Exception {
        NotificationManager notificationManager = (NotificationManager) App.getContext().getSystemService(Context.NOTIFICATION_SERVICE);
        if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.O) {
            NotificationChannel channel = new NotificationChannel(NOTIFICATION_CHANNEL_ID,
                    NOTIFICATION_CHANNEL_NAME,
                    NotificationManager.IMPORTANCE_DEFAULT);
            channel.setDescription(NOTIFICATION_CHANNEL_DESC);
            notificationManager.createNotificationChannel(channel);
        }
        NotificationCompat.Builder b = new NotificationCompat.Builder(App.getContext(), NOTIFICATION_CHANNEL_ID);

        if (String.valueOf(remoteMessage.getData().get("targetId")).equals("128")) {
            Logger.e("LastIdddd", "showNotification: " + remoteMessage.getData().get("entityId"));

            if (Dao.getInstance().Preferences.getString(Preferenses.ReceiptNotificationLastID, "").equals("0") ||
                    Dao.getInstance().Preferences.getString(Preferenses.ReceiptNotificationLastID, "").equals("") ||
                    Dao.getInstance().Preferences.getString(Preferenses.ReceiptNotificationLastID, "") == null) {
                Dao.getInstance().Preferences.setString(Preferenses.ReceiptNotificationLastID, remoteMessage.getData().get("entityId"));
                Logger.e("LastId", "showNotification: " + remoteMessage.getData().get("entityId"));
            }

            int notificationCount = Dao.getInstance().Preferences.getInteger(Preferenses.ReceiptNotificationCount, 0);
            notificationCount++;
            Dao.getInstance().Preferences.setInteger(Preferenses.ReceiptNotificationCount, notificationCount);
            b.setContentText("شما " + notificationCount + " پیام خوانده نشده دارید");
            b.setStyle(new NotificationCompat.BigTextStyle(b)
                    .bigText("شما " + notificationCount + " پیام خوانده نشده دارید\n" + remoteMessage.getData().get("body"))
                    .setBigContentTitle(remoteMessage.getData().get("title"))
                    .setSummaryText("You have " + notificationCount + " Notifications")
            );

            b.setContentTitle(remoteMessage.getData().get("title"));
            b.setContentText(remoteMessage.getData().get("body"));

            Intent intent = new Intent(App.getContext(), MainActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
            intent.putExtra("isNotif", "true");
            intent.putExtra("targetId", String.valueOf(remoteMessage.getData().get("targetId")));
            intent.putExtra("entityId", String.valueOf(remoteMessage.getData().get("entityId")));
            intent.putExtra("popup", String.valueOf(remoteMessage.getData().get("popup")));
            intent.putExtra("popup_title", String.valueOf(remoteMessage.getData().get("popup_title")));
            intent.putExtra("popup_text", String.valueOf(remoteMessage.getData().get("popup_text")));
            intent.putExtra("url", String.valueOf(remoteMessage.getData().get("url")));

            PendingIntent contentIntent = PendingIntent.getActivity(App.getContext(), 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
            b.setAutoCancel(true)
                    .setDefaults(Notification.DEFAULT_ALL)
                    .setWhen(System.currentTimeMillis())
                    .setSmallIcon(R.drawable.ic_statusbar)
                    .setColor(ContextCompat.getColor(this, R.color.orange));


            if (remoteMessage.getData() != null) {
                b.setContentIntent(contentIntent);
            }

            notificationManager.notify(2, b.build());

        } else {
            b.setContentTitle(remoteMessage.getNotification().getTitle());
            b.setContentText(remoteMessage.getNotification().getBody());

            Intent intent = new Intent(App.getContext(), MainActivity.class);
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
            intent.putExtra("isNotif", "true");
            intent.putExtra("targetId", String.valueOf(remoteMessage.getData().get("targetId")));
            intent.putExtra("entityId", String.valueOf(remoteMessage.getData().get("entityId")));
            intent.putExtra("popup", String.valueOf(remoteMessage.getData().get("popup")));
            intent.putExtra("popup_title", String.valueOf(remoteMessage.getData().get("popup_title")));
            intent.putExtra("popup_text", String.valueOf(remoteMessage.getData().get("popup_text")));
            intent.putExtra("url", String.valueOf(remoteMessage.getData().get("url")));
            intent.putExtra(KEY_ID_INSTITUTE, String.valueOf(remoteMessage.getData().get(KEY_ID_INSTITUTE)));
            intent.putExtra(KEY_PRICE, String.valueOf(remoteMessage.getData().get(KEY_PRICE)));

            PendingIntent contentIntent = PendingIntent.getActivity(App.getContext(), 0, intent, PendingIntent.FLAG_UPDATE_CURRENT);
            b.setAutoCancel(true)
                    .setDefaults(Notification.DEFAULT_ALL)
                    .setWhen(System.currentTimeMillis())
                    .setSmallIcon(R.drawable.ic_statusbar)
                    .setColor(ContextCompat.getColor(this, R.color.orange));

            if (remoteMessage.getData() != null) {
                b.setContentIntent(contentIntent);
            }

            notificationManager.notify(1, b.build());
        }
    }

}

**Comment by samtstern** [comment]
@mehdi-salehi how often does this happen and can you reproduce it reliably?
