### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by njboro** [firebase/quickstart-android#104]
* Android device: EMS Bk2021
  * Android OS version: 4.3
  * Google Play Services version: ___
  * Firebase/Play Services SDK version: 9.4.0
  
Issue Description:
I tried sending Firebase Notification to users. I got 1 crash on this device only. What may be reason?

Crash report :
Fatal Exception: java.lang.NullPointerException
       at android.os.Bundle.(Bundle.java)
       at android.content.Intent.getExtras(Intent.java:4824)
       at com.google.firebase.messaging.FirebaseMessagingService.zzm(Unknown Source)
       at com.google.firebase.iid.zzb$2.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by samtstern** [comment]
@njboro is this a device you own or one of your users devices?  If you own it, could you check the version of Google Play Services it's running by going to **Settings** > **Apps** > **Google Play Services**?

**Comment by njboro** [comment]
NO @samtstern , I don't know about Google Play Services version that the User is using. But, I haven't written code to check availability of GPS on a device.

**Comment by samtstern** [comment]
@njboro given that this is only happening on a small subset of your devices I believe it's an issue with out of date Google Play Services.

You can use the `makeGooglePlayServicesAvailable` method of [`GoogleApiAvailability`](https://developers.google.com/android/reference/com/google/android/gms/common/GoogleApiAvailability.html) to ensure your users have the right version.

**Comment by samtstern** [comment]
It's been over a month since we had an update here.  I am going to close this issue, please re-open if you have new details.
