### ISSUE TITLE
Cannot get confidence score with on-device Text Recognition?

### ISSUE THREAD

**Issue by lynx97** [firebase/quickstart-android#1040]
The confidence score when I invoke method `getConfidence()` with all text blocks, text lines, text element is null.
So is `getRecognizedLanguages()`.
I am using the newest version firebase-ml-vision:24.0.1.
thanks for any help!

**Comment by omarDG** [comment]
Hi have the save Issue:

Android OS version 8.0.1
Firebase Mlkit version: 24.0.1 (firebase-ml-vision:24.0.1)
Service : Textrecognition (OnDevice)

Problem:  Impossible to get confidence score  for either block or line
Code:
`Float blockConfidence = block.getConfidence();`
` Float confidence=line.getConfidence();`

Result: I'm getting null as confidence even if the block or line is well recognized.

**Comment by samtstern** [comment]
@gkaldev or @ulukaya do you know if this is one of the things that's only returned by the Cloud model?  Or is this a bug?

**Comment by lynx97** [comment]
> @gkaldev or @ulukaya do you know if this is one of the things that's only returned by the Cloud model? Or is this a bug?

thanks samtstern, this is only returned by Cloud model.

**Comment by Lelelo1** [comment]
I am using [google_ml_vision](https://github.com/brianmtully/flutter_google_ml_vision) and I always get null confidence.

**Comment by nabaasa** [comment]
This link will help you:
http://www.java2s.com/example/java-api/android/speech/speechrecognizer/confidence_scores-0.html
