### ISSUE TITLE
FireBase FireStore documentChanges not working when orderBy clause is applied

### ISSUE THREAD

**Issue by hassaanraza-rebel1025** [firebase/quickstart-android#1058]
* Android device: _OnePlus3T
  * Android OS version: Pie
  * Google Play Services version: 4.3.3
  * Firebase/Play Services SDK version: 19.2.0
  
#### Steps to reproduce:

  1. add record
  2. observe documentChanges
  
#### Observed Results:

  documentChanges is not triggered
  
#### Expected Results:

 should show result when orderby clause is applied
  
#### Relevant Code:

```
fun getChatMessages(chatId:String)
    {
        FirebaseFirestore.getInstance()
            .collection("messages")
            .whereEqualTo("chatId",chatId)
            .orderBy("date")
            .addSnapshotListener { querySnapshot, e ->
                if (querySnapshot != null) {
                        for (i in 0 until querySnapshot.documentChanges.size) {
                            if(querySnapshot.documentChanges[i].type == DocumentChange.Type.ADDED)
                          mMessages.add(Utils.bindMessage(querySnapshot.documentChanges[i].document))
                        }
                }
                messages.value = mMessages
            }
    }
```

**Comment by samtstern** [comment]
@hassaanraza-rebel1025 that query requires a custom index, and from your description I bet that index does not exist yet.

In your snapshot listener you should print out the error (`e`) which will give you a link to create the index automatically!
