### ISSUE TITLE
I am using ML Kit Library for scan the Driving License QR code by using PDF417 format only. I want to scan only QR code but it still capture the Barcode. How can we disbale the barcode scan? Please suggest me some option to disable the barcode scanning.

### ISSUE THREAD

**Issue by Himanshu119** [firebase/quickstart-android#1067]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@Himanshu119 please use the issue template when filing an issue.
