### ISSUE TITLE
I want to scan the PDF417 formatted code only and restrict all other codes using ML Kit library in Android. Please suggest how to restrict scanning of all codes except PDF417.  Note: It still allow to scan all other code if we use FirebaseVisionBarcode.FORMAT_PDF417 only.

### ISSUE THREAD

**Issue by Himanshu119** [firebase/quickstart-android#1068]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@Himanshu119 please use the issue template when filing an issue and try not to file duplicate issues (this looks like #1067).

This repository should only have issues with the quickstart itself.  If you have a bug or a feature request for the Firebase Android SDK please file it on the `firebase/firebase-android-sdk` repo.
