### ISSUE TITLE
ads slow app down

### ISSUE THREAD

**Issue by Xstar97** [firebase/quickstart-android#107]
when I re-implemented my project w/o ads...it was fast & w/o lag...however after adding ads again it became slow & lagged when switching to another option in the bottom navigation. I used bottomBar which is not the caused for the lag, but its your admob SDK that causing it.  any help will be greatly appreciated.

**Comment by samtstern** [comment]
@Xstar97 I will need more information to debug this, we have not had other reports of ads slowing down apps significantly so it's hard to guess what's going on here.

Can you provide a small code example that reproduces this issue?

**Comment by Xstar97** [comment]
I just updated bottombar to its latest version & implemented it in a better
way...so the lag is gone for now...
