### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to create application java.lang.NullPointerException: Attempt to invoke virtual method 'com.google.firebase.remoteconfig.RemoteConfigComponent.getDefault()' on a null object reference

### ISSUE THREAD

**Issue by prudhvi1** [firebase/quickstart-android#1073]
causing crash for devices 6.0.1 or anything with 6.0. can someone help

**Comment by samtstern** [comment]
@prudhvi1 please use the issue template when filing issues.  If you're not able to provide the information in the template try asking your question on StackOverflow or some other more general forum.
