### ISSUE TITLE
Suddenly the sms code is stop send to user who sign with phone

### ISSUE THREAD

**Issue by mahmood-heja** [firebase/quickstart-android#1077]
i have app build with flutter and is already published on google play and app store 

the app is work fine **until yesterday** the users not receive sms code  when sign with phone number 

Project Firebase Info 
- **Blaze** Plane 
- more than 20000 accounts sign with phone auth 

in debug mode the **codeSent** callback is called but still not have any send code 

**UPDATE :** the problem is happen with **specific mobile network**

**Comment by samtstern** [comment]
@mahmood-heja whenever you are having a problem with your project in production please contact Firebase Support:
https://firebase.google.com/support

They will help you resolve this.
