### ISSUE TITLE
camera resolution

### ISSUE THREAD

**Issue by ankitvaluepitch** [firebase/quickstart-android#1078]
at the point when I found an image from the camera of MLKIT , it's resolution is 768x1024 . but when I click the picture from my device native camera it gives me an 8 MP , i.e. 3264x2448 resolution image. so somehow I want to use this greater resolution image In MLKIT, which my device can capture as it's full capacity.so how can I increase MLKIT camera picture quality?

because when I get the face from the MLKIT camera picture, it also has low picture quality and I get lost my accuracy.One more thing here I am using the front camera for all.

if possible I can get the accuracy for the face more reliable.

**Comment by samtstern** [comment]
@ankitvaluepitch this seems like more of a general programming question not an issue with the quickstart code in this repo or a bug in the ML Kit SDK.  Please try on StackOverflow!
