### ISSUE TITLE
Notification body text getting truncated

### ISSUE THREAD

**Issue by saytomanish82** [firebase/quickstart-android#108]
When we send notification messages, its by default get shown in device tray(as expected). We have message body length of nearly 92 characters. When we try to view the message in device tray only first ~40 characters are being shown. Seems like message is not getting wrap in multiple lines. 

We have tested the same behavior on Android phones having 5.1 and 6.0 versions.

![screenshot_2016-08-17-14-38-57](https://cloud.githubusercontent.com/assets/20990075/17731972/568341a6-648d-11e6-88bb-5b8042e5030c.png)

**My question is how we can show these messages with full length using "notification" payload only.**

also as an alternate solution,  we can think of having "data" payload and handle it there with custom notification service (as described in sample code), but there also we are stuck with detecting the scenarios that whether app is in foreground or background or killed.  
Overall goal is to achieve functionality as below; -
1. App is in Foreground:  - we capture the notifications and display them in notification page(this is a page inside app). 
2. App is in background: - display messages in system tray. and when touched by user, app will get open.

Please let me know if we have any suggestions to implement the above requirement

message sent is (via Java code from server): 
    
    JSONObject info = new JSONObject();
    info.put("sound", "default");
    info.put("title", "My Test Title");   // Notification title
    info.put("body", "Survey launched: [July 2016] MONTHLY SURVEY OF MANUFACTURING BUSINESS CONDITIONS IN IRELAND"); // Notification body

    JSONObject json = new JSONObject();
    json.put("to",<Device token for testing>);
    json.put("notification", info);
    json.put("content_available", true);

**Comment by kroikie** [comment]
This should be fixed in SDK 9.4.0. Big Style notifications are used so there would be the option for the user to expand the notification if it is not expanded automatically.

**Comment by sonamgupta-kiwi** [comment]
is it implemented ?? I am getting this issue in latest SDK
