### ISSUE TITLE
How to get download progess firebase offline translate?

### ISSUE THREAD

**Issue by attaullahpro** [firebase/quickstart-android#1080]
Recently I used firebase MLkit for translate offline but how to get download progress for progressbar. 
because there is no method for getProgress, it interface consist of 4 method `download `, `deleteDownloadedModel`, `isModelDownloaded` and `getDownloadedModels`

**Comment by samtstern** [comment]
@attaullahpro right now there is no way to get progress, you can only see if the download is completed or not.

If you want you can file a Feature Request on the firebase-android-sdk repo for a more detailed progress indicator.
