### ISSUE TITLE
Cloud Vision API not enabled

### ISSUE THREAD

**Issue by gaglileo** [firebase/quickstart-android#1086]
### Step 1: Describe your environment

  * Android device: OUKITEL C8
  * Android OS version: 7.0
  * Google Play Services version: 4.3.3
  * Firebase SDK version: 24.0.1
  
#### Steps to reproduce:

  1. Directly from sample app here, without change anything, open Kotlin/Java demo
  2. Open StillImageActivity
  3. Select Landmark and take a picture of a face
  
#### Observed Results:

  Nothing happened and log registered this issue:

```
403 Forbidden
{
  "code": 403,
  "errors": [
    {
      "domain": "usageLimits",
      "message": "Cloud Vision API has not been used in project 911493030598 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/vision.googleapis.com/overview?project=911493030598 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
      "reason": "accessNotConfigured",
      "extendedHelp": "https://console.developers.google.com"
    }
  ],
  "message": "Cloud Vision API has not been used in project 911493030598 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/vision.googleapis.com/overview?project=911493030598 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.",
  "status": "PERMISSION_DENIED"
}
```
  
#### Expected Results:

  Infos about Landmarks

**Comment by gaglileo** [comment]
I forgot to download a google-services.json file with enabled api's

**Comment by mohity777** [comment]
Hey can u tell how did u resolve the issue? what needs to be enabled?
