### ISSUE TITLE
In android 10 can't open app from a firebase dynamic link(sumsang)

### ISSUE THREAD

**Issue by ljzyljc** [firebase/quickstart-android#1087]
In android 10 I can't open app from a firebase dynamic link(sumsang) when app is in background, but in android 9 or android 8 it can work, google has Restrictions on starting activities from the background(In android 10)，firebase is google's product，so how should I do if I want to make the dynamic link can work in android 10,please help me,thanks!

**Comment by rosariopfernandes** [comment]
@ljzyljc for that kind of situations, the Android Documentation recommends using [Notifications instead](https://developer.android.com/guide/components/activities/background-starts#display-notification). You can use the notification to launch a [full screen Intent](https://developer.android.com/training/notify-user/time-sensitive)

**Comment by samtstern** [comment]
Thanks for the quick answer @rosariopfernandes !

**Comment by ljzyljc** [comment]
@rosariopfernandes thank you!

**Comment by ljzyljc** [comment]
I have another question，If i click the dynamic link，use your recommend's way to create notification，but my app don't start，how should i create the notifictions?@rosariopfernandes
