### ISSUE TITLE
Suggestion: Use View Binding instead of synthetic binding and findViewById

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/quickstart-android#1088]
_(Our bot will not be happy with this issue)_

Now that we're using Gradle 3.6.1, we could enable [View Binding](https://developer.android.com/topic/libraries/view-binding) on our samples. Two reasons why I would recommend this change:
- Kotlin synthetic binding is [not recommended](https://www.reddit.com/r/androiddev/comments/ala9p2/why_kotlinx_synthetic_is_no_longer_a_recommended/efdvpkg/?utm_source=share&utm_medium=web2x);
- ViewBinding removes the need for `findViewById`, which would make our app implementation simpler, since it's meant for demonstration purposes.

**Comment by samtstern** [comment]
@rosariopfernandes oh that's really cool!  I had no idea this was available.  I never liked Kotlin synthetic binding but I was trying to be one of the Kotlin Cool Kids 😎

**Comment by rosariopfernandes** [comment]
Hahah, I see. Does that mean this is a go?

**Comment by samtstern** [comment]
Do we need to use any alpha/beta tooling or is this all powered by AGP
3.6.1 stable?  If it's stable I'm good to go with this but I don't want our
devs to have to use AS Canary or anything like that.

**Comment by rosariopfernandes** [comment]
ViewBinding is included in 3.6.1 stable. No need to use any alpha/beta tools.

**Comment by samtstern** [comment]
Ok then let's do it!

**Comment by gaglileo** [comment]
I have noticed that using ViewBinding, the camera in Kotlin MLKit sample app is finally working

**Comment by rosariopfernandes** [comment]
@samtstern As I was implementing this, I noticed that some of our layouts only contain a single view (e.g. [analytics/fragment_main.xml](https://github.com/firebase/quickstart-android/blob/master/analytics/app/src/main/res/layout/fragment_main.xml)). I think for these cases it's simpler to use `findViewById()` instead of View Binding, since the number of lines will remain the same and we'll actually have less binding classes being generated by the plugin during build.
Unless we want to use View Binding in all views for consistency. WDYT?

**Comment by samtstern** [comment]
@rosariopfernandes I don't have a strong opinion here, I think either choice you could make for a single-view layout is a reasonable one!  Whatever you think looks best as you implement is fine with me.
