### ISSUE TITLE
Firebase Face Detection Api issue whileusing cameraX API

### ISSUE THREAD

**Issue by Anasmirza20** [firebase/quickstart-android#1092]
Hi team, 

I used Camera X Api for detecting faces in Firebase ML kit because you used the depreciated camera API in our example and I faced a lot of performance issues in it.
CameraX API works perfectly but I am stuck in one place. CameraX uses Texture view in the layout view to open the camera and I want to show 3d objects and filters on the face.
In the example, we use CameraSourcePreview and GraphicOverlay classes in the quickstart sample app to show objects on the relative part of the face.
So, Could you please let me know how to how to achieve the same thing using cameraX Api.

Any help will be appreciated.
Thanks

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@Anasmirza20 this sounds like it's a question/issue with CameraX not with ML Kit in particular (or with this sample).

I would suggest asking here:
https://github.com/android/camera-samples
