### ISSUE TITLE
Is the firebase Face Detection support 3D objects to place over the camera view?

### ISSUE THREAD

**Issue by Anasmirza20** [firebase/quickstart-android#1093]
Hi,
I tried to place 3D objects over the camera view while detecting the face I am not able to place it on the camera view. If the firebase supports the 3D objects then could you please let me know how? And, which type of object firebase support like .obj,.fbx, etc.
Thanks for your help...

**Comment by samtstern** [comment]
@Anasmirza20 this looks very similar to https://github.com/firebase/quickstart-android/issues/1092, see my advice there.

**Comment by Anasmirza20** [comment]
@samtstern Its not a similar, I am not using cameraX now Ii just wanted to know can Firebase support 3d objects in our face detection example or not??
So, Could you please help me out in it.
Thanks for your support...

**Comment by samtstern** [comment]
@Anasmirza20 what you place over the Camera View is not related to Firebase.  We only help you interpret camera view data, we don't help with display or display enhancement.  So I still think this is a question for Android or AndroidX experts, not Firebase experts.
