### ISSUE TITLE
Twitter Login Setup

### ISSUE THREAD

**Issue by Rajerishka** [firebase/quickstart-android#1099]
You readme says
Open the file app/src/main/res/values/ids.xml and replace the value of the twitter_consumer_key and witter_consumer_secret with the key and secret you just put into the Firebase console.

But this does not exist in ids.xml, there is only a facebook one

**Comment by samtstern** [comment]
@Rajerishka thanks!  That's a good find.  We no longer require these keys at all within the app, want to send a Pull Request to fix this issue in the README?  If not, I can do it.

**Comment by samtstern** [comment]
There are no results for `twitter_consumer_key` in this repo so I assume this is fixed in `master`:
https://github.com/firebase/quickstart-android/search?q=twitter_consumer_key&unscoped_q=twitter_consumer_key
