### ISSUE TITLE
subscribe to topic button not creating a topic in the firebase console

### ISSUE THREAD

**Issue by biagionicp** [firebase/quickstart-android#11]
In the messaging quickstart app, the subscribe to news button is suppose to create a "news" topic in the firebase console, but even after I click it, the firebase console still shows the "This project does not have any topics" message when I click the topic bubble.

I can send notifications when I click the "User segment" button and when I click the "Single device" button. So firebase is aware of the installation of the app on the device and the token that was created for the device. It's just the subscribing to a topic feature that is not successfully communicating with firebase.

**Comment by samtstern** [comment]
I believe there is a delay in topics appearing in the console, possibly up
to 24h.  I have heard a number of users confused by this so I'll bring the
feedback to the console team.

Could you see if this issue persists tomorrow?

**Comment by biagionicp** [comment]
still no topics

**Comment by biagionicp** [comment]
now the "news" topic is appearing... 14 hours later

**Comment by samtstern** [comment]
@biagionicp glad to see this was resolved, I will close this issue and file some internal feedback.

**Comment by joesleiman** [comment]
i can't find the subscribe to "news" or any topic, where can I subscribe to the topic so I can add it in the topic section as target or tag, and test it.
i'm using firebase.subscribe('news') but i can't test it

**Comment by omkarfroz** [comment]
@joesleman you don't need to create the topic, you just need to subscribe the topic. FCM will create a new topic if topic with same name doesn't exist, else if it exists the user would simply subscribe to the topic.
No matter what platform (android/iOS/Cordova) you use.
