### ISSUE TITLE
How to collect the stay in every page(activity) time  or method execution time by firebase?

### ISSUE THREAD

**Issue by ljzyljc** [firebase/quickstart-android#1105]
The firebase has different event to collect ，I have already use it 。But I don't Know How to collect the user stay in every page(activity) time，and I want to see the result in website（If it can show the every page(activity) stay time from user start app to close app。）And I want to collect special method execution time，and onCreate to onResume total time？

**Comment by samtstern** [comment]
See this documentation for tracking screen views:
https://firebase.google.com/docs/analytics/screenviews

**Comment by ljzyljc** [comment]
@samtstern this url can't find the way to slove my problem，just one method setCurrentScreen()，In firebase I can find the count of page(activity) event，but I can't how long people stay in every page(time)
