### ISSUE TITLE
Slow frame analysis on some devices

### ISSUE THREAD

**Issue by Ibernato93** [firebase/quickstart-android#1107]
I have implemented an application that performs an authentication process in real time (closed eyes, smile, etc.). It works perfectly on some devices, while on a Samsung j5 2016 the frame analysis is slow (there is a delay in the verification). Example: I close my eyes -> wait a few seconds while the frame relating to the closing of the eyes arrives.

I am using the quick-start project as a basis. So I have the camerasource, camerasourcepreview and my customDetector which extends the visionProcessorBase class.

**Comment by Ibernato93** [comment]
Update:
The problem occur when i set Accuracy perfomance  mode, while if i set FAST Mode the app work perfectly. This problem occur only on my samsung device

**Comment by samtstern** [comment]
@Ibernato93 sorry for the slow response here but sounds like the Samsung device from 2016 just can't keep up with high-accuracy frame analysis at the normal framerate.  I would suggest skipping some frames on older devices.
