### ISSUE TITLE
Fabric Crashlytics reports display some letters instead of classes names of my Android App

### ISSUE THREAD

**Issue by jrafaelahmedov** [firebase/quickstart-android#1108]
i added my proguard for this 

-keep class com.crashlytics.** { *; }
-dontwarn com.crashlytics.**

but still this i cant to fix this please help

**Comment by jrafaelahmedov** [comment]
![Capture](https://user-images.githubusercontent.com/41021698/79774339-b7ec8500-8343-11ea-94b9-ecd6f580f185.PNG)

this is my problem

**Comment by samtstern** [comment]
@jrafaelahmedov sorry I never got to this issue back when you filed it.  This does not look like an issue with the quickstart in this repo, so I am going to close it.

It looks like you're having some issue uploading the obfuscation mapping with Crashlytics, I would suggest trying this guide and then contacting Support if you're still stuck:
https://firebase.google.com/docs/crashlytics/get-deobfuscated-reports?platform=android
