### ISSUE TITLE
 java.lang.IllegalArgumentException Service not registered: com.google.firebase.iid.zzw@530ac97  com.google.android.gms.common.stats.ConnectionTracker.unbindService(SourceFile:1)

### ISSUE THREAD

**Issue by LambdaXiao** [firebase/quickstart-android#1111]
### Step 1: Describe your environment

  * Android device: ___华为 EVR AL00__
  * Android OS version: _Android 9,level 28____
  * Google Play Services version: ___4.3.3__
  * Firebase/Play Services SDK version: ____4.3.3_
  
### Step 2: Describe the problem:
app crash

java.lang.IllegalArgumentException
Service not registered: com.google.firebase.iid.zzw@c13d0ef
#### Steps to reproduce:

 open app
  
#### Observed Results:

 java.lang.IllegalArgumentException
Service not registered: com.google.firebase.iid.zzw@530ac97
com.google.android.gms.common.stats.ConnectionTracker.unbindService(SourceFile:1)

1 android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1755)
2 android.app.ContextImpl.unbindService(ContextImpl.java:1925)
3 android.content.ContextWrapper.unbindService(ContextWrapper.java:717)
4 com.google.android.gms.common.stats.ConnectionTracker.unbindService(SourceFile:1)
5 com.google.firebase.iid.zzw.zzb(SourceFile:7)
6 com.google.firebase.iid.zzw.zza(SourceFile:30)
7 com.google.firebase.iid.zzz.handleMessage(Unknown Source:2)
8 android.os.Handler.dispatchMessage(Handler.java:108)
9 com.google.android.gms.internal.firebase_messaging.zze.dispatchMessage(SourceFile:1)
10 android.os.Looper.loop(Looper.java:216)
11 android.app.ActivityThread.main(ActivityThread.java:7625)
12 java.lang.reflect.Method.invoke(Native Method)
13 com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
14 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)

  
#### Expected Results:

  not crash
  
#### Relevant Code:

  ```
// Google Services plugin
        classpath 'com.google.gms:google-services:4.3.3'
 //谷歌推送
    implementation 'com.google.firebase:firebase-core:17.2.1'
    implementation 'com.google.firebase:firebase-iid:20.0.1'
    implementation 'com.google.firebase:firebase-messaging:20.0.1'
    implementation 'android.arch.work:work-runtime:1.0.1'

FirebaseInstanceId.getInstance().getInstanceId()
                        .addOnCompleteListener(new OnCompleteListener<InstanceIdResult>() {
                            @Override
                            public void onComplete(@NonNull Task<InstanceIdResult> task) {
                                if (!task.isSuccessful()) {
                                    Log.w(TAG, "getInstanceId failed", task.getException());
                                    return;
                                }

                                // Get new Instance ID token
                                String token = task.getResult().getToken();

                                // Log and toast
                                String msg = getString(R.string.msg_token_fmt, token);
                                Log.d(TAG, msg);
                                Toast.makeText(MainActivity.this, msg, Toast.LENGTH_SHORT).show();
                            }
                        });
              
  ```

**Comment by samtstern** [comment]
@LambdaXiao this does not seem like this is an issue with the Android Quickstarts.  If you can reproduce this crash please file a bug on the firebase-android-sdk repo explaining the issue.
