### ISSUE TITLE
iOS on device text recognizer scale error. 

### ISSUE THREAD

**Issue by artemsivcev** [firebase/quickstart-android#1119]
Hey there! I have 2 same images and 2 iPhones: 8 and X. UIImage have scale set to 1 and cropped width and height by app. Then I send this image in onDeviceTextRecognizer() and get 2 different maps with all different results. Why so? Is there some scale dependence in ML KIT library?

**Comment by samtstern** [comment]
@artemsivcev this repository is for issues with the Android quickstart.  It sounds like your issue has to do with iOS, please try asking on either the quickstart-ios repo or on StackOverflow.

For what it's worth: I know ML Kit can fail on very small images.

**Comment by artemsivcev** [comment]
@samtstern image have height = 2048, width = 1383.
I created iOS issue https://github.com/firebase/quickstart-ios/issues/970
