### ISSUE TITLE
I tried a lot of times but I just couldn't receive notification send from the firebase console?

### ISSUE THREAD

**Issue by raintears** [firebase/quickstart-android#112]
I added this to my manifest and do the necessary codes already. I can get the token but when I send I just can't receive from my emulator. I can only receive it when I run on my phone.
```
        <service
            android:name=".FCMMessageReceiverService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        <service
            android:name=".TokenService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
```

**Comment by kroikie** [comment]
hi @raintears just to be clear, you are saying that when you send to your emulator you do not receive the messages, but running the same code you receive the messages on your device?

If so, could you confirm that you are using an emulator with Google Services?
Also could you specify how you are sending the message and what the message contains?

**Comment by abehaskins** [comment]
Hey @raintears this is more of a StackOverflow question since it's not directly regarding this repo, so I'd try asking there if you're still having issues!
