### ISSUE TITLE
[feature request] FCM Messages: create notifications like system ones

### ISSUE THREAD

**Issue by danielesegato** [firebase/quickstart-android#1129]
With FCM when the app is in background the OS create a notification that has the image, icon and everything...

but to build a notification that looks the same when the app is in foreground you shouldn't be having to do it manually, I think we should have a method that receive the Notification object and provides the Notification Builder already filled with everything.

For instance I think the OS also download the image (if there) and build a bitmap to add to the notification and lot of other stuff.

Thanks

**Comment by danielesegato** [comment]
I got no template :)

by the way I realized this probably wasn't the place to do such a feature request and i've open this: https://github.com/firebase/firebase-android-sdk/issues/1663

**Comment by ashwinraghav** [comment]
Closing in favour of the other issue
