### ISSUE TITLE
No default large icon in push 

### ISSUE THREAD

**Issue by PenzK** [firebase/quickstart-android#113]
- Android device: Nexus, Samsung
- Android OS version: 6.0+
- Google Play Services version: 3.0.0
- Firebase/Play Services SDK version: 9.4.0
  
  I received push from FCM with notification and data, I need this type to handle on iOs also
  There is small icon which I have defined in notification it works on nexus, BUT not on samsung
  on samsng device there is empty space in status bar
  and on every device there is no large icon , it does not take ic_launcher
  just grey circle with small icon and just grey circle without icon on samsung

**Comment by kroikie** [comment]
Hi @PenzK what are you using to send the notifications? If you are using the HTTP API then could you include the request you are using?

**Comment by kroikie** [comment]
Hi @PenzK are you still facing this issue?

**Comment by kroikie** [comment]
Hi @PenzK you can now specify a custom default icon to be used with notification messages, this should work on more devices like the Samsungs that you were having issues with. There is still no large icon specification so if that is a must for you I'd send different messages to iOS and Android.

See more about the custom default icon in the [docs.](https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest)
