### ISSUE TITLE
Barcode scanner detected wrong barcode sometimes

### ISSUE THREAD

**Issue by longld103** [firebase/quickstart-android#1130]
![failed](https://user-images.githubusercontent.com/8160105/84851242-f4a6d500-b083-11ea-98f7-523619697b67.jpg)

These are results of detector. String `1209-002558GK28E21060524860000321` is correct

1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-, 9ZGK18E210523242150321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
3410702717477
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-, 9ZGK18E210523242150321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321

**Comment by longld103** [comment]
@zhouyiself Could you help me check

**Comment by samtstern** [comment]
@longld103 it looks like you have the correct result the majority of the time, can you explain what the issue is?

Please use the issue template when filing issue.s

**Comment by longld103** [comment]
### Step 1: Describe your environment

  * Android device: Samsung galaxy note10 (N975F)
  * Android OS version: Android 10
  * Google Play Services version: com.google.gms:google-services:4.3.3
  * Firebase/Play Services SDK version: com.google.firebase:firebase-ml-vision:24.0.3
  
### Step 2: Describe the problem:
I'm using camera2 api, get bitmap from onImageAvaiable function > put the bitmap to firebase barcode detector
#### Steps to reproduce:

  1. live stream camera view and focus to the barcode
  
#### Observed Results:

  * These are results of detector. String `1209-002558GK28E21060524860000321` is correct

1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-, 9ZGK18E210523242150321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
3410702717477
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-, 9ZGK18E210523242150321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
  
#### Expected Results:

  * always return `1209-002558GK28E21060524860000321` string value
  
#### Relevant Code:
This is my code:
        firebaseDetector = FirebaseVision.getInstance().getVisionBarcodeDetector();
and
          firebaseDetector.detectInImage(image)

**Comment by samtstern** [comment]
@longld103 the correct response is returned 12/15 frames.  Unfortunately there's no way to guarantee you get the correct response on every single frame, especially when the source image is imperfect (like yours).

I would suggest waiting until you get the same response in two frames, that way you know it's right.

**Comment by longld103** [comment]
Hi @samtstern 
When I tested with high quality image, the issue still occur but wrong rate down to <1%.
FirebaseBarcodeScanner is great however it not have trust 100%
So the point of the issue is input image not good or FirebaseBarcodeScanner can't decode correct 100%?

<img width="1144" alt="Screen Shot 2020-06-19 at 8 15 52 AM" src="https://user-images.githubusercontent.com/8160105/85088160-a28fbc00-b209-11ea-8b78-030e67fde49c.png">
these are results:
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
1118188288888
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321
9122181222222
1209-002558GK28E21060524860000321
1209-002558GK28E21060524860000321

**Comment by samtstern** [comment]
@longld103 thank you for trying again with a higher-quality image, that's really helpful.

Unfortunately we can't count on 100% accuracy for MLKit because there are too many factors:

- Phone cameras
- Lenses and focus distance
- Variable "correct" bar code widths

I would suggest the following ways to make your application more resilient:

- Wait until you get two results that are the same, it is highly likely that's correct.
- If you know the size of the barcode you're expecting, wait until you get a result of the right length.

**Comment by longld103** [comment]
@samtstern Thank for your reply. MLKit is wonderful :kissing_heart:
