### ISSUE TITLE
MLkit barcode scanner cannot decode simple 1D code, Example "2"

### ISSUE THREAD

**Issue by longld103** [firebase/quickstart-android#1131]
<img width="251" alt="Screen Shot 2020-06-17 at 10 26 38 AM" src="https://user-images.githubusercontent.com/8160105/84851690-2e2c1000-b085-11ea-9b22-b3f76a7a3595.png">

Can't read barcode of one character

**Comment by longld103** [comment]
@zhouyiself Could you help me check

**Comment by samtstern** [comment]
@longld103 please use the issue template when filing issues, this is not enough information to debug.
