### ISSUE TITLE
Not receiving firebase-inappmessaging

### ISSUE THREAD

**Issue by AmrutHaridas** [firebase/quickstart-android#1137]
### Step 1: Describe your environment

  * Android device: Lenovo K50a40 / Samsung T330NU
  * Android OS version:  6.0 / 5.1.1
  * Google Play Services version: 20.1.17 /20.1.28
  * Firebase/Play Services SDK version: com.google.firebase:firebase-database:17.0.0
  * FirebaseUI version: com.firebaseui:firebase-ui-database:5.0.0
  
### Step 2: Describe the problem:

I am not able to receive firebase-In-App Messaging. 
I have created new campaign and trying to send it to my Test Device.I can see app's Firebase installation ID in the Android studio logcat.
Please let us know whats wrong in the gradle dependencies.

#### Steps to reproduce:

  1. set the gradle dependencies as mentioned below
  2. Create a new In-App message Campaign and send it to Test Device (Emulator or real device)
  3. 
  
#### Observed Results:

  *  We have my another project where we have migrated our 2nd  project to androidx and there I am following this [guide](https://firebase.google.com/docs/in-app-messaging/get-started?authuser=0&platform=android) which works perfectly. but in  main project we couldn't migrate to androidx as there were too many various errors  and finally we had to give-up.. 
so in main project planning to stay on same version and not to upgrade to AndroidX.
  
#### Expected Results:

  * I should receive Firebase In-app message on my test device. 
  
#### Relevant Code:

  ```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 28

    defaultConfig {
        applicationId "<my package name>"
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }


}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.support:appcompat-v7:28.0.0'
    implementation 'com.android.support.constraint:constraint-layout:1.1.3'
    testImplementation 'junit:junit:4.12'
    implementation 'com.android.support:design:28.0.0'

    implementation 'com.android.support:recyclerview-v7:28.0.0'

    androidTestImplementation 'com.android.support.test:runner:1.0.2'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.2'

    implementation 'com.google.firebase:firebase-database:17.0.0'
    implementation 'com.google.firebase:firebase-core:16.0.9'
    implementation 'com.google.firebase:firebase-auth:17.0.0'
    implementation 'com.firebaseui:firebase-ui-database:5.0.0'
    implementation 'com.google.firebase:firebase-storage:17.0.0'

    implementation 'com.google.firebase:firebase-inappmessaging-display:17.0.2'
    implementation 'com.google.firebase:firebase-analytics:16.0.6'

  
}


apply plugin: 'com.google.gms.google-services'

  ```

**Comment by samtstern** [comment]
@AmrutHaridas the best way to make sure you're getting your dependencies right is to use the Bill of Materials (BoM):
https://firebase.google.com/docs/android/setup#firebase-bom

So in your case it would look like this:
```
  // This is the only version number you need!
  implementation platform('com.google.firebase:firebase-bom:25.5.0')

  implementation 'com.google.firebase:firebase-database'
  implementation 'com.google.firebase:firebase-core'
  implementation 'com.google.firebase:firebase-auth'
  implementation 'com.google.firebase:firebase-storage'
  implementation 'com.google.firebase:firebase-inappmessaging-display'
  implementation 'com.google.firebase:firebase-analytics'

  // FirebaseUI is not part of the BoM but 6.2.1 is the latest
  implementation 'com.firebaseui:firebase-ui-database:6.2.1'
```

Let me know if that helps!

**Comment by AmrutHaridas** [comment]
Thanks @samtstern I tried as you said..but I am getting following error. I also tried to change the `firebase-bom` version to match it to dependencies I am using in my project. but I get same error.

* What went wrong:
A problem occurred evaluating project ':app'.
Could not find method platform() for arguments [com.google.firebase:firebase-bom:25.5.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

CONFIGURE FAILED in 1s
Could not find method platform() for arguments [com.google.firebase:firebase-bom:25.5.0] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

**Comment by AmrutHaridas** [comment]
other way .. I checked [Firebase Bill of Materials (Firebase BoM) version 18.0.0](https://firebase.google.com/support/release-notes/android#bom_v18-0-0) and updated `inappmessaging` version like below and with this there is no any error but no In-App message either. Not receiving in-app message ...
`implementation 'com.google.firebase:firebase-inappmessaging:17.1.1'
    implementation 'com.google.firebase:firebase-inappmessaging-display:17.1.1'`

**Comment by AmrutHaridas** [comment]
@samtstern we upgraded our project to androidX and with latest dependencies we are now able to send and receive in App messaging. thanks !

**Comment by samtstern** [comment]
@AmrutHaridas that's great, thanks for following up!
