### ISSUE TITLE
How can I test the app?

### ISSUE THREAD

**Issue by manel00** [firebase/quickstart-android#114]
Hi everyone! 

Good job guys! It sounds really good! I want to try to understand this code to improve my firebase knowledge, but it's really annoying to get some errors when I import the project as 'Git' on Android Studio (The last edition). Could you give some information please about duties that must to do to make it working? Thanks you so much

**Comment by samtstern** [comment]
@manel00 what are the errors you're seeing?

**Comment by manel00** [comment]
[http://imgur.com/a/FVC4y](url) This is the problem, thanks hope to get some reply! ;)

**Comment by samtstern** [comment]
Try the instructions here:
http://stackoverflow.com/questions/37310188/failed-to-resolve-com-google-firebasefirebase-core9-0-0/37310513#37310513

That was posted when `9.0.0` was the newest version but the solution is the same for `9.4.0`

**Comment by manel00** [comment]
And should to put my own google-services.json right? hehe. The problem was I didn't had installed google play services and the other one... jeje

**Comment by manel00** [comment]
Sorry but I dont know how to make it work... always giving me the same error... need to paste google-services.json on multiple folders....

**Comment by manel00** [comment]
ok it works finally! just to paste google-services.json on module i want to use right? thanks you ;)

**Comment by samtstern** [comment]
@manel00 glad you finally got it!
