### ISSUE TITLE
Why i can't find the directory of this package "import com.google.firebase.example.fireeats.databinding.ActivityMainBinding;"?

### ISSUE THREAD

**Issue by MemoraApps** [firebase/quickstart-android#1146]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
This is a generated class, it is created at build time.   For more information please see the Android documentation:
https://developer.android.com/topic/libraries/view-binding

Also please do not file issues with an empty template on this repo, it's there to help us help you!
