### ISSUE TITLE
FirebaseVisionImage.fromMediaImage vs fromBitmap

### ISSUE THREAD

**Issue by patolax** [firebase/quickstart-android#1158]
Unfortunttely after releaseing the app that was developed on you sample code does not work on most devices. So I am trying to use CameraX or Camera2 apis. 

Those api output MediaImage. If I use FirebaseVisionImage.fromMediaImage detection is fast and provide desired performance. However, if I use front camera, FirebaseVisionImage.getBitmap outputs a flipped image.

In order to convert MediaImage  to a scaled, rotated and flipped image, I used YuvToRgbConverter.
https://github.com/xizhang/camerax-gpuimage/blob/master/app/src/main/java/com/appinmotion/gpuimage/YuvToRgbConverter.kt

Then output Bitmap is then used in FirebaseVisionImage.fromBitmap method. The detection of this approch is very slow and performane is so poor.

Any reason behind this?

I want to achive the similar performance I got from the smaple camera api, but I want to get the bitmap of correct orientation just like in the sample.

**Comment by rosariopfernandes** [comment]
@tpatikirikorala you might want to have a look at https://github.com/googlesamples/mlkit/tree/master/android

The MLKit samples have been moved there, where they're being updated and properly maintained.

**Comment by samtstern** [comment]
@ulukaya @gkaldev should we remove the `mlkit` samples here and point to the more up-to-dates ones that the Android team is maintaining?

**Comment by djj1109** [comment]
thanks

**Comment by ulukaya** [comment]
Firebase ML-Kit SDK is deprecated, please follow the Google ML-Kit at https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
