### ISSUE TITLE
Can't pass null for argument 'pathString' in child() in adapter recyclerview

### ISSUE THREAD

**Issue by mahmoudadel1999** [firebase/quickstart-android#1181]
package com.example.grocery.adapters;

import android.content.Context;
import android.content.Intent;
import android.text.format.DateFormat;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Filter;
import android.widget.Filterable;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import com.example.grocery.FilterOrderShop;
import com.example.grocery.FilterShops;
import com.example.grocery.R;
import com.example.grocery.activities.OrderDetailsSellerActivity;
import com.example.grocery.models.ModelOrderShop;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import java.util.ArrayList;
import java.util.Calendar;

public class AdapterOrderShop extends RecyclerView.Adapter<AdapterOrderShop.HolderOrderShop>
implements Filterable {

    private Context context;
    public ArrayList<ModelOrderShop> orderShopArrayList,filterList;
    private FilterOrderShop filter;

     public AdapterOrderShop(Context context, ArrayList<ModelOrderShop> orderShopArrayList) {
        this.context = context;
        this.orderShopArrayList = orderShopArrayList;
        this.filterList=orderShopArrayList;
    }

    @NonNull
    @Override
    public HolderOrderShop onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View view = LayoutInflater.from(context).inflate(R.layout.row_order_seller,parent,false);
        return new HolderOrderShop(view);
    }

    @Override
    public void onBindViewHolder(@NonNull HolderOrderShop holder, final int position) {
//get data
      final   ModelOrderShop modelOrderShop = orderShopArrayList.get(position);

        String orderId = modelOrderShop.getOrderId();
        String orderBy = modelOrderShop.getOrderBy();
        String orderCost = modelOrderShop.getOrderCost();
        String orderStatus = modelOrderShop.getOrderStatus();
        String orderTime = modelOrderShop.getOrderTime();
        String orderTo = modelOrderShop.getOrderTo();
        //load user /buyer Info
         loadUserInfo(modelOrderShop,holder);
        //set data
        holder.amountTv.setText("Amount : شيكل"+orderCost);
        holder.statusTv.setText(orderStatus);
        holder.orderIdTv.setText("Order ID :"+orderId);
//convert order status
        if (orderStatus.equals("In Progress")){
            holder.statusTv.setTextColor(context.getResources().getColor(R.color.colorPrimary));
        }else  if (orderStatus.equals("Completed")){
            holder.statusTv.setTextColor(context.getResources().getColor(R.color.colorGreen));
        }else  if (orderStatus.equals("Canceled")){
            holder.statusTv.setTextColor(context.getResources().getColor(R.color.colorRed));
        }
    //convert Time
        Calendar calendar = Calendar.getInstance();
        calendar.setTimeInMillis(Long.parseLong(orderTime));
        String formatedDate = DateFormat.format("dd/MM/yyyy",calendar).toString();
        holder.orderDateTv.setText(formatedDate);

        holder.itemView.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                //open order details
                Intent intent = new Intent(context, OrderDetailsSellerActivity.class);
                intent.putExtra("orderId",orderId);//to load order info
                intent.putExtra("orderBy",orderBy);//to load user info
                context.startActivity(intent);
            }
        });
    }

    private void loadUserInfo(ModelOrderShop modelOrderShop, HolderOrderShop holder) {
DatabaseReference reference = FirebaseDatabase.getInstance().getReference("Users");
reference.child(modelOrderShop.getOrderBy()).addValueEventListener(new ValueEventListener() {
    @Override
    public void onDataChange(@NonNull DataSnapshot snapshot) {
   String email = ""+snapshot.child("email").getValue();
   holder.emailTv.setText(email);
    }

    @Override
    public void onCancelled(@NonNull DatabaseError error) {

    }
});
    }

    @Override
    public int getItemCount() {
        return orderShopArrayList.size();
    }

    @Override
    public Filter getFilter() {
        if (filter == null){
            filter = new FilterOrderShop(this,filterList);
        }
        return filter;
    }

    class HolderOrderShop extends RecyclerView.ViewHolder{

        private TextView orderIdTv,orderDateTv,emailTv,amountTv,statusTv;

        public HolderOrderShop(@NonNull View itemView) {
            super(itemView);
            //init views
            orderIdTv = itemView.findViewById( R.id.orderIdTv);
            orderDateTv  = itemView.findViewById( R.id.orderDateTv);
            amountTv  = itemView.findViewById( R.id.amountTv);
            emailTv = itemView.findViewById( R.id.emailTv);
            statusTv = itemView.findViewById( R.id.statusTv);
        }
    }
}

**Comment by samtstern** [comment]
@mahmoudadel1999 please use the issue template and only file bugs here if they are related to bugs in these samples.  If you need someone to help you debug your app, try StackOverflow.
