### ISSUE TITLE
Firebase Storage: pausing/resuming will cause in wrong downloaded percentage

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-android#119]
The title says it all. When I am downloading a file from the storage like this:

```java
FileDownloadTask task = $reference.getFile($destinationFile);
```
The download progress starts and dispatched the progress all fine. However if I pause the download and resume it, the returning ```getBytesTransferred()``` is wrong and when I try to get the downloaded percentage with ```getBytesTransferred() / getTotalByteCount() * 100``` the result is a number larger than 100%! depending on how many times we have paused/resumed the download progress, the percentage number goes more crazy!

in my last download test, it finished at 290%. Nonetheless, the downloaded file is correctly downloaded with the correct size and it is useable. it's just that when pausing/resuming the download, the returning ```getBytesTransferred()``` seems corrupted.

Am I doing something wrong?

**Comment by samtstern** [comment]
@myflashlab that is very interesting.  If you never pause the download is `getBytesTransferred` equal to `getTotalByteCount` at the end?

**Comment by samtstern** [comment]
Ok I can reproduce this issue, will escalate accordingly.  Thanks for reporting!

**Comment by samtstern** [comment]
@myflashlab the fix for this bug will be included in a future release :+1:

**Comment by myflashlab** [comment]
Just tried Firebase 10.0.0 and this problem is still not fixed. Thought to let you know about this.

**Comment by luoyexk** [comment]
I have the same problem, did they forget to fix it, or is there something wrong with my code?

```
gradle

firebaseBOMVersion = '28.1.0'
implementation platform("com.google.firebase:firebase-bom:$firebaseBOMVersion")
implementation 'com.google.firebase:firebase-storage-ktx'
implementation 'com.firebaseui:firebase-ui-storage:7.2.0'
```

```
    private fun downloadApk(reference: StorageReference, destinationFile: File) {
        downloadTask = reference.getFile(destinationFile).apply {
            addOnProgressListener {
                progressState.tryEmit(calculateDownloadProgress(it))
            }
            addOnSuccessListener {
                viewModelScope.launch {
                    haveDownloaded(reference, destinationFile)
                }
            }
            addOnFailureListener {
            }
        }
    }
```
```
    private fun calculateDownloadProgress(it: FileDownloadTask.TaskSnapshot) = if (it.bytesTransferred == it.totalByteCount) {
        99
    } else {
        // When resume download, bytesTransferred always increases suddenly and returns to the value before the last pause seconds later
        ((100.0 * it.bytesTransferred) / it.totalByteCount).coerceAtMost(99.0)
    }.toInt()
```
