### ISSUE TITLE
Get facebook user's info

### ISSUE THREAD

**Issue by Neno0o** [firebase/quickstart-android#12]
I have no clue about getting user's facebook info from the current Firebase version. In old versions, onAuthenticated callback function had AuthData object which used to get user's info. How can this be done now?

**Comment by samtstern** [comment]
@Neno0o which information are you looking for?  Email, name, and profile photo should all be provided by the `FirebaseUser` object which you can access either from `AuthResult` or by calling `FirbaseAuth.getCurrentUser()`.

**Comment by Neno0o** [comment]
thanks, sorry my bad.
