### ISSUE TITLE
Firebase Storage: canceling a download works but Exception is null!

### ISSUE THREAD

**Issue by myflashlab** [firebase/quickstart-android#120]
I start the download just fine with ```FileDownloadTask task = $reference.getFile($destinationFile);``` but when I cancel the download ```Exception e``` is null! The same thing works fine on the UploadTask.

```java
FileDownloadTask task = $reference.getFile($destinationFile);

OnFailureListener listener = new OnFailureListener()
{
	@Override
	public void onFailure(@NonNull Exception e)
	{
		if(e != null)
		{
			
		}
		else
		{
			
		}
	}
};

task.addOnFailureListener(listener);
```

Please advice.

**Comment by samtstern** [comment]
@myflashlab let me try to verify this (and your other issue)

**Comment by samtstern** [comment]
Verified!  Thanks for reporting, will try and get this addressed.

**Comment by samtstern** [comment]
@myflashlab the fix for this bug will be included in a future release :+1:
