### ISSUE TITLE
Firebase Auth 20.0.0 update has crash

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/quickstart-android#1207]
All of a sudden there is a crash within SMS verification using Firebase UI and Firebase Auth.

`E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.happyluck9.pirate.slot, PID: 6678
    java.lang.NoSuchMethodError: No virtual method verifyPhoneNumber(Ljava/lang/String;JLjava/util/concurrent/TimeUnit;Ljava/util/concurrent/Executor;Lcom/google/firebase/auth/l0$b;Lcom/google/firebase/auth/l0$a;)V in class Lcom/google/firebase/auth/l0; or its super classes (declaration of 'com.google.firebase.auth.l0' appears in /data/app/com.myapp.packagename-LrsjEuG5HuZecGq-TAhBrQ==/base.apk)
        at com.firebase.ui.auth.ui.phone.d.v(PhoneNumberVerificationHandler.java:32)
        at com.firebase.ui.auth.ui.phone.b.D1(CheckPhoneNumberFragment.java:164)
        at com.firebase.ui.auth.ui.phone.b.onClick(CheckPhoneNumberFragment.java:140)
        at android.view.View.performClick(View.java:7252)
        at android.view.View.performClickInternal(View.java:7229)
        at android.view.View.access$3500(View.java:821)
        at android.view.View$PerformClick.run(View.java:27765)
        at android.os.Handler.handleCallback(Handler.java:914)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)`

This are the dependencies

```
  implementation 'com.google.firebase:firebase-config:20.0.0'
    implementation 'com.google.firebase:firebase-analytics:18.0.0'
    implementation 'com.google.firebase:firebase-firestore:22.0.0'
    implementation 'com.google.firebase:firebase-messaging:21.0.0'
    implementation 'com.google.firebase:firebase-crashlytics:17.2.2'
    implementation 'com.google.firebase:firebase-inappmessaging:19.1.2'
    implementation 'com.google.firebase:firebase-inappmessaging-display:19.1.2'
    // FirebaseUI for Firebase Auth
    implementation 'com.firebaseui:firebase-ui-auth:6.2.0'

    implementation 'com.google.firebase:firebase-auth:20.0.0'
```

One of the reason why I do not update dependency if not necessary is because of this crashes cause by the updates :< and unfortunately the app with this issue is already live in the store.

**Comment by rosariopfernandes** [comment]
@ArcherEmiya05 You say this crash happens in Auth 20.0.0, but in your dependencies I see 19.4.0

**Comment by ArcherEmiya05** [comment]
> 
> 
> @ArcherEmiya05 You say this crash happens in Auth 20.0.0, but in your dependencies I see 19.4.0

Sorry, updated

**Comment by rosariopfernandes** [comment]
@ArcherEmiya05 Thanks for the update, I was able to reproduce this error on my side.
This seems to be due to the fact that [v20.0.0](https://firebase.google.com/support/release-notes/android#auth_v20-0-0) removed the `PhoneAuthProvider#verifyPhoneNumber` method that takes an Executor as a parameter, which is still being used by FirebaseAuthUI.

A fix will probably come out with Firebase UI v7.0.0 . For now, I'd recommend you rollback to `19.4.0` and re-deploy the app to the PlayStore while we wait for the next Firebase UI release.

---

I feel like this issue should be moved to the FirebaseUI repo.

**Comment by ArcherEmiya05** [comment]
> 
> 
> @ArcherEmiya05 Thanks for the update, I was able to reproduce this error on my side.
> This seems to be due to the fact that [v20.0.0](https://firebase.google.com/support/release-notes/android#auth_v20-0-0) removed the `PhoneAuthProvider#verifyPhoneNumber` method that takes an Executor as a parameter, which is still being used by FirebaseAuthUI.
> 
> A fix will probably come out with Firebase UI v7.0.0 . For now, I'd recommend you rollback to `19.4.0` and re-deploy the app to the PlayStore while we wait for the next Firebase UI release.
> 
> I feel like this issue should be moved to the FirebaseUI repo.

Yes I agree after reading the changelog of 20.0.0 of Firebase Auth.

**Comment by samtstern** [comment]
@rosariopfernandes thanks for helping out with the debugging here!
@ArcherEmiya05 we're working on releasing a `7.0.0` version of FirebaseUI soon that will depend on the latest Firebase Auth SDK.  For now they are incompatible, FirebaseUI `6.x` only works with Firebase Auth `19.x`.
