### ISSUE TITLE
Android notification icon when app background

### ISSUE THREAD

**Issue by tekinarslan** [firebase/quickstart-android#121]
Hi ,
How can I change notification icon and icon area's color when my app in background. Also, I open app and send push,Then onMessageReceived called and I create my custom notification. 

Thanks

**Comment by kroikie** [comment]
Hi @tekinarslan you cannot use FCM to set the notification icon at this time, but this is a know issue and the team is working on a fix.

**Comment by einicher** [comment]
Does this work by now? I only find sources on how to set the default notification icon but not on how to set individual icons.

**Comment by kroikie** [comment]
@einicher You can set the notification icon to any resource in your application via the API ([reference](https://firebase.google.com/docs/reference/fcm/rest/v1/projects.messages#AndroidNotification)). The default notification icon is used when no icon is set in the notification message.

**Comment by einicher** [comment]
Any resource means, when i have a `messages.png` icon in my drawable folders and i set icon to `messages.png` it should work? Cause it does not.

**Comment by kroikie** [comment]
@einicher for example in the sample app, if you remove the default notification metadata from the [AndroidManifest.xml](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/AndroidManifest.xml#L13) then send a notification message without specifying the icon eg:

```
{
	"message": {
		"topic": "news",
		"notification": {
			"title": "Breaking News",
			"body": "Catch up on breaking news stories."
		}
	}
}
```

The launcher icon is used.

However if you add the icon as a notification override specifying the resource `ic_stat_ic_notification` which represents `ic_stat_ic_notification.png` eg:

```
{
	"message": {
		"topic": "news",
		"notification": {
			"title": "Breaking News",
			"body": "Catch up on breaking news stories."
		},
		"android": {
			"notification": {
				"icon": "ic_stat_ic_notification"
			}
		}
	}
}
```

The resource image is used as the icon.
