### ISSUE TITLE
why the in app message appears only when the button is pressed first time

### ISSUE THREAD

**Issue by hanchang97** [firebase/quickstart-android#1239]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
### Step 2: Describe the problem:

Firebase in app message only appears when I press the trigger button first time.
So I deleted the app and install again.
But I had the same problem.
Any idea why this is happening..?

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@hanchang97 please use the issue template when filing issues or we won't be able to help you!
