### ISSUE TITLE
Bundle data is not cleared when tap application from background (click_action cativity), firebase bundle values loading again and again,how to clear that bundle values?

### ISSUE THREAD

**Issue by alrweerasekara** [firebase/quickstart-android#124]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@alrweerasekara please use the issue template, it is there to help us understand your issue.  From the information you have provided I can't understand the problem, it's not clear what "firebase bundle values " are.

Please fill out the issue template and re-open the issue if you still need help.

**Comment by alrweerasekara** [comment]
thank your reply.i am sorry about my queation is not cleared.anyway.i got a solution for my problems .its not a issues of firebase.thank you again.

**Comment by samtstern** [comment]
@alrweerasekara glad you got it working!
