### ISSUE TITLE
our little dpebot got stuck/blocked :(

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/quickstart-android#1253]
@dpetbot seems to be pushing changes to the correct branch (`dpebot-repositorygardener`), but it mentions a PR that doesn't seem to exist: #1231. I tried opening a PR with the changes from that branch, but GitHub doesn't allow it because it detected a similar open PR (our ghost #1231).

**Comment by samtstern** [comment]
@rosariopfernandes huh I have no idea how a ghost PR like #1231 could happen!

**Comment by russparker37** [comment]
@

**Comment by samtstern** [comment]
See #1255
