### ISSUE TITLE
How can import import the code into android studio successfully

### ISSUE THREAD

**Issue by michaelMdMlavia** [firebase/quickstart-android#1256]
I have been trying to import the code to android studio I get so many errors .Please help

**Comment by michaelMdMlavia** [comment]
Please see here 
![Screenshot (409)](https://user-images.githubusercontent.com/77862705/108284396-d0a90f80-718d-11eb-9bd6-ec4e80c56425.png)
![Screenshot (408)](https://user-images.githubusercontent.com/77862705/108284401-d30b6980-718d-11eb-8840-6cf27c108496.png)

**Comment by michaelMdMlavia** [comment]
are there any dependencies, or anythin I should do the manifest file? as for the buttons and the class name I can work around that  still new at android studio

**Comment by samtstern** [comment]
@michaelMdMlavia this is not enough information to help you, we don't know what errors you're getting or what you've tried.  I would suggest asking on StackOverflow which is the better place to get general environment help like this.
