### ISSUE TITLE
FirebaseMessagingService forces you to implement a method zzaa?

### ISSUE THREAD

**Issue by kenMarquez** [firebase/quickstart-android#126]
FirebaseMessagingService forces you to implement a method that returns an Intent

```java
    @Override
    protected Intent zzaa(Intent intent) {
        return null;
    }
```

I can not know that I do with this method that is encrypted by the compiler, this method did not have to implement it before and now it is causing errrores and no docuemntacion about this

I am using the version of firebase messaging:

compile 'com.google.firebase: firebase-messaging: 9.0.0'

**Comment by samtstern** [comment]
@kenMarquez can you elaborate on what you mean by 'forces you to implement'?  This is not implemented in the `MyFirebaseMessagingService` class in this quickstart and I can confirm that class compiles/works.

**Comment by samtstern** [comment]
Also in general you should prefer the latest version of Firebase, which is `9.4.0`.  Version `9.0.0` had a number of issues that have since been fixes.

**Comment by kenMarquez** [comment]
@samtstern  thank you very much has been solved with the version.
