### ISSUE TITLE
Multiple different dependency versions

### ISSUE THREAD

**Issue by homels** [firebase/quickstart-android#1260]
When I cloned the project, I found that it depends on different versions of the same library.

For example, it seems to contain okhttp3:3.12.1, okhttp3:3.12.7

**Comment by homels** [comment]
![Uploading WeChat1543d265e0f5fda9c3ddba1d76a66dba.png…]()

**Comment by samtstern** [comment]
@homels that's normally not a problem, both are on the `3` major version and they should be compatible and they're even the same minor version `3.12.` so they should have the same API.

Gradle handles choosing a version when multiple versions of the same library appear in the dependency tree. This is extremely common in Android projects.

https://docs.gradle.org/current/userguide/dependency_resolution.html
