### ISSUE TITLE
onMessageReceived not called when app is in background

### ISSUE THREAD

**Issue by Softkeydel** [firebase/quickstart-android#1266]
I need to send information through pending intent. When the app in foreground onMessageReceived being called and I can get those information but  if the app in background onMessageReceived not being called and tapping on notification form tray app is starting from the launcher screen and I can't get those information. Please help asap.

Thanks

**Comment by samtstern** [comment]
@Softkeydel please look at some of the existing issues on this topic, this is not a new issue with the quickstart apps:
https://github.com/firebase/quickstart-android/issues?q=is%3Aissue+background

**Comment by Softkeydel** [comment]
I've already seen these but none of those worked for me. Please help
