### ISSUE TITLE
Crashlytics not sending any crash reports, getting " Settings request failed" error

### ISSUE THREAD

**Issue by TamaraShlomovMoveo** [firebase/quickstart-android#1267]
![image](https://user-images.githubusercontent.com/37972688/111159733-177a0180-85a2-11eb-9337-e2aef5d36a31.png)
android :
app-level:
classpath 'com.android.tools.build:gradle:3.3.1'
classpath 'com.google.gms:google-services:4.3.5'  
classpath 'com.google.firebase:firebase-crashlytics-gradle:2.2.0'

module-level:
apply plugin: 'com.android.application'
apply plugin: 'com.google.gms.google-services' 
apply plugin: 'com.google.firebase.crashlytics'

  implementation platform('com.google.firebase:firebase-bom:26.7.0')
    implementation 'com.google.firebase:firebase-analytics'
    implementation 'com.google.firebase:firebase-crashlytics'

I'm getting an error when trying to crash the app:

"FirebaseCrashlytics: Settings request failed.
03-15 15:19:06.133 12639 12836 E FirebaseCrashlytics: java.io.FileNotFoundException: https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:---:android:---/settings?instance=---&build_version=1&display_version=7.2&source=1"

and I also saw that I get "firebase-crashlytics-ebabled:false" - and I already enable it , so I don't understand
"
03-15 12:49:36.460  7341  7341 D FirebaseCrashlytics: Loaded cached settings: {"settings_version":3,"cache_duration":86400,"features":{"collect_logged_exceptions":true,"collect_reports":true,"collect_analytics":false,"prompt_enabled":false,"push_enabled":false,"firebase_crashlytics_enabled":false},"app":{"status":"activated","update_required":false,"report_upload_variant":2,"native_report_upload_variant":2},"fabric":{"org_id":"--------","bundle_id":"com.samsung.android.game.gamehome"},"expires_at":-----} "

please help me - thank you !!

**Comment by samtstern** [comment]
@TamaraShlomovMoveo this is not an issue with the quickstart app, please try StackOverflow or Firebase support for debugging.

**Comment by TamaraShlomovMoveo** [comment]
> @TamaraShlomovMoveo this is not an issue with the quickstart app, please try StackOverflow or Firebase support for debugging.

hi Sam, I saw the same issue opened here but on iOS and Unity , so I think this is the right place
