### ISSUE TITLE
Sticker packs are not showing up in Gboard

### ISSUE THREAD

**Issue by nrotonda** [firebase/quickstart-android#1271]
### Step 1: Describe your environment

  * Android device: Pixel 4 XL (Build number RQ2A.210305.006)
  * Android OS version: 11
  * Google Play Services version: 4.3.5
  * Firebase/Play Services SDK version: firebase-appindexing:19.2.0
  
### Step 2: Describe the problem:
Stickers from the app-indexing app do not show up in my gboard on my phone. My gboard version is 10.3.05.356487417.
Seems to be a pretty recent issue because we just had stickers disappear from my app as well.

#### Steps to reproduce:

  1. Install app-indexing app and tap add stickers from Kotlin activity
  2. Open up messages and navigate to stickers from gboard
  3. See that stickers are not in listed packs on right side
  
#### Observed Results:

  * No sticker pack
  
#### Expected Results:

  * Sticker pack should show up in listed packs on top menu bar of gboard

**Comment by rosariopfernandes** [comment]
@nrotonda This has been previously reported in firebase/firebase-android-sdk#2536

The reply to that issue states that:

>we can’t guarantee that App Indexing will still work as expected since it will be eventually removed from the Firebase product set. Currently, we do not recommend using App Indexing for most Firebase apps and no longer support this feature.

**Comment by nrotonda** [comment]
Ok thanks! Is there an alternate way in Firebase to add stickers to Android? That's the only way I can find in the documentation.

**Comment by samtstern** [comment]
Thanks @rosariopfernandes for providing that link. @nrotonda I would ask on that `firebase-android-sdk` issue if someone knows of a workaround, but unfortunately this may just be broken 😢
