### ISSUE TITLE
how to get RemoteInput text in FirebaseMessagingService

### ISSUE THREAD

**Issue by bhanuka96** [firebase/quickstart-android#1280]
I am creating **reply action button** in the message notification. I need to send that text to firestore when the user press sends button in the notification. 

**This is my FirebaseMessagingService service**

     override fun onMessageReceived(remoteMessage: RemoteMessage) {
    
            if (remoteMessage.data.isNotEmpty()) {
                if (!isAppForground(this)) {
                    sendNotification(...)
                }
            }
    
        private fun sendNotification(messageBody: String, messageTitle: String, groupKey: String, bigPicture: String) {
            val channelId = getString(R.string.default_notification_channel_id)
            val intent = Intent(this, MainActivity::class.java)
    
            //Inline Notification
            val replyLabel = "Enter your reply here"
    
            //Initialise RemoteInput
    
            val KEY_REPLY = "key_reply"
            val remoteInput: RemoteInput = RemoteInput.Builder(KEY_REPLY)
                    .setLabel(replyLabel)
                    .build()
    
    
            intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP)
            val pendingIntent = PendingIntent.getActivity(this, 0, intent,
                    PendingIntent.FLAG_ONE_SHOT)
    
            val action: NotificationCompat.Action =
                    NotificationCompat.Action.Builder(android.R.mipmap.sym_def_app_icon,
                            "Reply", pendingIntent)
                            .addRemoteInput(remoteInput)
                            .build()
    
            val notificationBuilder = NotificationCompat.Builder(this, channelId)
                    .setSmallIcon(R.drawable.yc_logo)
                    .setContentTitle(messageTitle)
                    .setContentText(messageBody)
                    .setGroup(groupKey)
                    .setAutoCancel(true)
                    .setLargeIcon(BitmapFactory.decodeResource(resources, R.drawable.yc_logo))
                    .setSound(defaultSoundUri)
                    .setPriority(2)
                    .setPriority(1)
                    .setDefaults(2)
                    .setContentIntent(pendingIntent)
    
            notificationBuilder.addAction(action)
    
    
            var notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
    
            val r = Random()
            // Since android Oreo notification channel is needed.
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                val channel = NotificationChannel(channelId,
                        "AppName",
                        NotificationManager.IMPORTANCE_HIGH)
                channel.setLockscreenVisibility(Notification.VISIBILITY_PUBLIC)
                notificationManager = getSystemService(NotificationManager::class.java)
                notificationManager.createNotificationChannel(channel)
            }
    
            notificationManager.notify(0, groupBuilder.build())
            notificationManager.notify(r.nextInt(), notificationBuilder.build())
        }
     }

I create another `broadcastReceiver` to get user input text (BUT This one not working)

     class NotificationReceiver: BroadcastReceiver() {
        private val db = Firebase.firestore
    
        override fun onReceive(context: Context?, intent: Intent?) {
    
            val remoteInput = RemoteInput.getResultsFromIntent(intent)
    
            val inputString = remoteInput?.getCharSequence("key_reply").toString()
    
            if (remoteInput != null) {
    
                val inputString = remoteInput.getCharSequence("key_reply").toString()
    
                if (inputString == "") {
                    return
                }
    
                val user = hashMapOf(
                        "test" to "data",
                        "test1" to "data"
                )
    
                db.collection("testingData")
                        .add(user)
            }
        }
    }

And also I want to get `remoteMessage.data` to broadcaseReceiver.

**Comment by samtstern** [comment]
@bhanuka96 this is a general Android programming question and not something related to the code in this quickstart, please try StackOverflow.

**Comment by bhanuka96** [comment]
@samtstern okay. I already added. waiting 3 days. https://stackoverflow.com/q/67112824/8822337
