### ISSUE TITLE
dont get notif when app is killed.

### ISSUE THREAD

**Issue by HartzDev** [firebase/quickstart-android#130]
Hai,

i test on : 
Asuz zenfone.
Lollipop.
chipset : intel

when app in foreground and background, i get notif.
but when i kill the app, i try send notif, but i dont get it.

anyone, can help me?

**Comment by Svoka** [comment]
https://github.com/firebase/quickstart-android/issues/4

**Comment by samtstern** [comment]
@HartzDev as @Svoka said there has already been a lot of discussion in #4.  Since you have not provided any details to suggest your issues is different, i will close this one and point you there.
