### ISSUE TITLE
Firebase AppIndexing no longer working with Gboard

### ISSUE THREAD

**Issue by tucson-tom** [firebase/quickstart-android#1300]
### Step 1: Describe your environment

  * Android device: Pixel 2
  * Android OS version: 11
  * Google Play Services version: Jan 1, 2021
  * Firebase/Play Services SDK version: firebase-appindexing:20.0.0
  
### Step 2: Describe the problem:

com.tucson.thisistucsonstickerpack is no longer loading stickers in Gboard on any device, including mine.

#### Steps to reproduce:

Install and run com.tucson.thisistucsonstickerpack.
  
#### Observed Results:

The software itself says that stickers are loaded successfully but then they do not appear anywhere in Gboard.  Looks like significant updates to Gboard itself have occurred that may have broken Firebase AppIndexing for custom sticker pack apps.

I know there is a rough sticker limit of about 85-ish stickers per pack (#435).  We're currently hanging around 70 stickers.  I reduced the limit in the dev version to 50 in case that's the issue but no change and no errors are occurring anywhere.  I then went back to the previous limit of 80 and modified the message in `AppIndexingUtil.java` to emit the number of indexables (it is now `"Successfully added " + (indexables.size() - 1) + " stickers"`) and the app says "Successfully added 71 stickers" which indicates that everything is working as expected on the app end of things.  That Toast is the last step inside the app to register or fail registration but it calls the success listener, indicating success.  Besides, the error from too many stickers in #435 was Toasted as an actual error to the user rather than saying "Success."  In this case, it is saying "Success" but is doing nothing over in Gboard.  That is, the sticker pack never appears.

#### Expected Results:

Gboard to show the sticker pack category as it's done in the past without issue.

#### Relevant Code:

We haven't changed anything in the app for quite a while other than to add new stickers here and there and, until recently, the app used to work fine even on my devices.  Our code is very similar to the code as seen in this quickstart repo since the code is what our app was based on.

My general thought is that this custom usage of Firebase AppIndexing doesn't seem like a good way to make sticker packs for Gboard.  It's pretty esoteric and currently broken for us anyway.  The most awkward aspect is that everything within the app can return success but there's no guarantee that stickers will actually appear in Gboard (even when it was working).

**Comment by rosariopfernandes** [comment]
@tucson-tom please see my [comment in #1271](https://github.com/firebase/quickstart-android/issues/1271#issuecomment-807334304)

**Comment by tucson-tom** [comment]
We have unpublished the associated app from Google Play due to Gboard apparently no longer supporting custom stickers via App Indexing and no path for continuity of functionality.  It's a sad day for cute and adorable cactus stickers everywhere.

**Comment by samtstern** [comment]
> It's a sad day for cute and adorable cactus stickers everywhere.

🌵 😢

**Comment by tucson-tom** [comment]
@rosariopfernandes Not sure why you are confused.  Please clarify.  The issue you linked to says that App Indexing is dead.  And our testing is showing that Gboard is not loading stickers via App Indexing and there are no alternatives available.  Removing the app from the Google Play store, especially since the sticker app is not free, is the most responsible thing to do.

**Comment by rosariopfernandes** [comment]
@tucson-tom Oops, my bad. I was looking for a 'sad' reaction and apparently 'confused' is the only one with that face :/

Sad to hear the app was removed from the store. I really hope we get a suitable alternative some day.

**Comment by JeremyR34** [comment]
Spent the 2 last hours trying to make it work until I found this issue...
Sad to see that custom stickers are not supported anymore. 
Even sadder to find no official announcement or update...

**Comment by samtstern** [comment]
Hey everyone. I am really sorry about some of the frustration you have experienced working with AppIndexing. As you noticed, it is definitely no longer fully working and we should have updated our documentation sooner to reflect that.

As of today the App Indexing docs give a much stronger warning to developers that this product should no longer be used in almost all cases: https://firebase.google.com/docs/app-indexing

Your recent comments were the direct motivation for us to finally update the documentation, so we really appreciate your feedback!
