### ISSUE TITLE
How can i get all the devices subscribed to a particular FCM topic?

### ISSUE THREAD

**Issue by George-Kihara** [firebase/quickstart-android#1302]

**Comment by thatfiredev** [comment]
This is not currently possible, as answered in all of these StackOverflow posts:
- https://stackoverflow.com/a/58380643/5861618
- https://stackoverflow.com/a/40861417/5861618
- https://stackoverflow.com/a/39632704/5861618
- https://stackoverflow.com/a/38379251/5861618
