### ISSUE TITLE
Token is written to the log files.

### ISSUE THREAD

**Issue by cyxin577** [firebase/quickstart-android#1319]
Describe the problem:
  1. Token is a piece of sensitive data.
  2. Token is written to the log files.  `Log.d(TAG, "onNewToken:" + token);` in CustomAuthFragment.java.
  
#### Observed Results:

This data leakage may result in session hijacking.
  
#### Expected Results:
Maybe just detele this statement is fine.

Thanks.

**Comment by thatfiredev** [comment]
@cyxin577 we're logging the token for demonstrative purposes. Notice that we're also displaying it on the UI here:

https://github.com/firebase/quickstart-android/blob/a219d94278faff75774509e5b09fb6d0f02004eb/auth/app/src/main/java/com/google/firebase/quickstart/auth/java/CustomAuthFragment.java#L144

Removing that line doesn't seem like a good option, as we want to make it easy for developers to debug their implementation. But maybe we could add a comment stating that this shouldn't be done in production. Does that sound like a good alternative for you?
