### ISSUE TITLE
Request to reopen https://github.com/firebase/quickstart-android/issues/83 

### ISSUE THREAD

**Issue by gdhananjay** [firebase/quickstart-android#1321]
Step 2: Describe your environment
first device:

Android device: LG G3
Android OS version: 5.0
Google Play Services version: 9.2.56
Firebase/Play Services SDK version: 9.2.0
second device:

Android device: asus zenpad 10
Android OS version: 5.0.2
Google Play Services version: 9.2.56
Firebase/Play Services SDK version: 9.2.0
Step 3: Describe the problem:
im trying to test the FCM capabilities using the messaging sample, however messages send via FCM console are highly unstable/unpredictable.
sometimes messages are received within a few seconds, sometimes after a few minutes (could even be over 10 and even 20 minutes!), and sometimes not at all...
this is happening randomly - for example, a message could be received immediately, and a message sent right after it will only be received after 10 minutes.

i have set the priority of the messages to high, and time-to-live to maximum to make sure the messages are not discarded.

Steps to reproduce:
add sample project to a new or existing FCM project
try send messages through FCM messaging console
Observed Results:
random behavior. messages are received with huge delay or not at all

Expected Results:
messages received immediately, or within less than 5 seconds.
`
Relevant Code:
none. sample "messaging" app
`

**Comment by gdhananjay** [comment]
So many users are facing issue with FCM notifications are missing or  not delayed . https://github.com/firebase/quickstart-android/issues/83   issue is closed 3 years back. 
Could you update on this. If it is possible to resolve this issue. Or please highlight it in document. We implemented entire app and now realised that notification are not guaranteed.  Its big set back for us. Please provide uodates

**Comment by kroikie** [comment]
Hi @gdhananjay sorry for the confusion there. Since there are many thing that can result in this message delivery delays I would reachout to [support](https://firebase.google.com/support) for specific situations. One way of better understanding the delivery of messages is by using the [Aggregated delivery API](https://firebase.google.com/docs/cloud-messaging/understand-delivery#aggregated_delivery_data_via_the_data_api).

**Comment by gdhananjay** [comment]
To: 
@kroikie

CC: 
@samtstern
@rosariopfernandes

My request you to not to close this issue. This is not only about delay messages are getting lost. As you said "I would reach-out to support for specific situations." 

Could you please revert back on possible cause for messages are getting lost. 

Please reopen this issue.

**Comment by kroikie** [comment]
@gdhananjay support is really the best place to resolve these issues since there are not specific issues with the SDK that can be employed to address delivery issues. For example if the device you are sending to is force stopping the app then there is nothing you can do with FCM to improve that situation.

Using things like the Aggregation API  will help you understand where and why messages are failing to be delivered then if you see that it is an FCM issue you can reach out to support. But since the issue is not likely an SDK issue then here is not the best place to resolve that.

**Comment by rosariopfernandes** [comment]
@gdhananjay You mentioned you're using this sample, so I assume you're using topics in your app.

It is mentioned on the [Firebase Docs](https://firebase.google.com/docs/cloud-messaging/android/topic-messaging) that:

> Topic messages are optimized for throughput rather than latency. For fast, secure delivery to single devices or small groups of devices, [target messages to registration tokens](https://firebase.google.com/docs/cloud-messaging/send-message#send_messages_to_specific_devices), not topics.

That said, I suggest you send your messages to specific devices if you want them to be delivered quickly.

**Comment by gdhananjay** [comment]
@rosariopfernandes,

CC: 
@kroikie
@samtstern

That seems great help to me. Thanks for your suggestion. Along the line i have a question. Yes, topic messages are optimized for throughput and i have same use case.  Problem in our use case is not latency. Problem is messages are getting lost. We observed this on both android and IOS.  Do you have any direction to work on its resolution for me ?

I was reading additional document and came across https://firebase.google.com/docs/cloud-messaging/concept-options#fanout_throttling

It says :
```
Message fanout is the process of sending a message to multiple devices, such as when you target topics and groups, or when you use the Notifications composer to target audiences or user segments.

Message fanout is not instantaneous and so occasionally you have multiple fanouts in progress concurrently. We limit the number of concurrent message fanouts per project to 1,000. After that, we may reject additional fanout requests or defer the fanout of the requests until some of the already in progress fanouts complete.  
```

Does this means if a topic has more than 1000 subscriptions there is possibility of notification lost due to concurrent fanout ? 
I am too poor to understand this description, please help me on this. 

Our Use Case is : topics are exposed to end devices for subscriptions. Admin Sdk code is simply broadcasting messages on topic so that all subscribed devices will receive notification.
