### ISSUE TITLE
Why it's so hard to download only one project? e.g. messaging

### ISSUE THREAD

**Issue by s7aycool** [firebase/quickstart-android#1324]
I only want to quickstart messaging ) why I have to download the entire 3 hundred projects and then .... ???? unzip and import the project I need .... this is just so bad

**Comment by rosariopfernandes** [comment]
@s7aycool That's mostly because this is a git repository and that's the way that git works.

According to this [StackOverflow answer](https://stackoverflow.com/a/52269934/5861618), you can actually clone a specific project using git 2.19 (I haven't tested this myself):

```bash
git clone --depth 1  --filter=blob:none  --sparse https://github.com/firebase/quickstart-android
cd quickstart-android

# Here we'll download the messaging project only:
git sparse-checkout set messaging
```

**Comment by s7aycool** [comment]
It worked out. Thanks) I think you should pin this somewhere, so people will download only projects they really need, and so will save some electricity and money for the well being of mother nature
