### ISSUE TITLE
I have found a Docs error

### ISSUE THREAD

**Issue by cluckbird** [firebase/quickstart-android#1328]
Dev Docs: https://firebase.google.com/docs/cloud-messaging/android/client?authuser=0#manifest

```xml
<service
    android:name=".java.MyFirebaseMessagingService"
    android:exported="false">
    <intent-filter>
        <action android:name="com.google.firebase.MESSAGING_EVENT" />
    </intent-filter>
</service>
```
It should be written as
```xml
<service
      android:name="com.google.firebase.messaging.FirebaseMessagingService"
      android:exported="false">
      <intent-filter>
          <action android:name="com.google.firebase.MESSAGING_EVENT" />
      </intent-filter>
</service>
```
Although I fully understand the meaning, it is not straightforward to use and may mislead newcomers with its vague meaning
Direct copying results in an `Class referenced in the manifest, com.xxx.java.MyFirebaseMessagingService, was not found in the project or the libraries` error message

**Comment by cluckbird** [comment]
> This issue does not seem to follow the issue template. Make sure you provide all the required information.

I understand, but this is a docs error

**Comment by vitexikora** [comment]
@cluckbird Thank you very much, this saved me.

Also a lot of thanks to the Firebase team, which instructed me to copy a snippet to my Manifest, that crashed my app upon receiving notifications... Many warm thanks.
