### ISSUE TITLE
Retrieving additional parameters passed by Firebase Invites

### ISSUE THREAD

**Issue by droidwala** [firebase/quickstart-android#133]
When using Firebase Invites we can send the additional referral parameters using the below method:          
`setAdditionalRefferalParameters(Map<String,String> map)`

Can you add code to **Invites sample** on how to retrieve those parameters in the DeepLinkActivity?
Asking because haven't found anything related to this in docs or mentioned anywhere in talks/blogs.

**Comment by samtstern** [comment]
@droidwala thanks for the suggestion, I will look into adding this to the sample

**Comment by samtstern** [comment]
@droidwala after talking to the team, looks like this method is no longer necessary and will be removed soon.  We used to interact with the Play Store in a different way than we do now.

Is there something you were looking to achieve with this method that you can't achieve by adding query parameters to the deep link URL?

**Comment by droidwala** [comment]
@samtstern I though this was the method to be used for sending the referral parameters to be handled at receiving end.
I was using Firebase Invites and Dynamic Links side by side.
So,I had big confusion related to generating the deepLinkUrl.

**TIL:**
In DL, deepLinkUrl = dynamicLinkDomain + App's deepLinkUrl + Query params
In FI, deepLinkUrl = App's deepLinkUrl + Query params

Sorry for the trouble and thanks for looking into it.
