### ISSUE TITLE
I had error on EntryChoiceActivity im using java

### ISSUE THREAD

**Issue by xfilesunlimited** [firebase/quickstart-android#1330]
package com.google.samples.quickstart.admobexample

import android.content.Intent
import com.firebase.example.internal.BaseEntryChoiceActivity
import com.firebase.example.internal.Choice
import com.google.samples.quickstart.admobexample.java.MainActivity

class EntryChoiceActivity : BaseEntryChoiceActivity() {

    override fun getChoices(): List<Choice> {
        return listOf(
                Choice(
                        "Java",
                        "Run the Firebase Admob quickstart written in Java.",
                        Intent(this, MainActivity::class.java)),
                Choice(
                        "Kotlin",
                        "Run the Firebase Admob quickstart written in Kotlin.",
                        Intent(this, com.google.samples.quickstart.admobexample.kotlin.MainActivity::class.java))
        )
    }
}

is it needed when using java? the app crashes without it

**Comment by marinacoelho** [comment]
Hello @xfilesunlimited . Can you paste the crash here too? It will help to understand what is happening.
