### ISSUE TITLE
Build failure without any warning

### ISSUE THREAD

**Issue by CaptainRock** [firebase/quickstart-android#1333]
### Step 1: Describe your environment

  * Android device: Emulator( Pixel 4 API 27)
  * Android OS version: 8.1
  * Google Play Services version:  Google Services 4.3.10
  * Firebase/Play Services SDK version: com.google.android.gms:play-services-auth:19.2.0
  * Android Studio Version - Arctic Fox
  
#### Steps to reproduce:

  1. Import project
  2. Run "Rebuild Project"
  3. Build status is shown as failed . There are no warnings.
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  * There is no warning or error. Following are the tasks that were attempted
  * Build failed
:app:preBuild
:app:preReleaseBuild
:internal:chooserx:preBuild
:internal:chooserx:preReleaseBuild
:internal:chooserx:compileReleaseAidl
:internal:lintchecks:preBuild
:internal:lintchecks:preReleaseBuild
:internal:lintchecks:compileReleaseAidl
:app:compileReleaseAidl
:internal:chooserx:packageReleaseRenderscript
:internal:lintchecks:packageReleaseRenderscript
:app:compileReleaseRenderscript
:app:dataBindingMergeDependencyArtifactsRelease
:app:dataBindingMergeGenClassesRelease
:app:generateReleaseResValues
:app:generateReleaseResources
:app:processReleaseGoogleServices
:internal:chooserx:compileReleaseRenderscript
:internal:chooserx:generateReleaseResValues
:internal:chooserx:generateReleaseResources
:internal:chooserx:packageReleaseResources
:internal:lintchecks:compileReleaseRenderscript
:internal:lintchecks:generateReleaseResValues
:internal:lintchecks:generateReleaseResources
:internal:lintchecks:packageReleaseResources
:app:generateReleaseBuildConfig
:app:generateSafeArgsRelease
:internal:chooserx:writeReleaseAarMetadata
:internal:lintchecks:writeReleaseAarMetadata
:app:checkReleaseAarMetadata
:app:createReleaseCompatibleScreenManifests
:app:extractDeepLinksRelease
:internal:chooserx:extractDeepLinksRelease
:internal:chooserx:processReleaseManifest
:internal:lintchecks:extractDeepLinksRelease
:internal:lintchecks:processReleaseManifest
:app:processReleaseMainManifest
:app:processReleaseManifest
:app:processReleaseManifestForPackage
:internal:chooserx:compileReleaseLibraryResources
:internal:chooserx:parseReleaseLocalResources
:internal:chooserx:generateReleaseRFile
:internal:lintchecks:compileReleaseLibraryResources
:internal:lintchecks:parseReleaseLocalResources
:internal:lintchecks:generateReleaseRFile
:internal:chooserx:generateReleaseBuildConfig
:internal:chooserx:javaPreCompileRelease
:internal:chooserx:compileReleaseJavaWithJavac
:internal:chooserx:bundleLibCompileToJarRelease
:internal:lintchecks:generateReleaseBuildConfig
:internal:lintchecks:javaPreCompileRelease
:internal:lintchecks:compileReleaseJavaWithJavac
:internal:lintchecks:bundleLibCompileToJarRelease
:app:javaPreCompileRelease
:internal:lintchecks:mergeReleaseJniLibFolders
:internal:lintchecks:mergeReleaseNativeLibs
:internal:lintchecks:stripReleaseDebugSymbols
:internal:lintchecks:copyReleaseJniLibsProjectAndLocalJars
:internal:lintchecks:extractReleaseAnnotations
:internal:lintchecks:mergeReleaseGeneratedProguardFiles
:internal:lintchecks:mergeReleaseConsumerProguardFiles
:internal:lintchecks:mergeReleaseShaders
:internal:lintchecks:compileReleaseShaders
:internal:lintchecks:generateReleaseAssets
:internal:lintchecks:packageReleaseAssets
:internal:lintchecks:prepareLintJarForPublish
:internal:lintchecks:prepareReleaseArtProfile
:internal:lintchecks:processReleaseJavaRes
:internal:lintchecks:mergeReleaseJavaResource
:internal:lintchecks:syncReleaseLibJars
:internal:lintchecks:writeReleaseLintModelMetadata
:internal:lintchecks:bundleReleaseLocalLintAar
:internal:chooserx:mergeReleaseJniLibFolders
:internal:chooserx:mergeReleaseNativeLibs
:internal:chooserx:stripReleaseDebugSymbols
:internal:chooserx:copyReleaseJniLibsProjectAndLocalJars
:internal:chooserx:extractReleaseAnnotations
:internal:chooserx:mergeReleaseGeneratedProguardFiles
:internal:chooserx:mergeReleaseConsumerProguardFiles
:internal:chooserx:mergeReleaseShaders
:internal:chooserx:compileReleaseShaders
:internal:chooserx:generateReleaseAssets
:internal:chooserx:packageReleaseAssets
:internal:chooserx:prepareLintJarForPublish
:internal:chooserx:prepareReleaseArtProfile
:internal:chooserx:processReleaseJavaRes
:internal:chooserx:mergeReleaseJavaResource
:internal:chooserx:syncReleaseLibJars
:internal:chooserx:writeReleaseLintModelMetadata
:internal:chooserx:bundleReleaseLocalLintAar
:app:extractProguardFiles
:internal:chooserx:bundleLibResRelease
:internal:chooserx:bundleLibRuntimeToJarRelease
:internal:chooserx:createFullJarRelease
:internal:lintchecks:bundleLibResRelease
:internal:lintchecks:bundleLibRuntimeToJarRelease
:internal:lintchecks:createFullJarRelease
:app:mergeReleaseJniLibFolders
:internal:chooserx:copyReleaseJniLibsProjectOnly
:internal:lintchecks:copyReleaseJniLibsProjectOnly
:app:mergeReleaseNativeLibs
:app:stripReleaseDebugSymbols
:app:extractReleaseNativeSymbolTables
:app:mergeReleaseNativeDebugMetadata
:app:mergeReleaseArtProfile
:internal:lintchecks:exportReleaseConsumerProguardFiles
:internal:chooserx:exportReleaseConsumerProguardFiles
:app:checkReleaseDuplicateClasses
:app:processReleaseJavaRes
:app:mergeReleaseShaders
:app:compileReleaseShaders
:app:generateReleaseAssets
:app:mergeReleaseAssets
:app:compressReleaseAssets
:app:collectReleaseDependencies
:app:sdkReleaseDependencyData
:app:validateSigningRelease
:app:writeReleaseAppMetadata
:app:writeReleaseSigningConfigVersions
  
#### Expected Results:

  * What did you expect to happen?
  * Successful build and deploy to emulator
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by thatfiredev** [comment]
@CaptainRock Whenever a build fails, there's always an error somewhere. Can you please double-check your logcat?
