### ISSUE TITLE
Realtime Database Android APK Deployment Issue

### ISSUE THREAD

**Issue by n0psn0ps** [firebase/quickstart-android#1355]
### Step 1: Describe your environment

  * Android device: Android Studio Emulator
  * Android OS version: Pixel 4A - 11.0 / API 30
  * Google Play Services version: n/a
  * Firebase/Play Services SDK version: most recent
  
#### Steps to reproduce:

  1. Build the app via the Quick Start Code with the corresponding google-service.json file and export APK via "release" format
  2. Push apk via adb and install
  3. Attempt to register user
  
#### Observed Results:

  * What happened?  
  * The APK installed correctly, but appears to stall while "registering" the user in the android application. I set the realtime database Rules per the guide. I set the Authentication Email/Password combo but that appears to not help the issue. 
  
#### Expected Results:

  * What did you expect to happen?
  * The user to register and login.
  
#### Relevant Code:

  ```
  // TODO(you): currently not any.
  ```

**Comment by thatfiredev** [comment]
@n0psn0ps when you say _"appears to stall while registering"_ do you mean it crashes?

I successfully reproduced this issue and the app only crashes when running the Kotlin quickstart in release build; the Java one works just fine.
I was able to track it down to some Kotlin model classes being removed from the APK by proguard. In our `proguard-rules.pro` file there's a rule to keep the Java models, but we forgot to add one for Kotlin:

https://github.com/firebase/quickstart-android/blob/320f5fb45f155de3daf8b997c3788a4a187a024d/database/app/proguard-rules.pro#L28-L30

I've opened a PR (#1356) to fix this, but in the meantime you can try adding that rule yourself and see if it works.

**Comment by n0psn0ps** [comment]
Awesome thank you @thatfiredev i will give that a try now and see if I can get it to deploy.

**Comment by n0psn0ps** [comment]
Looks like a may be missing something in my setup process. I can get the app to deploy into my android emulator no problem, but when I attempt to sign-up and login I am met with a failure in both regard. Screenshot below.

![image](https://user-images.githubusercontent.com/68410650/156855350-4c4c2a52-232f-40f1-8381-ed497a90c744.png)

I have set the correct permissions for the Realtime Database:
```
{
  "rules": {
    // User profiles are only readable/writable by the user who owns it
    "users": {
      "$UID": {
        ".read": "auth.uid == $UID",
        ".write": "auth.uid == $UID"
      }
    },

    // Posts can be read by anyone but only written by logged-in users.
    "posts": {
      ".read": true,
      ".write": "auth.uid != null",

      "$POSTID": {
        // UID must match logged in user and is fixed once set
        "uid": {
          ".validate": "(data.exists() && data.val() == newData.val()) || newData.val() == auth.uid"
        },

        // User can only update own stars
        "stars": {
          "$UID": {
              ".validate": "auth.uid == $UID"
          }
        }
      }
    },

    // User posts can be read by anyone but only written by the user that owns it,
    // and with a matching UID
    "user-posts": {
      ".read": true,

      "$UID": {
        "$POSTID": {
          ".write": "auth.uid == $UID",
        	".validate": "data.exists() || newData.child('uid').val() == auth.uid"
        }
      }
    },


    // Comments can be read by anyone but only written by a logged in user
    "post-comments": {
      ".read": true,
      ".write": "auth.uid != null",

      "$POSTID": {
        "$COMMENTID": {
          // UID must match logged in user and is fixed once set
          "uid": {
              ".validate": "(data.exists() && data.val() == newData.val()) || newData.val() == auth.uid"
          }
        }
      }
    }
  }
}
```

3) Enabled the login via email and password. 

<img width="968" alt="image" src="https://user-images.githubusercontent.com/68410650/156855123-57a8261f-2607-4df4-8c0c-f1bb5f3a942d.png">
 
Do I also need to set my root nodes via the Console? This is a quick demo of what it looks like on my end for the users nodes. 

<img width="268" alt="image" src="https://user-images.githubusercontent.com/68410650/156854843-e28cae11-ef7a-4800-b13a-1beee2d4950d.png">

Thanks in advance.

**Comment by thatfiredev** [comment]
@n0psn0ps Sorry for the delay here...
I tried to reproduce this with the security rules that you provided and it worked just fine, I had no errors.
I see from your database screenshot that you have a `password` field on the database that is not supposed to be there. I'm guessing that could be causing the error.
Can you please delete all the users that you have on your Database Console? And only add users through the sign up button on the app.
