### ISSUE TITLE
Firebase Analytics and Crashlytics events doesn't work in Corporate Proxy / VPN

### ISSUE THREAD

**Issue by Rajesh166** [firebase/quickstart-android#1369]
Step 1: Describe your environment
Android device: Android Studio Emulator
Android OS version: Pixel 4A - 11.0 / API 30 and API 29
Google Play Services version: n/a
Firebase/Play Services SDK version: most recent

Step 2: Describe the problem:
Steps to reproduce:
Build the app via the Quick Start Code with the corresponding google-service.json file and export APK via "release" format
When i am in Corporate Proxy/ VPN i see that it is blocking Analytics and Crashlytics are not being sent to firebase console with the below error.
`Network upload failed. Will retry later. code, error: 0, java.net.UnknownHostException: Unable to resolve host "app-measurement.com": No address associated with hostname`
I tried to whitelist `app-measurement.com` in network-security-config xml but didn't work.

I want this to be working since the devices i am tracking will be under proxy.

Observed Results:
As mentioned i the problem. I dont see any issue when i am not in VPN.

Expected Results:
Ideally Analytics and Crashlytics events should be sent to Console with or without VPN

Relevant Code:
// TODO(you): currently not any.

**Comment by thatfiredev** [comment]
@Rajesh166 I wonder if this could somehow be related to the emulator. Is it possible for you to test this in a physical device?
