### ISSUE TITLE
[Messaging] "Customize default notification" docs link is dead

### ISSUE THREAD

**Issue by maxxx** [firebase/quickstart-android#1386]
Here (https://github.com/firebase/quickstart-android/blob/master/messaging/README.md) is the link (https://goo.gl/sPggnS) which navigates to some outdated page (https://firebase.google.com/docs/notifications/android/console-audience#edit-the-app-manifest) which gives 404 in result. So how to read about additional customization of default notification?

**Comment by thatfiredev** [comment]
Nice finding @maxxx !
The correct documentation link should be this one: https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest
I'll update the README.md file
