### ISSUE TITLE
Since this is a Kotlin snippet, we might want to demonstrate KTX here

### ISSUE THREAD

**Issue by Rous110508** [firebase/quickstart-android#1404]
Since this is a Kotlin snippet, we might want to demonstrate KTX here
```suggestion
        Firebase.messaging.token
```

_Originally posted by @thatfiredev in https://github.com/firebase/quickstart-android/pull/1353#discussion_r814957506_

**Comment by thatfiredev** [comment]
Hi @Rous110508 If you need help with that particular snippet, please share more details so we can help you. Thanks
