### ISSUE TITLE
FragmentAdapter is deprecated

### ISSUE THREAD

**Issue by thatfiredev** [firebase/quickstart-android#1416]
Our analytics quickstart uses `FragmentAdapter` which has been deprecated. The [reference docs](https://developer.android.com/reference/androidx/fragment/app/FragmentPagerAdapter) suggests migrating to ViewPager2.

We've done a similar migration in the past for our RTDB quickstart https://github.com/firebase/quickstart-android/pull/1315 - it can be used as inspiration.

**Comment by AlbertoYabeda** [comment]
Helloo 🔥.
can you assign it to me? I would like to give it a try.

**Comment by thatfiredev** [comment]
@AlbertoYabeda Of course!

**Comment by AlbertoYabeda** [comment]
I think to be able to run it,  I need the google-services.json file for the google services plugin. Am I wrong??

**Comment by thatfiredev** [comment]
@AlbertoYabeda Yes, you'll need to create a Firebase Project and add the .json file to the app. We have instructions here: https://github.com/firebase/quickstart-android/tree/master/analytics

**Comment by AlbertoYabeda** [comment]
Thanks @thatfiredev

**Comment by saketkumar** [comment]
@AlbertoYabeda Is this still pending?
@thatfiredev Should I take this up? 🙂

**Comment by AlbertoYabeda** [comment]
You can take it @saketkumar.

**Comment by saketkumar** [comment]
Thanks for the update @AlbertoYabeda 
Let me know if you face any issues. I will take this up. 😃

**Comment by AlbertoYabeda** [comment]
I'll do that @saketkumar . Thankiuu😉

**Comment by thatfiredev** [comment]
@saketkumar if you're still interested in contributing, I have just opened a much simpler issue: #1428

**Comment by saketkumar** [comment]
@thatfiredev No problem . 
Please let me know again if there is anything I can contribute to. 🙂

**Comment by thatfiredev** [comment]
Done in #1427
