### ISSUE TITLE
onBackPressed() has been deprecated

### ISSUE THREAD

**Issue by thatfiredev** [firebase/quickstart-android#1417]
Our firestore quickstart makes use of the `onBackPressed()` method, which has been deprecated:

https://github.com/firebase/quickstart-android/blob/a219d94278faff75774509e5b09fb6d0f02004eb/firestore/app/src/main/java/com/google/firebase/example/fireeats/kotlin/RestaurantDetailFragment.kt#L136-L138

Since that app uses the [Navigation component](https://developer.android.com/guide/navigation/navigation-getting-started), we should probably replace that call with [`popBackStack()`](https://developer.android.com/reference/androidx/navigation/NavController#popBackStack()):

```kotlin
    private fun onBackArrowClicked() {
        findNavController().popBackStack()
    }
```

**Comment by AlgyJr** [comment]
Hi @thatfiredev , I'd like to try this, can you assign it to me?

**Comment by thatfiredev** [comment]
@AlgyJr  Go for it!
