### ISSUE TITLE
setHasOptionsMenu() and onCreateOptionsMenu() have been deprecated

### ISSUE THREAD

**Issue by thatfiredev** [firebase/quickstart-android#1418]
The `setHasOptionsMenu()` and `onCreateOptionsMenu()` used in our quickstarts have been deprecated in favor of [MenuProvider](https://developer.android.com/jetpack/androidx/releases/activity#1.4.0-alpha01).

We need to update our quickstart apps with the [proposed solutions](https://stackoverflow.com/a/71965674/5861618).

Affected apps:
- [ ] firestore
- [ ] database

**Comment by Nozotrox** [comment]
I would like to close the issue.

**Comment by thatfiredev** [comment]
@Nozotrox you mean you'll fix it? 😁 
Sure, assigned to you!

**Comment by Nozotrox** [comment]
Yes! :D

**Comment by thatfiredev** [comment]
Done in #1425
