### ISSUE TITLE
Use ConstraintLayout in dynamiclinks quickstart

### ISSUE THREAD

**Issue by thatfiredev** [firebase/quickstart-android#1428]
Our [dynamiclinks quickstart](https://github.com/firebase/quickstart-android/tree/master/dynamiclinks) has a single screen which uses nested LinearLayouts. It would be nice if we could simplify it with a `ConstraintLayout`.

**Comment by EdNgulele** [comment]
Hi @thatfiredev, can I take this one?

**Comment by thatfiredev** [comment]
Sure @EdNgulele , assigned to you
