### ISSUE TITLE
Firebase Auth Not Working When minifyEnabled

### ISSUE THREAD

**Issue by shreyaspatil99** [firebase/quickstart-android#145]
When I enabled proguard (minifyEnabled true) and released apk then it shows **DynamiteModule Not Found** and unfortunately app stops and when **disabling minifyEnabled** it works without any error.
Is there any solution.

**Comment by samtstern** [comment]
@shreyaspatil99 try adding these rules to `proguard-rules.pro`

```
-keepattributes Signature
-keepattributes *Annotation*
```

Source: https://firebase.google.com/docs/auth/android/start/

**Comment by Aakash-Venkatasubramanian** [comment]
The proguard rules suggested by @samtstern does not work

**Comment by suhocki** [comment]
Hi, I am currently working on setting up Firebase in my project and have encountered a problem when I run my R8-obfuscated app, the Firebase service no longer works.  Has anyone encountered the same problem? Any solution?

**Comment by DevVigilante** [comment]
> Hi, I am currently working on setting up Firebase in my project and have encountered a problem when I run my R8-obfuscated app, the Firebase service no longer works. Has anyone encountered the same problem? Any solution?

Did you found any fix?
