### ISSUE TITLE
firebaseError:DatabaseError: Permission denied; code:-3

### ISSUE THREAD

**Issue by vkarthikayan** [firebase/quickstart-android#154]
### Step 1: Are you in the right place?
- For issues or feature requests related to the code **in this repository** file a Github issue.
  - If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
- For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
- For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)
### Step 2: Describe your environment
- Android device: Samsung s7
- Android OS version: 6.0.1
- Google Play Services version: 3.0.0
- Firebase/Play Services SDK version: 9.6.1
### Step 3: Describe the problem:

On successful signInWithCustomToken() , subscribing to DB refs is triggering firebaseError:DatabaseError: Permission denied; code:-3.
#### Steps to reproduce:
1. signInWithCustomToken() successfully
2. subscribe to DB refs.
3. Observe firebaseError:DatabaseError: Permission denied; code:-3.
#### Observed Results:

 W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
  W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.
 D/FirebaseAuth: Notifying listeners about user ( 1************\* ).
D/FirebaseApp: Notifying auth state listeners.
D/FirebaseApp: Notified 1 auth state listeners.
D/AuthenticationHandler:onComplete: com.google.android.gms.tasks.zzh@e508f97
D/ConfigHandler:sysGatewaysEventListener:onCancelled: **firebaseError:DatabaseError: Permission denied; code:-3**
#### Expected Results:
- firebaseError:DatabaseError: Permission denied; code:-3**

Note: The issue is not always reproducible.

**Comment by samtstern** [comment]
@vkarthikayan are you only attaching your Database listeners **after** auth has completed successfully?  Also what do your Database rules look like?

**Comment by samtstern** [comment]
@vkarthikayan are you still having this issue?  Since it's been two weeks I am going to close this and assume you fixed it, but if not please re-open this issue, happy to discuss.

**Comment by jcampana** [comment]
Please @vkarthikayan I have a similar problem. What solution runs for you?
Thanks in advance!
