### ISSUE TITLE
What is `default_web_client_id` in the Auth Sample App

### ISSUE THREAD

**Issue by cancan101** [firebase/quickstart-android#1541]
The `default_web_client_id` string is used in a number of places, such as: https://github.com/firebase/quickstart-android/blob/505c4f19538cdb4be30fd577144b69203723d30d/auth/app/src/main/java/com/google/firebase/quickstart/auth/kotlin/GoogleSignInFragment.kt#L122C51-L122C72

but does not have any documentation nor placeholders in: https://github.com/firebase/quickstart-android/blob/505c4f19538cdb4be30fd577144b69203723d30d/auth/app/src/main/res/values/ids.xml

### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by thatfiredev** [comment]
@cancan101 The `default_web_client_id` is automatically set by the `google-services` Gradle plugin when parsing the `google-services.json` file. It will be set at build time, so we don't need to manually add it to the `strings.xml` resource.

For reference, this is the line in the plugin source code where the value gets set:

https://github.com/google/play-services-plugins/blob/6cec2f5eff7b84fb4ccd45d47e8fe9ee79828a83/google-services-plugin/src/main/kotlin/com/google/gms/googleservices/GoogleServicesTask.kt#L255

**Comment by cancan101** [comment]
Is there a placeholder value of sort that can be put into the code to keep the IDE from flagging those lines as having errors?

**Comment by thatfiredev** [comment]
You can try copying the `client_id` from the `google-services.json` file to `strings.xml` (as described in [this post](https://stackoverflow.com/a/37813058/5861618)). Since they're the same value, I assume there will be no problems.

I haven't tried setting a "fake" id as a placeholder so I'm not sure if that would take precedence over the one set by the `google-services` plugin.
