### ISSUE TITLE
I sent push notification to users and some of them in android 4 version have crash

### ISSUE THREAD

**Issue by siavashabdoli** [firebase/quickstart-android#155]
I sent data notification from firebase console. I have one key/value in data which the value is son String itself. I have no problem for getting notification on android 6 and there is no crash report by fabric(crashlytics) on other version of android os except android 4.x.x. 
image of fabric:
<img width="1182" alt="screen shot 2016-10-17 at 10 25 04 am" src="https://cloud.githubusercontent.com/assets/8090549/19428122/0342ece2-9455-11e6-805a-b990b0820d2c.png">
stack trace for 4.1.x - 4.2.x:

<img width="1141" alt="screen shot 2016-10-17 at 10 33 16 am" src="https://cloud.githubusercontent.com/assets/8090549/19428149/316abc76-9455-11e6-92b9-f3b0b3085cb1.png">

**Comment by kroikie** [comment]
@siavashabdoli to clarify, any message sent from the console is a notification message. Are you saying that you are getting a ConcurrentModificationException when you receive a message on 4.1.x and 4.2.x? Also are you getting this when using the messaging sample in the repo?

**Comment by samtstern** [comment]
@siavashabdoli it's been over a month since the last activity on this issue so I am going to close it, if you have more information and can answer @kroikie's questions please re-open the issue and we can continue discussing.

**Comment by jdsingh** [comment]
I'm having the same issue. It occurs in Android API 16, 17 and 18. This crash happened 61 times for 69 users in my app.

Here is the stack trace from Firebase Crash Reporting.

```java
Exception java.util.ConcurrentModificationException:
java.util.HashMap$HashIterator.nextEntry (HashMap.java:806)
java.util.HashMap$EntryIterator.next (HashMap.java:843)
java.util.HashMap$EntryIterator.next (HashMap.java:841)
java.util.HashMap.constructorPutAll (HashMap.java:208)
java.util.HashMap.<init> (HashMap.java:196)
android.os.Bundle.<init> (Bundle.java:125)
android.content.Intent.getExtras (Intent.java:5283)
com.google.firebase.messaging.FirebaseMessagingService.zzm ()
com.google.firebase.iid.zzb$2.run ()
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:573)
java.lang.Thread.run (Thread.java:841)
```

**Comment by jdsingh** [comment]
To answer @kroikie's question: I used Firebase Notifications to send push notifications in my app and these crashes are happening in Android API 16, 17 and 18.

I used the code from sample app to implement push notifications in my app but I have not tried messaging sample repo.
