### ISSUE TITLE
How can i display the records from above i mean descending order according to timestamp or as the keys come in . A new entry is displayed below of the scroll i would like to display at the top of the scroll 

### ISSUE THREAD

**Issue by goodlifechris** [firebase/quickstart-android#157]
### Step 1: Are you in the right place?
- For issues or feature requests related to the code **in this repository** file a Github issue.
  - If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
- For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
- For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)
### Step 2: Describe your environment
- Android device: _____
- Android OS version: _____
- Google Play Services version: _____
- Firebase/Play Services SDK version: _____
#### Steps to reproduce:
1. _____
2. _____
3. _____
#### Observed Results:
- What happened?  This could be a description, `logcat` output, etc.
#### Expected Results:
- What did you expect to happen?
#### Relevant Code:

```
  // TODO(you): code here to reproduce the problem
```

**Comment by samtstern** [comment]
@goodlifechris please use the issue template next time.  This sounds like an issue with your RecyclerView or ListView, not a Firebase library (and certainly not the code in this quickstart).

I'd suggest asking on StackOverflow.  You may want to check out the [friendlychat](https://github.com/firebase/friendlychat) sample, which demonstrates similar behavior.
