### ISSUE TITLE
Notifications not sent when using mobile data only sent on wifi

### ISSUE THREAD

**Issue by Keithwachira** [firebase/quickstart-android#161]
### Step 1: Are you in the right place?
- For issues or feature requests related to the code **in this repository** file a Github issue.
  - If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
- For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
- For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
- For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)
### Step 2: Describe your environment
- Android device: _____
- Android OS version: _____
- Google Play Services version: _____
- Firebase/Play Services SDK version: _____
#### Steps to reproduce:
1. _____
2. _____
3. _____
#### Observed Results:
- What happened?  This could be a description, `logcat` output, etc.
#### Expected Results:
- What did you expect to happen?
#### Relevant Code:

```
  // TODO(you): code here to reproduce the problem
```

**Comment by samtstern** [comment]
@Keithwachira please use the issue template, there is not enough information here to help you debug.  If you're still having this problem please fill out the template and then re-open this issue.

**Comment by Keithwachira** [comment]
seems this problem occured since my google play service data had been disabled.Solved it by enabling it.
