### ISSUE TITLE
App invite open email picker screen but when i click on  back phone was frozen

### ISSUE THREAD

**Issue by harmispatel** [firebase/quickstart-android#162]
Hello,

  I integrated firebase app invite successfully ,i  got success for sending invitation but when i will open email  listing screen, i will click on back without selecting any contact then suddenly phone frozen .I could not see any log for this error.
 so please help me how to resolve this.

Thank you.

**Comment by samtstern** [comment]
@harmispatel please use the issue template when filing issues in this repository.  This sounds like something specific to your application, I'd recommend posting it on StackOverflow where the community can help to debug.
