### ISSUE TITLE
Sign-in Failed: An SignInActivity: internal error has occurred. [PASSWORD_LOGIN_DISABLED

### ISSUE THREAD

**Issue by PingerWan** [firebase/quickstart-android#163]
I encountered such a problem: Sign-in Failed: An SignInActivity: internal error has occurred. [PASSWORD_LOGIN_DISABLED], should be how to solve it? Thank you

**Comment by harmispatel** [comment]
Hello,

  you have to enable login types in firebase console.

Thank you.

**Comment by samtstern** [comment]
@PingerWan yep, you need to go to **Auth > Sign In Methods** in the console and enable the correct method.
