### ISSUE TITLE
Can Any one give me the signOut code for Loggin off with android app

### ISSUE THREAD

**Issue by JaganJonnala** [firebase/quickstart-android#166]
com.tns.NativeScriptException: 
Calling js method onMenuItemClick failed

Error: Error in pages/upload-files/image-upload.html:2:20 caused by: firebase.auth is not a function
File: "/data/data/org.nativescript.NgAppRawMaterial/files/app/tns_modules/@angular/core/bundles/core.umd.js, line: 9668, column: 20

StackTrace: 
	Frame: function:'DebugAppView._rethrowWithContext', file:'/data/data/org.nativescript.NgAppRawMaterial/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9668, column: 21
	Frame: function:'', file:'/data/data/org.nativescript.NgAppRawMaterial/files/app/tns_modules/@angular/core/bundles/core.umd.js', line: 9681, column: 27
	Frame: function:'', file:'/data/data/org.nativescript.NgAppRawMaterial/files/app/tns_modules/nativescript-angular/renderer.js', line: 221, column: 26
	Frame: function:'ZoneDelegate.invoke', file:'/data/data/org.nativescript.NgAppRawMaterial/files/app/tns_modules/nativescript-angular/zone.js/dist/zone-nativescript.js', line: 190, column: 28
	Frame: function:'NgZ

**Comment by morganchen12** [comment]
This question is better suited for StackOverflow.
