### ISSUE TITLE
FirebaseApp: Notifying background state change listeners.

### ISSUE THREAD

**Issue by sunil-jhamnani** [firebase/quickstart-android#167]
### Step 1: Platform details
- Android device: Moto X play and Moto G2
- Android OS version: 6.0.1 and 6.0
- Google Play Services version: 9.8.77
- Firebase/Play Services SDK version: 9.6.1
### Step 2: Describe the problem:

I have a hybrid app on cordova and I am trying to implement push plugin with FCM. The only issue I am facing is when the app is in background then the push.on("notification") listener function is not getting called after clicking the push notification from the notification tray. Its only called on foreground. Also this issue is only for android. For iOS its working as expected.

I read that this can be achieved only when push notification are triggered via API. From backend, I am using python's **pyfcm** API to send the notification but same issue.

Also I checked the logs on Android studio. They just show this line "D/FirebaseApp: Notifying background state change listeners." whenever app goes in background and comes back in foreground.

Please let me know how can I call the notification listener when app is on background.  
#### Steps to reproduce:
1. Install the app
2. Press home button so that app goes in background.
3. Send a push notification.
4. Click on the push notification from the notification tray
#### Observed Results:
- The push.on("notification") listener function not getting called (I am using this [cordova push plugin](https://github.com/phonegap/phonegap-plugin-push/blob/master/docs/API.md#pushonnotification-callback))
#### Expected Results:
- The push.on("notification") listener function should have been called after clicking the notification.

**Comment by sunil-jhamnani** [comment]
Hi @kroikie,

Can you please help me on this. I am really stuck on this badly.
Thanks in advance!

**Comment by samtstern** [comment]
@sunil-jhamnani from the description it sounds like this problem could be part of "pyfcm" or the cordova push plugin.  Neither of those is something written by Google/Firebase so it's going to be very hard for us to troubleshoot.  

I would suggest posting this on StackOverflow or a forum specific to those libraries as it's not an issue with the Android quickstart code presented here.
