### ISSUE TITLE
FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 

### ISSUE THREAD

**Issue by fxsurf** [firebase/quickstart-android#168]
i got a problem with android studio and firebase
i running the notification on emulator, everything works fine

but when i starting project /build project in real device (mine is xiaomi) error came out
it says FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 40s
please help guys

**Comment by samtstern** [comment]
@fxsurf as far as I know Xiaomi devices don't support Google Play Services natively.  Do you have Google Play Services on that device?  Can you try it on another device?

**Comment by fxsurf** [comment]
@samtstern in my apps list i see google play services, but i dont know why it still doesnt work.
im already testing it to Asus and Samsung device, its working perfectly as i want. but didnt in my xiaomi
any sugest please?, btw thx for the reply

**Comment by kroikie** [comment]
What version of Google Play services do you have installed on the Xiaomi device?

**Comment by fxsurf** [comment]
@kroikie im using 9.8.77, my system says that this is the latest version

**Comment by kroikie** [comment]
9.8.x should work, so it may be a device specific issue. Are there any logcat issues when you run your application or when the message is sent indicating something went wrong?

**Comment by fxsurf** [comment]
@kroikie nope, there is nothing any logcat issues when i run my app. 
i ended up with building new app with the same content, it seems work for me
but i still dont get what the last issues about
i think that it can be some bug to connecting firebase
thanks btw for trying to help me
appreciate that!

**Comment by Keithwachira** [comment]
i think the background  data for your Google play services has been disabled.  i had the same issue and i solved it by  enabling background  data for google play  services.

**Comment by samtstern** [comment]
It's been a while since any update here so I am going to close this issue.  If anyone has this same problem or has some more information please comment and we can re-open the discussion.
