### ISSUE TITLE
email verification is not send to the user after the sign up is done.

### ISSUE THREAD

**Issue by Pangaj** [firebase/quickstart-android#170]
Step 1: Describe the problem:

#### Steps to reproduce:

  1. Open firebase app, signup a new account
  2. try to send a email verification to the user
  
#### Observed Results:
Email is not send. returns error block
```java
user.sendEmailVerification()
                                .addOnCompleteListener(task1 -> {
                                    hideProgressDialog();
                                    if (task1.isSuccessful()) {
                                        Toast.makeText(getApplicationContext(), getResources().getString(R.string.mail_sent), Toast.LENGTH_SHORT).show();
                                    } else {
                                        Toast.makeText(getApplicationContext(), getResources().getString(R.string.something_went_wrong), Toast.LENGTH_SHORT).show();
                                    }
                                });
```

returns to the "R.string.something_went_wrong state".
  
#### Expected Results:

  my expected result is : R.string.mail_sent

## But,
Once I again login to the same account and send the email, I receive the email

**Comment by samtstern** [comment]
@Pangaj what is the value of `task1.getException()`?  That should help.

**Comment by Pangaj** [comment]
it displays : USER_NOT_FOUND error in Log

**Comment by sscdvp** [comment]
Could you post also your singup code for completeness?

I did as per Firebase user guide, and it seems it works if you are doing email verification in the right place, e.g. after successfull singup. Tasks could be also cascaded via continueWith().

final FirebaseAuth auth = FirebaseAuth.getInstance();
Task<AuthResult> task =
                auth.createUserWithEmailAndPassword(email, password);
 task.addOnSuccessListener(threadPoolExecutor, new OnSuccessListener<AuthResult>() {
            @Override
            public void onSuccess(AuthResult authResult) {
                    Log.d(TAG, "User's account was created successfully.");
                    FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
                    Task<Void> subTask = user.sendEmailVerification();
                    subTask.addOnSuccessListener(threadPoolExecutor, new OnSuccessListener<Void>() {
                                     @Override
                                     public void onSuccess(Void aVoid) {
                                                     Log.d(TAG, "User's verification e-mail was sent successfully.");
                                     }
                    });
            }
});
`

**Comment by samtstern** [comment]
@Pangaj this is a pretty old issue and I suspect that you experienced a transient outage or device condition.  If this is still happening, could you re-open with more information?
