### ISSUE TITLE
Topic not being created in Release build 

### ISSUE THREAD

**Issue by saleeh93** [firebase/quickstart-android#174]
I have a different issue, In my case device token is generated.And I have subscribed to a topic,everything works while I test it on debug version. When comes to release version device token is registered and I can send notification by device token,it works.But when I sent notification via topic it doesn't work. I can also send from firebase console to a platform. Topic is not even appeared in there, I don't know does anyone has this issue 
Thanks

**Comment by kroikie** [comment]
Hi @saleeh93 could you add your request that you are making with the topic, are you sure you are using /topics/<your-topic-name> format? Also topics take some time before they are available in the console, up to 24 hours, so the topic could exist and not show up in the console.

**Comment by saleeh93** [comment]
@kroikie It was some delay issues, I don't know why that happened. The firebase team helped me to resolve this issue, 
Thanks for your reply @kroikie
