### ISSUE TITLE
FirebaseInstanceIdService onTokenRefresh doesn't work on MI Note

### ISSUE THREAD

**Issue by hedoudou** [firebase/quickstart-android#175]
Hi Team,

I'm getting start on Firebase and try sending notification from Firebase to my devices. But the notification message never received on my MI note device, then i checked back and found FirebaseInstanceIdService.onRefresh() never called even i reinstall the app etc. So does Firebase ONLY working on devices which has play-service framework? My MI Note doesn't has google play-servivce framework, it was customized by Xiao Mi. Any help would be appreciate. 

BTW: The same code working on my another device(Samsung S4)

Thanks & Best Regards,
Johnson

**Comment by hedoudou** [comment]
Just found this from log

> 11-08 10:42:13.397 11363-11363/com.famedgram.activity W/InstanceID/Rpc: Failed to resolve REGISTER intent, falling back
11-08 10:42:13.398 11363-11363/com.famedgram.activity W/InstanceID/Rpc: Both Google Play Services and legacy GSF package are missing

So it seems the devices must have google play service running on?

**Comment by kroikie** [comment]
@hedoudou you are correct Google Play services is required for FCM.
