### ISSUE TITLE
Application stopped - Unity - Play Games Services

### ISSUE THREAD

**Issue by GilVieira** [firebase/quickstart-android#178]
Hello, I'm developing an Android game with Unity, it already had PGS, IAP and AdMob configured, so I installed the Analytics and Cloud Messaging packages from Firebase. Since then the game lost the icon and when the PGS tries to authenticate the application to work, someone could help me with this problem.

Sorry for my English.
Ths

**Comment by samtstern** [comment]
@GilVieira I don't think we can diagnose Unity issues here, this quickstart is for Android applications built in Java.

I'd recommend emailing our [personalized support channel](https://firebase.google.com/support/contact/troubleshooting/) who can help you troubleshoot.
