### ISSUE TITLE
Google Login not working with Note 4 (6.0.1)

### ISSUE THREAD

**Issue by DagobertDokate** [firebase/quickstart-android#18]
After i get a valid token from google auth, auth at the firebase backend fails.
This happend on my Note 4 with 6.0.1. I have no problems with the emultar, S3, A3 and S3 mini.
Any suggestions?

lg.

**Comment by MariusBudin** [comment]
Migrated my login with FB, Twitter and Google to the new API and I have a similar issue.
Can't get it to work with Google, all the other providers seem to work as expected.
My problem is after selecting the account, I get a null `account.getIdToken()` , not sure if related

**Comment by DagobertDokate** [comment]
hm... i get a token with `account.getIdToken()`.

This is the method which failed. The task not return successful.

 ```
private void firebaseAuthWithGoogle(final GoogleSignInAccount acct) {
        Log.e(TAG, "firebaseAuthWithGoogle() " + acct.getIdToken());
        AuthCredential credential = GoogleAuthProvider.getCredential(acct.getIdToken(), null);
        mAuth.signInWithCredential(credential)
                .addOnCompleteListener(activity, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (!task.isSuccessful()) {
                            //TODO Fehlerbehandlung verbessern
                            Toast.makeText(activity, "Authentication failed.",
                                    Toast.LENGTH_SHORT).show();
                        } else {
                            Log.e(TAG, "Auth complete");
                            updateUserInformationIfEmpty(acct);
                        }
                    }
                });
    }
```

**Comment by DagobertDokate** [comment]
And i got these exception:

`05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app     W/System.err: com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.internal.zznp$zzb.zzv(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.internal.zzoj$zzc.zzz(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.internal.zzoj$zzc.onConnectionFailed(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.internal.zzoj$zzd.zzh(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.common.internal.zzd$zzk.zzl(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.common.internal.zzd$zza.zzc(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.common.internal.zzd$zza.zzw(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.common.internal.zzd$zze.zztr(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at com.google.android.gms.common.internal.zzd$zzd.handleMessage(Unknown Source)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at android.os.Looper.loop(Looper.java:158)
05-25 17:25:36.221 3434-3434/de.dokate.dagobert.foodchecker.android.app W/System.err:     at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by alecrespo** [comment]
I was having the same issue, I was able to obtain the token but not getting the auth from Firebase. To solve this I register oath of android and web in the Firebase app settings for Google auth. Hope this help you to solve this as well.

**Comment by mutablestudio** [comment]
Also having this issue. OnCompleteListener<AuthResult>() never returns after signing in with  mAuth.signInWithEmailAndPassword on Note 4 (SM-N910V, Android 5.0.1, API 21). Is there a minimum Android API which Firebase supports or a minimum google play services version?

**Comment by samtstern** [comment]
@mutablestudio the minimum Google Play Services version is `9.0.80`.

**Comment by samtstern** [comment]
There hasn't been any activity on this issue in a while and I believe the underlying issue here is that the problematic device does not have the required version of Google Play Services.  At this time that's all I can offer, so I am going to close this issue.

If you can reproduce this on a device with Google Play Services version `9.0.80` or higher, please re-open with some more information.
