### ISSUE TITLE
Small question

### ISSUE THREAD

**Issue by LenCewa** [firebase/quickstart-android#182]
I posted it on [Quora ](https://www.quora.com/unanswered/Why-does-this-code-example-doesnt-connect-with-the-Firebase-database-to-store-user?__filter__&__nsrc__=2&__snid3__=521045125) aswell.

I don't get why you don't build up a database connection how[ this tutorial](https://www.firebase.com/docs/android/guide/login/password.html) does. And why you don't add 
```java
public void onCreate() {
    super.onCreate();
    Firebase.setAndroidContext(this);
    // other setup code
}
```

as suggested [here](https://www.firebase.com/docs/android/quickstart.html). Because when I run your code I can't create a new user. The statement `task.isSuccessful()` [in line 128](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/EmailPasswordActivity.java) is always false.

My database rules are set like this:
```json
{
  "rules": {
    ".read": "auth != null",
    ".write": "auth != null"
  }
}
```

Because when I use your code in my App I can't store any users... and I don't get why it's not working (although it should work like this)

**Comment by samtstern** [comment]
Hi there @LenCewa.  Happy to help here, but in the future please do not disregard the issue template when filing issues.  It's really useful for us!

First of all `Firebase.setAndroidContext(this)` means you are using the old Firebase SDK (from before May 2016).  The tutorial you linked to is from the old Firebase documentation (which goes with that SDK).

The current docs are here: https://firebase.google.com/docs

And the current SDK is `com.google.firebase:firebase-database:10.0.0`.  Make sure you use that and then remove all references to the old SDK.  If you can still access the `Firebase` class, you have the wrong SDK!

**Comment by LenCewa** [comment]
Thank you very much. I tried it with the current docs and it didn't work out correctly that's why somehow I found the old Firebase SDK. I'll give it another shot maybe I did something wrong. If you like to, you can close this "issue". What is the best way to ask those problems? Quora? / SO / or would a mail to your inbox be okay aswell?

**Comment by samtstern** [comment]
Since I'd consider this troubleshooting (because it's likely an issue in your particular code rather than in our code or our samples) the best place for this is StackOverflow.  The reason is that once we help you, other people can learn from it.  If we helped over email then other people with the same question couldn't ever know.

Closing (as you suggested).  Good luck!
