### ISSUE TITLE
+@[[LIVE~STReam]]How to watch Man United vs Leicester City  Live Free stream , TV channel 10 November 2024

### ISSUE THREAD

**Issue by Boorvidadia0E** [firebase/quickstart-android#1825]
How to watch the Premier League match between Manchester United and Leicester City, as well as kick-off time and team news.

Ruud van Nistelrooy will conclude his four-game interim charge at Manchester United when Leicester City make the trip to Old Trafford for a Premier League tie on Sunday.

The Dutchman maintained an unbeaten run (W2 D1) after Thursday's 2-0 victory over PAOK in the Europa League, while the Foxes managed a 1-1 league draw with Ipswich Town last weekend.

Here, GOAL brings you everything you need to know about how to watch, including TV channel, streaming details and more.

How to watch Manchester United vs Leicester City online - TV channels & live streams
Country	TV channel / live stream
United Kingdom	NA
United States	Peacock Premium
Australia	Optus Sport
Canada	Fubo
Germany	Sky Sports Premier League
India	Disney+ Hotstar VIP
Republic of Ireland	NA
Spain	DAZN
Netherlands	Viaplay
South Africa	SuperSport
The Premier League match between Manchester United and Leicester City will not be telecast in the United Kingdom (UK).

In the United States (U.S.), the game will be available to stream live online on Peacock Premium.

logo
Watch the game in the USA on Peacock Premium
Sign up
Check out GOAL's Live Match Centre for updates.

How to watch anywhere with VPN
If you are abroad, you may need to use a virtual private network (VPN) to watch games using your usual streaming service. A VPN, such as NordVPN, allows you to establish a secure connection online when streaming. If you are not sure which VPN to use, check out GOAL's guide to the best VPNs for streaming sports.

logo
Stream live anywhere in the world with Nord VPN
Get NordVPN
Manchester United vs Leicester City kick-off time & stadium
Date:	November 10, 2024
Kick-off time:	9 am ET / 2 pm GMT
Venue:	Old Trafford
The Premier League match between Manchester United and Leicester City will be played at Old Trafford in Manchester, England.

It will kick off at 6 am PT / 9 am ET / 2 pm GMT on Sunday, November 10, 2024.

Team news & squads
Manchester United team news
Amad Diallo emerges as a doubt after picking up a knock following his brace against PAOK, while Luke Shaw, Harry Maguire, Kobbie Mainoo

**Comment by daeypaover** [comment]
ytuyt

**Comment by jadurbasko** [comment]
vcvc

**Comment by palabikoi** [comment]
dffdf
