### ISSUE TITLE
[（live．free™！）] Nottm Forest vs Newcastle Live Streams Free On TV Channel 10 NOV 2024

### ISSUE THREAD

**Issue by 12345we** [firebase/quickstart-android#1846]
Nottingham Forest will look to continue their remarkable start to the season when they host Newcastle United at the City Ground on Sunday.

The Reds have been the Premier League's surprise package through the first 10 games of the 2024/25 campaign, and sit third in the table on 19 points - above the likes of Chelsea, Arsenal, Aston Villa and Tottenham.

Forest beat Liverpool and earned impressive draws against Brighton and Chelsea earlier on in the season, but it's their recent run of three wins on the bounce that has them up in the top four.

It's no fluke either. Only leaders Liverpool (six) have conceded fewer goals than Nuno Espírito Santo's side (seven) this term, while Chris Wood has hit a real purple patch - scoring eight times in 10 league appearances - and will hope to add to his tally against his former club on Sunday.

Watch Nottingham Forest v Newcastle United on Sky Sports
Newcastle head down south with plenty of confidence themselves after ending their recent rough spell by beating Chelsea, in the Carabao Cup, and Arsenal, in the Premier League, in back-to-back games.

They sit 11th in the table, but are just three points back from the top four – and will look to cut that gap on Sunday.

The City Ground has been a happy hunting ground for the Mags in recent years, as they've won on both their visits since Forest's return to the top flight, but Eddie Howe's side will know their hosts have stepped their levels up significantly in 2024/25.

RadioTimes.com has rounded up everything you need to know about how to watch Nottingham Forest v Newcastle United on TV and online.

Read more football features: Best players in the world | Best players of all time | Live football on TV today

When is Nottingham Forest v Newcastle United?
Nottingham Forest v Newcastle United will take place on Sunday 10th November 2024.

Check out our live football on TV guide for the latest times and information.

Nottingham Forest v Newcastle United kick-off time
Nottingham Forest v Newcastle United will kick off at 2pm.

Stay on the ball
Our Football newsletter: news, views and previews of this week's games on TV

Email address
Email address
By entering your details, you are agreeing to our terms and conditions and privacy policy. You can unsubscribe at any time.

What TV channel is Nottingham Forest v Newcastle United on?
You can watch the game live on Sky Sports Premier League and Main Event from 1pm.

Sky Sports can be added to any Sky TV package for just £22 per month for all nine sports channels, or you can pick up the complete sports package plus Netflix for £43 per month.

Sky Sports + will feature more than 1,000 EFL games throughout the season and is included as part of Sky Sports packages.

Find out more about the best Sky packages
How to live stream Nottingham Forest v Newcastle United online
Sky Sports customers can live stream the game via the Sky Go app on a variety of devices including most smartphones and tablets as part of their subscription.

You can also watch the match via NOW with a day membership (£14.99) or month membership (£34.99).

NOW can be streamed through a computer or apps found on most smart TVs, phones and consoles. NOW is also available via TNT Sports.

Listen to Nottingham Forest v Newcastle United on radio
You can listen to the match on BBC Radio 5 Live Sports Extra.

BBC Radio 5 Live Sports Extra are available on DAB radio or you can tune into the station via most TV packages. You can also listen to BBC Radio 5 Live Sports Extra online via the BBC website or BBC Sounds app.

Advertisement

Nottingham Forest v Newcastle United
In working partnership with the Radio Times, bet365 has provided the following betting odds for this event:

bet365 odds: Nottingham Forest (13/8) Draw (5/2) Newcastle United (31/20)*

For all the latest football odds and more, visit bet365 today. Bet £10 & Get £30 in Free Bets for new customers at bet365.

Min deposit requirement. Free Bets are paid as Bet Credits and are available for use upon settlement of bets to value of qualifying deposit. Min odds, bet and payment method exclusions apply. Returns exclude Bet Credits stake. Time limits and T&Cs apply.

*Odds subject to change. 18+. T&Cs apply. GambleAware.org. Note – The bonus code RT365 does not change the offer amount in any way.

**Comment by daeypaover** [comment]
dfgergtr

**Comment by sumaiyatonni25** [comment]
cvbcbbbbbbbbc

**Comment by tonmoyshohel** [comment]
cvcvc
