### ISSUE TITLE
Error: Failed to resolve: com.google.firebase:firebase-appindexing:

### ISSUE THREAD

**Issue by jsroyal** [firebase/quickstart-android#188]
Question is here.   [StackOverflow](http://stackoverflow.com/questions/40853022/error-failed-to-resolve-com-google-firebasefirebase-appindexing9-6-1)

### Step 2: Describe your environment

  * Android device: 16 API
  * Android OS version: Andoird
  * Google Play Services version: 3.0.0
  * Firebase/Play Services SDK version: 9.6.1
  
### Step 3: Describe the problem:
Error:(56, 13) Failed to resolve: com.google.firebase:firebase-appindexing:10.0.1 </br>
<a href="openFile:/friendlychat/android-start/app/build.gradle"></br>

**Comment by samtstern** [comment]
@jsroyal please don't duplicate posts, let's address this on StackOverflow.
