### ISSUE TITLE
Documentation for the Android Firebase SDK incomplete or absent

### ISSUE THREAD

**Issue by larrytech7** [firebase/quickstart-android#189]
While using firebase as a backend in a mobile application like android, i find it useful to have the quick  documentation ready and well made. This is currently not the case 
I am using Android Studio 2.2.2,
Firebase version 9.8.0

This should be added to further simplify the developer's life

**Comment by samtstern** [comment]
@larrytech7 here are a few documentation resources I can recommend:

  * [Firebase Android Codelab](https://codelabs.developers.google.com/codelabs/firebase-android/#0)
  * [Firebase Database - Read and Write Data on Android](https://firebase.google.com/docs/database/android/read-and-write)
