### ISSUE TITLE
HERE’S!! WAY TO WATCH Chelsea vs Arsenal LIVE STREAMS FREE Broadcast ON TV CHANNEL 10 NOV 2024

### ISSUE THREAD

**Issue by 12345we** [firebase/quickstart-android#1894]
How to watch today's Chelsea vs Arsenal Premier League game: Live stream, TV channel, and start time
How to watch the Premier League match between Chelsea and Arsenal, as well as kick-off time and team news.

The last Premier League clash before the international break promises to be thrilling, as London rivals Chelsea and Arsenal square off at Stamford Bridge on Sunday.

Currently, both teams sit close in the standings after a promising start to the season for Enzo Maresca's Blues. While they've impressed in major matches, their recent 1-1 draw with Manchester United left fans wanting more.

Meanwhile, Mikel Arteta is likely frustrated with the Gunners holding onto fifth place after 10 matches, especially given their high standards from the past two seasons. They will approach this clash with something to prove, hoping to revive their title bid after a recent slump. Last weekend's 1-0 loss at Newcastle marked their second defeat in their last three league games.

They also suffered a setback midweek, falling 1-0 to Inter Milan in the Champions League, which snapped their unbeaten European run. Nevertheless, a crucial three points are up for grabs, and both sides will be determined to come away with the victory.

Here, GOAL brings you everything you need to know about how to watch, including TV channel, streaming details and more.

How to watch Chelsea vs Arsenal online - TV channels & live streams
Country	TV channel / live stream
United Kingdom (UK)	Sky Sports Main Event, Sky Sports Premier League, Sky GO
United States (U.S.)	USA, Telemundo, Fubo, Sling Blue, DirecTV Stream,
Australia	Optus Sport
Canada	Fubo
Germany	Sky Sports Premier League
India	Star Sports, Disney+ Hotstar VIP
Republic of Ireland	Sky Sports Premier League, Sky Sports Main Event, Sky GO
Spain	DAZN
Italy	Sky Sports Uno, Sky Go Italia
Netherlands, Denmark, Sweden, Poland	Viaplay
South Africa	SuperSport
In the UK, the Premier League match between Chelsea and Arsenal will be broadcast live on TV on Sky Sports Main Event, Sky Sports Premier League and Sky Sports Ultra HDR, and is available to stream online live through Sky Go.

In the United States (US), the Premier League match will be available to stream live online on Fubo (sign up for a free 7-day trial), Sling Blue and DirecTV Stream, as well as being broadcast live on USA and Telemundo.

Check out GOAL's Live Match Centre for updates.

How to watch anywhere with VPN
If you are abroad, you may need to use a virtual private network (VPN) in order to watch games using your usual streaming service. A VPN, such as NordVPN, allows you to establish a secure connection online when streaming. If you are not sure which VPN to use, check out GOAL's guide to the best VPNs for streaming sport.

logo
Stream live anywhere in the world with Nord VPN
Get NordVPN
Chelsea vs Arsenal kick-off time
Date:	Sunday, November 10, 2024
Kick-off time:	11:30 am ET/ 8:30 am PT/ 4:30 pm GMT
Venue:	Stamford Bridge
The Premier League match between Chelsea and Arsenal will be played at the Stamford Bridge in London, England.

It will kick off at 11:30 am ET/ 8:30 am PT/ 4:30 pm GMT on Sunday, November 10, 2024.

Team news & squads
Chelsea team news
Chelsea remain optimistic about Cole Palmer's availability following his recent injury, with head coach Enzo Maresca set to reshuffle the lineup significantly from Thursday's squad. Key players like Moises Caicedo, Nicolas Jackson, Reece James, Wesley Fofana, and Romeo Lavia are all likely to make their returns.

Chelsea possible XI: Sanchez; Gusto, Fofana, Colwill, James; Caicedo, Lavia; Madueke, Palmer, Neto; Jackson

Position	Players
Goalkeepers:	Sanchez, Bettinelli, Bergstrom, Jorgensen
Defenders:	Disasi, Cucurella, Adarabioyo, Badiashile, Colwill, Chilwell, James, Gusto, Fofana, Veiga
Midfielders:	Fernandez, Felix, Chukwuemeka, Palmer, Caicedo, Casadei, Dewsbury-Hall, Lavia
Forwards:	Neto, Mudryk, Madueke, Jackson, Nkunku, Sancho, Guiu
Arsenal team news
Midfielder Declan Rice is a concern heading into this high-stakes matchup due to a suspected broken toe, putting his participation in doubt. Kai Havertz also awaits medical clearance after a head collision with Inter's Yann Bisseck on Wednesday.

Meanwhile, Riccardo Calafiori (knee), Takehiro Tomiyasu (knee), and Kieran Tierney (hamstring) are all sidelined until after the international break. Martin Odegaard is expected to play in some capacity, while Raheem Sterling is unavailable due to his loan terms, barring him from facing his parent club.

**Comment by altapkhan001** [comment]
cvcv
