### ISSUE TITLE
service unstable - messages received after huge delay or not at all 

### ISSUE THREAD

**Issue by ksachdeva11** [firebase/quickstart-android#190]
### Step 2: Describe your environment

  * Android device: Emulator Nexus 5
  * Android OS version: 7.0

### Step 3: Describe the problem:

Notification messages sent via FCM console or via using FCM API are not received with huge delay or not received at all.

#### Steps to reproduce:

  1.  POST 
API-   https://fcm.googleapis.com/fcm/send

Request body -  {
	"to":"ekeBVIfgHzc:APA91bGJ3ncPobSXY-QfaKlEynTprlANpabEh543cBNPravOMsUr0vO3KooMZqo6yRfHllKyTOUdMbdaja6SMXynD9wCdF3bJxN_84mafP1AHPTaMaJEscMHQtU4fNrIRaPFK1r2ZcdK",
	"notification": {
    "title": "Portugal vs. Denmark",
    "body": "5 to 1"
  }
}

Response - 200 OK
{
  "multicast_id": 5406170109250505162,
  "success": 1,
  "failure": 0,
  "canonical_ids": 0,
  "results": [
    {
      "message_id": "0:1480480100858521%31bd1c9631bd1c96"
    }
  ]
}

  
#### Observed Results:

 Notification messages are not received.
  
#### Expected Results:

 Notification should be received on the device within seconds or least in a minute or two.

**Comment by kroikie** [comment]
Hi @ksachdeva11 there are several things that could cause notifications sent by FCM to have delays. If you are receiving them at all then the issue is unlikely to be your code and more likely to be the networks that exist between the device and FCM.

I suggest that you file an issue with [firebase support](https://firebase.google.com/support/contact/troubleshooting/) so you can give more information about your particular case.

**Comment by Narender8** [comment]
I am still facing this exact issue. Please don't close it. And there is no any network problem. It is an issue by FCM

**Comment by karique01** [comment]
I have the same problem, but i note that if i turn off the wifi and then turn on again the notifications come in that exact moment. Maybe the problem it's in the client side.

**Comment by katowulf** [comment]
This issue tracker is dedicated to issues related to the Android Quickstart. The gurus working on this project don't have access to any diagnostics to help troubleshoot FCM issues. Please [contact support](https://firebase.google.com/support/).
