### ISSUE TITLE
Anonymous Login 

### ISSUE THREAD

**Issue by rajat028** [firebase/quickstart-android#191]
I got stucked in a scenario.
Step 1 - whenever user comes to my app anonymous login process begin and in return i got firebase UID.
Step 2 - After Selecting some products . User try to login by email and password which were already registered on firebase . In this case i am getting **Exception The email address is already in use by another account.**. If user enters the email which is not registered on firebase it works fine ."Anonymous user replaced with the email id .
Is there any way through which i can link the anonymous user with existing firebase user?

**Comment by samtstern** [comment]
@rajat028 yep, we call this "account linking":
https://firebase.google.com/docs/auth/android/account-linking

So you'll want to call the `linkWithAccount` method to link your anonymous users to an existing account.

**Comment by noung1234** [comment]
https://firebase.google.com/docs/auth/android/account-linking

**Comment by noung1234** [comment]
linkWithAccount
