### ISSUE TITLE
Login not working - Just shows 'Loading' forever

### ISSUE THREAD

**Issue by vinigfer** [firebase/quickstart-android#192]
I'm trying to run a simple example from the repository (storage), in the Android Emulator and after clicking in the "Sign In" button, the App just shows the loading animation forever. Doesn't ask me for email or anything. I already enable anonymous and email/password as my login providers, but this issue still persists. What should I do to bypass this?? 

Already supplied to the App the google-services.json file that have should have all the necessary information.

**Comment by samtstern** [comment]
@vinigfer could you provide some of the information that was in the issue template.  For instance, what version of the firebase SDK are you using, and what is the version of Google Play services installed on your device?

**Comment by vinigfer** [comment]
Sorry for the late response.
Firebase SDK (from storage/app/build.gradle):
compile 'com.google.firebase:firebase-auth:10.0.1'

Google Play Services (from storage/build.gradle):
classpath 'com.google.gms:google-services:3.0.0'

As I said before, I'm trying to run it in the Android Emulator, not an actual device.

Other things I already tried:
- Disabled instant run
- Download and used on the emulator a new android image (7.1.1, API Level 25)
- Updated Google Play Services using the SDK manager. Currently Android Studio/SDK Manager says it is on revision 38

I am getting this messages on Android Studio Console:
V/FA: Connecting to remote service
W/GooglePlayServicesUtil: Google Play services out of date.  Requires 10084000 but found 9879480
W/FA: Service connection failed: ConnectionResult{statusCode=SERVICE_VERSION_UPDATE_REQUIRED, resolution=null, message=null}
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 10s
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED, retry in 20s
W/FA: Tasks have been queued for a long time

**Comment by samtstern** [comment]
Ah ok, this is (sadly) working as intended.

Right now the `7.1.1` emulators don't have the latest version of Google Play Services, so they can't run this sample.  If you try an emulator running on `7.0` or `6.0` it should work fine.

**Comment by vinigfer** [comment]
Forgot to mention: this issue is also happening with android 6. I already had an image downloaded some time ago (API Level 23, x86 version), and I received the same console messages.
Should I try with API Level 24 (Android 7.0)?

**Comment by samtstern** [comment]
Are all the images up to date in the Android SDK manager?

**Comment by vinigfer** [comment]
Found a missing update for the 6.0 image.
Have no idea why, but the SDK created 2 entries: one for the installed revision (at the top) and another one for the newly available update (at the bottom). Thats why I though there were no updates for 6.0 image. After updating, it finally went through the anonymous login. Thanks @samtstern

**Comment by tonialiyev333** [comment]
Hello vinigfer.
I've also met same issue.
My app can login android API 22.
But can't login API23~.
What is problem?
Thanks

**Comment by vinigfer** [comment]
Sorry for the late response @tonialiyev333 
I ended up solving my problem with a (well hidden) image update. Maybe try to remove/uninstall the SDK download and download it again. That may fix your issue.

**Comment by PrafulAnand** [comment]
I am also facing the same issue ...how did you get it solved the login thing...

**Comment by tonialiyev333** [comment]
Thanks vinigfer
