### ISSUE TITLE
Firebase onMessageReceived not called when app in foreground

### ISSUE THREAD

**Issue by sant527** [firebase/quickstart-android#195]
My app is in foreground: That is i opened the app and seeing it. Then i send a notification from firebase console. My android log shows the message: Here its (gaura)

```
12-24 16:53:17.719 6384-11491/shyamananda.com.articles D/FA: Logging event (FE): _nr, Bundle[{_o=fcm, _ndt=0, _nmn=gaura, _nmt=1482578598, _nmid=7276511211719764766}]
12-24 16:53:17.733 6384-11491/shyamananda.com.articles D/FA: Logging event (FE): _nf, Bundle[{_o=fcm, _ndt=0, _nmn=gaura, _nmt=1482578598, _nmid=7276511211719764766}]
```

But my onMessageReceived is not being called. 

I have the below inside onMessageReceived.

`Log.d(TAG, "From: " + remoteMessage.getFrom());` 

I cant see any log having `From:  .......`

**Comment by kroikie** [comment]
Glad you got it working.
