### ISSUE TITLE
Unable to integrate latest 10.0.1

### ISSUE THREAD

**Issue by MohamedImthiaz** [firebase/quickstart-android#196]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____any device
  * Android OS version: _____any OS 
  * Google Play Services version: _____3.0.0
  * Firebase/Play Services SDK version: _____9.2.1 works but not 10.0.1
  
### Step 3: Describe the problem:

Unable to add compile 'com.google.firebase:firebase-messaging:10.0.1'
Always throws not found though i have updated the Google Play Repository as expected, so able to build only wiht 9.2.1

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@MohamedImthiaz can you try following these steps: http://stackoverflow.com/a/37310513/324977

**Comment by samtstern** [comment]
@MohamedImthiaz due to the nature of this issue and the lack of updates I assume you have solved it?  Closing, but please add a note or re-open if this is still happening.
