### ISSUE TITLE
signInWithEmailAndPassword method problem

### ISSUE THREAD

**Issue by balajivenkat52** [firebase/quickstart-android#198]
I find issues in the above method. Inspite of being an in-built method, Android studio fails to recognise it. I get an error stating "**symbol not resolved**". Give me directions to resolve this.

**Comment by Salil999** [comment]
You could try to sync your project with Gradle and see if that fixes it. Did you add all the Firebase dependencies?

**Comment by samtstern** [comment]
@balajivenkat52 I believe @Salil999 has the right idea.  You need to do a few things:

  1. Make sure you have the latest Google Play services SDK, which you can get using [this procedure](http://stackoverflow.com/a/37310513/324977)
  2. Make sure you have the proper dependencies added to your app, such as `com.google.firebase:firebase-auth:10.0.1`
  3. In Android Studio, hit **sync**

If the above steps don't work for you, please re-open this issue.
