### ISSUE TITLE
Add Database rules to readme

### ISSUE THREAD

**Issue by Maragues** [firebase/quickstart-android#199]
I would like to see the database rules in Database's [readme](https://github.com/firebase/quickstart-android/blob/master/database/README.md)

Thanks!

**Comment by samtstern** [comment]
@Maragues are there specific rules you think we should add or do you mean a general description of DB rules?

**Comment by Maragues** [comment]
Since this is an example, I was thinking of the full JSON describing the rules, but that may be hard to maintain if the sample is still WIP.

Considering there are 3 models (User, Post and comment), it would help seeing a real world example that manages objects that belong to other entities, authentication, flat hierarchies created to improve speed and other aspects I might be missing.

**Comment by samtstern** [comment]
Fixed by #201, hope that helps!

Please note that in the end this is still a sample and (as I put in the updated docs) some choices were made for simplicity.

**Comment by Maragues** [comment]
Looks great, thanks!
