### ISSUE TITLE
Deeplinking Shared on Faceboook

### ISSUE THREAD

**Issue by panagorn** [firebase/quickstart-android#202]
Hello,

I am trying to share a link on facebook and when you click on the link i want to open the app but it always send me to the play store. if i press the link from an email then it opens the application.

**Comment by ianbarber** [comment]
Thanks for the report - we released an update to Dynamic Links earlier this month which should have improved this situation. If you're still seeing problems, please feel free to file a bug with the platform support team: https://firebase.google.com/support/contact/bugs-features/
