### ISSUE TITLE
onMessageReceived not working when application closed

### ISSUE THREAD

**Issue by PankajSavaliyaGit** [firebase/quickstart-android#204]
### onMessageReceived not working when application closed

  * when application is open while this method is called but when application close at that time not working this method for custom notification.
  * I have add all service for firebase notification in AndroidManifest and also try to default icon notification when add meta-data in AndroidManifest but i want to just custom notification but this onMessageReceived not working.

**Comment by samtstern** [comment]
I believe this is similar to #4 or #89.  Let's move the conversation over there, since this issue report does not contain any new information.
