### ISSUE TITLE
Every time getting null data in extra intent

### ISSUE THREAD

**Issue by ashishparmar** [firebase/quickstart-android#205]
Android device: Nexus 5 or emulator
Android OS version: Android N or Android M
Google Play Services version: 9.2.1
Firebase/Play Services SDK version: 9.2.1
Steps to reproduce:

Using the Firebase console (or via the REST API), send a notification with custom data (for e.g. key "discount" value "10" )
app is in background or not running
Observed Results:

though, the notification does appear in the system tray, the data is NOT available in the intent... either in onNewIntent or in onCreate, the extras is null.

Expected Results:

According to the Firebase Notifications docs, when App State is Background and a Notification with data is sent, the notification appears in the system try and the data will be available in the extras of the intent.

```java
@Override
public void onCreatet() {
    Bundle extras = getintent().getExtras();
    // ---> extras is always null when app is not running or when app is in background
}

@Override
public void onNewIntent(Intent intent) {
    Bundle extras = intent.getExtras();
    // ---> extras is always null when app is not running or when app is in background
}
```

Remarks: The data is available when App State is in the Foreground. But the notification console is pretty much unusable with this bug because ALL (background, app not running, foreground) users need to be able to get the data in a notification. Otherwise, how does a developer know what data a user saw or didn't see (e.g. whether a user was shown the discount 10% or not).

**Comment by kroikie** [comment]
Hi @ashishparmar please use the latest version of the SDK 10.0.1. The custom data would only be in the extras if the intent is launched as a result of the user tapping the displayed notification. Could you confirm that the user is tapping the notification to launch the intent?

**Comment by amarantedaniel** [comment]
@kroikie I'm having a similar problem, I'm using the SDK 10.0.1 and sending a notification with both `notification` and `data`. When I receive the notification in background, I tap the notification to launch the intent and the intent extras is null.

**Comment by wilsondezapp** [comment]
@kroikie I'm also having a similar issue while using the SDK 10.0.1. The notification and data is sent through the Firebase web console. When the notification is tapped while the app is in background, but not killed, the app is re-opened normally and the intent extras doesn't have the payload. The data payload is not delivered in the extras of the intent of the launcher Activity per the documentation and the Activity's onNewIntent(Intent intent) is never called.

**Comment by ashishparmar** [comment]
Hi @kroikie  yes i have try but as experienced by @amarantedaniel same i have. so can you please suggest a demo example for handle fcm notification so it is easy to understand. 

Thnks in advance

**Comment by Querschlag** [comment]
Same issue here.
SDK: 10.0.1
Device: Google Pixel - Android 7.1.1

When the app is running (Activity in foreground) I can read the extras from the intent, but as soon as the app is in background or removed from the app switcher and the user taps on a notification the intent won't have any of my custom extras.

**Comment by AshkanImmortal** [comment]
Any solution for this, I have same issue, I get data when app is killed thou, but not when in background

**Comment by kenk11** [comment]
I got this problem too, any solution for this guys ?

**Comment by zmarwa** [comment]
same thing to me, any solution ?

**Comment by jogilsang** [comment]
I'm solved it. no problem.~~

나의 SOL에서 보냄
2017. 3. 6. 오후 8:27에 zmarwa <notifications@github.com>님이 작성:same thing to me, any solution ?

**Comment by kenk11** [comment]
@jogilsang , how did you solve it ? Could you share it ?
Thanks advance

**Comment by zmarwa** [comment]
@jogilsang could you please give us how to solve it ?
thks !

**Comment by jogilsang** [comment]
Sorry. I dont`t remember that. 
Because, my app is startversion. many problem is accured and i solveed that.
 Recently my issues are belong.

1. proguard build error
-> my query code about firebasereference
   ex) mRootRef -> users -> uid
              A -> b -> c
    Very wrong conversion. 
    And i`m startup developer. i`m actually dont' know proguard. so,
     Just cansel proguard. and build it. well done in release mode

Thank you for feedback :)
    

2017. 3. 8. 오전 4:21에 zmarwa <notifications@github.com>님이 작성:@jogilsang could you please give us how to solve it ?
thks !

**Comment by sanyuzhang** [comment]
@kroikie 

Excuse me, I have the same issue. 

Firebase sdk is the newest one - 10.2.4.

- [x] - App is foreground, onMessageReceived() method is called and data got.
- [x] - App is killed, intent extras could be received successfully after I tap the notification.
- [ ] - App is background but not killed, the app will be brought back to foreground with null intent extras after I tap the notification.

Btw, the launch mode of my activity is singletask.

Thanks a lot.

**Comment by kroikie** [comment]
Hi All,

Data being passed to the intent launched as a result of tapping the notification only applies to notification messages when the app is in the background. If you are handling the incoming message in onMessageReceived then you will have to extract the data and pass it to the intended intent yourself.

The launch mode of the intent should not affect the passing of the data to it.

Could someone confirm that they are seeing this issue with notifications generated by the SDK and not notifications that are generated by your app?

Thanks.

**Comment by MohitTest1** [comment]
@kroikie @ashishparmar @amarantedaniel @wilsondezapp @Querschlag 

I am also getting the same problem. Anyone have something to solve it.

Thanks in advance

**Comment by zmarwa** [comment]
Hello,
I did not found how to solve it using firebase console. But to go around this, i used to send notification with the API (PHP). Exemple of script here: https://gist.github.com/MohammadaliMirhamed/7384b741a5c979eb13633dc6ea1269ce

Hope that helps you!

**Comment by kroikie** [comment]
@MohitTest1 thanks for confirming, could you let me know what device you are seeing this with? Also could you try with an emulator and let me know if you are seeing the same?

**Comment by MohitTest1** [comment]
@kroikie 

Thanks for reply.

I got the solution.

@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);

        Log.d("Msg", "Message received ["+remoteMessage+"]");
        //Toast.makeText(this, "onDeletedMessages1", Toast.LENGTH_LONG).show();
        // Create Notification
        Intent intent = new Intent(this, MainActivity.class);
        intent.putExtra("body",remoteMessage.getNotification().getBody());
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 1410, intent,
                PendingIntent.FLAG_UPDATE_CURRENT);


        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                .setSmallIcon(R.drawable.ic_stat_name)
                .setContentTitle(remoteMessage.getNotification().getTitle()).setContentText(remoteMessage.getNotification().getBody())
                .setAutoCancel(true)
                .setContentIntent(pendingIntent);

        NotificationManager notificationManager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

        notificationManager.notify(1410, notificationBuilder.build());
    }

@Override
public void handleIntent(Intent intent) {
    super.handleIntent(intent);
    Intent intent1 = new Intent(this, MainActivity.class);
    Bundle extras = intent.getExtras();
    String body = extras.getString("gcm.notification.body");
    String Nick = extras.getString("Nick");
    intent1.putExtra("body",body);
    SharedPreferences.Editor editor = getSharedPreferences("MY_PREFS_NAME", MODE_PRIVATE).edit();
    editor.putString("body", body);
    editor.commit();
    //startActivity(intent1);
    Log.d("handleIntent", "handleIntent "+body);
} 

Need to override handleIntent() method which will give you all the payload and notification.

**Comment by kroikie** [comment]
Glad you found a solution.

For others using this approach, generating the notification yourself means
you are responsible for passing data to the launched intent. The automatic
passing of data from the FCM data payload only happens when the
notification is automatically generated by the SDK.

**Comment by pollyfat** [comment]
@MohitTest1 Thanks for the solution!

But how to know it is notification be clicked or just the logo?

I handle the notification strings in MainActivity's onResume() and in this way the "handleNotification" function will called every time MainActivity start, which is wrong. :(

**Comment by RazielMx** [comment]
@kroikie  as @pollyfat  mentions, the workaround proposed by @MohitTest1  will result in weird behaviours by the app, if the user taps the notification or the launcher (app icon) we will have the information saved on Shared Preferences and as far as I've been researching there is no clear way to check if the user entered from notification or from app icon. 

I thinks the thread should not be closed, the problem is still active.

**Comment by rubenlop88** [comment]
This issue should not be closed. Data is not being sent in the launcher intent when a user taps the notification. That workaround is not a solution.

**Comment by sbouiachref** [comment]
Any solution please !!! If messages contain both notification and data payload ,when I receive the notification in background, I tap the notification to launch the intent and the intent extras is null.

**Comment by YousufSohail** [comment]
I am also facing this issue and I ran all possible scenarios and observed that it's not the App state (i.e. Background or Killed) at the TIME OF TAP that causing the issue but it's App state (i.e. Background or Killed) at the TIME OF NOTIFICATION CREATION that is causing this issue. Find this graph below: 
  
![fullsizeoutput_3](https://user-images.githubusercontent.com/2059838/31398386-37c8ce06-ae02-11e7-896d-2639ebcceb97.jpeg)

**Comment by abhibhingarde** [comment]
send  DATA payload to fcm endpoint.

like,
{
   "to" : "deviceid...",
   "data" : {
     "Title" : "Notification title",
     "body" : "Notification body"
   },
 }

**Comment by akshayejh** [comment]
If app is in Foreground you can receive the "Notification" as well as "Data" in "onMessageReceived"
and there you can create PendingIntent including the click action.

But if the app is running in background the "Notification" is delivered to SystemTray but the "Data" is delivered to "Intent Extra" if you deliver Notification and Data both at same time. So instead in you "onMessageRecieved" method, what you need to do is. In you Activity where you are redirecting users to when they click notification.

Just create : 

String data_message = getIntent().getStringExtra("data-key");

Replace "data-key" with the key of data.

Say for example : 

`const payload = {
        notification: {
          title : "Notification Title",
          body: "Notification Message",
          icon: "default",
          click_action: "TARGETNOTIFICATION"
        },
        data: {
          message : "Notification Message"
        }
      };`

If you want detailed explaination, you can checkout : 
https://www.youtube.com/playlist?list=PLGCjwl1RrtcRHjHyZAxm_Mq4qvtnundo0

**Comment by Drakot** [comment]
@soufianeEssabbane solutions works nicely

**Comment by taar1** [comment]
I found a solution that worked for me: https://github.com/firebase/quickstart-android/issues/822#issuecomment-507231930

**Comment by krupeshMH** [comment]
Use Bundle instead of Intent to pass data. This will solve the problem.

**Comment by gimartinez17** [comment]
I had this same issue and I solved it by changing json payload
```
{
   "to":"xxxxx:...",
   "data":{
          "title":"Title",
          "body":"Body",
          "click_action":"MyActivity",
          "item_id":"123"
      }
}
```

**Comment by praveenb** [comment]
I had the same issue, solved it by below code


```
Intent notificationIntent = new Intent(getApplicationContext(), viewmessage.class);
notificationIntent.putExtra("NotificationMessage", notificationMessage);
notificationIntent.addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP);
PendingIntent pendingNotificationIntent = PendingIntent.getActivity(getApplicationContext(),notificationIndex,notificationIntent,PendingIntent.FLAG_UPDATE_CURRENT);
notification.flags |= Notification.FLAG_AUTO_CANCEL;
notification.setLatestEventInfo(getApplicationContext(), notificationTitle, notificationMessage, pendingNotificationIntent);
```

In the above code using
Intent flags Intent.FLAG_ACTIVITY_SINGLE_TOP | Intent.FLAG_ACTIVITY_CLEAR_TOP, 
and Pending intent flag as PendingIntent.FLAG_UPDATE_CURRENT .

Then we can get the intent data in Activity `onNewItent `method.

**Comment by somshine** [comment]
For mi it's solved by using the below code that Bundle data is not available in the onResume() method.

@Override
    protected void onNewIntent(Intent objIntent) {
        super.onNewIntent(getIntent());
        Log.e(TAG, "onNewIntent() called. neww intenet");
        Log.e(TAG, objIntent.getExtras().size() + " total nodes");
        Bundle extras = null;
        if (objIntent != null && objIntent.getExtras() != null && objIntent.getExtras().size() > 0) {
            extras = objIntent.getExtras();
            Log.i(TAG, extras.getString("action"));
            Log.i(TAG, extras.getString("message"));
            Log.i(TAG, extras.getString("clickAction"));
            Log.i(TAG, extras.getString("module"));
            Log.i(TAG, extras.getString("mainMenu"));
            Log.i(TAG, extras.getString("subMenu"));
        }
    }

**Comment by backspacelab** [comment]
I had the null issue too. You need to check  intent.extras in the very first activity your app opens up. For me it was my splash screen activity and not MainActivity.
