### ISSUE TITLE
Local module descriptor class for com.google.firebase.auth not found

### ISSUE THREAD

**Issue by BRoy98** [firebase/quickstart-android#208]
### My Device info:

  * Android device: Redmi Note 3
  * Android OS version: 7.1
  * Google Play Services version:10.0.85
  * Firebase/Play Services SDK version: 10.0.1
  
### Problem Description:

 When I am adding a new user with `createUserWithEmailAndPassword(email, password)` method it is not getting registered and showing this error:

`W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.`

 **NOTE:** When first time I registered a user, it registered successfully without any error. After that, I am constantly getting this error.

any way to solve this error?

**Comment by samtstern** [comment]
@BRoy98 is this device specific?  I have seen the Redmi Note 3 cause strange behavior in the past.  If you could try this on either another device (preferably non-Xiaomi) or an emulator with Google Play Services that would help narrrow it down.

**Comment by BRoy98** [comment]
@samtstern I tried on another device.
Device info:
- Android device: Moto E
- Android OS version: 5.1
- Google Play Service verion: 10.0.84

I got the same error there.

**Comment by samtstern** [comment]
@BRoy98 ok I think this log might be a red herring and the problem might be something else.  Since you are trying email/password authentication are you sure that you have enabled that auth method in the Firebase console?

https://console.firebase.google.com/project/_/authentication/providers

**Comment by samtstern** [comment]
It's been a long time since the last update here so I am going to close this issue.  Thank you for reporting it and feel free to re-open if it you'd like to discuss further.

**Comment by munibhamza** [comment]
I am having the same error If anybody please help me to resolve this issue 
![screen shot 2018-06-29 at 2 50 29 am](https://user-images.githubusercontent.com/38657444/42063124-b74c43a0-7b49-11e8-93d0-37f496a9beec.png)

**Comment by samtstern** [comment]
Are you using an emulator or a device without Google Play services?
