### ISSUE TITLE
How to get error message when createUserWithEmailAndPassword

### ISSUE THREAD

**Issue by wangbourne** [firebase/quickstart-android#209]
In order to get result and error message from 'createUserWithEmailAndPassword', in iOS, we can know exactly the error message from  NSError. How can we do this on Android?

`[[FIRAuth auth] createUserWithEmail:email password:password
                             completion:^(FIRUser * _Nullable user, NSError * _Nullable error)`

**Comment by samtstern** [comment]
When you attach a failure listener to a `Task` you get an `Exception`.  For auth operations this will be an instance of [`FirebaseAuthException`](https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseAuthException)

You can use `instanceof` to see if it's an instance of a specific direct subclass you're interested in like the following:
  * FirebaseAuthActionCodeException
  * FirebaseAuthInvalidCredentialsException
  * FirebaseAuthInvalidUserException
  * FirebaseAuthRecentLoginRequiredException
  * FirebaseAuthUserCollisionException

Hope that helps!

**Comment by wangbourne** [comment]
Sorry for my poor expression.
Actually, my question is: Can API  correctly feedback  an appropriate message for following cases rather than exception?  (in iOS, these feedback messages could used to show an alert dialog to tell users what to do next)

create 
1. user name has been used 
2. password is too simple

sign
1. user name does not exist
2. password is not correct
