### ISSUE TITLE
Sign in using same email on multiple devices

### ISSUE THREAD

**Issue by abhinav272** [firebase/quickstart-android#211]
I am integrating firebase auth for google and facebook sign-in, everything works perfect but in a scenario I m stuck.

Any help would be appreciated.

  * Android device: Nexus 5
  * Android OS version: 7.1 Android
  * Google Play Services version: 10.0.84
  * Firebase/Play Services SDK version: 9.8.0
  
### Step 3: Describe the problem:

If I sign-in using one device and keep it logged in and sign in using same email id in the second device, I want the first one to automatically log out. 
Is there a way handle this case..

#### Steps to reproduce:

  1. Sign in using an email Id in Device 1 
  2. Keep Device 1 signed in (do not log out)
  3. Sign in using same email id (used in step 1) to sign in another device say Device 2
  
#### Observed Results:

Both devices are logged in using same email id
  
#### Expected Results:

I want the somehow the first device to log out automatically

**Comment by samtstern** [comment]
Sorry @abhinav272 that's not a supported feature of Firebase Auth right now, but I will take it as feedback.

**Comment by ejswenson15** [comment]
+1
