### ISSUE TITLE
fcm token BLACKLISTED

### ISSUE THREAD

**Issue by Rohit-purpleDeck** [firebase/quickstart-android#212]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@Rohit-purpleDeck since there's no information filled in for the issue template I am going to close this issue.

Based on the title, sounds like you may want to reach out to our [personalized support channel](https://firebase.google.com/support/contact/troubleshooting/) to troubleshoot.

**Comment by Rohit-purpleDeck** [comment]
It got submitted by mistake while I was editing it. We're having an issue where some of our fcm token come up as blacklisted. There's not much information available on the web about the same. Sure thanks for the comment I'll have my issue put out there.

**Comment by 2ndGAB** [comment]
Hello,
I saw this morning that a Nexus 5X sent me 'BLACKLISTED' instead of a regular token.
What does that mean?

**Comment by Rohit-purpleDeck** [comment]
Hi, 
We had that issue for a while and then it stopped. The issue is from Google's servers and shouldn't have anything to do with you've implemented Firebase in you application. We didn't get any solid answers from Google when we had this issue but it randomly started and stopped after a few days.

**Comment by 2ndGAB** [comment]
good point

**Comment by rockneverdies55** [comment]
Almost 6 years later having the same exact issue. Nothing to go after, no clue at all.

**Comment by jpeggdev** [comment]
Same here. I'm getting Blacklisted tokens on my app. I'm going to add some more information to the API that my app uses so I can better detect the settings and maybe the reason. Any new information you can shed would be great.
