### ISSUE TITLE
at com.google.firebase.iid.zzb$2.run(Unknown Source)  crash on android 16

### ISSUE THREAD

**Issue by ziad20** [firebase/quickstart-android#215]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@ziad20 there is no information in the issue body here (the template has been left blank) so I am going to close this issue as I can't debug it.  If you have more information you'd like to share, please fill out the template as best you can and we can continue discussing.

**Comment by ziad20** [comment]
Hi

As I have seen, the issue is not new for you, therefore, I kept the tpic in
the subject of the issue which  app crash due to :



 com.google.firebase.iid.zzb$2.run(Unknown Source) crash on android 16


Regards

**Comment by samtstern** [comment]
@ziad20 I think you should check out issue #16

**Comment by suhadzain** [comment]
Please update firbase api and google api. problem will fix as my experience

**Comment by suhadzain** [comment]
I think u can use Firebase version 10.2.1
