### ISSUE TITLE
Firebase Deep link not working in background in Android

### ISSUE THREAD

**Issue by shivangbtech** [firebase/quickstart-android#217]
I am using firebase deep linking for Android, but it does not work properly in background. Here is my code that I am using

 ```
mGoogleApiClient = new GoogleApiClient.Builder(this)
                .enableAutoManage(SplashActivity.this, SplashActivity.this)
                .addApi(AppInvite.API)
                .build();
        boolean autoLaunchDeepLink = false;
        AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, this, autoLaunchDeepLink)
                .setResultCallback(
                        new ResultCallback<AppInviteInvitationResult>() {
                            @Override
                            public void onResult(@NonNull AppInviteInvitationResult result) {

}}}
```

It's working when Application is not in Background, but If app is in background it open the app but 'onResult' method of 'ResultCallback' does not call that's why I am unable to navigate application screen according to requirement.

**Comment by samtstern** [comment]
@shivangbtech you have called `.enableAutoManage(SplashActivity.this, SplashActivity.this)` which means that the lifecycle of the `GoogleApiClient` is tied to `SplashActivity`.   In `onStart` there is a call to `mGoogleApiClient.connect()` and in `onStop` there is a call to `mGoogleApiClient.disconnect()`

Could you explain what you are trying to do with deep links in the background?

**Comment by shivangbtech** [comment]
When Application is in background (Any Screen)  and I tap on link shared in email than app should open with desired screen(Fragment) but it just open the app and `ResultCallback` does not call at that time. Also I am just using above (Shared) code in `onCreate` method of Activity not like you shared `mGoogleApiClient.connect()`

**Comment by samtstern** [comment]
@shivangbtech are you sure that `onCreate` is called at all when your `Activity` resumes from the background?  Maybe you should check in `onResume` or `onNewIntent`?

**Comment by samtstern** [comment]
Closing this issue as stale, it's been a while since the last response.
