### ISSUE TITLE
onMessageReceived not called when app killed for certain devices (data-only payload, Xiaomi, ASUS)

### ISSUE THREAD

**Issue by app-ad** [firebase/quickstart-android#219]
I am sending a data-only packet to my firebase client, and onMessageReceived is not getting called for a certain set of devices (Android > 5.0). I am assuming the problem could be because of auto start added in these latest version, so I have implemented a BOOT receiver to rectify that as well. But, the method onMessageReceived is still not getting triggered when the app is killed. This is happening for Xiaomi Mi, ASUS.

I am looking for a solution add my app in auto-start by default.

**Comment by samtstern** [comment]
@app-ad for discussions of FCM in the background please consult #4 or #89, I believe the majority of the possibilities have already been discussed there.

**Comment by shihabmi7** [comment]
It's been trending topics about Firebase Cloud Messaging that Data Payload message is not fired onMessageReceived() method for some lower end device. And it's true. Here is the result.

App is killed scenario

Devices got payload:: 1. Nexus 5s : OS 7.1

Device not get payload:: 1. Xiomi MI 4c: OS 5.1 2. Huawei LUA -U22 :OS 5.1

Ensure that i'm not sending notification key from server / postman.

I am looking for the solution, i got data payload from firebase including all types of devices and Android OS & obviously From API level 15. My postman details are as follows.

 {
    "registration_ids": ["fC5uxGSRCsg:APA91bHh9fMXQ41LpX6tjjSsBKGrKTWYpzKimLDzvBGSHDPo2pq87JHqogUp2kqrmJi06siG_p6DfgRCim23iFzlBQAIrgtMDqRW4s39zUqv9CzyPqzxVl5PtnHPRDs4OagTuTePNyDI"],
    "data": {
        "title" : "my_custom_value",
        "message" : "tekksdasdasdsa",
         "isBackground" : "",
          "payload" : {


          },
           "timestamp" : "",
            "imageUrl" : "",
     }

}

**Comment by KORuL** [comment]
I have the same problem on Meizu m1 note android 5.1
When the application is minimized or active - the pushes come, and when the application is killed, the pushes do not come

**Comment by ezechinwa** [comment]
> I have the same problem on Meizu m1 note android 5.1.
> 
> When the application is backgroung or active - the data-only payload pushes come.
> But when the application is killed, the pushes do not come!
> On other phones everything is fine.

Please have you solved this issue?
