### ISSUE TITLE
Multiple Queries on Database Reference

### ISSUE THREAD

**Issue by troy21688** [firebase/quickstart-android#223]
I am using the FirebaseRecyclerAdapter and am trying to perform a query, I created a [StackOverflow question](http://stackoverflow.com/questions/42016194/cannot-limit-firebase-query-before-ordering-by-child-value-recyclerview), basically here is my code:

`mFireAdapter = new FirebaseRecyclerAdapter<Poll, PollHolder>(
    Poll.class, R.layout.latest_item, PollHolder.class, 
    mBaseRef.child("Polls").limitToLast(3).orderByChild("vote_count"))`

Essentially, I was told that multiple queries of this sort are not possible. Before I consider restructuring and alternative options, are there plans to allow for multiple queries? I thought I read that there would be a release in 2016, just want to make sure I know if there are plans to add as it appears to be heavily requested.

**Comment by samtstern** [comment]
Looks like @puf already answered this on StackOverflow, so closing this issue.

**Comment by troy21688** [comment]
He helped and pointed me to some of my options, however I was curious if there were plans to add this type of feature (multiple queries on one database reference). I read in a thread that it was hopefully being released in 2016 or possibly early 2017, but was hoping to gather more information before I restructured my database.

**Comment by samtstern** [comment]
Sorry I can't comment on upcoming features or timelines, but we are definitely always looking at ways to give more query powers!

**Comment by troy21688** [comment]
Much appreciated Sam! I look forward to hearing more.
