### ISSUE TITLE
Google Play services out of date.  Requires 10084000 but found 9877470

### ISSUE THREAD

**Issue by wangbourne** [firebase/quickstart-android#224]
Following configuration is used in my project, which is recommended by demo:
compile `'com.google.firebase:firebase-auth:10.0.1'`
classpath `'com.google.gms:google-services:3.0.0'`

Then I got an error of `Google Play services out of date.  Requires 10084000 but found 9877470` when executing `createUserWithEmailAndPassword`.

So I changed  `com.google.firebase:firebase-auth:10.0.1` to `com.google.firebase:firebase-auth:9.0.1` and it works but also comes a warning of  

"Failed to load 
    module descriptor class: Didn't find class 
    "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" 
on path: DexPathList"

**Comment by samtstern** [comment]
@wangbourne the 'out of date' error message just means that the version of Google Play Services on your device is not up to date.  If you're using a real phone this should resolve itself automatically.  If you're using an emulator you need to update the image and re-create the emulator.  Try an emulator on Android Marshmallow as those are guaranteed to have the right versions.
