### ISSUE TITLE
How to change Firebase Dynamic Links Domain?

### ISSUE THREAD

**Issue by vipulasri** [firebase/quickstart-android#225]
How to change Firebase Dynamic Links Domain?

**Comment by ianbarber** [comment]
You can't right now, sorry! Its something we're considering though - please feel free to add your voice by filing a feature request: https://firebase.google.com/support/contact/bugs-features/

**Comment by deesk** [comment]
still not available....

**Comment by 3netra** [comment]
You can now specify up to five custom page.link subdomains for your Dynamic Links. Short links using these new custom subdomains look like the following example: https://example.page.link/abcXYZ

Firebase Dynamic Link domains assigned on projects couldn't be deleted at this time.( firebase team is working on it.)

You can now whitelist the URL patterns that can be used as a Dynamic Link's deep link (link) or fallback link (ifl, ipfl, afl, ofl). If you define a whitelist, Dynamic Links won't redirect to URLs that don't match a whitelisted pattern.

You can try both of these features in the Firebase console.

**Comment by thomasbabuj** [comment]
Hi @3netra, 
Do you know the reason for creating subdomains for "page.link" instead of "mydomain.com"?  After creating the custom subdomain, now "link previews" are working when sharing. Do you have any solutions for that?

**Comment by P-Zenker** [comment]
> You can now specify up to five custom page.link subdomains for your Dynamic Links

Why only five? I have a android app with different product flavors for different customers (each got his own corporate identity and most of the code is the same). With only five domains I have to rebuild my app if I want to use dynamic links for each of them

**Comment by CristiTr** [comment]
BTW if you share links from "page.link" inside some apps like Instagram(direct message) or Kik Messenger they are not seen as a link and are not clickable, this is because of '.link' tld.

**Comment by steprescott** [comment]
You can now delete domains using the firebase console. Navigate to the domain you wish to delete and then hit the three vertical dots near the new dynamic link button and select the delete domain option.

**Comment by pschneider** [comment]
> BTW if you share links from "page.link" inside some apps like Instagram(direct message) or Kik Messenger they are not seen as a link and are not clickable, this is because of '.link' tld.

Also it looks like they're being blocked by social media because some are using them for spam etc. 

Supporting full custom domains is the only solution, otherwise that feature is not really worth it I guess.

**Comment by ParveenBhadooOfficial** [comment]
Any Updates?

**Comment by MarinPostma** [comment]
# validated
