### ISSUE TITLE
Feature Request: Firebase Crash reporting: add custom comments on "Close Issue" from Firebase Console

### ISSUE THREAD

**Issue by sscdvp** [firebase/quickstart-android#226]
* Android device: HTC One S_____
  * Android OS version: 6.0_____
  * Google Play Services version: 10.0.1_____
  * Firebase/Play Services SDK version: 10.0.1_____
  
Firebase Crash reporting customer could benefit if on issue closure/re-openning it would be possible to add/edit comment (in order to indicate issue closure reason, how it was solved etc).

Thank you.

**Comment by samtstern** [comment]
@sscdvp thanks for the input!  Agreed that this seems useful, but a Github issue is not the right place for a Firebase feature request.  Could you fill out this form with the details of your request? https://firebase.google.com/support/contact/bugs-features/

**Comment by sscdvp** [comment]
OK, Feature request 3-4111000015952 was opened.

**Comment by samtstern** [comment]
@sscdvp  :+1: thanks for replying with the feature request number!
