### ISSUE TITLE
app invites of gmail send to marketing and not to social

### ISSUE THREAD

**Issue by sivi29y** [firebase/quickstart-android#227]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by BrahmiImen** [comment]
2017-02-14 10:27 GMT+01:00 Sivan Langer <notifications@github.com>:

**Comment by samtstern** [comment]
@sivi29y sounds like your issue is that emails sent from App Invites are going to the wrong folder when you receive them in GMail.  Since this cannot be fixed by the maintainers of this quickstart, could you please file a bug report here:
https://firebase.google.com/support/contact/bugs-features/

That will get routed to the proper folks.  Thank you for your feedback!
