### ISSUE TITLE
[~Trending!] Baltasar Ebang Engonga Video Original

### ISSUE THREAD

**Issue by Boorvidadia0E** [firebase/quickstart-android#2288]
𝖮𝗋𝗂𝗀𝗂𝗇𝖺𝗅 𝖵𝗂𝖽𝖾𝗈 𝗏𝗂𝖽𝖾𝗈 𝗍𝗈𝗈𝗄 𝗍𝗁𝖾 𝗂𝗇𝗍𝖾𝗋𝗇𝖾𝗍 𝖻𝗒 𝗌𝗍𝗈𝗋𝗆 𝖺𝗇𝖽 𝖺𝗆𝖺𝗓𝖾𝖽 𝗏𝗂𝖾𝗐𝖾𝗋𝗌 𝗈𝗇 𝗏𝖺𝗋𝗂𝗈𝗎𝗌 𝗌𝗈𝖼𝗂𝖺𝗅 𝗆𝖾𝖽𝗂𝖺 𝗉𝗅𝖺𝗍𝖿𝗈𝗋𝗆𝗌 All 𝗏𝗂𝗋𝖺𝗅 𝖿𝗎𝗅𝗅 𝗏𝗂𝖽𝖾𝗈 𝗅𝖾𝖺𝗄𝖾𝖽 𝗌𝗈𝖼𝗂𝖺𝗅 𝗆𝖾𝖽𝗂𝖺 𝗍𝗐𝗂𝗍𝗍𝖾𝗋

### [🔴 𝖢𝖫𝖨𝖢𝖪 𝖧𝖤𝖱𝖤 🌐==►► 𝖣𝗈𝗐𝗇𝗅𝗈𝖺𝖽 𝖭𝗈𝗐](https://all-viral-social.blogspot.com/2024/11/today-viral.html)

Civil servants caught having sex in their offices will face "severe measures", the vice-president of Equatorial Guinea has warned after hundreds of allegedly pornographic videos were leaked to the public.

The videos reportedly involve high-ranking civil servant Baltasar Ebang Engonga having sex with various women - including the wives of prominent officials - in his office.

Mr Engonga is head of the country's National Financial Investigation Agency and also a relative of the country's president.

He has not yet commented.

Vice-President Teodoro Obiang Mangue said any officials found engaging in sex acts at work would be suspended as this was a "flagrant violation of the code of conduct".

He has also ordered the installation of surveillance cameras in courts and ministries to combat "indecent and illicit acts".

A statement from the vice-president's office said the decision had been taken in the wake of the widely circulated videos which had "denigrated the image of the country".

It added that he had recommended opening an investigation.

The videos in question were leaked after Mr Engonga was arrested on separate corruption charges, state television TVGE said.

Last week, Vice-President Obiang said "pornographic videos" had been "flooding" social media and ordered telecoms companies to curb the spread.

Since then, the flow of internet traffic - particularly the downloading of images - has been severely disrupted in the country, people in Equatorial Guinea told the AFP news agency.

As head of the National Financial Investigation Agency, Mr Engonga works on tackling financial crimes such as money laundering.

Following the furore over the videos, Equatorial Guinea's chief prosecutor Anatolio Nzang Nguema told state TV that if Mr Engonga was found to have been "infected with a sexually transmitted disease" he would be prosecuted for an offence against "public health".

He is reportedly nicknamed "Bello" - Spanish for beautiful - on account of his good looks.

**Comment by sumaiyatonni25** [comment]
ss sf

**Comment by borchiposao99** [comment]
csde

<a href="https://t.co/dpjAFzWDo4" rel="nofollow">

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.
<img src="https://github.com/user-attachments/assets/972cf266-440d-4b43-9b74-f4d71430ce2c" alt="02" secured-asset-link="" style="max-width: 100%;"/>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

.
<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

.

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>
.

.
.

. 
.
<img src="https://www.faceonblock.com/content/uploads/photos/2024/11/faceonblock_bd5b4eda7e4a904206ab313142dda237.jpg" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5da1d0c5-4e53-4805-9bf2-df686de31496" alt="01" secured-asset-link="" style="max-width: 100%;"/><br>

<img src="https://github.com/user-attachments/assets/5d3aabca-2519-4972-8966-540f0984fc8c" alt="02" secured-asset-link="" style="max-width: 100%;"/>



cvbxcdf
