### ISSUE TITLE
Firebase error: symbolFileMappings:upsert: The uploaded file is not a valid Breakpad Symbol file

### ISSUE THREAD

**Issue by PN1019** [firebase/quickstart-android#229]
I am trying to upload a dSYM file to Firebase using this command:

> ./Pods/FirebaseCrash/batch-upload -i ./Info.plist -p ./GoogleService-Info.plist ./service-accounts/mtb.json 78*****C-5**4-3***-***C-00*********7

But each time I run this, I get back the following errors

> ./Pods/FirebaseCrash/upload-sym-util.bash:377: error: symbolFileMappings:upsert: The uploaded file is not a valid Breakpad Symbol file.
> ./Pods/FirebaseCrash/upload-sym-util.bash:378: note: symbolFileMappings:upsert: The metadata for the symbol file failed to update.

I find below solution from one of google group but haven't had any luck as it errors out to this:

>   usage: batch-upload [-hv] [-p google-service] [-i info] service-account-file {mach-o file|uuid}

 Solution from  one of google-groups:
The best way is to perform the process manually:

- mdfind "com_apple_xcode_dsym_uuids = '$UUID'"

- The above command should return one or more paths. Pick one. Set the variable PATH to it.

- mdls "$PATH" -name com_apple_xcode_dsym_paths -name com_apple_xcode_dsym_uuids

- The above command will return two lists. Find the UUID in the second list and note its position. Find the corresponding relative path in the first list (they may be the same, but there's no guarantee about that). Set DSYM_PATH to it.

- batch-upload "$PATH/$DSYM_PATH"
How to sort this??Please help  badly stuck.........

**Comment by samtstern** [comment]
@PN1019 I am pretty sure this is an iOS issue, do you mind re-filing it on the [quickstart-ios](/firebase/quickstart-ios) repo?
