### ISSUE TITLE
FCM Messaging onTokenRefresh() is not called. 

### ISSUE THREAD

**Issue by SagarGang** [firebase/quickstart-android#23]
it gives the token but it doesn't go to onTokenRefresh() which i need to trigger my sendRegistrationToServer().

**Comment by kroikie** [comment]
onTokenRefresh in FirebaseInstanceIdService is only called when a new token is generated. If your app was previously installed and generated a token then onTokenRefresh would not be called. Try uninstalling and reinstalling the app to force the generation of a new token, this would cause onTokenRefresh to be called.

Also be sure that your FirebaseInstanceIdService is properly defined in your AndroidManifest.xml

**Comment by SagarGang** [comment]
thanks for your reply.It work.

**Comment by sohel2178** [comment]
Thanks Kroikie Bro, Its Work

**Comment by zigic88** [comment]
Sorry, for my bad english.
My token doesn't go to onTokenRefresh() 
I'm already add that service into manifest and also unistalling that application.
But onTokenRefresh() never trigger.
How to solve this ? Please help me.

**Comment by seunggabi** [comment]
@kroikie Thanks for your reply

**Comment by comm1x** [comment]
The bug still exists. It's very strange I need to ask my users to reinstall app.

**Comment by thewijaysharma** [comment]
Its really strange that this topic is closed but in my app onTokenRefresh() is not getting called even after the reinstallation

**Comment by kroikie** [comment]
@comm1x the recommendation of uninstall and reinstall is only for development, this is not a solution for an app that is already in the hands of users. You are able to call `FirebaseInstanceId.getInstance().getToken();` at any time to get the current token.

@thewijaysharma please ensure that your `FirebaseInstanceIdService` is correctly defined in your [manifest](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/AndroidManifest.xml#L45).

**Comment by sakshamsd** [comment]
what if users have already installed the app and in a new update we need to implement FCM??

**Comment by kroikie** [comment]
@sakshamsd in that case you would get the same callbacks as if the app had been initially installed.

**Comment by sakshamsd** [comment]
I tried implementing FCM on app updates but I can't get any token. What
should be done??

**Comment by mob-rockstar** [comment]
I have uninstalled app and installed again, but onTokenRefresh is never called.
I am using Firebase 11.4.2 in Android studio 3.1.4.
`classpath 'com.google.gms:google-services:3.3.0'`

**Comment by kroikie** [comment]
@sakshamsd and @mob-rockstar could you try using the latest SDK `17.3.0` and also be sure that you are extending the FirebaseMessagingService and overriding [`onNewToken`](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java#L94).

**Comment by ksurya28995** [comment]
Can someone give us a solution for this? onNewToken is called or initialized. Thus not getting the token to test the notification service in Firebase console.

Using:
<service android:name="com.example.ray.fcm.service">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
</service>

**in class:**
@Override
    public void onNewToken(String s) {
        super.onNewToken(s);
        Log.e("newToken", "newToken: " + s);
        sendRegistrationToServer(s);
        SharedPreferences pref = getApplicationContext().getSharedPreferences(FCMNotificationVariables.SHARED_PREF, MODE_PRIVATE);
        pref.edit().putString("regId", s).apply();
    }

Log e -> "new token" is not found in the logcat console, thus seems like onNewToken() is not even called/intialized :(

**Comment by kroikie** [comment]
@ksurya28995 `onNewToken` is only called when a new token is created. Try uninstalling the app and reinstalling, this will force the generation of a new token and you should see the token in the log.

**Comment by lgtout** [comment]
@ksurya28995 I've had the same problem.  What I've seen is that, after the app is installed, Google may issue a new token and NOT execute `FirebaseMessagingService#onNewToken`.  That leaves the app (and your notification-sending backend if you have one) with the old token, which will fail when sending notifications.  To remedy this, whenever a new screen is displayed, I request a token using `FirebaseInstanceId.getInstance().getToken()`.  If the token has changed, I update my notification-sending backend.

**Comment by leocarona** [comment]
Having same issue here.
Service is registered on the AndroidManifest (as it should be), but onNewToken doesn't get called. I'll have to work around same way as @lgtout did.

**Comment by sreejithvijayan** [comment]
After two days of troubleshooting, finally i found out that the latest versions of the below nuget packages (or may be one of them) is causing this. I downgraded to the below versions and it started working.

  ```
  Xamarin.Azure.NotificationHubs.Android -> v0.6.0
    Xamarin.Firebase.Messaging -> v71.1740.0
    Xamarin.GooglePlayServices.Base -> v71.1610.0
```
