### ISSUE TITLE
Firebase SDK Not openning launcher activity when app is background

### ISSUE THREAD

**Issue by Hardik-mehta** [firebase/quickstart-android#230]
Below is the link of my issue.
http://stackoverflow.com/questions/42342313/firebase-sdk-not-openning-launcher-activity-when-app-is-background

steps that i followed (it works in my case)
kill the app and send push it is redirecting to desired activity after processing this push put app in background and send push. it will resume last activity with intent extras as null.

  * Android device:  moto e 2nd gen
  * Android OS version: Lolipop (5.0)
  * Google Play Services version: 9.8.0
  * Firebase/Play Services SDK version: 9.8.0
  
after processing push notifications 3 or 4 times (I can't say exactly 3 or 4 times but approx 3 times or some times even on first push). I put app in background mode and send the push to device from postman. as per documentation it displays notification in system tray.but when I tap on that notification it does not launch launcher activity.i declared SplashScreen as launcher activity in manifest file. it resumes last activity before the app goes in background

**Comment by elvalelucho** [comment]
To this issue you must add a additional data like:

{
   "data": {
       "type" : "mytype",
       "title": "My Title",
       "body": "My Notification Message",
       "image":"image URI",
       ...
    },
    "to": "/topics/all"
}

Them you can read that on atcivity resume

**Comment by samtstern** [comment]
Closing this issue since it's been a long time since the last response.  Thank you @elvalelucho for chiming in, I hope that helped you @Hardik-mehta .
