### ISSUE TITLE
Google Sign-In (Authentication) will not work

### ISSUE THREAD

**Issue by therealccarter** [firebase/quickstart-android#231]
* Android device: Samsung-SM-G530A
  * Android OS version: 5.1.1
  * Google Play Services version: 10.2.0
  * Firebase/Play Services SDK version: 10.2.0

Step 3: Describe the problem:

Cannot sign in with Google authentication. Nothing modified, simply downloaded the .zip and imported it into Android Studio. Set it up as a new project in Firebase Console, added SHA1 fingerprint, enabled Google Sign-In under authentication tab. 

#### Steps to reproduce:

I changed nothing from the original quickstart

#### Observed Results:

I click the Sign-In button, the user selector comes up, I select my Google profile, the dialog disappears, and nothing happens. I added a toast to the onActivityResult method's failure conditional, which runs. So it is making it into onActivityResult, but result.isSuccess() returns false. 
  
#### Expected Results:

I'm not sure what's supposed to happen after successful log-in, as I've never gotten that far. 
  
#### Relevant Code:

     // [START onactivityresult]
    @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == RC_SIGN_IN) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            if (result.isSuccess()) {
                // Google Sign In was successful, authenticate with Firebase
                GoogleSignInAccount account = result.getSignInAccount();
                firebaseAuthWithGoogle(account);
            } else {
                // Google Sign In failed, update UI appropriately
                // [START_EXCLUDE]
                updateUI(null);
                // [END_EXCLUDE]
                CharSequence toastText = "Failed in onActivityResult";
                int duration = Toast.LENGTH_SHORT;
                Toast toast = Toast.makeText(getApplicationContext(), toastText, duration);
                toast.show(); // this toast runs, so obviously the sign in was not a success. 
            }
        }
    }
    // [END onactivityresult]

Some extra context: I'm trying to user Firebase Google sign-in for my main app. So I downloaded this quickstart so I could easily see how to get Google auth up and running...but even the quickstart isn't working for me

**Comment by MintuReena** [comment]
enable google sign in from firebase

**Comment by MintuReena** [comment]
or enable  
Email/Password 
from Authentication  -> Sign-in Method  ->Email/Password  -> enable

**Comment by therealccarter** [comment]
That was the first thing I did...nothing happens.

**Comment by aswinks88** [comment]
did you add google-services.json file to your project
?

Aswin Kutuva Sudharsanam
Department of computer and Mathematical Science,
Auckland University of Technology,
Auckland,
+64223637094.

**Comment by therealccarter** [comment]
The problem looks like it was an issue with my SHA-1

**Comment by jogilsang** [comment]
Thank you feed back!

나의 SOL에서 보냄
2017. 2. 21. 오후 5:08에 MintuReena <notifications@github.com>님이 작성:or enable
Email/Password
from Authentication  -> Sign-in Method  ->Email/Password  -> enable

**Comment by satendrarocks** [comment]
W/GoogleActivity: Google sign in failed
                                     com.google.android.gms.common.api.ApiException: 10: 
                                         at com.google.android.gms.common.internal.zzb.zzz(Unknown Source)
                                         at com.google.android.gms.auth.api.signin.GoogleSignIn.getSignedInAccountFromIntent(Unknown Source)
                                         at com.igenesys.powerscape.GoogleSignInActivity.onActivityResult(GoogleSignInActivity.java:105)
                                         at android.app.Activity.dispatchActivityResult(Activity.java:7292)
                                         at android.app.ActivityThread.deliverResults(ActivityThread.java:4516)
                                         at android.app.ActivityThread.handleSendResult(ActivityThread.java:4563)
                                         at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1698)
                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                         at android.os.Looper.loop(Looper.java:154)
                                         at android.app.ActivityThread.main(ActivityThread.java:6776)
                                         at java.lang.reflect.Method.invoke(Native Method)
                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1496)
                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1386)

**Comment by soonsam123** [comment]
If someone has the same problem, I was getting `getSignedInAccountFromIntent(Unknown Source)` . I had an client ID in [google cloud](https://console.cloud.google.com/apis/credentials?project=leafsoon-201022&folder&organizationId) for my website, and then I forgot to create one for my android application. I realized that I needed to create one OAuth Client ID for my android app also.

**Comment by tobytraylor** [comment]
@soonsam123 Is this what's expected?  I'm encountering the same error except its not that the login has to be cancelled but just that it never will complete successfully.  But afterward the firestore credentials are good for the user that was attempting to log in.
![untitled](https://user-images.githubusercontent.com/8820598/47923184-b779d900-de86-11e8-9987-d5196b692618.png)

**Comment by tobytraylor** [comment]
Mine however isn't api exception 10 it's 8
```
PlatformException(sign_in_failed, com.google.android.gms.common.api.ApiException: 8: , null)
E/flutter ( 3674): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:551:7)
E/flutter ( 3674): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:279:18)
E/flutter ( 3674): <asynchronous suspension>
E/flutter ( 3674): #2      GoogleSignIn._callMethod (package:google_sign_in/google_sign_in.dart:217:58)
E/flutter ( 3674): <asynchronous suspension>
E/flutter ( 3674): #3      GoogleSignIn._addMethodCall (package:google_sign_in/google_sign_in.dart:256:20)
E/flutter ( 3674): #4      GoogleSignIn.signIn (package:google_sign_in/google_sign_in.dart:324:48)
E/flutter ( 3674): #5      Authentication.startGoogleSignIn (package:built_redux_sample/authentication.dart:40:57)
```

**Comment by tobytraylor** [comment]
When removing the sha-1 key and replacing it with a sha-256 in the firebase console I started getting the "ApiException: 10" error.  I'm guessing that is a step backward and that most people are able to solve their "ApiExeption: 10" error by adding the sha-1 key.

**Comment by soonsam123** [comment]
@tobytraylor Unfortunatelly, mine was a different problem. Did u solve your issue?

**Comment by akatski316** [comment]
Can anyone please elaborate the whole solving because i'm getting the same error and it sucks..pleaseeee

**Comment by sivansundar** [comment]
I faced the same error today and this is how I rectified it. 

First of all, head over to your console > Project Settings > General > Your apps > Add your SHA-1 key.
Now download and replace the google-services.json file in your app folder. 

Usually your problem is solved here but you have one more small thing to do. In your code, when you define your GoogleSignInOptions Object, make sure you pass the right client id to the requestIdToken(); function. 

`  GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.clientID))
                .requestEmail()
                .build();`

In the place `(getString(R.string.clientID)` paste your client id. You can find your client id in your google-services.json file. Make sure to copy the correct client id though. 

` "oauth_client": [
        {
           <BLAH BLAH BLAH>
                   Your oauth client details are here. 
            </BLAH BLAH BLAH>
          }
        },
        {
          "client_id": "<THIS IS THE ONE YOU GOT TO COPY>",
          "client_type": XXXXXXXXX
        }`


There. This should solve your problem.

**Comment by akjaanalam** [comment]
hello guys can anyone guide me on "com.google.android.gms.common.api.ApiException: 7:  " ? I am unable to sign in using google sign in firebase. But i can get the information from  GoogleSignInAccount but unable to sign in Credential.... Thank you
