### ISSUE TITLE
Document the Analytics Sample App

### ISSUE THREAD

**Issue by hiranya911** [firebase/quickstart-android#233]
It's not clear what this app is supposed to do, and what the user is supposed to see. Some explanation in the README would be very useful.

**Comment by samtstern** [comment]
@hiranya911 that's a good point.  Also with the recent release of [Firebase Analytics DebugView](https://firebase.google.com/docs/analytics/debugview) we can provide a real-time view of the events logged by this app.

I will update the README to reflect this.
