### ISSUE TITLE
LocalStorage background insert from Firebase Messaging service?

### ISSUE THREAD

**Issue by Vinothapplife** [firebase/quickstart-android#240]
Once getting messages from onMessageReceived - I am trying to store data in localStorage using webView. 

Kindly help me on how to use webview in FirebaseMessagingService (non Activity class) in Android? 

Its not working background insert from Firebase Messaging service

**Comment by samtstern** [comment]
@Vinothapplife this does not sounds like an issue with this sample, please ask on StackOverflow I am sure someone can help you there!
