### ISSUE TITLE
Android Messaging Sample Does Not Work

### ISSUE THREAD

**Issue by lifeelement** [firebase/quickstart-android#241]
Using Android Studio 2.3, I loaded the firebase/quickstart-android/messaging sample as is and as suggested, but no notifications are being fried in the debug log. When using the Firebase Notification Console, whether I send messages from the to the "news" subscribers/topic or by sending directly to the emulator using the InstanceID token copied from the debug log, nothing happens.

No code has been added to the project. As mentioned, I'm using it as is. Below is my google-services.json and AndroidManifest.xml file. I have an app that will not be successful without notifications. If anyone has suggestions as to what else I can try, please let me know ASAP.

**google-services.json**
_With project ids removed._
```
{
  "project_info": {
    "project_number": "<removed>",
    "firebase_url": "https://<removed>.firebaseio.com",
    "project_id": "<removed>",
    "storage_bucket": "<removed>.appspot.com"
  },
  "client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:411948329052:android:5920de3503a2d18c",
        "android_client_info": {
          "package_name": "com.google.firebase.quickstart.fcm"
        }
      },
      "oauth_client": [
        {
          "client_id": "411948329052-hekvrcnphi2jn1evm4k8gi9bu3hnv2r5.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "<removed>"
        }
      ],
      "services": {
        "cloud_messaging_service": {
          "status": 2,
          "apns_config": []
        },
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ],
  "configuration_version": "1"
}
```

**AndroidManifest.xml**
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.google.firebase.quickstart.fcm">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:theme="@style/AppTheme">
        
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_ic_notification" />
        
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorAccent" />
        
        <activity
            android:name="com.google.firebase.quickstart.fcm.MainActivity"
            android:label="@string/app_name">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>

        
        <service
            android:name=".MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        
        
        <service
            android:name=".MyFirebaseInstanceIDService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        
    </application>

</manifest>

**Comment by sandman0** [comment]
I am experiencing the same problem.

**Comment by jaimeagudo** [comment]
Change your gradle plugin version & gradle wrapper distribution and give it a try

**Comment by kroikie** [comment]
@lifeelement Sorry you were having trouble with the messaging sample. Your issue if a bit general, so could you try the latest SDK and see if that helps.

**Comment by lifeelement** [comment]
Thanks we went another route.
