### ISSUE TITLE
Local module descriptor class for com.google.firebase.auth not found

### ISSUE THREAD

**Issue by Aki58** [firebase/quickstart-android#242]
I have made a register fragment and when i add account i get the following error

**Comment by samtstern** [comment]
@Aki58 in many cases this error can be ignored.  However without any more information on your side it's impossible to tell if there is a specific problem.

Please take a look at these similar issues:

  * https://github.com/firebase/quickstart-android/issues/208
  * https://github.com/firebase/quickstart-android/issues/110
