### ISSUE TITLE
not receiving notification of data messages on cellular data network, background.

### ISSUE THREAD

**Issue by armennazaretyan** [firebase/quickstart-android#246]
Hi
I have start with messaging example
It works good when mobile connected via WiFi
But after I switch to Mobile (Cellular) data internet, close app, close mobile and the FCM stop to work,
since other similar Apps ( facebook messanger, etc. ) continue to receiving data

What happens ? what should I do ?

**Comment by samtstern** [comment]
@armennazaretyan this is not enough information to help you debug.  FCM works fine on both cellular or WiFi networks.  I'd suggest looking at #4 or #89 and seeing if there's anything there to help you.
