### ISSUE TITLE
FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device

### ISSUE THREAD

**Issue by iForests** [firebase/quickstart-android#249]
* Google Play Services version: 10298438
  * Firebase/Play Services SDK version: 10.2.0

Our users encounter the following error when they signInAnonymously():

```
com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
```

with the following code:

```
Crashlytics.log(Log.DEBUG, "Google Play Service", "Google Play Service version: ${packageManager.getPackageInfo(GoogleApiAvailability.GOOGLE_PLAY_SERVICES_PACKAGE, 0 ).versionCode}")

FirebaseAuth.getInstance().signInAnonymously()
        .addOnCompleteListener {
            if (it.isSuccessful) {
                // ...
            } else {
                Crashlytics.log("signInAnonymously notSuccessful: ${it.exception}")
            }
        }
```

And the log is:

```
D/Google Play Service Google Play Service version: 10298438
D/CrashlyticsCore signInAnonymously notSuccessful: com.google.firebase.FirebaseApiNotAvailableException: API: InternalFirebaseAuth.FIREBASE_AUTH_API is not available on this device.
```

Is there any way I can do to resolve this issue? Thanks.

**Comment by litus92** [comment]
same problem here... Did you get a solution?

**Comment by Max01010101010101** [comment]
sameeeee

**Comment by diha-o** [comment]
yep, same problem

**Comment by thran** [comment]
Same here

**Comment by lmckenzie** [comment]
Same

**Comment by itelab** [comment]
Same problem on Xiaomi MI 5 and SDK version 10.2.6, Google Play Services Version 10.2.98 (448-146496160)

**Comment by lmckenzie** [comment]
For me this was related to using an emulator/device without play services. I was not aware that Firebase Auth required play services.

**Comment by Leslio7** [comment]
Hi, I had the same problem.
Solved it by clearing the Google Play Services data.

**Comment by samtstern** [comment]
Hi all.  It's been a long time since this issue was updated, and we've stopped receiving reports of this in the wild. If you're seeing this issue, make sure you're on a device with an up to date version of Google Play services installed from a legitimate source.
