### ISSUE TITLE
D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED

### ISSUE THREAD

**Issue by tisalph** [firebase/quickstart-android#25]
Hi,

I am trying Firebase Cloud messaging. I cloned this project and created google.service.json as per instruction (https://firebase.google.com/docs/android/setup#prerequisites) and put that file under quickstart-android\messaging\app folder. But I keep getting 

D/FirebaseInstanceId: background sync failed: AUTHENTICATION_FAILED

Also, when i click on Log Token button in the emulator, i getnull token.

Can someone please help me?

**Comment by samtstern** [comment]
@tisalph what kind of device are you using, and what version of Google Play Services does it have?

**Comment by tisalph** [comment]
The issue is resolved. I was trying this example from our company netowrk and because of firewall, emulator could not connect to FCM server. When I tried from home, it worked fine. Thanks for taking a look at it.
