### ISSUE TITLE
firebase user control

### ISSUE THREAD

**Issue by fxo140130** [firebase/quickstart-android#250]
Is there any way to deny some part of an App to a specific user using Firebase?

The flow is as follow : 

- User X is authenticated and fill some field in the app and have his/her state on pending. 

- Firebase admin  receive the data input from the end user, validate it and release the account so He/she can have access to the remaining part of the App. 

I have been working on this the whole day.  Hope someone help.

**Comment by samtstern** [comment]
@fxo140130 please post these types of "How To" questions on StackOverflow, that's the best place to get this answer.
