### ISSUE TITLE
Icon and sound for data messages?

### ISSUE THREAD

**Issue by ickata** [firebase/quickstart-android#253]
Hi,

Probably this is the Nth question on this topic, but I just cannot get this. According to the [documentation](https://firebase.google.com/docs/cloud-messaging/android/receive), push notification messages do not invoke `onMessageReceived` callback when app is running in background. Data messages do it. Okay. Then:

   - How do I set tray icon for the message in the notification tray? Right now I get a white blank square. I tried adding `data-meta` tags in `AndroidManifest.xml` as [shown here](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/AndroidManifest.xml#L13) – no success.
   - How do I set sound?
   - If I cannot set icon + sound for data messages, then why they are shown in notification tray? It is pointless to show just a blank white square.
   - If I cannot set icon + sound – can I disable appearance in notification tray, but still get `onMessageReceived` callback executed?

**Comment by opus1269** [comment]
For data messages, in the onMessageReceived you can create any kind of notification you want based on the message type. So you don't need to pass any notification info.

This is the example code from [ MyFirebaseMessagingService.java](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java#L106-L130):

```
	/**
	 * Create and show a simple notification containing the received FCM message.
	 *
	 * @param messageBody FCM message body received.
	 */
	private void sendNotification(String messageBody) {
		Intent intent = new Intent(this, MainActivity.class);
		intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
		PendingIntent pendingIntent = PendingIntent.getActivity(this, 0 /* Request code */, intent,
				PendingIntent.FLAG_ONE_SHOT);

		Uri defaultSoundUri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_NOTIFICATION);
		NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
				.setSmallIcon(R.drawable.ic_stat_ic_notification)
				.setContentTitle("FCM Message")
				.setContentText(messageBody)
				.setAutoCancel(true)
				.setSound(defaultSoundUri)
				.setContentIntent(pendingIntent);

		NotificationManager notificationManager =
				(NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

		notificationManager.notify(0 /* ID of notification */, notificationBuilder.build());
	}

```

Here is one of my apps that does it this way:

[Pushy Clipboard](https://github.com/Pushy-Clipboard/pushy-android)

**Comment by ickata** [comment]
Thank you for the reply, @opus1269 , but another portion of questions raises:

1. Will this work if the application is killed? If I understand correctly, I have to call `sendNotification` from `onMessageReceived`, but the latter won't get called when app is killed. And the notification will be already in tray. Or I miss something?

2. I just cannot get it – is this the only way to customize the notification? I mean, why the icon defined in AndroidManifest.xml is not used?

3. Is there a way to disable data messages appearing in tray? But in the same time still invoke `onMessageReceived`?

**Comment by opus1269** [comment]
1. If the user "swipes away" the app, `onMessageReceived` will still be called, the notification you create will show up, and if they click on it it will launch whatever is in the intent. If they do a "force stop" that might cause a problem but the user is told all bets are off when they do that. I don't know all the ins and outs of other ways apps might get "killed" in Android, but I haven't had problems with messages not getting delivered. I have seen delivery delays sometimes, even with High Priority messages, on some devices. Not sure why that is, it seems like others have the same problem.

2. I don't know about that, I've never used any of the built in notification stuff in fcm, just data messages. Maybe one of the firebase people can explain it.

3. If you pass a data only message with no notification stuff in the manifest, a notification will not show up unless you create one. `onMessageReceived` will be called.

All my experience is based on sending data messages from a backend server or upstream messages from an app. I've never used the notifications console, for instance, so I don't know how that works.

**Comment by ickata** [comment]
1. Hm, on my end, `onMessageReceived` is called when I open the "swiped out" app again. This may happen 1 minute after I get the tray message. I don't think that I will be able to control the icon and sound of the tray message from `onMessageReceived` , since it is called after I tap on the tray message.

2. I am asking about data messages. I do not provide `notification` payload. Just data.

3. Nope – I always get the tray message with the annoying white blank square.

Anyway, thanks @opus1269 . I was hoping to get some info from firebase team people...

**Comment by l1br3** [comment]
@ickata I'm so surprised this is so hard to find information about that. I'm struggle with the same issue. I do prefer `data` payload as it shows our beautiful logo in the notif tray but there is this white square/circle (in fact I believe its the logo). I'm able to set the color of this one but not the image. 
Did you get any chance with that ?

**Comment by l1br3** [comment]
It took me few minutes more to find it ! (I was looking for this for more than 2 hours).
Use the `smallIcon` parameter ! The icon must be in mipmap instead of drawable.
https://github.com/zo0r/react-native-push-notification/issues/515
