### ISSUE TITLE
onTokenRefresh does not work on background

### ISSUE THREAD

**Issue by hvar90** [firebase/quickstart-android#256]
### Step 2: Describe your environment

  * Android device: Huawei
  * Android OS version: 4.4
  * Google Play Services version: 10.2.1
  * Firebase/Play Services SDK version: 10.2.1
  
### Step 3: Describe the problem:
i was experimenting to know if onTokenRefresh is called on background and i realized that onTokenRefresh is callled only when i open my app, but is necessary to call onTokenRefresh when the app is on background too
#### Steps to reproduce:

  1. i call FirebaseInstanceId.getInstance().deleteInstanceId();
  2. i close my app 
  3. i wait for a while and onTokenRefresh is called never
  4. i open my app 
  5. onTokenRefresh is called finally

but that is the problem, i want that onTokenRefresh be called when my app is closed too

**Comment by morton2565** [comment]
Hacker has control of my Google account through Google development App and
Google security suite , etc ! Controls my devices , PC etc ! I need help !
Call me 5733600083. And not sure if you will even get this email

**Comment by kroikie** [comment]
@hvar90 Thanks for that feedback. Currently onTokenRefresh is called when a new token is generated. Calling deleteInstanceId() does not automatically trigger the generation of a new token. Try calling getToken after deleting the current token, in that case a new token will be generated and you should see the onTokenRefresh callback whether the app is in the foreground or background.

**Comment by hvar90** [comment]
but, that is not the problem, yes, Calling deleteInstanceId() and calling
getToken after deleting the current token the new token will be generated
but, what happen when  a new token is generated but the app have not been
open during long time ? the new token is generated when i open the app
only, but that is a mistake, because not all the people open the app
frecuently so some messages will be missed

2017-06-30 16:44 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
If a new token is generated when your app is in the background then the onTokenRefresh will be called. You can then use the new token to ensure that your user does not miss messages.

**Comment by hvar90** [comment]
i tested it many times and when a new token is generated when my app is in
the background  the onTokenRefresh is called never. only when i open the
app onTokenRefresh is called or maybe is only on my cellphone huawei but
for me that does not work

2017-07-01 13:03 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
Are you sure that a new token is being generated while your app is in the background? It could be that the new token is only being generated when your app is opened and thats why onTokenRefresh is then being called.

**Comment by hvar90** [comment]
but, i mean, when a token is created  it works for a while, after a couple
of weeks or months when the user does not open the app the token expires
and  onTokenRefresh is called never, only when the user open the app
onTokenRefresh is called

2017-07-03 23:19 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
If the token expires while the app is in the background onTokenRefresh should be called. If you are seeing tokens expiring and onTokenRefresh not being called then that is a bug. Note though that deleting a token is not the same as a token expiring.

**Comment by hvar90** [comment]
i have a messaging app and many users when the token expires onTokenRefresh
not being called, with my cellphone occur the same problem when the token
expires

2017-07-04 9:17 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
The tokens should not be invalidated or expired unless the user uninstalls and reinstalls the app or Google invalidates the token for security reasons. A user not using an app for some time should not invalidate the token so there should be no expectation that onTokenRefresh would be called.

Sorry if I am missing your point but could you explain how you know they tokens are expired?

**Comment by hvar90** [comment]
for two things:
because when the tokens are expired we do not receive notifications, only
when we open the app, we can receive notifications
also with my https://pypi.python.org/pypi/gcm-client/ i see many errors
with this message: GCMNotRegisteredException: Registration id is not valid
anymore



2017-07-04 13:48 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
Thanks, one more clarification: to reproduce, you mentioned that deleting the token. Are you deleting the token?

**Comment by hvar90** [comment]
i dont understand your question, deleting the token on what on moment ??

2017-07-04 14:12 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
In step 1 of your original post you said:

> i call FirebaseInstanceId.getInstance().deleteInstanceId();

I was wondering if you are doing that in your app and if so when are you using `deleteInstanceId()`?

**Comment by hvar90** [comment]
i tested again and when i use

FirebaseInstanceId.getInstance().deleteInstanceId();
FirebaseInstanceId.getInstance().getToken();

onTokenRefresh is called, so, the problem is only when the token have
expired, onTokenRefresh is called only when the person open the app, also
ir weird that the token expire after the person does not use the app for a
while

2017-07-04 14:24 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
If you are using `deleteInstanceId` then the token will be invalidated and onTokenRefresh would only be called when you call `getToken`. Are you using `deleteInstanceId()` in your app?

**Comment by hvar90** [comment]
yes but i use deleteInstanceId only to reproduce the problem, in my app i
dont use deleteInstanceId never

2017-07-04 15:06 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
When you get the GCMNotRegisteredException from the library you are using, is there a canonical ID that is returned?

**Comment by hvar90** [comment]
With canonical ID do you mean the firebase token?
Nothing is returned but i could print what ID has expired

2017-07-05 13:39 GMT-05:00 Arthur Thompson <notifications@github.com>:

**Comment by kroikie** [comment]
If a device has multiple tokens then only the last one should be used. All others may result in Not Registered error and that error should contain a canonical ID (the last token) indicating that that is the one that should be used.

However I think you are indeed experiencing an issue that we should investigate further. Could you file a [ticket](https://firebase.google.com/support/contact/troubleshooting/) and include my name Arthur Thompson so that I can continue assisting you with more details about your issue.

I'll close this issue here, looking fwd to your ticket.
