### ISSUE TITLE
The Firebase Storage app demo throws Exception on M device due to absence of requests to Runtime permissions for storage.

### ISSUE THREAD

**Issue by rakeshgopathi** [firebase/quickstart-android#259]
###On

  * Android device:  Xiamoi mi4
  * Android OS version:  24
  * Firebase/Play Services SDK version: 10.0.1
  
While uploading an image using the storage API demo App there is a failure to upload Image due to an Exception  **StorageException: An unknown error occurred, please check the HTTP result code and inner exception for server response**. I figured out the problem to be storage permission being not granted. There is acutually no Runtime permission request in the sample.

**Comment by samtstern** [comment]
It's been a long time since the last update here so I am going to close this issue.  Thank you for reporting it and feel free to re-open if it you'd like to discuss further.
