### ISSUE TITLE
not send notification when app is background (app exit & remove from recent apps)

### ISSUE THREAD

**Issue by farzadnone** [firebase/quickstart-android#260]
Hi, i use:
```
buildToolsVersion "25.0.0"
minSdkVersion 17
targetSdkVersion 25
compileSdkVersion 25
compile 'com.google.android.gms:play-services-auth:10.2.1'
compile 'com.google.firebase:firebase-messaging:10.2.1'
```

when app is oprn and launched notification recieved and good working. but when app is killed and remove from recent apps not recieve notification :|

i use firebase console from web and send notificaion with custom data for intent.

what is problems? thanks

**Comment by MikeSoft** [comment]
Sometimes the push notification arrive, but the way you send isn't the correct and the app recognize the package like data , and not like a notification.  
read this: [Firebase http documentation](https://firebase.google.com/docs/cloud-messaging/http-server-

**Comment by kroikie** [comment]
@farzadnone what device are you using to test this?

Removing an app from the recents list should not kill it, but some devices incorrectly do that, we are working with manufactures to ensure that apps are not killed when removed from recents.

Note that once an app is killed is should not be able to receive notifications until the user explicitly restarts the app.

**Comment by samtstern** [comment]
Closing this issue as stale, it's been a long time since the last response.
