### ISSUE TITLE
Mistake in documentation

### ISSUE THREAD

**Issue by DarshanGowda0** [firebase/quickstart-android#262]
Hey,
I don't know if this is the right place to report this but yeah,
There is mistake in the documentation part of [this](https://firebase.google.com/docs/cloud-messaging/android/receive#edit-the-app-manifest).

It shows the website code than what's supposed to be put in the manifest by the app developer.
PFA to the same ![picture](http://204.152.203.111/shape/Screen%20Shot%202017-05-03%20at%205.55.39%20PM.png)

Thank you.

**Comment by samtstern** [comment]
@DarshanGowda0 thanks for the report!  This isn't really the right place (see 'Send Feedback' in the top right of your screenshot) but I appreciate it anyway.  Gonna close this github issue and get this fixed asap.

cc @kroikie

**Comment by samtstern** [comment]
@DarshanGowda confirming I found the issue and should have a fix in by the end of the day.
