### ISSUE TITLE
How can I sync my SQLite db with Firebase DB?

### ISSUE THREAD

**Issue by rmaelongakit** [firebase/quickstart-android#265]
I have a db in sqlite and I want to sync it to firebase when invoking a button. I already connected my android project to firebase. What would be the next steps? Thank u.

**Comment by samtstern** [comment]
@rmaelongakit there's no built-in way to do this, you will have to read each row from your database and write it to Firebase.  Remember Firebase is a NoSQL database so the data structure will be totally different.
