### ISSUE TITLE
Email verification on android

### ISSUE THREAD

**Issue by bingdow** [firebase/quickstart-android#266]
I've already verified email account on one device however after I changed to another device and signed in with same account my email verification status seems to be reset? so I need to verify again.

**Comment by samtstern** [comment]
@bingdow thanks for the bug report.  Just a few questions (please use the template!):

  1. What version of the Firebase SDK are you using?
  2. Is either device an emulator?
  3. Is this account associated with a Google account on the device?

**Comment by samtstern** [comment]
@bingdow I see you closed the issue.  Did you fix it?  If so could you share what the problem was?
