### ISSUE TITLE
How to check whether same data exist before adding data to firebase realtime database

### ISSUE THREAD

**Issue by ManuBabu** [firebase/quickstart-android#268]
Hi Firebase, 

I am working with realtime databse, creating objects of students(name,id,class,age) 
the problem is duplication of data. how can i check whether same data exist before i add new student object.. is there any method to check for existing data??? 
I am stuck here, please help ASAP...

Thanks
Manu

**Comment by samtstern** [comment]
Hi @ManuBabu. This does not seem to be an issue with the code in this repository nor it is an issue with the Firebase SDK.  Please post this question on StackOverflow which is a better venue for this type of question.
