### ISSUE TITLE
FirebaseIndexRecyclerAdapter onDataChanged is called but getItemCount() always return 0

### ISSUE THREAD

**Issue by Shirane85** [firebase/quickstart-android#273]
### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: 10.2.0
  
### Step 3: Describe the problem:
I'm using FirebaseIndexRecyclerAdapter and I'm overriding onDataChanged for hiding a progress bar and/or displaying an empty state depends on the itemsCount (Something which i've already done with FirebaseRecyclerAdapter and works as expected) but getItemCount always return 0(!)

I've investigate it and the reason is that FirebaseIndexRecyclerAdapter is using FirebaseIndexArray which is overriding getItemCount and return mDataSnapshots.size() but the data was not loaded yet - the onDataChanged was called because the keyRef loaded - and indeed i can see in debug that the keys are loaded (with the correct count) but unfortunately they are private so i can't use them to get the count.

I know i can override onChildChanged and then call getItemCount and get the correct count (which i've done) but still i can't know if there are no items and i need to display the empty state.

Is there something i'm missing?

Note - I know i can manage my own count (child) beside the data and just load it before setting the adapter but i'm saving this as a last resort.

#### Steps to reproduce:

  1. Set new FirebaseIndexRecyclerAdapter to a RecyclerView
  2. Override onChildChanged
  3. Call getItemCount inside
  
#### Observed Results:

  * It returns 0 always
  
#### Expected Results:

  * Should return the data/keys child count
  
#### Relevant Code:

Thanks

**Comment by samtstern** [comment]
Please close this issue and file a new one on the FirebaseUI-Android
repository.  That's where the index recycler adapter comes from.

**Comment by Shirane85** [comment]
Oops, will do, thanks...
