### ISSUE TITLE
firebase-core added automatically even if i only want to use firebase-messaging

### ISSUE THREAD

**Issue by llooz** [firebase/quickstart-android#274]
The gradle plugin automatically adds "firebase-core" even if i want to only use "firebase-messaging".
Is there to prevent the gradle plugin from adding "firebase-core"?
I can see that "firebase-messaging" doesn't have "firebase-core" as a dependency

**Comment by samtstern** [comment]
@llooz `firebase-core` just includes `firebase-analytics` right now.  If you have both analytics and FCM in your app you will get some nice automatic reporting about notification open rates, etc.

There's no way to tell the plugin not to bring in `firebase-core` but you can avoid using the plugin altogether by reading this guide:
https://developers.google.com/android/guides/google-services-plugin
