### ISSUE TITLE
How do I track the performance of dynamic links created with the REST API (programmatically) in the Firebase console?

### ISSUE THREAD

**Issue by deesk** [firebase/quickstart-android#276]
i'm using js ajax request to make a dynamic link for web to web..(not mobile) but it can't connect generated dynamic link with firebase dynamic link analitic. please help...

**Comment by samtstern** [comment]
@deesk this issue is not related to the code in this repository, please ask in another forum (maybe try the firebase-talk mailing list).

**Comment by deesk** [comment]
ok tnx...
