### ISSUE TITLE
play services 9.8.0 can't be compiled with firebase performance 10.2.6

### ISSUE THREAD

**Issue by mafdy92** [firebase/quickstart-android#277]
i am trying to implement firebase performance but i am having building issues
when i add those lines together in my app build gradle

`
 compile 'com.google.android.gms:play-services:9.8.0'
compile 'com.google.firebase:firebase-perf:10.2.6'

is this version of play services not compatible ? the problem is i can't update the play services version
is there any workaround ?
`

**Comment by samtstern** [comment]
You should almost never use `com.google.android.gms:play-services:9.8.0`!  That will make your app really big because it loads **every single Play services API**.

Try using more specific dependencies like:

```groovy
// Some play services examples
compile 'com.google.android.gms:play-services-auth:10.2.6'
compile 'com.google.android.gms:play-services-drive:10.2.6'


// Some firebase examples
compile 'com.google.firebase:firebase-analytics:10.2.6'
compile 'com.google.firebase:firebase-database:10.2.6'
```

**Comment by mafdy92** [comment]
upgraded my compile version sdk from 23 to 24
i was able to implement play services 10.2.6 and firebase performance using specific dependencies
issue solved
