### ISSUE TITLE
Cannot build firebase performance tool with experimental gradle plugin

### ISSUE THREAD

**Issue by williamchong007** [firebase/quickstart-android#278]
In my project level `build.gradle` i have
```
    dependencies {
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'com.android.tools.build:gradle-experimental:0.9.2'
        classpath 'com.google.firebase:firebase-plugins:1.1.0'
    }
```

In my app level `build.gradle` i have
```
apply plugin: "com.android.model.application"
apply plugin: 'com.google.firebase.firebase-perf'
```

However i receive the error 
```
Error:(2, 0) FirebasePerformancePlugin may only be applied to Android projects

```
When syncing gradle project

**Comment by samtstern** [comment]
@williamchong007 sorry we never got back to you here.  As you may have figured out, we can't support experimental, alpha, or canary plugins when using the performance plugin.  If you update to a stable version, everything should work.
