### ISSUE TITLE
      Compilation problem

### ISSUE THREAD

**Issue by rahulbusal** [firebase/quickstart-android#279]
can not compile - com.google.firebase:firebase-auth:11.0.0.

**Comment by samtstern** [comment]
@rahulbusal can you give some more detail on the issue?  This is not enough information to start debugging.

**Comment by rahulbusal** [comment]
Error:Failed to resolve: com.google.firebase:firebase-core:11.0.0

**Comment by rahulbusal** [comment]
Issue solved!
I haven't updated Google services.
