### ISSUE TITLE
Error converting bytecode to dex after integrating Firebase Performance Monitoring

### ISSUE THREAD

**Issue by rvijayraghavan** [firebase/quickstart-android#281]
- Followed https://firebase.google.com/docs/perf-mon/get-started-android
- Building after step 3 results in 
```
Error:Error converting bytecode to dex:
Cause: java.lang.RuntimeException: Exception parsing classes
```

Using Play Services version 10.2.6.

**Comment by samtstern** [comment]
@rvijayraghavan sorry we never got back to you here!  It's been a while so I am going to close this issue as stale.  I hope you figured something out in the meantime,

**Comment by GrinGraz** [comment]
Following the same steps this is still happening using Play Services version 11.8.0.
