### ISSUE TITLE
'com.google.firebase:firebase-invites:11.0.0' does not exist

### ISSUE THREAD

**Issue by marianobilli** [firebase/quickstart-android#282]
### Step 2: Describe your environment

  * Android device: N/A
  * Android OS version: N/A
  * Google Play Services version: 10.2.6
  * Firebase/Play Services SDK version: 11.0.0
  
#### Steps to reproduce:

  1. Clone the current version of quickstart-android/dynamiclinks/
  2. Compile it in Android Studio
  
#### Observed Results:
Error:(41, 13) Failed to resolve: com.google.firebase:firebase-invites:11.0.0
<a href="openFile:/Users/mariano/AndroidStudioProjects/quickstart-android/dynamiclinks/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>  
#### Expected Results:

  * What did you expect to happen?
Project should be compiled
  
#### Relevant Code:
N/A

**Comment by samtstern** [comment]
@marianobilli you need to update your SDK, specifically 'Google Repository' in the SDK tools tab.

**Comment by marianobilli** [comment]
Yes, you were right, my bad.
