### ISSUE TITLE
Not receiving sms using firebase android phone verification

### ISSUE THREAD

**Issue by abba-maker** [firebase/quickstart-android#283]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: HTC one A9
  * Android OS version: 7.0
  * Google Play Services version: 11.0.55 (448-156917137)
  * Firebase/Play Services SDK version: 11.0.0
  
### Step 3: Describe the problem:  

I have set up the firebase android phone verification following the guide [here](https://firebase.google.com/docs/auth/android/phone-auth). i double and triple check the steps. Everything seems fine, but after calling `PhoneAuthProvider.verifyPhoneNumber`, the `codeSent` callback gets fired but i never received any sms or code. Tried so many times with no luck. plus the `onVerificationFailed` callback is not called which makes me believe the problem is not from my end. BTW am testing from Nigeria and Nigeria is in the list of supported countries.

#### Steps to reproduce:

  1. get a valid phone number to verify
  2. pass it to `PhoneAuthProvider.verifyPhoneNumber` along with other arguments
  3. `codeSent` callback gets fired but no sms is sent to device
  
#### Observed Results:

  The code executes with no error, but the sms is never sent to the device even though the `codeSent` callback gets fired. Nothing to show from the logcat
  
#### Expected Results:

  I was expecting to receive and SMS with the verification code to complete the phone verification.
  
#### Relevant Code:

  ```java
//in a fragment
  @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.fragment_verify_phone, container, false);
        ButterKnife.bind(this, view);

        mAuth = FirebaseAuth.getInstance();
        mPhoneAuthProvider = PhoneAuthProvider.getInstance();
        return view;
    }
   
   public void onNextClick(){
     mPhoneToVerify = phoneUtil.format(numberProto, PhoneNumberUtil.PhoneNumberFormat.E164); //am using libphoneNumber from google. the number is OK
                Log.e(TAG, phoneUtil.format(numberProto, mPhoneToVerify);
                requestVerificationCode(mPhoneToVerify);
}
  private void requestVerificationCode(String number){
        mPhoneAuthProvider.verifyPhoneNumber(number, 60, TimeUnit.SECONDS, getActivity(), verificationStateChangedCallbacks);
        mProgressDialog = new ProgressDialog(getActivity());
        mProgressDialog.setMessage("Sending verification code...");
        mProgressDialog.show();
    }

     private PhoneAuthProvider.OnVerificationStateChangedCallbacks verificationStateChangedCallbacks = new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
        @Override
        public void onVerificationCompleted(PhoneAuthCredential phoneAuthCredential) {
            mAuthCredentials = phoneAuthCredential;
        }

        /* This one is never called: so i assume there's no problem on my part */
        @Override
        public void onVerificationFailed(FirebaseException e) {
            e.printStackTrace();
            Log.e(TAG, e.getMessage());
        }

        /* This one is called */
        @Override
        public void onCodeSent(String s, PhoneAuthProvider.ForceResendingToken forceResendingToken) {
            //super.onCodeSent(s, forceResendingToken);
            mProgressDialog.dismiss();
            phoneVerificationView.setVisibility(View.GONE);
            enterCodeView.setVisibility(View.VISIBLE);
            mVerificationId = s;
            mResendToken = forceResendingToken;
            Log.e(TAG, s);
        }

        /* This one is also called */
        @Override
        public void onCodeAutoRetrievalTimeOut(String s) {
            super.onCodeAutoRetrievalTimeOut(s);
            pleaseWait.setVisibility(View.VISIBLE);
        }
    };
  ```

**Comment by samtstern** [comment]
@abba-maker thanks for the report!  Do you have any access to a phone number not registered in Nigeria?  Maybe a friend in another country?  I want to see if this really is country-specific, as you suspect.

**Comment by abba-maker** [comment]
Sadly, I have non that I can reach now. Am not sure if this will help but
I've also used firebase-auth from firebase-ui Android bindings, still same
problem of not receiving SMS :(
Thanks in advance.

**Comment by moderateepheezy** [comment]
@abba-maker I was having the same issue of not getting SMS, until I change from this

```
@Override
            public void onCodeSent(String s, PhoneAuthProvider.ForceResendingToken forceResendingToken) {
               super.onCodeSent(s, forceResendingToken);
                progress.dismiss(); 
```

Changed to this

```
@Override
            public void onCodeSent(String s, PhoneAuthProvider.ForceResendingToken forceResendingToken) {
               // super.onCodeSent(s, forceResendingToken);
                progress.dismiss();
```

**Comment by abba-maker** [comment]
@moderateepheezy I did that change but no luck. The SMS seem to be delivered to other carriers even without the change, but all MTN NG I've tried so far are not receiving the SMS. The problem seem to be specific to that carrier and unfortunately MTN NG are the largest carrier in my target location :(
Please #firebase help resolve the issue

**Comment by abba-maker** [comment]
@moderateepheezy that's really weird, because all other carriers work just fine. Tried more than 4 different MTN NG numbers, non worked. But all other carriers works with same code

**Comment by abba-maker** [comment]
I just tried verifying one of the numbers through [firebase-ui auth demo](https://fir-ui-demo-84a6c.firebaseapp.com/) but still did not receive any SMS. However, when I tried same number on the demo [here on digits](https://get.digits.com/), I received an SMS with a code almost immediately.

**Comment by inger** [comment]
Hmm, similar issue here - except: I received a text when I started the auth on one phone but used a sms number of another one (manual typing mode), I did not receive anything when using the same number where the app was running.

**Comment by samtstern** [comment]
Hey all.  We've received a number of issues about people unable to get SMS sent to their device.  These tend to be related to the device carrier and we're working on fixing the issues.  Instead of tracking them here (since I can't really help) can you report such issues to [Firebase support](https://firebase.google.com/support/) where they'll get routed and tracked properly.  Thank you!

**Comment by jorgecasariego** [comment]
Hello everybody, in my case, I realised that this problem happens with all numbers that has ported from one provider to another. With phone numbers that has never ported Firebase Authentication works like a charm!

And also, the same happened with Digits. I had the same problem with ported numbers and my solution was give the user his verification code via a voice call but with unluckily Firebase it's not possible to do this.

**Comment by saryuvc** [comment]
let number = "+91"+ number;     
      this.platform.ready().then(()=>{
      (<any>window).FirebasePlugin.verifyPhoneNumber(number, 120, (credential) => {
        var verificationId = credential.verificationId;
        this.navCtrl.push(VerificationPage, { verificationId: verificationId, phoneNumber: this.emailPasswordForm.value["phoneNumber"]  }); //This is STEP 3 - passing verification ID to OTP Page
      }, (error) => {
        //this.eer = error;
        alert('Failed to send OTP. Try again');
        console.error(error);
      });

first set the sha1 to firebase setting and generate google config.json then add to poject's root directory and add to build.gradle dependency.
it'll work properly

**Comment by jermainec** [comment]
Hey guys, we are currently having what @jorgecasariego is facing too. Firebase Auth works well for numbers that haven't been ported but the ones who ported are usually the ones who cannot receive the SMS despite numerous retries.

**Comment by samtstern** [comment]
@jermainec if you're having trouble with SMS delivery please reach out to Firebase support:
https://firebase.google.com/support/

**Comment by Mohit1099** [comment]
after successfull vaerification completion i am getting error of invalid verification


my code is this:
package com.example.dpka.ess;

import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.TextView;
import android.widget.Toast;

import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.FirebaseException;
import com.google.firebase.FirebaseTooManyRequestsException;
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.auth.FirebaseAuthInvalidCredentialsException;
import com.google.firebase.auth.PhoneAuthCredential;
import com.google.firebase.auth.PhoneAuthProvider;


public class PhoneLogin extends AppCompatActivity {
    private static final String TAG = "PhoneLogin";
    private boolean mVerificationInProgress = false;
    private String mVerificationId;
    private PhoneAuthProvider.ForceResendingToken mResendToken;
    private PhoneAuthProvider.OnVerificationStateChangedCallbacks mCallbacks;
    private FirebaseAuth mAuth;
    TextView t1,t2;
    ImageView i1;
    EditText e1,e2;
    Button b1,b2;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_phone_login);

        e1 = (EditText) findViewById(R.id.Phonenoedittext);
        b1 = (Button) findViewById(R.id.PhoneVerify);
        t1 = (TextView)findViewById(R.id.textView2Phone);
        i1 = (ImageView)findViewById(R.id.imageView2Phone);
        e2 = (EditText) findViewById(R.id.OTPeditText);
        b2 = (Button)findViewById(R.id.OTPVERIFY);
        t2 = (TextView)findViewById(R.id.textViewVerified);
        mAuth = FirebaseAuth.getInstance();
        mCallbacks = new PhoneAuthProvider.OnVerificationStateChangedCallbacks() {

            @Override
            public void onVerificationCompleted(PhoneAuthCredential credential) {
               // Log.d(TAG, "onVerificationCompleted:" + credential);
                mVerificationInProgress = false;
                Toast.makeText(PhoneLogin.this,"Verification Complete",Toast.LENGTH_SHORT).show();
               signInWithPhoneAuthCredential(credential);
            }

            @Override
            public void onVerificationFailed(FirebaseException e) {
               // Log.w(TAG, "onVerificationFailed", e);
                Toast.makeText(PhoneLogin.this,"Verification Failed",Toast.LENGTH_SHORT).show();
                if (e instanceof FirebaseAuthInvalidCredentialsException) {
                    // Invalid request
                    Toast.makeText(PhoneLogin.this,"InValid Phone Number",Toast.LENGTH_SHORT).show();
                    // ...
                } else if (e instanceof FirebaseTooManyRequestsException) {
                }

            }

            @Override
            public void onCodeSent(String verificationId,
                                   PhoneAuthProvider.ForceResendingToken token) {
               // Log.d(TAG, "onCodeSent:" + verificationId);
                Toast.makeText(PhoneLogin.this,"Verification code has been send on your number",Toast.LENGTH_SHORT).show();
                // Save verification ID and resending token so we can use them later
                mVerificationId = verificationId;
                mResendToken = token;
                e1.setVisibility(View.GONE);
                b1.setVisibility(View.GONE);
                t1.setVisibility(View.GONE);
                i1.setVisibility(View.GONE);
                t2.setVisibility(View.VISIBLE);
                e2.setVisibility(View.VISIBLE);
                b2.setVisibility(View.VISIBLE);
                // ...
            }
        };

        b1.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PhoneAuthProvider.getInstance().verifyPhoneNumber(
                        e1.getText().toString(),
                        60,
                        java.util.concurrent.TimeUnit.SECONDS,
                        PhoneLogin.this,
                        mCallbacks);
            }
        });

        b2.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                PhoneAuthCredential credential = PhoneAuthProvider.getCredential(mVerificationId, e2.getText().toString());
                // [END verify_with_code]
                signInWithPhoneAuthCredential(credential);
            }
        });


    }

    private void signInWithPhoneAuthCredential(PhoneAuthCredential credential) {
        mAuth.signInWithCredential(credential)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                           // Log.d(TAG, "signInWithCredential:success");
                            startActivity(new Intent(PhoneLogin.this,NavigationDrawer.class));
                            Toast.makeText(PhoneLogin.this,"Verification Done",Toast.LENGTH_SHORT).show();
                            // ...
                        } else {
                           // Log.w(TAG, "signInWithCredential:failure", task.getException());
                            if (task.getException() instanceof FirebaseAuthInvalidCredentialsException) {
                                // The verification code entered was invalid
                                Toast.makeText(PhoneLogin.this,"Invalid Verification",Toast.LENGTH_SHORT).show();
                            }
                        }
                    }
                });
    }
}

**Comment by sharifullahsh** [comment]
I have the same issue with ionic 3. Have any one solved it or not.

**Comment by mapo-lp** [comment]
same problem here :/ has anyone find a fix?

**Comment by alexanderkhitev** [comment]
I faced the same problem on iOS

**Comment by sharifullahsh** [comment]
I had the same problem. First check the phone verification from firebase auth demo [firebase auth demo](https://fir-ui-demo-84a6c.firebaseapp.com/). If your are receiving the sms, than the problem is in your code, to solve it use the plugin directly not the way that ionic suggest. If you are not able to receive the sms from firebase auth demo, than the problem is from firebase and phone company.

**Comment by Devajeet1995** [comment]
sharifullahsh ...can u suggest the direct plugin for this

**Comment by HiteshDevganiya** [comment]
Having same issue with Airtel zambia and its coming for only some users. 10 % of registered users are getting failed due to not receiving SMS.

**Comment by HadiDhahds** [comment]
Same but there is "String s" from onCodeSent in the console with a hashed code
but no sms code received

**Comment by HadiDhahds** [comment]
@Override
        public void onVerificationFailed(FirebaseException e) {
                Toast.makeText(Main3Activity.this, e.getMessage(), Toast.LENGTH_LONG).show();
        }

try this, maybe the message can help you as it did to me

**Comment by TaslimHartmann** [comment]
In my case, I tested using 
https://github.com/firebase/quickstart-android/tree/master/auth
NO LUCK!!!

i tested using: 
https://fir-ui-demo-84a6c.firebaseapp.com/
SMS Sent successfully.
Above I tested on phone with no card.

But when I tested on phone with active card, SMS SENT SUCCESSFULLY.

Hopefully this can help someone out there.

**Comment by sawepeter** [comment]
Hae guys, 
I have a problem with the firebase authentication for Android when using phone number auth. When I run the application for the first time.it sends the OTP but when I try running the application for the send time inputting the same mobile number it fails to send the OTP what might be the main issue in this case.

**Comment by chitra-bahadur** [comment]
@abba-maker  i used to get otp but today i am not getting. i added my number in testing after removing it from testing, otp has stopped coming.

**Comment by mdhaider** [comment]
If you added your mobile number in test phone in Firebase. Please remove it.

**Comment by Shubham1011** [comment]
for me , it worked when I restarted my phone and installed the application again

**Comment by scookies** [comment]
I am seeing the same issue but on Myanmar phone number.  Is it really carrier specific?

**Comment by jeroternero** [comment]
the problem is that the firebase auth sms service will only send messages when the app is in production mode (uploaded to the store). But to be able to test the methods from test mode, it is adding a test number in the white list of firebase.

**Comment by saqibsoftwares** [comment]
> If anyone has added his phone number for testing under firebase(Sign-in method->Phones), then please remove from there to get otp.

OMG you just saved my a$$ :D thanks I was trying since 3 straight hours.

**Comment by criminact** [comment]
> Hmm, similar issue here - except: I received a text when I started the auth on one phone but used a sms number of another one (manual typing mode), I did not receive anything when using the same number where the app was running.

@inger  Found any solution for this buddy?

**Comment by buuzuu** [comment]
Worked for me .

Sometimes Google is unable to verify the request coming from you app.
In order to solve it. Generate your app's signing report and get your SHA-1 or SHA-256 fingerprints.
Go to your firebase project setting and add those fingerprints.


[How to generate fingerprints](https://stackoverflow.com/questions/39144629/how-to-add-sha-1-to-android-application)

**Comment by Abosrie** [comment]
I am still facing the same issue! 
Still, some users are not getting the OTP! 

Is there any permanent solution for this?

**Comment by katowulf** [comment]
There is no permanent solution to flakiness of SMS delivery. There are multiple systems involved and phone carriers have unreliable networks. So no, there will not ever be a permanent solution nor 100% delivery. That's the nature of cell phones.

If running into issues with more than 5 devices in a single region, please [reach out to Firebase Support to report](http://firebase.google.com/support). 

Locking this (previously closed) issue since the Android Quickstart repo is not the proper place for troubleshooting Auth SMS related issues, in order to prevent people from not getting resolution; please use proper channels.
