### ISSUE TITLE
problem in getting SMS in Phone Number verification method

### ISSUE THREAD

**Issue by safiyaAkhtar** [firebase/quickstart-android#287]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _Redmi 3s____
  * Android OS version: ___6.0.1 MMB29M__
  * Google Play Services version: _3.1.0____
  * Firebase/Play Services SDK version: __25___
  
### Step 3: Describe the problem: 

i have used the code given for Phone number authorization but it isn't working well, as i am not getting any sms for verification , my application is installed and when i click start button nothing happens, please tell me steps to help resolve this problem

**Comment by samtstern** [comment]
@safiyaAkhtar what carrier is your device on?  Do you have access to another device on a different carrier you could try?

**Comment by safiyaAkhtar** [comment]
i have tried on Vodafone ,reliance and airtel on different devices nothing helped

**Comment by samtstern** [comment]
@safiyaAkhtar can you provide any logs, error messages, or code snippets? Just "not getting SMS" is not enough information to debug.

**Comment by safiyaAkhtar** [comment]
![img_20170619_221629](https://user-images.githubusercontent.com/29547660/27296246-bbce158a-553d-11e7-9c10-30566d29684a.jpg)
only this line i get on my logcat

**Comment by samtstern** [comment]
@safiyaAkhtar can you send this issue to [Firebase support](https://firebase.google.com/support/).  This is likely a carrier-specific issue with phone authentication and they can help.

**Comment by ltthao** [comment]
Hi! Can you help me please! Firebase not sent pin code for my phone number but sent with orther phone number

**Comment by Asrar-7** [comment]
Even i am facing the same issue , unable to receive OTP for specific numbers, i really don't know whats wrong , at the beginning i had received but now its not working with me

**Comment by lkphul47** [comment]
same issue I have in both apps- one created in android studio and another in react native. I cant receive otp  on some devices, but receiving on all other devices. If I fill these numbers in app running on other device, then I receive the OTP

**Comment by lkphul47** [comment]
Has anyone found a solution?

**Comment by jhoanarango** [comment]
I have an app in production, so far most of the users have been able to receive SMS codes, but I am receiving reports of some users not getting SMS verification codes. Has anyone found a solution to this yet ?

**Comment by Abosrie** [comment]
+1
