### ISSUE TITLE
Speed up Travis CI build

### ISSUE THREAD

**Issue by samtstern** [firebase/quickstart-android#288]
Right now our builds are very slow.  Each module takes about ~20m, even running them in parallel on Travis we get a total build time of close to an hour:

![screenshot from 2017-06-19 08 58 46](https://user-images.githubusercontent.com/8466666/27294205-9aba2246-54cd-11e7-9562-870f15739843.png)

I recently tried increasing the resources in #286 but it didn't have much of an effect.

The build for [FirebaseUI-Android](https://github.com/firebase/FirebaseUI-Android) is only about 7 minutes even though it's a multi-module build including test, which should be much slower than our build in theory.

(cc: @SUPERCILEX any ideas?)

**Comment by SUPERCILEX** [comment]
@samtstern Before I get in too deep, is there a reason for having a billion different gradle projects instead of having just one with multiple modules? It's a bit messy... 😕

**Comment by samtstern** [comment]
@SUPERCILEX well actually it's both.  You can load the entire thing as a multi-module project via the root `build.gradle` file or you can load any individual project as an app project with a single module via the `build.gradle` in the directory.  So it is possible to just `./gradlew build` all of the apps from the root.

**Comment by SUPERCILEX** [comment]
@samtstern I absolutely **_NAILED IT_**!!! 😄😆 Check out this sweet build: https://travis-ci.org/SUPERCILEX/quickstart-android/builds/244702068. I've maxed out all Gradle parallelism and the Gradle build itself only takes 2m. I'm working on a PR where I'll explain more.
