### ISSUE TITLE
How to clear Firebase Crash reports?

### ISSUE THREAD

**Issue by pranaypatel512** [firebase/quickstart-android#29]
I am using Firebase crash reporting service for android.
Can any one help me to clear crash report from Firebase console or any way to remove it by Firebase crash android API?

**Comment by kroikie** [comment]
Currently there is no way to remove an uploaded report. If possible could
you give more details on why this would be important in your case?

**Comment by jhalborg** [comment]
I found this issue on Google Search by searching for "closing issue/ticket". I've previously used Twitter's Fabric as my crash reporting tool, and have been a fan of being able to mark issues as 'closed' or 'handled' so as to keep the dashboard clean and only list the new/reoccuring errors that should be handled.

**Comment by samtstern** [comment]
@jhalborg @pranaypatel512 this is all good feedback thanks!  As this is not a samples issue, I am going to close this.  I will pass it on to the team.

**Comment by k0shk0sh** [comment]
We are in 2017 and this issue haven't been fixed. why would it be not simple? you could just add an extra checkbox for us to select multiple issues & close them with just a single click.

**Comment by olejnjak** [comment]
I think that _clearing_ all crashes might be useful...e.g. I always create a version that crashes on purpose to make sure that crash reporting works, once I see it does I'd love to reset crashes in dashboard and start with clean sheet. Of course I close created issue, but number of crashes in the dashboard still remains the same.

**Comment by samtstern** [comment]
@k0shk0sh @olejnjak we agree that this would be a useful feature.  Since we acquired Crashlytics we've been looking at a number of improvements we can make, stay tuned!

**Comment by sp0rk** [comment]
@samtstern What's the status on this feature?

**Comment by k0shk0sh** [comment]
@sp0rk you better off using fabric since now its aquired by firebase/google

_Sent from my Samsung SM-G950F using [FastHub Debug](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by freak4pc** [comment]
Sorry to bump this issue, but it seems that to this very day there is no way to clear (or close) all issues at once. 

The use case here for me is to close all issues when uploading a new version so my dashboard is clean and I can concentrate on crashes coming from users of the latest version. 

Having to go one by one to close them (or mark all of them by hand) is a bit tedious. 

Would appreciate any feedback, or if I should open a new issue :)

**Comment by fiftysoft** [comment]
any update ?

**Comment by zeffa** [comment]
I have some forced crashes on my dashboard which i used while testing this tool. I'd like to clear them for real reports from production app. If you could add a functionality to select and clear it could be wow!

**Comment by samtstern** [comment]
As @jhalborg said, this feature is available in Crashyltics.

Check out this guide for upgrading from Firebase Crash Reporting to Crashlytics, which is recommended:
https://firebase.google.com/docs/crashlytics/upgrade-from-crash-reporting

**Comment by JanNash** [comment]
@samtstern Could you elaborate on how it is possible to select multiple crashes and close them all at once? I can't seem to find a way to do this.

**Comment by JanNash** [comment]
There is even [a video from December 2018](https://www.youtube.com/watch?v=KKaZFkIvs_M) where the first information is that it is not possible to close multiple issues at once. Is there any plan to implement this at all?

**Comment by samtstern** [comment]
@JanNash sorry I must have been misinformed.  If this  feature is not available and you would like to advocate for it, the best place to do so is here:
https://firebase.google.com/support/troubleshooter/report/features
