### ISSUE TITLE
Instant verification or Auto-retrieval not working

### ISSUE THREAD

**Issue by jianleon** [firebase/quickstart-android#292]
* Android device: LG X Screen, LG X Play
  * Android OS version: Android 6.0.1
  * Google Play Services version: com.google.gms:google-services:3.0.0
  * Firebase/Play Services SDK version: compileSdk = 25, targetSdk = 23

I've tried the phone auth guide for Android(https://firebase.google.com/docs/auth/android/phone-auth) and this callback
`PhoneAuthProvider.OnVerificationStateChangedCallbacks`, never gets into onVerificationCompleted(). I always have to type manually the verification code.

  * I want the cellphone to validate automatically the SMS code and start the normal flow.

**Comment by samtstern** [comment]
Double-posted: https://github.com/firebase/FirebaseUI-Android/issues/775

**Comment by jianleon** [comment]
@samtstern I have tested more than 10 times the verification in my personal cellphone, and there is not a single time that instant verification works. I always receive the SMS, but nothing happends, I have to type it manually. I hope you can help me with it.

**Comment by samtstern** [comment]
@jianleon as I said instant verification / auto retrieval are not always expected to work and your code should be ready to handle manual entry.

- Auto-retrieval works for SMS delivered via GSM network. Virtual phone numbers are not supported. At this moment, we limit the capability to certain countries / carriers and the requirement will be loosened in releases later this year (no SDK update required)

- Instant validation works if Google has verified the phone number for this Android device and the device passes certain security checks.

I am going to close this issue as I believe the likely cause is that your particular device/carrier/OS does not meet all of the requirements.

**Comment by jQrgen** [comment]
@samedson So Auto-retrieval and instant validation still _has_ to have a fallback to manual support edge cases? Or else some users will never be able to authenticate using sms?

**Comment by samedson** [comment]
I believe you meant to mention @samtstern

**Comment by samtstern** [comment]
@jQrgen yes all of these fall back to manual when necessary.

**Comment by MOhsain** [comment]
> @samtstern I have tested more than 10 times the verification in my personal cellphone, and there is not a single time that instant verification worked. I always receive the SMS, but nothing happends, I have to type it manually. I hope you can help me with it.

Send Me Your Code
