### ISSUE TITLE
When login with phone no than OTP SMS get after 1 hour.

### ISSUE THREAD

**Issue by deepikaopenxcell** [firebase/quickstart-android#293]
I use firebase  auth for phone no verification, when send OTP than not get sms when resend code than after 1 hour got SMS. when i try with febric digit than got sms  within 5 sec.

**Comment by samtstern** [comment]
@deepikaopenxcell thanks for reporting this.  Can you file a new ticket with [Firebase support](https://firebase.google.com/support/).  This is likely a carrier issue and they can help you debug it.
