### ISSUE TITLE
onMessageReceived not triggered

### ISSUE THREAD

**Issue by rajas47** [firebase/quickstart-android#297]
@Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (remoteMessage != null) {
            Intent intent1 = new Intent(this, NotificationService.class);
            intent1.putExtra("notification", remoteMessage);
            startService(intent1);
        }
    }

When the app is swiped out of the background tasks on OnePlus3T the onMessageReceived is not triggered.

OS build for OnePlus3T is 4.1.6
Android Nougat 7.1.1

The method works perfectly on all other devices .ie. when app is swiped out of memory.  
Android OS 4.2, 4.4, 5.1.1, 6.0.1, 7.1.1 Lineage OS.
And I am using data in FCM messaging and not notifications.

Please help me. Thanks in advance.

**Comment by kroikie** [comment]
Thanks for this feedback, I believe that you app may be getting killed when swiped from recents. Killed apps do not and should not receive messages. Seems like the OPT3 is being a bit aggressive in killing your app.

Could you check is there is a way to exempt your app from being killed when swiped away? Iikely in the recents list.

**Comment by rajas47** [comment]
Could you guide me with it? Cause i have tried adding an alarm manager in the inTaskRemoved method of the service and tried to restart the service, but I have not been successful.

If you could just give me a hint that would be great.
Thanks in advance.

**Comment by kroikie** [comment]
Could you confirm that this issue exists even if you white list the app on the OPT3?

**Comment by rajas47** [comment]
How do you whitelist the app?
Please guide me.

**Comment by kroikie** [comment]
I believe there is a way to indicate which apps should not be swiped from resents. I don't have one of those devices but I think there is an option in the resents screen.

Also you can check if aggressive dose is on for the device, that may affect the apps ability to receive messages while in the background.

**Comment by samtstern** [comment]
Closing due to lack of response.  @rajas47 I hope you got this sorted out in the meantime.
