### ISSUE TITLE
SMS not received

### ISSUE THREAD

**Issue by FinCendikia** [firebase/quickstart-android#298]
### Step 1: Are you in the right place?
Yes, I have read other closed issue about SMS not received, but none of the solutions works for me.
  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: XiaoMi Redmi 4 Prime
  * Android OS version: 6.0.1
  * Google Play Services version: 11.0.55
  * Firebase/Play Services SDK version: 11.0.2
  * Country : Indonesia
  * Carrier : 3 and Telkomsel
### Step 3: Describe the problem:
SMS from Phone Authenticator never received
#### Steps to reproduce:

  1. get a valid phone number to verify
  2. pass it to PhoneAuthProvider.verifyPhoneNumber along with other arguments
  3. codeSent callback gets fired but no sms is sent to device
  
#### Observed Results:
  The code runs smoothly,
PhoneAuthActivity: onCodeSent:AM5PThBhkU9ZeI3ldOWBhNpqmquQyHNYpo6j02NAXbcJAV_QE8ou7ivAdjNcSN3AJl8pABTslSauA8WPatx-D28zk9jsIrgpCTEWPxf35fQ1E5qmHZRDOpKjcdRSYxkxJMRomy7bMdWchDHdByZ9q3YSPSw4Syyw9A.
But the sms never sent to the designated number.
#### Expected Results:

Receive the verification SMS.
  
#### Relevant Code:

I am using [this](https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/PhoneAuthActivity.java) code on quickstart-android

**Comment by samtstern** [comment]
@FinCendikia please contact [Firebase Support](https://firebase.google.com/support/) about this issue, they are the best way to get help with SMS issues at the moment.
