### ISSUE TITLE
Unknown intent action: com.google.firebase.MESSAGING_EVENT﻿

### ISSUE THREAD

**Issue by burhanshakir** [firebase/quickstart-android#299]
Whenever I try to send a notification from the console using the registration token, I get this on my monitor : Unknown intent action: com.google.firebase.MESSAGING_EVENT﻿. What could be wrong ?

**Comment by kroikie** [comment]
Hi, could you give a bit more information on how to reproduce this issue?
Where exactly are you seeing the message?

**Comment by vinod1988** [comment]
I have the same issue.

 Unknown intent action: com.google.firebase.MESSAGING_EVENT

Any one resolved this

**Comment by burhanshakir** [comment]
Seems like you have a issue in your gradle file. Maybe your Google play
services dependencies do not match with your firebase dependencies. Make
sure both the versions are same

**Comment by samtstern** [comment]
Closing this issue due to lack of updates, unfortunately we need more information to debug.  Hope you got it all working in the end.

**Comment by haris15** [comment]
check that your google play service version and firebase messaging library version is same

**Comment by dbwelch** [comment]
Yes,have same issue, @haris15 not sure I understand "same version", they do not coordinate release levels for these libraries, how can they be "same"?
