### ISSUE TITLE
Error Failed to resolve: com.google.firebase:firebase-auth:9.0.0

### ISSUE THREAD

**Issue by WanClem** [firebase/quickstart-android#3]
Help.I need to migrate my code base.Am so madly in love with the new firebase features.I followed all the instructions by altering all my build.gradle files in android studio just to start using the new features but this is what I keep getting...`Error Failed to resolve: com.google.firebase:firebase-auth:9.0.0`,`Error Failed to resolve: com.google.firebase:firebase-database:9.0.0`.Please help..Thanks

**Comment by samtstern** [comment]
The `9.0.0` versions of the `com.google.android.gms:*` and `com.google.firebase:*` packages were just released in the SDK manager so it's likely you just need to update.

In Android Studio:

  - Click **Tools** > **Android** > **SDK Manager**
  - Click into the **SDK Tools** tab
  - Select and install **Google Play Services** (rev 30) and **Google Repository** (rev 26).  See the image below.
  - **Sync** and **Build** your project.

[![enter image description here][1]][1]


  [1]: http://i.stack.imgur.com/qc3AG.png
