### ISSUE TITLE
how to create a topic in firebase console and use it via cordova-plugin-firebase

### ISSUE THREAD

**Issue by joesleiman** [firebase/quickstart-android#302]
i'm using cordova-plugin-firebase , and i did : 
```
this.firebase.subscribe('news')
.then(
(data)=>{
console.log(data);
},
(error)=>{
console.log(error);
}
```
but i can't add a topic or send notifications with topic to test it . 
anyone know how ?
)

**Comment by samtstern** [comment]
@joesleiman  sorry we can't answer questions about other libraries here.  Try filing an issue on their repo: https://github.com/arnesson/cordova-plugin-firebase
