### ISSUE TITLE
Firebase 11 doesn't let Proguard strip out Logs from release builds

### ISSUE THREAD

**Issue by gracejang** [firebase/quickstart-android#305]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Insignia Tablet
  * Android OS version: 6.0.1
  * Google Play Services version: 11.0.55
  * Firebase/Play Services SDK version: 11+
  
#### Steps to reproduce:

  1. Use proguard to strip Logs from release builds
  
#### Observed Results:

- You see the Logs still.

  
#### Expected Results:

  * Shouldn't see Logs.

However if you don't upgrade Firbease to 11 and remain on 10, Logs are stripped by Proguard. So I concluded that Firebase 11 update is what made my Logs come back.
  
#### Relevant Code:

1. Updated to Firebase 11

```groovy
    compile 'com.google.firebase:firebase-storage:11.0.1'
    compile 'com.google.firebase:firebase-auth:11.0.1'
    compile 'com.google.android.gms:play-services-auth:11.0.1'
    compile 'com.firebaseui:firebase-ui-auth:2.0.1'
    compile 'com.google.firebase:firebase-database:11.0.1'
```

2. Add this rule to Proguard to strip logs from release builds:

```
-assumenosideeffects class android.util.Log {
    public static boolean isLoggable(java.lang.String, int);
    public static int v(...);
    public static int i(...);
    public static int w(...);
    public static int d(...);
    public static int e(...);
}
```

**Comment by samtstern** [comment]
@gracejang sorry I mever got back to you here!  Do you still see this issue with `11.0.4`?

**Comment by gracejang** [comment]
Hi Sam!

I just tried and I think I have a different issue with 11.0.4 when running
proguard.

I get the following warning and a signed APK can't be generated:

Warning: com.firebase.ui.auth.provider.TwitterProvider: can't find
referenced class retrofit2.Call

Any help in resolving this is much appreciated! Thanks Sam!

Best,
Grace

**Comment by samtstern** [comment]
@gracejang that sounds like a problem with FirebaseUI (which I also maintain) but it's not one I have seen before.  Can you try adding a `dontwarn` proguard rule?

```
-dontwarn retrofit2.**
```

**Comment by gracejang** [comment]
Hi Sam!

That "dontwarn" proguard rule worked but I just confirmed that indeed with
11.0.4, the proguard rule for removing debug logs don't work and I still
see it. But I did confirm if I change it back to 10.2.0, it works.

Thanks!

**Comment by samtstern** [comment]
@gracejang thanks for confirming!  What version of FIrebaseUI are you using?

**Comment by gracejang** [comment]
I'm using 2.2.0 with 11.0.4 :)

**Comment by samtstern** [comment]
@gracejang ok I think I figured it out.  You're being bit by this issue:
https://issuetracker.google.com/64177053

FirebaseUI messed up our proguard configuration which causes the `-dontoptimize` flag to be applied to your build.  This will be fixed in the next release of FirebaseUI.

However you should be able to override this yourself (worked in my testing).  Change this:

```groovy
proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
```

to this:

```groovy
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
```

**Comment by gracejang** [comment]
Hi Sam,

Thanks for your reply!

Where should I be making this change?

I already make this change for my app/build.gradle file with:

minifyEnabled true
 proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), '
proguard-rules.pro'

But it still causes the same problem.

Is there another place I should make the change? :) Thanks!

**Comment by samtstern** [comment]
@gracejang hmmm it seems like the consumer proguard rules of FirebaseUI are overriding your rules.

I actually don't know enough about Proguard to answer this.  I will ask.

**Comment by gracejang** [comment]
Sounds great!

Also quick question Sam,

so are you saying that even though I am adding the flag to optimize with
Proguard, the proguard rules of FirebaseUI are overriding and so optimizing
isn't actually happening for my app? I haven't deeply confirmed whether
optimization was happening or not (assumed it was since I have it on) - I
just thought this one rule was breaking with FirebaseUI, not necessarily
that all my rules for proguard weren't working.

**Comment by samtstern** [comment]
@gracejang it seems that is the case.  We'll add that to the pile labeled "proof that proguard is a secret alien program designed to get humans to throw computers out of windows".

I investigated this for a while and tried to fix it, all of the solutions were terrible.  But the good news is we can fix this in FirebaseUI.  Look out for version `2.3.0` today which will include the fix.

Thank you so much for your patience and fast responses!

**Comment by samtstern** [comment]
@gracejang FirebaseUI version 2.3.0 has been released.  I am 99% sure this will solve your issue so I am going to close this, but please let me know if it doesn't!

**Comment by gracejang** [comment]
Hi Sam!

It indeed worked! :) My proguard rules apply with 2.3.0

Quick question though: My target and compile sdk versions are 25 and we
were hoping to release this update with those version numbers but it looks
like 2.3.0 required use to use 26? Is that correct?

**Comment by samtstern** [comment]
@gracejang you need to update to `compileSdkVersion 26` in order to use support lib `26.0.0+` but you don't need to update target SDK version.  Updating the compile SDK version should have absolutely no effect on the behavior of your app and should be a safe upgrade to make, even if you wait a while to upgrade your target SDK version.

**Comment by gracejang** [comment]
Hi Sam!

Thank you so much for your reply! I am new to Android Development so really
appreciate the help you give me.
So just to clarify, in order to use FirebaseUI 2.3.0 I indeed *need to
update compileSdkVersion to 26* (can't leave it at 25) but I can leave
targetSDKversion as 25?

Thanks!!

**Comment by samtstern** [comment]
@gracejang that's the recommendation, yes.  You could also override our transitive dependencies to choose support library 25 but it's possible other strange bugs would appear if you did that.
