### ISSUE TITLE
In your Database sample, how do we display profile pics? 

### ISSUE THREAD

**Issue by FromNigeria** [firebase/quickstart-android#308]
### Step 1: Are you in the right place?

How do we display the profile pics since you did a great job.For those of us upcoming Developers..I mean in your Database sample qucikstart..You only display the name of the user, and his post but the profile pics are not showing

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by FromNigeria** [comment]
How do we display current user profile images? on your Database sample? iHave been toiling all night to do that but App keep crashing

**Comment by samtstern** [comment]
If your user has a picture you can use FirebaseUser#getPhotoUrl to retrieve a link to it:
https://developers.google.com/android/reference/com/google/firebase/auth/FirebaseUser.html#getPhotoUrl()

You can then use any library you want to load the images.  I'd suggest using Glide:
https://github.com/bumptech/glide
