### ISSUE TITLE
404 URL

### ISSUE THREAD

**Issue by emansih** [firebase/quickstart-android#310]
### Step 1: Describe the problem:
The URL in README.md for pref folder (https://firebase.google.com/docs/performance) leads to a 404 page
#### Steps to reproduce:
1. Click on the above mentioned URL.

#### Observed Results:

Sees 404 page
  
#### Expected Results:

  * What did you expect to happen?
Page should not be 404
  

#### How to fix

Replace the above mentioned URL with this instead. https://firebase.google.com/docs/perf-mon/

**Comment by samtstern** [comment]
@emansih thanks for catching this!  I made the fix you suggested.
