### ISSUE TITLE
Notification icon when app in background doesn't match declared in manifest in meta tag when using GCM push

### ISSUE THREAD

**Issue by DDeg** [firebase/quickstart-android#311]
Android device: Samsung Galaxy S6 SM-G920F, Motorola Nexus 6
Android OS version: 7.0, 6.0.1
Google Play Services version: 11.3.02
Firebase/Play Services SDK version: 11.0.1
  
Notification icon when app in background doesn't match declared in manifest in meta tag.

  1. Integrate GCM messaging (GcmReceiver and GcmListenerService)
  2. Add com.google.firebase.messaging.default_notification_icon meta-data to manifest
  3. Receive push when app in background
  
Observed Results:
Notification show ic_launcher icon instead declared in com.google.firebase.messaging.default_notification_icon meta-data.
  
Expected Results:
Icon instead declared in com.google.firebase.messaging.default_notification_icon meta-data displayed in Play Services notification (white square on Android 5.0+)
  
Relevant Code:

        <receiver
            android:name="com.google.android.gms.gcm.GcmReceiver"
            android:exported="true"
            android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION" />
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />

                <category android:name="{applicationId}" />
            </intent-filter>
        </receiver>

        <service
            android:name="push.PushMessagingService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
            </intent-filter>
        </service>

        <meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/mono_icon" />
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/notification_red" />

**Comment by samtstern** [comment]
@DDeg the default icon configured through `meta-data` is only supported if you use FCM.  It's one of many reasons to update your code from GCM to FCM!

https://firebase.google.com/docs/cloud-messaging/
