### ISSUE TITLE
How to send non-collapsible message via Firebase console?

### ISSUE THREAD

**Issue by accursedm0** [firebase/quickstart-android#312]
I understand that at present the Firebase console can only send notification messages which are collapsible by default. How to make them non-collapsible, or how to unset the collapse_key parameter?

**Comment by ioannisa** [comment]
Hi,

If I understand correctly, you want to treat Notifications as non-collapsible messages, right?

Well, data messages are non-collapsible as far as I know.  So if I were you, I would remove notification part, and deliver everything to the data.  

Then from your OnMessageReceived method, you can produce a custom notification.  That way your message is a data message that is by default non-collapsible and you produce your own notification.

**Comment by accursedm0** [comment]
Thank you for your answer ioannisa, that's exactly what I'd like to do. 
But afaik, and according to the documentation, the firebase console, that is the notification composer, cannot send pure data messages at the moment. 
Leaving "message text" field empty and putting everything into the custom data fields would be great but the send button is grayed out then, which is the correct behaviour according to the docs.
Yet, I'd like to use this notification composer in the firebase console which is great except for this one missing checkbox ala "make this a data message" and/or "make this message non-collapsible".

**Comment by ioannisa** [comment]
Ok, I see...

Well in that case, you can address the problem by sending yourself the messages, without using the actual dashboard.  One good method is to do that with PHP, or if you are confident, you can use the firebase cloud functions.

I will give you the "easy" method with the php approach.  By utilizing this php approach, you can send messages that contain only data....


`<?php
#API access key from Google API's Console
    define( 'API_ACCESS_KEY', 'YOUR_API_KEY_HERE' );
   define( 'PROJECT_ID', 'YOUR_PROJECT_ID_HERE' );

#to find the api key and project id, click the "gear" next to the "overview'.  
# Then go to the "Project Settings"->"Cloud Messaging"
# your api key will be the "Server Key" (yes, that long thing)
# your project_id will be the "sender id"
#by  defining those values above, you have connected your php script to your firbase project
#
# little later on, at the "to" section I send to a topic called "my_topic"
# if you want to target a topic follow the pattern: 'to' => '/topics/whatever_topic_you_want'
#if you want to target individual device then follow: 'to' => 'whatever_device_token_you_have'
#
# hope this helps :)

#prep the bundle
    
	$fields = array
			(
				'to'		=> '/topics/my_topic,
				'data' => array(
					'title' => 'my_title',
					'message' => 'my_message',
				),
				'time_to_live' => 0
			);

	$headers = array
			(
				'Authorization: key=' . API_ACCESS_KEY,
				'Content-Type: application/json',
				'project_id: ' . PROJECT_ID
			);
#Send Reponse To FireBase Server	
		$ch = curl_init();
		curl_setopt( $ch,CURLOPT_URL, 'https://fcm.googleapis.com/fcm/send' );
		curl_setopt( $ch,CURLOPT_POST, true );
		curl_setopt( $ch,CURLOPT_HTTPHEADER, $headers );
		curl_setopt( $ch,CURLOPT_RETURNTRANSFER, true );
		curl_setopt( $ch,CURLOPT_SSL_VERIFYPEER, false );
		curl_setopt( $ch,CURLOPT_POSTFIELDS, json_encode( $fields ) );
		$result = curl_exec($ch );
		curl_close( $ch );
#Echo Result Of FireBase Server
echo $result;`

**Comment by accursedm0** [comment]
Thank you for the help and the codesample. Probably I have to do something like that although the point was that I'd like to use the console cause in the end, non-it colleagues must be able to send the messages on their own.
It's a bit disappointing having to rebuild the firebase console just to add that extra option to send data messages. The more so since the devs know about the issue and might add that feature to the console at some point. Would be great to know if there is an update planned in the near future.

**Comment by samtstern** [comment]
@ioannisa thanks for jumping in!

@accursedm0 we hear you, we also want to add more capabilities to the console.  For now though the information above is correct, you'll need to use the API if you want to send data messages.  I hope you get something working!
