### ISSUE TITLE
Overriding FirebaseMessagingService.handleIntent(Intent intent)

### ISSUE THREAD

**Issue by accursedm0** [firebase/quickstart-android#313]
I'd really love to use the Firebase console to send FCM Messages but unfortunately it can only send notification messages which are not handled by `onMessageReceived()` if the app is not active.
The issue is known for over a year and like so many other people struggling with that problem I ended up overriding
`FirebaseMessagingService.handleIntent(Intent intent)` bypassing `onMessageReceived()` completely.
The former is always called even for notification messages no matter if the app is in background or not.
It seems to work fine, yet `handleIntent()` is not event mentioned in the docs. 

Is it considered 'ok' to override `FirebaseMessagingService.handleIntent(Intent intent)`, in order to always manually handle messages send via the Firebase console?

If not, why not?
If yes, why is it not described in the docs? People are struggling with this all over stackoverflow for quite some time.

Is there any update on sending Data Messages via the Firebase console? Would render all the above obsolete.

using com.google.firebase:firebase-messaging:11.0.1

**Comment by samtstern** [comment]
@accursedm0 as you've discovered, there's no way to send data messages from the Firebase console.  As for overriding methods of `FirebaseMessagingService`, it may work but we can't guarantee your solution will continue to work as we release new versions.  We do not intend for developers to override methods except for the ones we mention explicitly in the docs, so if you do it it's at your own risk!

**Comment by andreinitescu** [comment]
@accursedm0 Doesn't this send Data Messages?
![image](https://user-images.githubusercontent.com/743918/34227238-27fbbe92-e5d5-11e7-8f0b-2f50d6e34343.png)

**Comment by accursedm0** [comment]
@andreinitescu Unfortunately not, this will just add a data payload to the Notification Message. And unlike the behaviour of a pure Data Message, a Notification Message (even with data payload) is not handled by `onMessageReceived()` if the app is not active.
