### ISSUE TITLE
Firebase onMessageReceived not called in foreground

### ISSUE THREAD

**Issue by symphonicz** [firebase/quickstart-android#314]
i have a problem.

My app is running in foreground but onMessageReceived() not called when i use firebase console send notification. And in background Default Notification that create from firebase not appear on notification bar.

This error is appear on Zenfone 6 and Zenfone 2.
but after i restart my device all of notification that send before is appear on notification bar.

i dont know what it happen. 

help me pls.

ps. In other device it work fine.

**Comment by ioannisa** [comment]
So since you now restarted your device, its all working fine or after some time it stoped delivering messages again?

I mean, is there a way to replicate the problem?

**Comment by symphonicz** [comment]
thank for reply ioannisa

after i restarted my device, After few minute it stoped delivering message.

**Comment by samtstern** [comment]
Sounds like this is going to be hard to reproduce since @symphonicz has a working device now.  Closing this issue, but we can re-open if we find a consistent reproduction path.
