### ISSUE TITLE
Notification does not popup in background

### ISSUE THREAD

**Issue by sneps85** [firebase/quickstart-android#315]
Hello, i need to send a push with both data and notification fields set in the payload. Unfortunately, when the app is in background or killed (by swiping), the notification does not pop up. It does only vibrate/sound and make a icon in the toolbar.

How can i achieve to make the notification pop up in android?

**Comment by accursedm0** [comment]
Unfortunately, this doesn't seem to be possible at the moment when using the firebase console.
You must send pure data messages to handle them consistently in `onMessageReceived` no matter if the app is in the background or not. See this about notification and data messages: https://firebase.google.com/docs/cloud-messaging/concept-options
You can set your notification fields in the data payload and pass them to your android notification title and text when handling the message inside `onMessageReceived`.

Problem is, via the firebase console you cannot send data messages at the moment, only notification messages. So you have to post your data messages yourself like described here:

https://firebase.google.com/docs/cloud-messaging/server

And here in a similar issue:

https://github.com/firebase/quickstart-android/issues/312

If you must use the firebase console then one dirty workaround consists of overriding`FirebaseMessagingService.handleIntent(Intent intent)` which is always called even if it's a notification message and the app is in the background. This bypasses `onMessageReceived` and is undocumented, see my other issue here:

https://github.com/firebase/quickstart-android/issues/313

**Comment by samtstern** [comment]
Thanks @accursedm0 for jumping in!  @sneps85 I hope that answered your question.
