### ISSUE TITLE
INVALID_APP_CREDENTIAL:App validation failed 

### ISSUE THREAD

**Issue by amicwall** [firebase/quickstart-android#316]
I cloned the firebase quickstart project, but get this error:
com.google.firebase.quickstart.auth W/PhoneAuthActivity: onVerificationFailed
                                                                                        com.google.firebase.FirebaseException: An internal error has occurred. [ INVALID_APP_CREDENTIAL:App validation failed ]

Firebase console: Authentication - Sign-in Method - Phone - enabled
and I downloaded the generated google-services.json file, and copied it to the app/ directory

**Comment by samtstern** [comment]
@amicwall this almost always occurs when your SHA1 is not set properly in the Firebase console.  Please double-check.

**Comment by amicwall** [comment]
yes that was the problem
