### ISSUE TITLE
Google Cloud Messaging for android not working when the app is closed

### ISSUE THREAD

**Issue by shomronh** [firebase/quickstart-android#318]
Hello People,

i'm trying to use android firebase cloud messaging for the case where the app is closed but my device never receive any push notification, is this a known issue ? is there a solution for that ?

i'm using the following format:

```
{  
    "to":"dsadsadsadsaweq341242343",
    "data":{  
       more data in here
    },
    "collapseKey":"fdsfdsfdsferw32432",
    "priority":"high",
    "timeToLive":6960
}
```

btw when the app is running i'm receiving push notifications, as well as when i subscribe for topics and in that case it's working when the app runs and when it's closed. so all that is very weird.

i forgot to mention that when i use a simulator using android 7.1.1 actually the push notification is working when the app is closed on the condition i manually run the app myself.

but on my device which has lower version of android than this simulator, the push notification works only when the app runs.

i really need your help here.

Thanks.

**Comment by samtstern** [comment]
@shomronh please see #4 and #89, this topic has been discussed a lot.

**Comment by shihabmi7** [comment]
It's been trending topics about Firebase Cloud Messaging that Data Payload message is not fired onMessageReceived() method for some lower end device. And it's true. Here is the result.

> App is killed scenario

**Devices got payload:: 1. Nexus 5s : OS 7.1

Device not get payload:: 1. Xiomi MI 4c: OS 5.1 2. Huawei LUA -U22 :OS 5.1**

Ensure that i'm not sending notification key from server / postman.

I am looking for the solution, i got data payload from firebase including all types of devices and Android OS & obviously From API level 15. My postman details are as follows.

```
 {
    "registration_ids": ["fC5uxGSRCsg:APA91bHh9fMXQ41LpX6tjjSsBKGrKTWYpzKimLDzvBGSHDPo2pq87JHqogUp2kqrmJi06siG_p6DfgRCim23iFzlBQAIrgtMDqRW4s39zUqv9CzyPqzxVl5PtnHPRDs4OagTuTePNyDI"],
    "data": {
        "title" : "my_custom_value",
        "message" : "tekksdasdasdsa",
         "isBackground" : "",
          "payload" : {


          },
           "timestamp" : "",
            "imageUrl" : "",
     }

}
```
