### ISSUE TITLE
App can not run unless you update your google play services? Ask a Question

### ISSUE THREAD

**Issue by Naveed-anwar123** [firebase/quickstart-android#321]
When I try to sign in using firebase and run app on emulator then I notify me to update you google play services.Now what should I do to fix this?

**Comment by samtstern** [comment]
@Naveed-anwar123 emulator images come with a version of Google Play services baked in, but most emulators cannot auto update.  You need to download the latest emulator image and then re-create your emulator.

There are also now some emulators that support the full Play Store.  On those images the update prompt will actually work.
