### ISSUE TITLE
Not able to get token.

### ISSUE THREAD

**Issue by night-cypher** [firebase/quickstart-android#324]
Hi my friends, I am facing an issue in firebase authentication. The problem is I am not able to get token after I register an account. I tried to use **getIdToken(true)** its return me an object "com.google.android.gms.tasks.zzn@b782139". 

Any other approach to get an access token from the firebase authentication? Or I need to implement some code in order to get token?

**Comment by night-cypher** [comment]
String TokenID = FirebaseInstanceId.getInstance().getToken();

**Comment by samtstern** [comment]
@night-cypher `getIdToken` is an async operation, it returns a `Task<GetTokenResult>`

```java
user.getIdToken(true)
   .addOnCompleteListener(new OnCompleteListener<> {
      // ...
   });

Then you can get the result from the `GetTokenResult`.

https://firebase.google.com/docs/reference/android/com/google/firebase/auth/FirebaseUser.html#getIdToken(boolean)

**Comment by night-cypher** [comment]
thanks !!!!

how can i know the token has been refreshed?

**Comment by samtstern** [comment]
@night-cypher yes that's correct, us an ID token listener.  When you call `getToken(true)` you're guaranteed to get a fresh token, but it will expire eventually.
