### ISSUE TITLE
gender info not avialable in google login

### ISSUE THREAD

**Issue by rahuldevanavar91** [firebase/quickstart-android#325]
google login using firebase, gender info not available.
but it's available for Facebook login.
i am using 
` mAuth.signInWithCredential(credential).addOnCompleteListener(getActivity(), new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
               task.getResult().getAdditionalUserInfo().getProfile()
}`

**Comment by samtstern** [comment]
@rahuldevanavar91 this is not a Firebase issue so I am going to close this, but check out the [People API](https://developers.google.com/people/) for getting more information from Google user profiles.

**Comment by rahuldevanavar91** [comment]
I am not using people API user I am accessing info from firebase.

**Comment by samtstern** [comment]
@rahuldevanavar91 Firebase does not provide any information on your users.  That information comes from an identity provider like Google, Facebook, or Twitter and is stored in Firebase.

So if you want more information on a Google user (like your example) you need to use a Google API to fetch it.
