### ISSUE TITLE
Build Issue: Build tool not recognised

### ISSUE THREAD

**Issue by ishandutta2007** [firebase/quickstart-android#328]
It clearly shows I have Build Tools 25.0.3 installed, but I still get the following error.

![screen shot 2017-09-02 at 9 25 27 am](https://user-images.githubusercontent.com/2527354/29992760-e8b7ed7e-8fc0-11e7-8ff0-a28153b1e936.png)
![screen shot 2017-09-02 at 9 24 40 am](https://user-images.githubusercontent.com/2527354/29992761-e8bcc0c4-8fc0-11e7-9fa7-dc1194454b1c.png)

**Comment by samtstern** [comment]
@ishandutta2007 this seems like an issue with Android Studio or with your machine's configuration, it's unlikely to be an issue with the `quickstart-android` repository.

Maybe try reporting the bug here:
https://developer.android.com/studio/report-bugs.html
