### ISSUE TITLE
Wrong key name: should be "isPartOf" instead of "partOf"

### ISSUE THREAD

**Issue by cybergen78** [firebase/quickstart-android#329]
The name of the key for the Indexable.Builder should be `isPartOf` instead of `partOf `according to the documentation at
https://firebase.google.com/docs/reference/app-indexing/index-builders#stickers

https://github.com/firebase/quickstart-android/blob/d224414e4bdb92e7e48c25d1a814d7a8a3904d96/app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/AppIndexingUtil.java#L107

**Comment by samtstern** [comment]
cc @kroikie

**Comment by kroikie** [comment]
@cybergen78 thanks for the issue. The incorrect string is used here. However this is no longer the recommended way of indicating that is sticker is part of a sticker pack.

[Builders](https://firebase.google.com/docs/reference/android/com/google/firebase/appindexing/builders/StickerBuilder.html#setIsPartOf(com.google.firebase.appindexing.builders.StickerPackBuilder)) are now available to avoid this type of issue. As implemented [here](https://github.com/firebase/quickstart-android/blob/master/app-indexing/app/src/main/java/com/google/samples/quickstart/app_indexing/AppIndexingUtil.java#L160)
