### ISSUE TITLE
Firebase google login not working 

### ISSUE THREAD

**Issue by rahuldevanavar91** [firebase/quickstart-android#331]
Hi,
I migrated my code from google login to firebase authentication, 
I followed following steps to whitelist the current OAuth2.0 client id for google authentication.
First, find your existing project's OAuth 2.0 client ID. To do this:

**Go to the Credentials page of the Google  console.** 

1. If the project containing the OAuth 2.0 client ID doesn't open automatically, select it from the drop down menu in the upper right corner of the page.
2. Under the OAuth 2.0 client IDs section, locate the client name containing the SHA-1 and package name you used for your Firebase project. If you're unsure which one is correct, click the name of the client to see the details.
3. When you have located the correct client name, copy the full value in the Client ID column.
4. Next, whitelist this client ID for Google as a sign in provider. To do this:

**Go to the Firebase console and select your project.**

1. Select Auth from the menu on the left.
2. Select the Sign in method tab.
3. On the Sign in method page, click on Google in the Sign in providers card.
4. Click on Enable to enable Google Sign-In
5. Expand the Whitelist client IDs from external projects option.
6. Paste your client ID from the Cloud console into the text field and click Add.
7. Add Web Client id and Secret id of existing GCM project under Web SDK configuration in Sign-In Method Page.

but still, I am getting **developer error** for google login

**Comment by rahuldevanavar91** [comment]
Any solution for this.?

**Comment by samtstern** [comment]
@rahuldevanavar91 you have not posted enough information here to debug.  When you see `developer error` that almost always means you have entered the wrong SHA1/packageName combination in the console or used the wrong web client ID in your app (or both).

**Comment by rahuldevanavar91** [comment]
@samtstern Which addition information I have to provide.
I tried to add my SHA1 to firebase console , I am getting following error
```
An OAuth2 client already exists for this package name and SHA-1 in another project.
You can omit the SHA-1 for now and read more about this situation and how to resolve i
```

**Comment by samtstern** [comment]
@rahuldevanavar91 that means you have another Google/Firebase project where you have already registered this app.  You'll need to use that project.

Closing this issue as it's now clear it's a configuration issue and not a code issue with this repository.  Please contact [Firebase support](https://firebase.google.com/support/) if you need help locating that project.

**Comment by rahuldevanavar91** [comment]
@samtstern I have existing Google project,impoterd to firebase [as mentioned here](https://support.google.com/firebase/answer/6401008?authuser=0) if not using the invite can whitelist the existing google project use that in firebase.
