### ISSUE TITLE
How to build a library project that includes 'google-services.json'

### ISSUE THREAD

**Issue by DanielByoungChul** [firebase/quickstart-android#332]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Any Android Device
  * Android OS version: Android 6.0 and above
  * Google Play Services version: com.google.android.gms:play-services:11.0.0
  * Firebase/Play Services SDK version: com.google.firebase:firebase-core:11.0.0
  
### Step 3: Describe the problem:

I want to build Android library project that includes Firebase features such as Message, which can be plugged in any Android application. 

But, in order to use Firebase it is required for application to add a 'google-services.json' file in app/ folder and app's package name should be defined from Firebase console in order to genearte this Json file as shown : 

"android_client_info": {
          **"package_name": "com.app.package.name"**
}

Issue is this package name should be same as applicationId in build.gradle file. 

build.gardle : 
defaultConfig {
        applicationId "com.app.package.name"
}

Otherwise it returns an error - 
Error:Execution failed for task ':app:processDebugGoogleServices'.
> No matching client found for package name 'com.app.lib'

I want to register an project in Firebase console with, for example, the package name(i.e. com.app.lib',  download  'google-services.json' file from Firebase and release library project that include this 'google-services.json' file to client so that clients just build client's app without modifying this 'google-services.json' file and putting it in app/ folder. 

Is there any workaround to tackle this ???

#### Steps to reproduce:

  1. This issue is related to app's configuration settings. It mentioned above.
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
"client": [
    {
      "client_info": {
        "mobilesdk_app_id": "1:111111111:android:9baaaaaaaaa",
        "android_client_info": {
          **"package_name": "com.app.package.name"**
        }
      },
      "oauth_client": [
        {
          "client_id": "xxxxxxxx.apps.googleusercontent.com",
          "client_type": 3
        }
      ],
      "api_key": [
        {
          "current_key": "xxxxxxxxx"
        }
      ],
      "services": {
        "analytics_service": {
          "status": 1
        },
        "appinvite_service": {
          "status": 1,
          "other_platform_oauth_client": []
        },
        "ads_service": {
          "status": 2
        }
      }
    }
  ]
  ```

**Comment by samtstern** [comment]
@DanielByoungChul I think you will find this guide helpful:
https://developers.google.com/android/guides/google-services-plugin

All the `google-services` plugin does is turn the `google-services.json` file into a bunch of xml `<string>` resources. 

If you're making a library module just ignore all of this, and then make sure to apply the plugin to the `app` module that depends on the library module.  Android resource merging will take care of the rest.

**Comment by samtstern** [comment]
@mmitic-lotusflare libraries should not receive FCM, apps receive FCM messages.  So you don't need to add the library's details to any JSON file, instead the library should be configured with the app's details (either at compile time or at runtime).

**Comment by mmitic-lotusflare** [comment]
@DanielByoungChul You can use `FirebaseApp.initializeApp(context, options, "<name>");`, where options reflect data from `google-services.json` (ApplicationId and ApiKey seem mandatory). However, I believe you'll need a Firebase project per application having your library, I don't think one Firebase project can cover more than one app. To get token, you can use this: `FirebaseInstanceId.getInstance(FirebaseApp.getInstance("<name>")).getToken();`

**Comment by JimmyDeemo** [comment]
I stumbled upon this issue when I ran into a similar problem. I wanted to metions that in order to so as the above poster suggested you need to remobe the line `apply plugin: 'com.google.gms.google-services` from your libraries `build.gradle` file. It is likely that this was added if you used the wizard to setup Firebase for your library.
