### ISSUE TITLE
SearchView for RecyclerView from firebase database/storage

### ISSUE THREAD

**Issue by thippesha** [firebase/quickstart-android#336]
How to implement a SearchView for RecyclerView which is retrieved pots data from firebase database
(in my case a blog app)
I am trying to implement for this app quickstart-android/database/

**Comment by thippesha** [comment]
How to implement a SearchView for RecyclerView which is retrieved pots data from firebase database 
(in my case a blog app)
I am trying to implement for this app quickstart-android/database/

**Comment by samtstern** [comment]
@thippesha Firebase does not natively support full text search so you will need to use an external solution.

Here's an example that shows how to achieve search using Cloud Functions:
https://github.com/firebase/functions-samples/blob/master/fulltext-search/README.md

**Comment by thippesha** [comment]
@samtstern 
That is much complicated and hard to implement to basic app for testing purposes 
_Just I need to sort posts by users search keywords_ 
**(ex: if user search keyword matches to blog posts title, I need to retrieve/filter those posts in new recycler view or existing recycler view)**

I'm referring to this one https://github.com/firebase/quickstart-android/tree/master/database

Some questions are here but don't know how to implement to this app

[Firebase Android SearchView by values](https://stackoverflow.com/questions/42329436/firebase-android-searchview-by-values)
and
[Firebase searching by character](https://stackoverflow.com/questions/42536273/firebase-searching-by-character)
