### ISSUE TITLE
GetInvitation resultCallback is called twice

### ISSUE THREAD

**Issue by GeorgeArgyrakis** [firebase/quickstart-android#34]
GetInvitation resultCallback is called when I tap a deep link. But after that if I force stop my app and relaunch the main activity through the launcher,  the callback is triggered again.
The first time `AppInviteReferral.hasReferral(getIntent()))` is true but when it is triggered again it is false.
This is in onCreate of MainActivity:

```
`		boolean autoLaunchDeepLink = false;`
`		AppInvite.AppInviteApi.getInvitation(mGoogleApiClient, this, autoLaunchDeepLink)`
`                .setResultCallback(`
`                        new ResultCallback<AppInviteInvitationResult>() {`
`                            @Override`
`                            public void onResult(@NonNull AppInviteInvitationResult result) {`
`                                if (result.getStatus().isSuccess()) {`
`                                    Intent intent = result.getInvitationIntent();`
`                                    Intent launchGameIntent = new Intent(MainActivity.this, GameActivity.class);`
`                                    startActivity(launchGameIntent);`
`                                } else {`
`                                    Log.d("tag", "getInvitation: no deep link found.");`
`                                }`
`                            }`
`                        });`
`    }     `
```

**Comment by samtstern** [comment]
@GeorgeArgyrakis could you try calling `AppInviteApi.getInvitation(mGoogleApiClient, null, false)` in your `GameActivity`'s onCreate method?  For certain flows that is necessary to prevent the double-trigger that you're describing.

**Comment by GeorgeArgyrakis** [comment]
@samtstern Thanks , calling AppInviteApi.getInvitation() in the second activity did the trick.
