### ISSUE TITLE
PhoneAuthentication is not working below android os version of 6

### ISSUE THREAD

**Issue by Soumya7391** [firebase/quickstart-android#344]
Hey there,

The phone authentication is working for only 6 and above. I need it to support to all the other version. Please let me know what needs to be done. Its really urgent.

**Comment by palanivelayudam** [comment]
is it so.?? i am also need to do dat.

**Comment by samtstern** [comment]
@Soumya7391 we do not have a requirement that you must be on Android 6, so I suspect this is an issue with your device or carrier.  Please contact Firebase support if you're still seeing this.
