### ISSUE TITLE
Error:Could not find com.google.gms:google-services:3.0.0.

### ISSUE THREAD

**Issue by kjhatis** [firebase/quickstart-android#351]
I followed the steps from android studio, also checked instruction on firebase.google.com. but even after this i am getting this error.

Error:Could not find com.google.gms:google-services:3.0.0.
Searched in the following locations:
    file:/F:/AndroidStudio/gradle/m2repository/com/google/gms/google-services/3.0.0/google-services-3.0.0.pom
    file:/F:/AndroidStudio/gradle/m2repository/com/google/gms/google-services/3.0.0/google-services-3.0.0.jar
Required by:
    project :

**Comment by samtstern** [comment]
@kjhatis can you paste the contents of your `build.gradle` file here?  The one that contains the `google-services` plugin.

**Comment by kjhatis** [comment]
Build.gradle: Project
`buildscript {
    dependencies {
        classpath 'com.google.gms:google-services:3.0.0'
    }
}`

Build.gradle: Application

`buildscript {
    repositories {
        jcenter()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
    }
}

apply plugin: 'com.android.application'

repositories {
    jcenter()
    maven {
        url 'https://maven.google.com'
    }
}

dependencies {
    compile 'com.android.support:support-v4:26.1.0'
    compile 'com.android.support:gridlayout-v7:26.1.0'
    compile 'com.android.support:cardview-v7:26.1.0'
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
}

// The sample build uses multiple directories to
// keep boilerplate and common code separate from
// the main sample code.
List<String> dirs = [
        'main',     // main sample code; look here for the interesting stuff.
        'common',   // components that are reused by multiple samples
        'template'] // boilerplate code that is generated by the sample template process

android {

    compileSdkVersion 26

    buildToolsVersion "26.0.1"

    defaultConfig {
        minSdkVersion 14
        targetSdkVersion 22
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }

    sourceSets {
        main {
            dirs.each { dir ->
                java.srcDirs "src/${dir}/java"
                res.srcDirs "src/${dir}/res"
            }
        }
        androidTest.setRoot('tests')
        androidTest.java.srcDirs = ['tests/src']

    }

}

apply plugin: 'com.google.gms.google-services'`

**Comment by samtstern** [comment]
@kjhatis Try adding this to your project-level `build.gradle`:

```
repositories {
        jcenter()
}
```

**Comment by kjhatis** [comment]
Fixed It By Using : 

`buildscript {
    dependencies {
        classpath 'com.google.gms:google-services:3.1.0'
    }
}`
