### ISSUE TITLE
Delay in Verfication email delivery.

### ISSUE THREAD

**Issue by jombie** [firebase/quickstart-android#356]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Redmi Note 4
  * Android OS version: Nougat
  * Google Play Services version: 3.1.0
  * Firebase/Play Services SDK version: 11.2.2
  
### Step 3: Describe the problem:
There is subsequent delay in receiving verification email and password reset email when mail is sent using the firebase android sdk for EmailAuthFlow. In some cases it takes hour to receive email. Previously this problem was not there started noticing the delay in past week.

#### Steps to reproduce:

  1. Register using email and password
  2. Send email verification mail.
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
Subsequent delay in delivery of mail.
  
#### Expected Results:
Since these are user registration mails should be fast enough that user can verify there account as on when created.

Can this happen due to load on firebase email servers? Is there way to send the email using our services.

**Comment by samtstern** [comment]
@jombie thanks for filing this and for taking the time to fill out the entire issue template.

Unfortunately an issue like this is almost definitely unrelated to the code in this `quickstart-android` repository and probably not even related to the code in the Firebase Android SDK.

Please contact Firebase Support, who can better help you troubleshoot this issue:
https://firebase.google.com/support/

**Comment by jombie** [comment]
Thanks for the update.
