### ISSUE TITLE
Phone authentication code not delivered to the mobile number while tesing without any sim card in device and the sim is on another device

### ISSUE THREAD

**Issue by deepaksime** [firebase/quickstart-android#357]
### Step 2: Describe your environment

  * Android device: Redmi 4
  * Android OS version: 6.0.1
  * Google Play Services version: 11.0.4
  * Firebase/Play Services SDK version: 11.0.4
  
### Step 3: Describe the problem: 
On implementing firebase phone authentication if there is no sim card present on the testing device and the number entered is on other device, it calls onSent() , but verification code is not delivered to the number. But if  you insert a sim(valid/invalid) on the test device and try phone auth, then it delivers auth code to the number which is in another device.

#### Steps to reproduce:

  1. Remove all sims in android device.
  2. Test phone auth with a number inserted in another device.
  3. It will call onSent() but not deliver sms to the entered number.
  4. Insert an invalid/valid sim to test device, then try phone auth with number in another device

**Comment by samtstern** [comment]
@deepaksime thank you for reporting this, and I apologize for the delayed response.  This sounds like an interesting issue, but not one that we can help to debug here on the `quickstart-android` repo.

Could you please contact [Firebase support](https://firebase.google.com/support/) if you are still experiencing this issue?
