### ISSUE TITLE
Custom events not shown on console

### ISSUE THREAD

**Issue by dj-4war** [firebase/quickstart-android#359]
We are facing couple of issues with the data set on firebase console when we run the sample. 

1. mFirebaseAnalytics.setUserProperty("favorite_food", mFavoriteFood);

We are not seeing above Property in User Property tab in firebase console below is the screenshot. 

<img width="680" alt="screen shot 2017-10-25 at 10 11 40 am" src="https://user-images.githubusercontent.com/2337160/31980941-9241dd84-b96d-11e7-805d-ee42fce7d639.png">

2. The other parameters such as  "favorite_food",  "share_image" , "select_content" are visible in Events tab but the custom data is not visible.

Here is the screenshot. 

<img width="1005" alt="screen shot 2017-10-25 at 10 33 55 am" src="https://user-images.githubusercontent.com/2337160/31981321-1b953296-b970-11e7-8c19-64b907c8b17f.png">

Please let us know if there is any other view to look at the custom data, even we tried to add parameter for event data but still now use.

**Comment by kroikie** [comment]
Hi @dj-4war how long ago have you added the custom properties?

**Comment by dj-4war** [comment]
48 hrs.

**Comment by kroikie** [comment]
Have you manually added the user property to the console? Also are you using DebugView to see near real-time analytics events?

**Comment by dj-4war** [comment]
No, we just ran the sample where sample has customer events added programmatically , we would like to see these events on console.

**Comment by kroikie** [comment]
sorry for the delay, you must add the user properties to the console manually for them to show up.

**Comment by samtstern** [comment]
It's been a while since the last non-Googler response so closing this issue.  @dj-4war feel free to open a new one or comment again here if you're still having trouble.

**Comment by tarun4279** [comment]
I added the user property on the console and added the property and logged an event just after setting that property. There is no update yet on console. How much time it takes to update the results.

Some logs
D/FA: Setting user property (FE): Location, Delhi
Logging event (FE): SET_PROPERTY, Bundle[{item_name=sampleItem345, firebase_event_origin(_o)=app, content_type=SampleItem, item_id=sampleId123}]

**Comment by mochadwi** [comment]
i also have this problem.... the firebase logevent dosent found in the consol firebase. here the code

```
fun logEvents(
        featureName: String,
        category: String
) {
    firebaseAnalytics.logEvent(
            FirebaseAnalytics.Event.VIEW_ITEM,
            bundleOf(
                    FirebaseAnalytics.Param.ITEM_NAME bundleTo featureName,
                    FirebaseAnalytics.Param.ITEM_CATEGORY bundleTo category
            )
    )
}

```

**Comment by NiranjanShirke** [comment]
I am also not able to see custom events on console . please help if anybody have any idea.

**Comment by OlgaFlower** [comment]
I have the same problem! Is any solution??
P.S. view_item is tracked as "screen_view"
