### ISSUE TITLE
Does the crash reporting plugin works with Gradle plugin 3.0?

### ISSUE THREAD

**Issue by b95505017** [firebase/quickstart-android#361]
I still encounter the [known issue](https://firebase.google.com/docs/crash/android#known_issue) with the stable plugin (3.0).
Do I still have to use the crash plugin `1.1.0-alpha1` with Gradle plugin 3.0?

**Comment by kroikie** [comment]
Yes, we are working on a fix.

**Comment by kroikie** [comment]
@b95505017 this issue has been resolved. If you are using plugin 3.0 then use firebase-plugin:1.1.2

**Comment by b95505017** [comment]
@kroikie Sounds great! I'll try it out!

**Comment by b95505017** [comment]
@kroikie I found a new issue with `firebase-plugin:1.1.2`
https://github.com/firebase/quickstart-android/issues/366
