### ISSUE TITLE
Can't add performance SDK using 'implementation' in Gradle

### ISSUE THREAD

**Issue by b95505017** [firebase/quickstart-android#366]
I use `classpath 'com.google.firebase:firebase-plugins:1.1.2'` then the Gradle shows the following error:
```
Error:To use the Firebase Performance Plugin, the Firebase Performance Monitoring SDK must be added to the app's build.gradle. Please add compile 'com.google.firebase:firebase-perf:VERSION_NUMBER_GREATER_THAN_OR_EQUAL_TO_11.0.4' to the app's build.gradle.
```
But my dependencies already has
```
implementation 'com.google.firebase:firebase-perf:11.4.2'
```

Finally I found that if I change `implementation` back to `compile` then Gradle sync success.
Previous firebase plugin works with `implementation`.

**Comment by kroikie** [comment]
This has been resolved please use `15.0.0`. Feel free to open a new issue if you are still having problems.
