### ISSUE TITLE
Not able to lauch the app

### ISSUE THREAD

**Issue by hegebharat** [firebase/quickstart-android#367]
I am able to generate the apk.  But app is crashing. I debug it and found after executing the mAuth = FirebaseAuth.getInstance(); app is crashing. I mean not able to launch the app.
I used android version 11.7.44
How do i solve it?
Thanks for the response

**Comment by samtstern** [comment]
@hegebharat we need more information to debug.  Please post at least some of the logs containing the error message and the code that makes it happen.

**Comment by samtstern** [comment]
It's been a while since the last response so I am closing this issue.  If you run into this again just file a new issue!
