### ISSUE TITLE
Tutorial for Dynamic links usage in Authentication

### ISSUE THREAD

**Issue by ancientloregames** [firebase/quickstart-android#375]
The topic on how to use the FDL for the authentication (sendVerificationEmail and sendPasswordResetEmail, at least) is not fully explained in the Firebase Docs. It took me some time to figure it out. It will be nice to have an example here for the newbies.
Also, I haven't been able to get the account actually verified. After opening my app via DL in the email, user.isEmailVerified() still returns false. The code for checking it out looks like this:
```
FirebaseDynamicLinks.getInstance().getDynamicLink(getIntent()).addOnSuccessListener(...
user.reload().addOnCompleteListener(task -> if (user.isEmailVerified())...)
```
Help will be most welcome.

**Comment by samtstern** [comment]
@ancientloregames thanks for the note!  I have forwarded this request on to the doc writers for Authentication and FDL, going to close it here but we will try and improve this documentation for you (and others).
