### ISSUE TITLE
Unable to retrieve one of the Nested data from Firebase Realtime Database

### ISSUE THREAD

**Issue by SkyTreasure** [firebase/quickstart-android#377]
### Step 2: Describe your environment
 
  * Google Play Services version: 11.6.0
  * Firebase/Play Services SDK version: 11.6.0
  *  Kotlin
  
### Step 3: Describe the problem:
I have the following structure in firebase. 
 
[![enter image description here][2]][2]

In order to retrieve the data i am using the following code-

     mFirebaseDatabaseReference = FirebaseDatabase.getInstance().reference.child("androidchat").child("users").child("uid-6")

    mFirebaseDatabaseReference?.addValueEventListener(object : ValueEventListener {
        override fun onCancelled(p0: DatabaseError?) {
            callback?.handleData(false, requestType)
        }

        override fun onDataChange(p0: DataSnapshot?) {
            var userModel: UserModel? = p0?.getValue<UserModel>(UserModel::class.java)

            }
        }
    })

When onDataChange() is called p0 contains all other data except **group** data. 

Here's my dataclass UserModel-

    data class UserModel(var uid: String? = null,
                     var name: String? = null,
                     var image_url: String? = null,
                     var user_location: String? = null,
                     var email: String? = null,
                     var group: MutableMap<String, Boolean> = mutableMapOf(),
                     var deviceIds : MutableMap<String,String> = mutableMapOf(),
                     var online: Boolean? = null,
                     var unread_group_count: Int? = null,
                     var last_seen_online: String? = null,
                     var last_seen_message_timestamp: String? = null,
                     var admin: Boolean? = null,
                     var delete_till: String? = null,
                     var active: Boolean? = null)

Any idea why that data is not coming? here is the screen shot of the data , user has many groups but it shows 0 groups-
[![enter image description here][3]][3]

Here is the datasnapshot which i received-

    DataSnapshot { key = uid-6, value = {deviceIds={cc2583f5a2c92eff=dafO8mlj7aa:APA91bETLdet4b-oUnyYAe-GU68BuI4Sw1iT0jGCkUZdjes-ybA_9ZgHtZO-AoApVXQL9NfatyCgSfPSO74fsCUMY-6AY_8826D5AROVkFlQSUs8VKO5_FswoQceTxZ }, last_seen_message_timestamp=1510664398869, name=Akash Nidhi, uid=uid-6, online=true, user_location=USA-OTHERS, image_url=https://s3.ap-south-1.amazonaws.com/employees/images/150528664259b8d9f29c385.jpeg} }

There's no group inside the datasnapshot!.

I tried adding this line mFirebaseDatabaseReference?.keepSynced(false). It worked few times yesterday and its not working now!

  [1]: https://i.stack.imgur.com/1185a.png
  [2]: https://i.stack.imgur.com/zshMd.png
  [3]: https://i.stack.imgur.com/DbBw3.png

**Comment by samtstern** [comment]
Ok so the issue here is that the `DataSnapshot` does not contain the `group` information, not an issue with mapping the snapshot to your `data` class right?

Could you make sure of this by calling `hasChild("group")` on the snapshot and making sure the data is not there?

**Comment by SkyTreasure** [comment]
I was using this code at one place, after removing this it started working. 
```
` /*   mFirebaseDatabaseReference = FirebaseDatabase.getInstance().reference.child("androidchat").child("users").child(uid)
                   mFirebaseDatabaseReference?.runTransaction(object : Transaction.Handler {
                       override fun onComplete(p0: DatabaseError?, p1: Boolean, p2: DataSnapshot?) {
                           var userModel: UserModel? = p2?.getValue<UserModel>(UserModel::class.java)
                           if(userModel!=null){
                               sCurrentUser=userModel;
                               SharedPrefManager.getInstance(BaseActivity.context!!).savePreferences(PrefConstants.USER_DATA, Gson().toJson(sCurrentUser))
                               callback?.handleData(true, requestType)
                           }

                       }

                       override fun doTransaction(p0: MutableData?): Transaction.Result {

                           return Transaction.success(p0)
                       }

                   })*/`
```

**Comment by samtstern** [comment]
@SkyTreasure glad it's working for you now!
