### ISSUE TITLE
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found

### ISSUE THREAD

**Issue by luizfranca** [firebase/quickstart-android#384]
### Step 2: Describe your environment

  * Android device: Emulator Nexus 5X
  * Android OS version: 8 (API 24)
  * Google Play Services version: 11.7.43
  * Firebase/Play Services SDK version: 10.0.1
  I have enabled provider email/password on firebase.google.com.

### Step 3: Describe the problem:

Can’t get firebase auth to work. 

#### Steps to reproduce:

1. Start the app

#### Observed Results:

Whenever I start the app I get this:

`11-29 06:17:05.212 2779-2779/com.chocosoda.h_plus D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
11-29 06:17:05.228 2779-2801/com.chocosoda.h_plus W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found`
  
#### Expected Results:

Be able to register a user.
  
#### Relevant Code:

```
import com.google.firebase.auth.AuthResult;
import com.google.firebase.auth.FirebaseAuth;

public class LoginActivity extends AppCompatActivity {

    private Button signup;
    private EditText emailText;
    private EditText passwordText;

    private FirebaseAuth firebaseAuth;
    private LoginActivity context;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_login);

        signup = (Button) findViewById(R.id.sign_up);
        emailText = (EditText) findViewById(R.id.email);
        passwordText = (EditText) findViewById(R.id.password);

        firebaseAuth = FirebaseAuth.getInstance();
        context = this;

        signup.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                final String email = emailText.getText().toString();
                final String password = passwordText.getText().toString();

                if (email.isEmpty() || password.isEmpty()) {
                    Toast.makeText(context, "Please enter the email and password", Toast.LENGTH_SHORT).show();
                    return;
                }

                firebaseAuth.createUserWithEmailAndPassword(email, password)
                        .addOnCompleteListener(context, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        if (task.isSuccessful()) {
                            Toast.makeText(context, "You were successfully registered", Toast.LENGTH_SHORT).show();
                        } else {
                            Toast.makeText(context, "Your registration could not be completed", Toast.LENGTH_SHORT).show();
                        }
                        emailText.setText("");
                        passwordText.setText("");
                    }
                });
            }
        });
    }
}
`

**Comment by samtstern** [comment]
@luizfranca apologies for the very late response.  If you're still having this problem, could you show the error message that you get?  I think the `DynamiteModule` log message is unimportant but if you're getting an error from `createUserWithEmailAndPassword` I'd love to see what `task.getException()` contains.

**Comment by luizfranca** [comment]
Hi @samtstern, thanks for replying. It is working now. It seems to be a warning and I was getting another error. The log message is still there, but I'm ignoring it now, as it is working.

**Comment by samtstern** [comment]
@luizfranca thanks for following up!
