### ISSUE TITLE
Firestore offline -> No writes visible

### ISSUE THREAD

**Issue by Seikilos** [firebase/quickstart-android#386]
**Environment**

  * Android device: Emulator
  * Android OS version: 7.0
  * Google Play Services version: 11.7.43
  * Firebase/Play Services SDK version: 11.6.0
  
**Describe the problem:**

I modified the firebase quickstart for firestore and added persistence to the database:

```
        // Firestore
        mFirestore = FirebaseFirestore.getInstance();

        FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
                .setPersistenceEnabled(true)
                .build();
        mFirestore.setFirestoreSettings(settings);
```

I can open the app, I can generate data while online and then issue an `ipconfig /release` to drop my network connection. I can restart the app, it appears to use the offline data as I see cached data.

But I cannot write to it. When I add a review to any restaurant it does not get added. The only lines added to the log are:
```
12-01 19:27:04.663 26834-26855/com.google.firebase.example.fireeats D/EGL_emulation: eglMakeCurrent: 0x97d263c0: ver 3 1 (tinfo 0x97ee6630)
12-01 19:27:04.706 26834-26855/com.google.firebase.example.fireeats D/EGL_emulation: eglMakeCurrent: 0x97d263c0: ver 3 1 (tinfo 0x97ee6630)
12-01 19:27:04.707 26834-26834/com.google.firebase.example.fireeats W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
```

The [docs ](https://firebase.google.com/docs/firestore/manage-data/enable-offline?authuser=0) say I do not need to change anything to make writes etc.

I've debugged the `addRating` code and neither the `addOnSuccessListener`  nor the `addOnFailureListener` are triggered when I am offline. This how ever changes after a couple of minutes of staying offline (I suppose a timeout?), then each `addRating` gets immediately directed to `addOnFailureListener` which causes a 

> Add rating failed

in the log and in the Snackbar.

The exception associated with this failure is an `com.google.firebase.firestore.FirebaseFirestoreException: UNAVAILABLE`

There seems to be a difference between the docs and the actual observed behaviour.

**Comment by samtstern** [comment]
@Seikilos this sounds like the intended behavior, but there may be a few points of confusion:

- Persistence is enabled by default on Android, so you shouldn't need to modify that setting.
- Writes take effect immediately on Android, which means they are reflected by subsequent reads.  However the `onComplete` listener will not fire until the write has actually propagated to the server.
- The `addRating` function uses a transaction which does not work offline.  Transactions have some built-in retry attempts which is probably why you see an `onFailure` call after some delay.

**Comment by Xavier-Josephh** [comment]
Hi,

I came across the above same issue, from the comments mentioned by @samtstern  I got to know that addRating function should use a transaction which works offline.

Any code/reference for this? like which which transaction/function to be used to write the data offline?

Thanks.
