### ISSUE TITLE
Firebase not available in Iran

### ISSUE THREAD

**Issue by opus1269** [firebase/quickstart-android#389]
* Firebase/Play Services SDK version: 11.6.0
  
Is this still a legal requirement or has the policy just not been updated?

`Exception caught: Sign-in failed. Please try again later: Sign-in to firebase failed com.google.firebase.FirebaseException: An internal error has occurred. [ This service is not available from Iran. If you believe the country of origin was incorrectly identified, please report it at https://support.google.com/websearch/contact/ip. ] at com.google.android.gms.internal.zzdkj.zzak(Unknown Source) at com.google.android.gms.internal.zzdjl.zza(Unknown Source) at com.google.android.gms.internal.zzdku.zzal(Unknown Source) at com.google.android.gms.internal.zzdkw.onFailure(Unknown Source) at com.google.android.gms.internal.zzdkl.onTransact(Unknown Source) at android.os.Binder.execTransact(Binder.java:404) at dalvik.system.NativeStart.run(Native Method)`

**Comment by samtstern** [comment]
@opus1269 we can't help with this sort of request on Github, issues on this repository should be related to the code in the repo or the SDK.

If Firebase is not available in your country and you believe it should be, consider filing a [feature request](https://firebase.google.com/support/contact/bugs-features/) with Firebase Support.
