### ISSUE TITLE
app indexing

### ISSUE THREAD

**Issue by lu769257351** [firebase/quickstart-android#390]
你好，我在使用APP Indxing时想控制 Indexable noteToIndex = new Indexable.Builder()
                    .setName("audi is name")
                    .setDescription("audi is description")
                    //.setText("audi")
                    .setUrl("mystickers://sticker/audi")
                    .setImage(imageUrl)             
                   .setKeywords("bmw","Aston ").setDescription("bmw Aston")
                    .put("keywords","Aston","bmw")
                    .build();
里面的image 大小，但是我没有找到对应的API，我使用的图片最后结果都是显示不全，有被截取，请问我应该怎么办。

**Comment by samtstern** [comment]
@lu769257351 I apologize but we can only respond to issues filed in English on this repository.  Please try asking this question on StackOverflow or another forum.
