### ISSUE TITLE
Not getting Notifications if app is closed via swipe

### ISSUE THREAD

**Issue by rajeshjakhar1092** [firebase/quickstart-android#391]
I have oneplus 3 ,I am getting notifications when app is open or is in background but when i swipe off it does not get fcm notifications.

Is it my device or what?

**Comment by rajeshjakhar1092** [comment]
It is because of DOZE mode and battery optimization,you just have to turn off battery optimization for all apps or particular app.

Settings>> Battery >> battery Optimization >> find your app >> select >> if optimized click on don't optimize >> try pushing notification.. 
Hope this helps..
Enjoy :) :)

**Comment by samtstern** [comment]
@rajeshjakhar1092 there are a number of existing issues on this topic, most notably #4 and #89.  Please consult those threads.

**Comment by daveabes** [comment]
Sorry battery optimization did not resolve the issue for me.
