### ISSUE TITLE
not able to signup with email

### ISSUE THREAD

**Issue by RajuSE** [firebase/quickstart-android#395]
I've followed project [database](https://github.com/firebase/quickstart-android/blob/master/database/README.md)
I am not getting any response & not able to signup with email.

Console :
>google Play services out of date.  Requires 11910000 but found 11055480

**Comment by samtstern** [comment]
@RajuSE that means you need to install a newer version of Google Play services on the device you're using. If you're using a real device this will happen automatically, if you're using an emulator just update the image and create a new emulator or use one of the images with the Play Store on it.
