### ISSUE TITLE
Error:Unknown host 'services.gradle.org'. You may need to adjust the proxy settings in Gradle. Enable Gradle 'offline mode' and sync project.Learn about configuring HTTP proxies in Gradle

### ISSUE THREAD

**Issue by Ankush10** [firebase/quickstart-android#399]
after downloading and importing project qickstart-android .Android says Failed to sync Gradle project 'quickstart-android-master'.

I know i m doing some mistake But i don't know where i m doing the mistake.Please tell me how to fix it

**Comment by samtstern** [comment]
@Ankush10 this is not an issue with the quickstart but has something to do with your system network configuration.  I would suggest consulting StackOverflow or another forum.
