### ISSUE TITLE
Failed to load module descriptor class

### ISSUE THREAD

**Issue by mdavila** [firebase/quickstart-android#40]
There seems to be problem with the app or perhaps I am running it in the wrong way.  I am able to start the app. However, if I tap on "Sign in" the app does not respond, but the Android Monitor shows the following error:

![image](https://cloud.githubusercontent.com/assets/3312235/15849654/3cd1c4d8-2c59-11e6-9015-027f89e3f651.png)

06-07 02:18:39.017 6396-6396/com.google.firebase.quickstart.firebasestorage E/Storage#MainActivity: signInAnonymously:FAILURE
                                                                                                    com.google.firebase.FirebaseException: An internal error has occured. [ OPERATION_NOT_ALLOWED ]
                                                                                                        at com.google.android.gms.internal.zzacq.zzbN(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzacn$zzg.zza(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzacy.zzbO(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzacy$zza.onFailure(Unknown Source)
                                                                                                        at com.google.android.gms.internal.zzact$zza.onTransact(Unknown Source)
                                                                                                        at android.os.Binder.execTransact(Binder.java:453)
06-07 02:18:47.052 6396-6426/com.google.firebase.quickstart.firebasestorage I/FA: Tag Manager is not found and thus will not be used
06-07 02:18:48.353 6396-6413/com.google.firebase.quickstart.firebasestorage E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.google.firebase.quickstart.firebasestorage-1/base.apk"],nativeLibraryDirectories=[/data/app/com.google.firebase.quickstart.firebasestorage-1/lib/arm, /vendor/lib, /system/lib]]

What could be missing?

**Comment by samtstern** [comment]
@mdavila can you confirm a few things:

  * What kind of device/emulator are you running this on?  Does it have Google Play Services `9.0.80` or higher?
  * When did you clone the code for this sample?  Is it using the `9.0.2` SDKs?

**Comment by mdavila** [comment]
Hi @samtstern I am using my mobile phone.  It is a Nexus 5 with Android Marshmallow 6.0.1.  

The Android SDK manager app has Google Play Services 30:

![image](https://cloud.githubusercontent.com/assets/3312235/15878880/5afddb96-2ce4-11e6-81b9-8c413476bd13.png)

I cloned the files on 27-may-2016. It seems that the cloned files are using the SDK version 9.0.0.  I am going to clone the files again.  It seems that there is a newer SDK.

Thanks,

**Comment by mdavila** [comment]
@samtstern I just cloned the files and the dependencies show the new SDK version:

compile 'com.google.firebase:firebase-auth:9.0.2'
compile 'com.google.firebase:firebase-storage:9.0.2'

However, the same error is still showing and when I tap on "Sign in" the app doesn't do anything:

06-07 19:31:33.057 29354-29354/com.google.firebase.quickstart.firebasestorage E/Storage#MainActivity: signInAnonymously:FAILURE
                                                                                                      com.google.firebase.FirebaseException: An internal error has occured. [ OPERATION_NOT_ALLOWED ]
                                                                                                          at com.google.android.gms.internal.zzacq.zzbN(Unknown Source)
                                                                                                          at com.google.android.gms.internal.zzacn$zzg.zza(Unknown Source)
                                                                                                          at com.google.android.gms.internal.zzacy.zzbO(Unknown Source)
                                                                                                          at com.google.android.gms.internal.zzacy$zza.onFailure(Unknown Source)
                                                                                                          at com.google.android.gms.internal.zzact$zza.onTransact(Unknown Source)
                                                                                                          at android.os.Binder.execTransact(Binder.java:453)
06-07 19:31:42.478 29354-29876/com.google.firebase.quickstart.firebasestorage E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.google.firebase.quickstart.firebasestorage-2/base.apk"],nativeLibraryDirectories=[/data/app/com.google.firebase.quickstart.firebasestorage-2/lib/arm, /vendor/lib, /system/lib]]


Did I miss anything? I am only importing the "storage" folder from this repository into into Android Studio 2.1.2.

**Comment by mdavila** [comment]
@samtstern I have been able to solve the problem. I had to enable anonymous login from the Firebase console.

**Comment by samtstern** [comment]
@mdavila glad you solved your error!

For future people who may find this issue, enabling anonymous auth in the Firebase console fixes the `OPERATION_NOT_ALLOWED` error.  The `ModuleDescriptor` error was likely transient and unrelated.

**Comment by anuj1708** [comment]
Here is the video and stack trace. After the Accounts on my phone are shown I choose one. But Then I just come back to the original Screen and no account added in the firebase console
link for video : https://drive.google.com/file/d/0B8tYKC1-UERHZlF2Q0dyRURaZEk/view?usp=sharing

Stack trace : 

06-12 13:16:05.915 29115-29145/com.google.firebase.quickstart.auth E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.google.firebase.quickstart.auth-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
06-12 13:16:05.926 29115-29115/com.google.firebase.quickstart.auth D/FirebaseApp: Initialized class com.google.firebase.auth.FirebaseAuth.
06-12 13:16:05.938 29115-29145/com.google.firebase.quickstart.auth V/GoogleSignatureVerifier: com.google.android.gms signature not valid.  Found: 
                                                                                              MIIEQzCCAyugAwIBAgIJAMLgh0ZkSjCNMA0GCSqGSIb3DQEBBAUAMHQxCzAJBgNVBAYTAlVTMRMw
                                                                                              EQYDVQQIEwpDYWxpZm9ybmlhMRYwFAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29n
                                                                                              bGUgSW5jLjEQMA4GA1UECxMHQW5kcm9pZDEQMA4GA1UEAxMHQW5kcm9pZDAeFw0wODA4MjEyMzEz
                                                                                              MzRaFw0zNjAxMDcyMzEzMzRaMHQxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlhMRYw
                                                                                              FAYDVQQHEw1Nb3VudGFpbiBWaWV3MRQwEgYDVQQKEwtHb29nbGUgSW5jLjEQMA4GA1UECxMHQW5k
                                                                                              cm9pZDEQMA4GA1UEAxMHQW5kcm9pZDCCASAwDQYJKoZIhvcNAQEBBQADggENADCCAQgCggEBAKtW
                                                                                              LgDYO6IIrgqWbxJOKdoR8qtW0I9Y4sypEwPpt1TTcvZApxsdyxMJZ2JORland2qSGT2y5b+3JKke
                                                                                              dxiLDmpHpDsz2WCbdxgxRczfey5YZnTJ4VZbH0xqWVW/8lGmPav5xVwnIiJS6HXk+BVKZF+JcWjA
                                                                                              sb/GEuq/eFdpuzSqeYTcfi6idkyugwfYwXFU1+5fZKUaRKYCwkkFQVfcAs1fXA5V+++FGfvjJ/Cx
                                                                                              URaSxaBvGdGDhfXE28LWuT9ozCl5xw4Yq5OGazvV24mZVSoOO0yZ31j7kYvtwYK6NeADwbSxDdJE
                                                                                              qO4k//0zOHKrUiGYXtqw/A0LFFtqoZKFjnkCAQOjgdkwgdYwHQYDVR0OBBYEFMd9jMIhF1Ylmn/T
                                                                                              gt9r45jk14alMIGmBgNVHSMEgZ4wgZuAFMd9jMIhF1Ylmn/Tgt9r45jk14aloXikdjB0MQswCQYD
                                                                                              VQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNTW91bnRhaW4gVmlldzEUMBIG
                                                                                              A1UEChMLR29vZ2xlIEluYy4xEDAOBgNVBAsTB0FuZHJvaWQxEDAOBgNVBAMTB0FuZHJvaWSCCQDC
                                                                                              4IdGZEowjTAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBAUAA4IBAQBt0lLO74UwLDYKqs6Tm8/y
                                                                                              zKkEu116FmH4rkaymUIE0P9KaMftGlMexFlaYjzmB2OxZyl6euNXEsQH8gjwyxCUKRJNexBiGcCE
                                                                                              yj6z+a1fuHHvkiaai+KL8W1EyNmgjmyy8AW7P+LLlkR+ho5zEHatRbM/YAnqGcFh5iZBqpknHf1S
                                                                                              KMXFh4dd239FJ1jWYfbMDMy3NS5CTMQ2XFI1MvcyUTdZPErjQfTbQe3aDQsQcafEQPD+nqActifK
                                                                                              Z0Np0IS9L9kR/wbNvyz6ENwPiTrjV2KRkEjH78ZMcUQXg0L3BYHJ3lc69Vs5Ddf9uUGGMYldX3Wf
                                                                                              MBEmh/9iFBDAaTCK
06-12 13:16:05.953 29115-29115/com.google.firebase.quickstart.auth D/FirebaseApp: Initialized class com.google.firebase.iid.FirebaseInstanceId.
06-12 13:16:05.954 29115-29145/com.google.firebase.quickstart.auth E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.google.firebase.quickstart.auth-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
06-12 13:16:05.958 29115-29115/com.google.firebase.quickstart.auth D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
06-12 13:16:05.976 29115-29145/com.google.firebase.quickstart.auth W/ResourcesManager: Asset path '/system/framework/com.android.media.remotedisplay.jar' does not exist or contains no resources.
06-12 13:16:05.977 29115-29145/com.google.firebase.quickstart.auth W/ResourcesManager: Asset path '/system/framework/com.android.location.provider.jar' does not exist or contains no resources.
06-12 13:16:06.045 29115-29145/com.google.firebase.quickstart.auth D/ChimeraCfgMgr: Reading stored module config
06-12 13:16:06.066 29115-29123/com.google.firebase.quickstart.auth W/art: Suspending all threads took: 8.247ms
06-12 13:16:06.093 29115-29128/com.google.firebase.quickstart.auth I/art: Background sticky concurrent mark sweep GC freed 10543(1410KB) AllocSpace objects, 39(591KB) LOS objects, 9% free, 7MB/8MB, paused 9.110ms total 60.616ms
06-12 13:16:06.112 29115-29115/com.google.firebase.quickstart.auth I/FA: App measurement is starting up, version: 9080
06-12 13:16:06.112 29115-29115/com.google.firebase.quickstart.auth I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
06-12 13:16:06.236 29115-29115/com.google.firebase.quickstart.auth D/FirebaseApp: Initialized class com.google.android.gms.measurement.AppMeasurement.

**Comment by abredykhin** [comment]
I see the same error in logcat, but I don't even use Auth module of Firebase

**Comment by HarshGrandeur** [comment]
I am facing the same issue, cant work it out.I am using marshmallow with play services verison 9.2. Can anybody help me out. I am getting this error.
W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found

**Comment by calistus** [comment]
I am also facing the same issue since Migrated to the latest Firebase console.
Has anybody been able to solve this issue?
@HarshGrandeur @abredykhin  @mdavila  Have you been able to resolve this issue?

**Comment by monusurana** [comment]
I'm using Firebase version 9.4.0 and I've Google Play Services version 9.4.52 on my emulator.  

I'm facing the same issue when trying to login, I see these failures in logcat logs:
`08-26 05:28:17.704 6020-6033/com.example.auth W/DynamiteModule: Local module descriptor class for com.google.firebase.auth not found.`

I also enabled Firebase logging I see these WebSocket failures. 

```
08-26 05:27:20.514 6020-6061/com.example.auth D/WebSocket: ws_0 - |IO Error|
08-26 05:27:20.535 6020-6061/com.example.auth D/WebSocket: ws_0 - closed
08-26 05:27:20.577 6020-6061/com.example.auth D/WebSocket: ws_0 - had an error
    byk: IO Exception
         byo.a(:com.google.android.gms.DynamiteModulesC:148)
         at byp.run(:com.google.android.gms.DynamiteModulesC:1022)
         at java.lang.Thread.run(Thread.java:818)
    Caused by: java.net.SocketException: Socket is closed
         at com.android.org.conscrypt.OpenSSLSocketImpl.checkOpen(OpenSSLSocketImpl.java:247)
         at com.android.org.conscrypt.OpenSSLSocketImpl.-wrap0(OpenSSLSocketImpl.java)
         at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:756)
         at java.nio.channels.Channels$OutputStreamChannel.write(Channels.java:348)
         at byo.b(:com.google.android.gms.DynamiteModulesC:127)
         at byo.a(:com.google.android.gms.DynamiteModulesC:145)
         at byp.run(:com.google.android.gms.DynamiteModulesC:1022) 
         at java.lang.Thread.run(Thread.java:818) 
08-26 05:27:20.580 6020-6061/com.example.auth D/WebSocket: ws_0 - |IO Exception|
```

**Comment by ombhurbhuva** [comment]
I had similar problem. I fixed it by removing Google account from Android settings. So next when I tried to signin from the app, everything went fine...!
