### ISSUE TITLE
Application crashes while Google Sign in for api level 23

### ISSUE THREAD

**Issue by banerjeedeba** [firebase/quickstart-android#400]
[api23_issue_log_20170102.txt](https://github.com/firebase/quickstart-android/files/1598936/api23_issue_log_20170102.txt)
[api24_no_issue_log_20170102.txt](https://github.com/firebase/quickstart-android/files/1598937/api24_no_issue_log_20170102.txt)

Describe your environment

  * Android device: Motorola X Pure Edition
  * Android OS version: 6.0
  * Google Play Services version: 11.8.0
  * Firebase/Play Services SDK version: 11.8.0
  
### Step 3: Describe the problem:
i am using
implementation 'com.google.firebase:firebase-auth:11.8.0'
implementation 'com.google.firebase:firebase-messaging:11.8.0'
implementation 'com.firebase:firebase-jobdispatcher:0.6.0'
implementation 'com.google.android.gms:play-services-auth:11.8.0'

google sign in working fine when i am testing in an emulator with api 24 but its crashing when i am testing in an emulator with api 23.

I have also tested in two Moto X pure one having api 23 and another having api 24 same issue is replicated. I cant find any system generated issue issue in logcat .

From the logs thats getting printed from the application i can see onActivityResult method is not getting called after we call the startActivityForResult(signInIntent, RC_SIGN_IN);

#### Steps to reproduce:

  1. In device with api level 23 or android 6.0 open the app
  2. Click on the Google Sign in button
  3. The app with crash and an modal will pop up to select the Google account to sign in with
  4. On selecting the Google account the modal closes and nothing happens
  
#### Observed Results:

  Application crashes.
  
#### Expected Results:

onActivityResult is not called
  
#### Relevant Code:
onActivityResult must be called to further check for the firebase authentication
  ```
  public void signIn(View v) 
{ 
Log.d(TAG, "signIn"); 
Intent signInIntent = mGoogleSignInClient.getSignInIntent(); 
Log.d(TAG, "signIn Intent"+(signInIntent!=null)); 
startActivityForResult(signInIntent, RC_SIGN_IN); 
Log.d(TAG, "signIn startActivityForResult"); 
}
  ```

**Comment by samtstern** [comment]
@banerjeedeba can you provide the stack trace of the crash?

**Comment by banerjeedeba** [comment]
Sure, I have attached the log in first comment and mailed you the same.

**Comment by samtstern** [comment]
From the email conversation it appears that this crash is not related to Google Sign In or Firebase so I am going to close this issue.  I will re-open it if new evidence appears.

**Comment by thebeingapp** [comment]
I am facing the same issue with Android 6.0 or lower. What was the conclusion and why not share the conversation with us before marking this as closed?
