### ISSUE TITLE
Issue while using the change password functionality.

### ISSUE THREAD

**Issue by akhileshAwasthi** [firebase/quickstart-android#403]
This issue is not related to the code posted on github but is quite critical. I also raised this issue when I met the google experts at **GDD India** in december.

We have developed an application which uses firebase auth. We have used Google sign-in, along with normal email-password sign-in. However, we have applied few password rules while signing in with email-password credential to reduce unnecessary server calls. But when we provide user functionality to change password or creating new password when forgotten the current one, firebase sends an email to the user providing him/her a link to a web interface of firebase **where he/she can create a new password**.

**The issue is that there is no way to apply some password rules when user changes or creates new password using that **web interface of firebase**.** Since, user can put any password there(only constraint is that it should be six char long). But while signing in into our app with new password he/she will face difficulties because of the password rules we have on signing in.

**Comment by samtstern** [comment]
@akhileshAwasthi thanks for the feedback.  I agree with you that this sounds like something we could improve.  However (as you noted) this repository is not the right place to file this feedback.

Please use this form for all bugs and feature requests:
https://firebase.google.com/support/contact/bugs-features/
