### ISSUE TITLE
when get 2 notifications and press on the second notification it make the first notification action android

### ISSUE THREAD

**Issue by alishawky212** [firebase/quickstart-android#406]
i have 2 actions that should notification handle  when get 2 notification the action of the first one is done

**Comment by samtstern** [comment]
@alishawky212 this is not enough information to debug.  Can you describe how you're sending the notifications?  If you're writing any code to receive or display them, could you show that code?

**Comment by alishawky212** [comment]
I solved it the issue was with the pending intent that i was set the same request code on it.Thanks for your response .

**Comment by samtstern** [comment]
@alishawky212 glad it worked for you!
