### ISSUE TITLE
When back to MainActivity, the recyclerview reloaded

### ISSUE THREAD

**Issue by simonho1989** [firebase/quickstart-android#413]
If there are 30-40 restaurant posts, you will notice it is a pain to look the restaurant post at the bottom, everytime when i go back from RestaurantDetailActivity to MainActivity , the recyclerview reloaded and the post start from the top again. Anyway to solve the problem?

**Comment by samtstern** [comment]
@simonho1989 this is because we start and stop the adapter in `onStart` and `onStop`:

**onStart**
```java
       // Start listening for Firestore updates
        if (mAdapter != null) {
            mAdapter.startListening();
        }
```

If the start/stop calls are moved to `onCreate` and `onDestroy` then they would not reload as often.  Can you try and see if tha gives the behavior you wanr?

**Comment by simonho1989** [comment]
Thank you, it solves my problem
