### ISSUE TITLE
Firestore Example App Authentication Activity Bug

### ISSUE THREAD

**Issue by dharan1011** [firebase/quickstart-android#416]
### Step 1: Are you in the right place?
Yes
### Step 2: Describe your environment

  * Android device: Pixel running in the emulator on MacOS
  * Android OS version: 23
  * Firebase/Play Services SDK version: 11.8.0
  
### Step 3: Describe the problem:
- In firestore example app when in SignIn Activity, when back button is pressed app doesn't closes.    Instead it calls SignIn Activity is opened again. This kinda form a loop where user can't exit the app by pressing back button.
- Opening app when user hasn't authenticated and internet is disabled, `onActivityResult()` method is called again with `resultCode = 0` i.e 'startSignIn()' is called again and again it form a recursion and device screen flickers  
#### Steps to reproduce:
- Scenario  : Back Button Press 
  1. Open Friendly Eats app
  2. If Logged In Sing Out
  3. In Sing In Activity Press Back Button
- Scenario : No Internet Connection
  1. If sign into the app then sign out
  2. Close the app
  3. Turn of Internet connection
  4. Open the app
  5. Observer the Log Output
  6. Screen flickers  

#### Observed Results:

```
01-27 10:04:30.544 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.545 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.548 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.549 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.580 11472-11513/com.google.firebase.example.fireeats V/FA: Activity resumed, time: 16249263
01-27 10:04:30.581 11472-11513/com.google.firebase.example.fireeats V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 1
01-27 10:04:30.585 11472-11513/com.google.firebase.example.fireeats V/FA: Activity paused, time: 16249264
01-27 10:04:30.595 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.596 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.599 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.600 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.618 11472-11513/com.google.firebase.example.fireeats V/FA: Activity resumed, time: 16249300
01-27 10:04:30.620 11472-11513/com.google.firebase.example.fireeats V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 3
01-27 10:04:30.621 11472-11513/com.google.firebase.example.fireeats V/FA: Activity paused, time: 16249301
01-27 10:04:30.629 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.630 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.633 11472-11472/com.google.firebase.example.fireeats V/FA: onActivityCreated
01-27 10:04:30.633 11472-11472/com.google.firebase.example.fireeats D/KickoffActivity: No network connection
01-27 10:04:30.648 11472-11513/com.google.firebase.example.fireeats V/FA: Activity resumed, time: 16249332
01-27 10:04:30.651 11472-11513/com.google.firebase.example.fireeats V/FA: Screen exposed for less than 1000 ms. Event not sent. time: 3
```
#### Expected Results:

  In SignIn activity when back button is pressed, the app should close.
  Notify user to enable internet connection and retry authentication.
  
#### Relevant Code:

  ```
     @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        if (requestCode == RC_SIGN_IN) {
            mViewModel.setIsSigningIn(false);
            if (resultCode != RESULT_OK && shouldStartSignIn()) {
                startSignIn();
            }
        }
    }
  ```
- In SignIn Activity whenever the user press back button, SignIn Activity closes and the `resultCode != RESUTL_OK`, in the above code this cases is just handled by starting `startSignIn()` which a kind of becomes loop and user will never be able to close the app by pressing back button.
- Also when internet is disabled in `onActivityResult ` method  'startSignIn()' is called and SignIn activity open's and close immediately, which flicker the screen and becomes a recursion.
and

**Comment by samtstern** [comment]
@dharan1011 thanks for calling this out!  gonna fix it.
