### ISSUE TITLE
i am generating alert message app by using android and firebase but i want to app for when a fire-base data  updated automatically generate alert message

### ISSUE THREAD

**Issue by dvprasad45** [firebase/quickstart-android#417]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by dharan1011** [comment]
So you want to get notified using notification when ever the data in **firebase** database is updated. 😄 
You can make use of [firebase functions](https://firebase.google.com/docs/database/extend-with-functions), they trigger when ever a event happens and execute the code to send _notification_ to app whenever data in the firebase database is updated. Here is the [repo ](https://github.com/firebase/functions-samples)to help you get started with **firebase functions** .

**Comment by samtstern** [comment]
Thanks @dharan1011 for the answer!

Given the lack of information in the issue, I am going to close this as fixed.  This is not the right forum for general how-to/Q&A.
