### ISSUE TITLE
When app in background icon in meta dada white

### ISSUE THREAD

**Issue by pavelupward** [firebase/quickstart-android#418]
In manifest i declared that:
```
<meta-data
            android:name="com.google.firebase.messaging.default_notification_icon"
            android:resource="@drawable/ic_stat_logo_big_white3x"/>
        <meta-data
            android:name="com.google.firebase.messaging.default_notification_color"
            android:resource="@color/colorPrimary"/>
```
in api 26, android 8.0 when app in background  PUSH from FCM show only my round **@color/colorPrimary**
example:
https://image.ibb.co/d9hidb/Screenshot_1.png

**Comment by mathieuedet** [comment]
Hi ! 
I have a problem with the 11.8.0 version too. I've the default android app icon in status bar for remote notification and not the icon specified in AndroidManifest.xml. I've downgrade to 11.6.2 version and it works but I don't know why

**Comment by samtstern** [comment]
This is a known issue with the `11.8.0` SDK, it should be fixed in the next release.

**Comment by harsh3five8** [comment]
Is there any work around to this for now, it looks very bad for an app.

**Comment by samtstern** [comment]
You can downgrade your Firebase SDK to `11.6.0` if you are careful to avoid this critical bug: https://github.com/firebase/quickstart-android/issues/382

**Comment by ahabbaba9** [comment]
Hello, when will the next release be shipped?

**Comment by kroikie** [comment]
@ahabbaba9 We can't give an exact date but we are working on getting the next release out as soon as we can.

**Comment by kroikie** [comment]
This issue has been resolved please use `15.0.0`.

**Comment by prashantwosti** [comment]
still not fixed. i'm using `15.0.2`. the dot is still here.

**Comment by durzoflint** [comment]
Using `17.1.0` still persists

**Comment by CallumCoombes** [comment]
I have just tested this in `17.1.0` and it appears to be fixed. The icon is as defined as default in the manifest.

**Comment by amirdew** [comment]
it's working, I'm using `17.3.4`, but the point is you should add them to the `application` level, not in the `service` level, that was my problem
it would be useful if you add a clear note in the documentation

**Comment by Tech-AJ** [comment]
It's not working , I'm using 
implementation 'com.google.firebase:firebase-core:16.0.4'
implementation 'com.google.firebase:firebase-messaging:17.3.4'

and added notification icon  to the application level, and not in the service level,
but still in Android Oreo 8.0 its showing a square of notificationColor instead of showing notification icon.

**Comment by amirdew** [comment]
@Tech-AJ try using a transparent png file.
check this: https://stackoverflow.com/questions/30795431/android-push-notifications-icon-not-displaying-in-notification-white-square-sh

**Comment by amirdew** [comment]
@Tech-AJ 
No, there is no way to have a colorful icon (in the status bar) for the notification, because of lollipop design principles,  the only way is setting your target SDK to 20, which is not recommended and you will lose a lot of features.

Try to design another icon for notifications
checkout 'photos', 'inbox' and other apps notification icons:
https://i.pinimg.com/originals/9a/c5/75/9ac575fa694166cbca87dfb2c6c444ca.jpg

**Comment by SuryaJmm** [comment]
It's working, I'm using
 implementation 'com.google.firebase:firebase-core:16.0.7'
 implementation 'com.google.firebase:firebase-messaging:17.3.4'

I have just checked in 17.3.4 and it appears to be fixed. The icon is as defined as default in the manifest.

**Comment by SuryaBhati** [comment]
It is working, I have checked on
implementation 'com.google.firebase:firebase-core:16.0.7'
implementation 'com.google.firebase:firebase-messaging:17.3.4'

The icon is as defined as default in the manifest.

**Comment by michaelsof47** [comment]
it's still not working when i downgrade into 17.3.4 because i have using onNewToken when i got a new token. sorry for i'm a newbie on fcm. so that, i can't resolve in 2 weeks ago. how i resolve it?
