### ISSUE TITLE
Can't use Firebase phone auth in realese version 

### ISSUE THREAD

**Issue by sh3lan93** [firebase/quickstart-android#420]
phone auth working fine in debug version and when realesing and upload it to play store phone auth not working and saying app not authorized to use Firebase phone auth.
some notes:
* i configure sha1 for both debug and realese version on firebase console

**Comment by samtstern** [comment]
@sh3lan93 this sounds like an issue with your specific app and not this quickstart.  This is very likely a SHA1 issue, please double check.  You can always reach out to Firebase support for more help.
