### ISSUE TITLE
Broken link on Firestore quickstart

### ISSUE THREAD

**Issue by gricey432** [firebase/quickstart-android#430]
On the page https://firebaseopensource.com/projects/firebase/FirebaseUI-Android/ under Getting Started there's a broken link to FirebaseUI. https://github.com/firebase/quickstart-android/blob/master/firestore/README.md#L14

**Comment by samtstern** [comment]
@gricey432 sorry I don't see a "Getting Started" section here:
https://firebaseopensource.com/projects/firebase/firebaseui-android

Can you clarify?

**Comment by samtstern** [comment]
Ohhh I see there's a broken link on this page:
https://firebaseopensource.com/projects/firebase/quickstart-android/firestore/README.md

And this is the broken link:
https://firebaseopensource.com/projects/firebase/FirebaseUI-Android/

Seems like an issue of case sensitivity, thanks!

**Comment by samtstern** [comment]
I moved this issue over to firebaseopensource.com

**Comment by gricey432** [comment]
Ah sorry, pasted the wrong link. Thanks!
