### ISSUE TITLE
Stickers/Sticker Packs:  Why so awkward?

### ISSUE THREAD

**Issue by hoopjumpers** [firebase/quickstart-android#433]
Okay, after much thought, I think I understand the logic behind the current approach to stickers and sticker packs via Firebase app indexing.  My best guess is that someone important at Google said, "Hey, iOS has stickers and people are using them and paying money for them!  [sigh]  I guess we could try to do that too."  The decision to rely on the Firebase API was probably so that other keyboard app developers could query sticker packs too.

Here's the interface that "developers" should see:  Sign into the Google Play Console, click "Create New Sticker Pack", upload images, Publish.  No APK required.  Nor setting up Android Studio.  Nor submitting a Google Form for inclusion that no one at Google apparently views for at least a month (which is a tad annoying, BTW).  Stickers should be seamlessly integrated into Google Play and capable of being created and published entirely by a graphic designer.

Keyboard developers should see:  A simple set of Google Play Services APIs (not necessarily Firebase?) to retrieve the sticker packs sitting on the device.  As the user's keyboard is integral to the overall user experience, I see no reason why Google Play and Google Play Services wasn't the right location for this feature.

End user should see:  Sticker packs section in Google Play.  They hit download.  If there is a cost for the pack, then they pay for it with money.  The pack is associated with their account, so it automatically shows up on all their signed in devices.  They also don't have to launch an app to install stickers after they just installed something already and updates to the sticker packs are fully automated.  No APK has to be installed because the Google Play app itself manages the sticker packs that the user has.  There are also no issues with security vulnerabilities with a possibly poorly written and/or malware laden APK sitting on their device because sticker packs are just a set of images (okay so the built-in image loader libraries could have vulnerabilities, but that's an OS-level issue).

Why does it take a software developer to implement what amounts to uploading a set of images?  Methinks this could be far more elegant.

**Comment by samtstern** [comment]
Thank you for the super detailed feedback!  I'm personally not an expert in
this API but a lot of what you're saying sounds sensible to me.

I'll share this around with some other Firebasers and see what they think.
We love when community members like you take the time to tell us what
you're thinking.

Also don't be offended when I eventually close this GitHub issue, GitHub
just isn't a great place to store arbitrary feedback.

**Comment by kroikie** [comment]
Hi @hoopjumpers point taken, it would be cool if sticker developers had an easier way to submit their stickers. Your recommendation of using the Play Store to do this is reasonable.

However neither the Play Store nor Google Play Services have explicit support for sticker packs at this time. So if you want to have your stickers indexed by keyboards now then Firebase App Indexing is the way.

Thanks for the feedback.

**Comment by samtstern** [comment]
@hoopjumpers just FYI we forwarded this feedback on to the Product Manager for App Indexing, so you are heard!
