### ISSUE TITLE
firebasedatabase.getinstance vs new firebase

### ISSUE THREAD

**Issue by neo-xy** [firebase/quickstart-android#44]
why in your tutorial video  it is used : 
Databasereference  mRootRef = FirebaseDataBase.getInstance().getReference(); 
 but  at firebase.com in docs they use:
Firebase rootRef = new Firebase("https://docs-examples.firebaseio.com/web/data");
-what's the difference ?when we should use 1st one & when the 2nd one?? :S﻿

**Comment by samtstern** [comment]
@neo-xy the `Firebase` class is part of the old SDK which was replaced on May 19th by the new SDK which uses the `DatabaseReference` class.  You should always use the newer code when possible.

In general, firebase.com is deprecated and is kept live as a resource for users who have not yet migrated to the new SDK.  All of the most up to date docs are on firebase.google.com/docs.

**Comment by neo-xy** [comment]
ok, Perfect -thank you (y)
