### ISSUE TITLE
addSnapshotListener triggers twice when setting timestamp field with FieldValue.serverTimestamp()

### ISSUE THREAD

**Issue by mourjan** [firebase/quickstart-android#442]
### Step 2: Describe your environment

  * Android device: ___samsung J7 & emulator__
  * Android OS version: __23 & 26___
  * Google Play Services version: __11.9.75___
  * Firebase/Play Services SDK version: _11.8.0____
  
### Step 3: Describe the problem:
the scenario goe like this:

I have a recyclerView setup with a firestore adapter setup along with a query fetching documents like CHAT/MESSAGES (for example). all is normal.

now whenever I choose to insert a new message or update it, I set {**stamp**: FieldValue.serverTimestamp()| on a new docRef or update {**stamp**:FieldValue.serverTimestamp()} on a docRef. 
both of setting and updating cause the addSnapshotListener to **trigger twice**.
first time, the message object (snapshot) will return with stamp field set to **null**, 
and the second time with **stamp** field set with the correct **server timestamp** value.

I also assure you, that my addSnapshotListener is well implemented and there is only one listener running.. no more.
  
#### Expected Results:

  I should not get an update from snapshot listener if the document's stamp field <FieldValue.serverTimestamp()> is null

**Comment by mourjan** [comment]
After researching the matter, I found this explanation which makes sense [](https://stackoverflow.com/a/47764065/2199894). therefore I am closing this issue.

**Comment by samtstern** [comment]
@mourjan thanks for following up, glad you figured it out.
