### ISSUE TITLE
`onTokenRefresh` not being called after `getToken(entity, scope)`

### ISSUE THREAD

**Issue by fedetrim** [firebase/quickstart-android#446]
* Android device: Emulator (Nexus 5X API 26 x86)
  * Android OS version: 8.0 (Google APIs)
  * Google Play Services version: 10.2.6
  * Firebase/Play Services SDK version: 10.2.6
  
I'm trying to reproduce a situation where `onTokenRefresh` would get called, such as deleting the instance ID (`deleteInstanceId()`) and then calling `getToken()`.
I can get this to work perfectly with the regular `getToken()` (which returns the master token for the default Firebase project), but I'm having issues reproducing it if I use `getToken(entity, "FCM")` (which authorizes an entity to perform an action) instead of using `getToken()`.

Here is the strange part: after deleting the instance ID and calling `getToken(entity, "FCM")`, if I take the app to the background, close the app, and open it again, then `onTokenRefresh()` is called on startup. It does not get called at all if I don't previously take the app to the background.

#### Steps to reproduce:

  1. Generate a token with `getToken(entity, "FCM")`
  2. Delete the instance ID with `deleteInstanceId()`
  3. Regenerate a new token with `getToken(entity, "FCM")`
  4. Notice `onTokenRefresh()` doesn't get called
  5. Close the app
  6. Open the app: `onTokenRefresh()` still doesn't get called.
  7. Delete the instance ID with `deleteInstanceId()`
  8. Regenerate a new token with `getToken(entity, "FCM")`
  9. Take the app to the background
  10. Close the app
  11. Open the app
  12. `onTokenRefresh` gets called
  
#### Observed Results:

  * `onTokenRefresh` doesn't get called reliably. Sometimes it isn't called at all.
  
#### Expected Results:

  * I expected to have `onTokenRefresh` get called as soon as a new token is generated, with both `getToken()` and `getToken(entity, scope)`.
  
#### Relevant Code:

  `onTokenRefresh` implementation:
  ```java
  public class InstanceIdService extends FirebaseInstanceIdService {
    
    ...

    public void onTokenRefresh() {
      ...
    }
  }
  ```

  Regenerating the entity authorization token:
  ```java
  new Thread(new Runnable() {
    @Override
    public void run() {
      try {
        FirebaseInstanceId.getInstance().deleteInstanceId();
        FirebaseInstanceId.getInstance().getToken(entity, "FCM");
      } catch (IOException e) {
        e.printStackTrace();
      }
    }
  }).start();
  ```

**Comment by fedetrim** [comment]
To add a little more context: I was trying to do this because we are seeing an increasing number of failed messages, so we believe that we are failing to report tokens back to our server when they are refreshed on the clients.

Based on the tests I made, I'm starting to be a little paranoid that it is because we are using specific scope authorization rather than the master token.

**Comment by kroikie** [comment]
Hi @fedetrim `onTokenRefresh()` is only called for the default application. If you are using additional senders (entities) then you need to call `getToken(entity, scope)` in order to get those tokens.
