### ISSUE TITLE
FirebaseApp initialization unsuccessful when app killed

### ISSUE THREAD

**Issue by kimnamcham** [firebase/quickstart-android#447]
When i force close app by stop all background app button , i see this log:
03-20 11:28:10.348 28852-28852/? I/FirebaseInitProvider: FirebaseApp initialization unsuccessful

Is that reason of firebase notification not working when app killed ? And how to recevied notification when app killed ?

**Comment by samtstern** [comment]
@kimnamcham as far as I am aware that is nothing to worry about, just an artifact of the way we initialize `FirebaseApp` in a `ContentProvider`.  Is anything bad happening?   If not, inclined to close this issue and just say to ignore the noisy log message.

**Comment by samtstern** [comment]
@kimnamcham gonna close this issue, but let me know if you want me to re open it!
