### ISSUE TITLE
Auth quickstart app Null pointer error Android 4.4.2

### ISSUE THREAD

**Issue by danleahy** [firebase/quickstart-android#466]
### Step 1: Are you in the right place?
  * yes
### Step 2: Describe your environment

  * Android device: Samsung Tab 3 SM-T210   Kernel version 3.4.5-4081557
  * Android OS version: 4.4.2
  * Google Play Services version: 
  * Firebase/Play Services SDK version: com.google.firebase:firebase-auth:12.0.1/com.google.android.gms:play-services-auth:12.0.1

replicated on 
  * Android device: Samsung Tab A SM-T230   Kernel version 3.10.65-10429622
  * Android OS version: 5.1.1
  * Google Play Services version: 
  * Firebase/Play Services SDK version: com.google.firebase:firebase-auth:12.0.1/com.google.android.gms:play-services-auth:12.0.1
  
### Step 3: Describe the problem:
Null pointer error when you click sign on the email and password activity UI

#### Steps to reproduce:

Firebase app project created, application added, google-services.json downloaded and put in app root folder.

Same app works on my personal nexus 6p running Android 8 with no modification

  1. launch quickstart auth app
  2. Select EmailPasswordActivity 
  3. enter username and password
  4. click sign in button
  
#### Observed Results:

  * What happened?  
Null pointer exception

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.google.firebase.quickstart.auth, PID: 21515
                  java.lang.NullPointerException
                      at com.google.android.gms.internal.zzdza.zzb(Unknown Source)
                      at com.google.android.gms.internal.zzdzh.zzb(Unknown Source)
                      at com.google.firebase.auth.FirebaseAuth.signInWithEmailAndPassword(Unknown Source)
                      at com.google.firebase.quickstart.auth.EmailPasswordActivity.signIn(EmailPasswordActivity.java:129)
                      at com.google.firebase.quickstart.auth.EmailPasswordActivity.onClick(EmailPasswordActivity.java:246)
                      at android.view.View.performClick(View.java:4640)
                      at android.view.View$PerformClick.run(View.java:19431)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:146)
                      at android.app.ActivityThread.main(ActivityThread.java:5598)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                      at dalvik.system.NativeStart.main(Native Method)
  
#### Expected Results:

  * Signed in UI screen should have been shown if login was successful
  
#### Relevant Code:
* The code works on Nexus 6P, same project fails on Android 4.4.2 

  ```
      mAuth.signInWithEmailAndPassword(email, password)
                    .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                        @Override
                        public void onComplete(@NonNull Task<AuthResult> task) {
                            if (task.isSuccessful()) {
                                // Sign in success, update UI with the signed-in user's information
                                Log.d(TAG, "signInWithEmail:success");
                                FirebaseUser user = mAuth.getCurrentUser();
                                updateUI(user);
                            } else {
                                // If sign in fails, display a message to the user.
                                Log.w(TAG, "signInWithEmail:failure", task.getException());
                                Toast.makeText(EmailPasswordActivity.this, "Authentication failed.",
                                        Toast.LENGTH_SHORT).show();
                                updateUI(null);
                            }

                            // [START_EXCLUDE]
                            if (!task.isSuccessful()) {
                                mStatusTextView.setText(R.string.auth_failed);
                            }
                            hideProgressDialog();
                            // [END_EXCLUDE]
                        }
                    });
  ```

**Comment by samtstern** [comment]
@danleahy thank you for reporting this!  I'll show it to the fIrebase auth android team and see what they think.

Could you check what version of the Google Play services app is installed on the devices where this crashes?

**Comment by danleahy** [comment]
On the Samsung T280 Google play services 7.8.95
On the Samsung T210 Google play services 6.1.88

**Comment by samtstern** [comment]
Wow those are some very old versions!  Is there a reason you can't get Play
services 12.x on those?

**Comment by danleahy** [comment]
Hi, some back history, the apps Kinesis developed were developed and designed on those old Samsung tablets over 5 years ago now, we still sell our app preinstalled on those tablets types, the tablets are sourced and provisioned by a 3rd party (and they charge for everything they do to them), our apps are installed and sent on to the end customer in custom case with associated bluetooth sensors with those old versions of google play services and the old versions of chrome installed (Chrome version 40 and 43) respectively, we could bring in the tablets in house and provision them ourselves and update everything ourselves just not in the near future due to other commitments. I would love to have an android system image that would include an up to date android image with our apps as part of the image but I haven't seen any tools for that for small businesses.

I hope that explains why we are stuck with the old versions of Google play services for now.

There are very few options in terms of new Android tablets that have the latest versions of Android and are within our price range.
If you have a suggestion for a modern Android tablet that would be equivalent to the old Samsung Tab A or Samsung Tab that would be great.
Regards,
               Daniel Leahy.

**Comment by samtstern** [comment]
@danleahy thank you for the background

Before I continue the discussion, I want to just say that I am going to close this issue because the authentication team officially does not try to support compatibility when SDK version >> Play services version.  We intend for developers to trigger the Google Play services upgrade flow if they're having trouble with issues like this.  I understand in your situation that's not possible/easy, but it is our official position and I hope you can understand.

So do your tablets not have the play store?  That would explain why they can't get the upgrade flow.  As for a modern Android tablet, I actually think the most promising future hardware in this space is Chromebook tablets:
https://www.theverge.com/circuitbreaker/2018/3/26/17157444/acer-chromebook-tab-10-first-chrome-os-tablet-announced

They can run Android apps natively (not sure about the bluetooth APIs though?) and they are extremely simple to provision and update over the air.  In my personal opinion these devices are perfectly suited to a point of sale / kiosk / etc installation.

**Comment by danleahy** [comment]
Thank Sam for the update.

It is understandable.

The tablets do a have the playstore but as i mentioned in the last post our
tablets are provisioned by a 3rd party (they would charge a fortune to
update verything), they don't add a google account, the end customers don't
care, they just use whatever came pre-installed.

and we can't force them to add a google account to force the updates.

Anyways we now have a working prototype using AWS Cognito identity pools
that work with our old tablets.

Thank you for the link about the modern tablet, we will check it out.

Regards,
                Daniel Leahy.

**Comment by samtstern** [comment]
@danleahy thanks for following up.  I am going to file a feature request with the Play Store team to see if there's any possibility of allowing devices with no Google account to still receive critical updates, like Google Play services.  Of course this is just a speculative FR so I wouldn't hold out for it, but thanks for the idea!
