### ISSUE TITLE
This app is not authorised to use Firebase Authentication

### ISSUE THREAD

**Issue by rags016** [firebase/quickstart-android#468]
This app is not authorised to use Firebase Authentication. Please verify that the correct package name and SHA1 are configured in the Firebase Console.[App Validation Failed]
what i did
* I used Firebase Assitant
packagename is present  and SHA1 is also present
and i am testing on one plus 3T
inspite of this its showing above error

please help me out

**Comment by TheMacNerd** [comment]
Perhaps one of these might solve your problem:

https://stackoverflow.com/questions/45707173/this-app-is-not-authorized-to-use-firebase-authentication-in-emulator
https://stackoverflow.com/questions/46751766/this-app-is-not-authorized-to-use-firebase-authentication-please-verify-that-the?rq=1
https://stackoverflow.com/questions/45707173/this-app-is-not-authorized-to-use-firebase-authentication-in-emulator?rq=1
https://stackoverflow.com/questions/46484685/firebase-auth-this-app-is-not-authorized-to-use-firebase?rq=1

**Comment by samtstern** [comment]
Thanks @NickSiena for posting all those useful links.

I apologize I never got around to responding here, but closing as I believe the solution(s) are presented on StackOverflow.

**Comment by G3niushacker** [comment]
I've Also same Error in flutter
