### ISSUE TITLE
Adding tools:node="replace" to Android Manifest application tag causes FCM not working

### ISSUE THREAD

**Issue by sreejithbnaick** [firebase/quickstart-android#477]
### Summary:
If I add `tools:node="replace"` to AndroidManifest Application tag, Android App will never get 
`FirebaseInstanceIdService` `onTokenRefresh()` callback and FCM doesn't work.

### Environment
  * Android device:  Emulator or Any device
  * Android OS version: 7.1.1
  * Google Play Services version: 124510001
  * Firebase/Play Services SDK version: 15.0.0 or 12.0.1
  
### Description of the problem:
Adding  `tools:node="replace"` to AndroidManifest Application tag as below

```
<application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:node="replace">
```

will cause the app never getting `FirebaseInstanceIdService` `onTokenRefresh()` callback. 

I can manually call ```FirebaseInstanceId.getInstance().getToken()``` to get a token. But this token will never work. Using this token will give success result on first call, but from next call onwards it will give `notRegistered` error.

 
#### Steps to reproduce:

  1. Create any sample project with FCM messaging
  2. Just add `tools:node="replace"` to application tag in AndroidManifest
  3. Build and install the app
  
#### Observed Results:

  * onTokenRefresh never called. Manual call to `getToken()`  will give a token, but will give `notRegistered` error all the time (except first time)
  
#### Expected Results:

  * On every fresh install of the app, `onTokenRefresh` method of `FirebaseInstanceIdService` implementation will be called everytime and given token will work properly
 
Please look into this issue, since `tools:node="replace"` is used widely for solving manifest merge issues. 

Adding ` tools:node="replace"` to any manifest file (doesn't need to be main manifest, it can be sub module manifest or library manifest) can cause the issue.

(PS: I was trying to migrate from GCM to FCM. And GCM was working for us, but for some users token was giving `notRegistered` error. I believe it is because of this.)

**Comment by nikitamarysoloman** [comment]
try to replace in 
<application
        android:name=".MyApplication"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme"
        tools:node="replace">
with the below attributes
   android:allowBackup="false"
        tools:node="merge"
        tools:replace="android:label,android:allowBackup"

**Comment by kroikie** [comment]
Many of the Firebase SDKs depend on manifest merging, replacing the Application tag in the manifest will undo that. FCM in particular will not work if the Application tag is replaced. I'd recommend using another option besides `replace`, maybe `merge` like @nikitamarysoloman suggests.

**Comment by alphaguy4** [comment]
Hi i also have the same problem. when i replace `tools:node="replace"` with `tools:node="merge"`
Manifest merging fails.
Can you help ?

**Comment by rlechetaudemy** [comment]
Oh my god. I lost 1 week to discover this. Just a simple Firebase Analytics was not working because I had tools:node="replace" in my Manifest. Please Firebase, could you document that? The documentation sometimes is too much simple, you can do better for sure!

**Comment by OfirAlo** [comment]
> Oh my god. I lost 1 week to discover this. Just a simple Firebase Analytics was not working because I had tools:node="replace" in my Manifest. Please Firebase, could you document that? The documentation sometimes is too much simple, you can do better for sure!

another week here as well. "oh my god" indeed

**Comment by venky145** [comment]
tools:replace="android:label" in androidManifest fixed issue
