### ISSUE TITLE
Firebase auth error -23, "limits exceeded" on staging server

### ISSUE THREAD

**Issue by mutablestudio** [firebase/quickstart-android#48]
I can authenticate the user on iOS without any issues, so Firebase is accepting auth requests for this user. It is working for iOS auth on both our staging AND production Firebase URLs.

However, on Android simulator/device I cannot login with same user on the staging Firebase.

I have tried using older login example with 'com.firebase:firebase-client-android:2.0.3+'  as we well as newer example using Google GSM and com.google.firebase:firebase-auth:9.0.2. Both return auth error -23 with message "limits exceeded".

Does this require some additional settings or config in the Firebase dashboard?

Thanks,
Anthony

**Comment by mutablestudio** [comment]
Update - we enabled Google auth as well as email/pwd in our Firebase dashboard under Authorization -> Sign In Method. Also added SHA1 from ~/.android/debug.keystore. Here is the latest stack trace:

`06-13 16:23:59.599 10460-10460/com.helium.mobile.android.pulse D/com.helium.mobile.android.pulse.util.Preferences: signInWithEmail:onComplete:false
06-13 16:24:02.373 10460-10530/com.helium.mobile.android.pulse E/DynamiteModule: Failed to load module descriptor class: Didn't find class "com.google.android.gms.dynamite.descriptors.com.google.firebase.auth.ModuleDescriptor" on path: DexPathList[[zip file "/data/app/com.helium.mobile.android.pulse-1/base.apk"],nativeLibraryDirectories=[/data/app/com.helium.mobile.android.pulse-1/lib/x86, /vendor/lib, /system/lib]]
06-13 16:24:06.523 10460-10460/com.helium.mobile.android.pulse W/com.helium.mobile.android.pulse.util.Preferences: signInWithEmail
                                                                                                                   com.google.firebase.FirebaseTooManyRequestsException: We have blocked all requests from this device due to unusual activity. Try again later.
                                                                                                                       at com.google.android.gms.internal.zzacq.zzbN(Unknown Source)
                                                                                                                       at com.google.android.gms.internal.zzacn$zzg.zza(Unknown Source)
                                                                                                                       at com.google.android.gms.internal.zzacy.zzbO(Unknown Source)
                                                                                                                       at com.google.android.gms.internal.zzacy$zza.onFailure(Unknown Source)
                                                                                                                       at com.google.android.gms.internal.zzact$zza.onTransact(Unknown Source)
                                                                                                                       at android.os.Binder.execTransact(Binder.java:453)`

**Comment by mutablestudio** [comment]
Here is more info on how I'm calling the Firebase auth:

Init mAuth per google Firebase example:

`mAuth = FirebaseAuth.getInstance();`
`mAuthListener = new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                FirebaseUser user = firebaseAuth.getCurrentUser();
                if (user != null) {
                    // User is signed in
                    Log.d(TAG, "onAuthStateChanged:signed_in:" + user.getUid());
                } else {
                    // User is signed out
                    Log.d(TAG, "onAuthStateChanged:signed_out");
                }
                //updateUI(user);
            }
        };`

Initially user is NULL so onAuthStateChanged:signed_out gets logged. Next, after signing in with email and pwd (same user credentials are working with iOS Firebase SDK) the onCompleteListener is called and the Exception is produced (shown in last comment) in the `if (!task.isSuccessful())` block:

`mAuth.signInWithEmailAndPassword(email, pwd)
                .addOnCompleteListener(this, new OnCompleteListener<AuthResult>() {
                    @Override
                    public void onComplete(@NonNull Task<AuthResult> task) {
                        Log.d(TAG, "signInWithEmail:onComplete:" + task.isSuccessful());
                        if (!task.isSuccessful()) {
                            Log.w(TAG, "signInWithEmail", task.getException());
                            Toast.makeText(SignInActivity.this, "Authentication failed.",  Toast.LENGTH_LONG).show();
                        }
                    }
                });
`

**Comment by samtstern** [comment]
@mutablestudio is it possible you have an infinite loop in your application somewhere?  In your logs the Firebase server is saying it's getting too many requests from your client.

**Comment by samtstern** [comment]
@mutablestudio it's been a few weeks since the last reply on this thread and I have heard no additional reports of this issue.  I am going to mark this as closed, please re-open this issue if you are still stuck.
