### ISSUE TITLE
Android PushNotification Title issue when app is in background

### ISSUE THREAD

**Issue by bhaskar2342** [firebase/quickstart-android#491]
I have an issue with **setContentTitle**. Im working with flavors in android. I'm comfortably receiving notifications when app is in foreground/background/killed. But the problem is when app is in background/killed the title i'm receiving is incorrect i.e the title i'm getting from server what they've set but not the flavors title. If the app is in foreground the title works fine.
For example i have 2 flavors **Flavor1** and **Flavor2**  and set the titles as **F1** and **F2** respectively and from server side they set the title as **TstNotif**. When the app is in foreground the title for the notification i'm receiving is **F1** or **F2** depends on flavor, but when the app is in background i'm receiving **TstNotif**  for both the flavors.
For iOS they are working fine....!
When i send from FCM console everything works fine in all aspects...!

**Comment by rupeshgohil** [comment]
Fist to check firebase description for update version Orio android api level 27 and see the Notification channel id and how to implement for Notification as Background and foreground as vise 
bellowing the document as a firebase "https://firebase.google.com/docs/cloud-messaging/concept-options "
i hope that help to you and feting more description about firebase Notification Messaging
Thanks,
By Rupesh Gohil

**Comment by samtstern** [comment]
@bhaskar2342 I apologize that nobody from our team ever got to this issue when you filed it.  Since it is very old and @rupeshgohil has offered some advice I assume that you have either found the fix or moved on.  If you experience something similar now please file a new bug.

**Comment by bhaskar2342** [comment]
It got fixed. Thanks for your help..!
