### ISSUE TITLE
Cannot connect to realtime database

### ISSUE THREAD

**Issue by timothegenzmer** [firebase/quickstart-android#492]
We are facing a similar issue already discussed in the firebase unity repo:
https://github.com/firebase/quickstart-unity/issues/106

Using our office wifi we can neither read from nor write to the realtime database.
If we switch our devices to mobile connection it works as intended.
We see the same behavior for one developer's private network at home.

We don't have special firewall rules that might block the access.
Both our office routers and the private router use default settings.

For our own networks we could probably find a solution, but from user feedback we know that this is also happening in the wild.

The proposed solution from the unity thread to use the REST Api is not a viable solution for us.

FYI: We are using the latest firebase version, but this is not a new issue.

**Comment by samtstern** [comment]
@timothegenzmer sorry to hear about that!  Unfortunately this repo (the Android quickstarts) is not the right place to get help for an issue like that.

Please file a ticket with Firebase support, who will help you with your connection issues:
https://firebase.google.com/support/

**Comment by Quy-NguyenTrong** [comment]
I think that your router IP was recored in black list of GG security  , just restart router , it is working again .!

**Comment by raojagannath11** [comment]
###
