### ISSUE TITLE
Request for user profile from GMail is returning null

### ISSUE THREAD

**Issue by laylizzlle** [firebase/quickstart-android#50]
I would like to retrieve the user's profile picture and name after google login:

    GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestIdToken(getString(R.string.default_web_client_id))
                .requestEmail()
                .requestProfile()
                .build();

    ...
    mAuthListener = new FirebaseAuth.AuthStateListener() {
            @Override
            public void onAuthStateChanged(@NonNull FirebaseAuth firebaseAuth) {
                FirebaseUser user = firebaseAuth.getCurrentUser();
                if (user != null) {
                    // User is signed in
            Log.v(TAG,"pic "+user.getPhotoUrl()+" name "+user.getDisplayName());
                } else {
                    // User is signed out
                    Log.d(TAG, "onAuthStateChanged:signed_out");
                }
            }
        };

In the logcat am getting: pic null name null

**Comment by samtstern** [comment]
@laylizzlle your app should be ready to handle a `null` result for the photo URL as many users who have never set a public picture on Google+ will not have a picture that we can provide to your app.

The issue of `displayName` being null is something we are looking into.  We have seen other developers reporting this and are trying to work out the exact conditions where it happens.  Thanks for your patience!

As this is not an issue with the samples I will close the issue. Feel free to reach out to our [support team](https://firebase.google.com/support/) if you have follow up questions.

**Comment by muhalifalgibran** [comment]
if you using google auth it will works fine but if you using just email and password auth it couldn't return the user profil(null) because you just initialize email and password by your own, your app just borrow your email.
