### ISSUE TITLE
Not able to build firebase perf project

### ISSUE THREAD

**Issue by yashasvigirdhar** [firebase/quickstart-android#503]
* Android device: NA
  * Android OS version: NA
  * Google Play Services version: 3.3.0
  * Firebase/Play Services SDK version:  core - 15.0.2, perf: perf:11.8.0
  
I am not able to build perf project in this repository. It fails with this reason:

`All firebase libraries must be either above or below 14.0.0`. 

#### Steps to reproduce:

Just build the perf project using `./gradlew build`.

**Comment by samtstern** [comment]
#504 also makes sure this won't happen again.
