### ISSUE TITLE
Can't connect to Firestore over Vodafone in some devices

### ISSUE THREAD

**Issue by tallnato** [firebase/quickstart-android#507]
### Step 1: Are you in the right place?

Can't connect to Firestore over Vodafone in some devices

### Step 2: Describe your environment

  * Android device: Xiaomi, Asus and Huawei
  * Android OS version: Several
  * Google Play Services version: Several
  * Firebase/Play Services SDK version: 
  
### Step 3: Describe the problem:

I've encountered some weird behavior using Firestore SDK over a mobile data connection in some devices.

In devices like Xiaomi, Asus and Huawei with a mobile internet connection over Vodafone (I'm from Portugal), the application can't connect to the firestore server. Also, it doesn't provide any error messages, like no network for instance , but sometimes it does show the error "client is offline".

Over wifi there is no problem connecting to the server, and using other portuguese mobile internet providers like NOS or MEO or using other devices with Vodafone, there is no problem connecting to the server.

I've tried in the same device, changing the SIM card from Vodafone, not working, to NOS and it works perfectly.

This project shows that error, for those devices and for that mobile data connection.

When the app starts it tries to get data from the server, and instead of returning and error, it returns empty data.

The logs for this error can be found in https://github.com/tallnato/firebase-mobile-data-bug/blob/master/logs.txt  file.

There is a log in the logs file that says `Firestore: (0.6.6-dev) [OnlineStateTracker]: Could not reach Firestore backend.`

Any suggestions is appreciated on how to solve this.

You can see the sample project here https://github.com/tallnato/firebase-mobile-data-bug

#### Observed Results:

  * Error connecting to the backend 
  *  `Firestore: (0.6.6-dev) [OnlineStateTracker]: Could not reach Firestore backend.`
  
#### Expected Results:

  * Connect to Firestore backend
  
#### Relevant Code:

https://github.com/tallnato/firebase-mobile-data-bug/blob/master/logs.txt

**Comment by samtstern** [comment]
@tallnato could you please contact Firebase support with this request?  They are much more able to debug something as specific as this. 

https://firebase.google.com/support
