### ISSUE TITLE
Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.name' on a null object reference: com.google.android.gms.internal.zzaua.zzKq(Unknown Source) error Firebase Messaging

### ISSUE THREAD

**Issue by ErdincOzdemir** [firebase/quickstart-android#516]
### Describe your environment

  * Android device: Samsung Note 5
  * Android OS version: 7.0
  * Google Play Services version: 3.2.0
  * Firebase/Play Services SDK version: 10.2.1
  
#### Steps to reproduce:

  1. Created an project and application on console.firebase.google.com
  2. Downloaded google-services.json
  3. Added FirebaseInstanceIdService & FirebaseMessagingService classes
  4. Added service nodes to AndroidManifest.xml
  
#### Observed Results:

  * E/FA: Task exception on worker thread: java.lang.NullPointerException: Attempt to read from field 'java.lang.String android.content.pm.PackageItemInfo.name' on a null object reference: com.google.android.gms.internal.zzaua.zzKq(Unknown Source)
  
#### Relevant Code:

  ```

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        String token = FirebaseInstanceId.getInstance().getToken();
    }
}

  ```
AndroidManifest.xml

  ```
        <!-- Firebase services -->
        <service
            android:name=".services.PushNotificationMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT"/>
            </intent-filter>
        </service>
        <service
            android:name=".services.PushNotificationInstanceIdService">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT"/>
            </intent-filter>
        </service>
        <!-- Firebase services -->

  ```

**Comment by samtstern** [comment]
@ErdincOzdemir what happens when you see this error?  Does the app crash?  Does FCM stop working?  Neither?

**Comment by samtstern** [comment]
@ErdincOzdemir closing due to no recent response in this conversation, but let me know if you're still seeing this and want to discuss more!
