### ISSUE TITLE
Cannot run sample app due to failing download of barcode lib

### ISSUE THREAD

**Issue by rdoubleui** [firebase/quickstart-android#517]
### Describe your environment

  * Android device: Huawei P9 Lite
  * Android OS version: 7.0
  * Google Play Services version: 12.5.86
  * Firebase/Play Services SDK version: 16.0.0

#### Steps to reproduce:

  1. Add sample app within Firebase console
  2. Follow steps e.g. import google-services.json
  3. Run app
  
#### Observed Results:

- Barcode (and for that matter any other) detection doesn't work. 

```
[ 05-28 14:14:37.027   539:11107 E/         ]
void hw::COutMetaSplitBase::dump_thermal_meter(monitor_t): open  failed!
05-28 14:14:37.044 10888-10932/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
05-28 14:14:37.049 10888-10932/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
05-28 14:14:37.050 10888-10932/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
05-28 14:14:37.056 10888-10932/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
05-28 14:14:37.056 10888-10932/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
05-28 14:14:37.061 10888-10932/com.google.firebase.samples.apps.mlkit I/Vision: Loading library libbarhopper.so
05-28 14:14:37.061 10888-10932/com.google.firebase.samples.apps.mlkit I/Vision: libbarhopper.so library load status: false
```

In a first step to fix this state (as with the current google vision barcode scanner issue) I also cleared the app data of the Play Services installation (12.6.85) and was able to get this sample app running, logcat eventually indicating that the download succeeded (detection works from here):

```
05-28 14:19:33.880 13685-13730/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
05-28 14:19:33.886 13685-13730/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
05-28 14:19:33.887 13685-13730/com.google.firebase.samples.apps.mlkit W/DynamiteModule: Local module descriptor class for com.google.android.gms.vision.dynamite not found.
05-28 14:19:33.892 13685-13730/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:1702
05-28 14:19:33.892 13685-13730/com.google.firebase.samples.apps.mlkit I/DynamiteModule: Selected remote version of com.google.android.gms.vision.dynamite, version >= 1702
05-28 14:19:33.897 13685-13730/com.google.firebase.samples.apps.mlkit I/Vision: Loading library libbarhopper.so
05-28 14:19:33.902 13685-13730/com.google.firebase.samples.apps.mlkit W/linker: /data/data/com.google.android.gms/app_vision/barcode/libs/arm64-v8a/libbarhopper.so: unused DT entry: type 0x7ffffffd arg 0x6dd
05-28 14:19:33.904 13685-13730/com.google.firebase.samples.apps.mlkit I/Vision: libbarhopper.so library load status: true
```

**However, a restart of the device brings back the above mentioned download issue.** This is something out of user's control, so I was wondering if there's any other workaround available for ML.

**Comment by samtstern** [comment]
cc @isaisachen @gkaldev have you seen anything like this before?

**Comment by samtstern** [comment]
There is a recent issue with Huawei devices / Google Play services / file permissions that caused a widely-noticed "outage" of Google Maps views on those devices.  It's very likely that this is the same issue.

@rdoubleui can you reproduce this on any non-Huawei device?

**Comment by isaisachen** [comment]
@rdoubleui There's a potential fix for Huawei issue which just went out with Google Play services 12.6.85. 

Could you:
1. Check on non-Huawei device like @samtstern suggested
2. Check on your Huaiwei device Google Play services version:
adb shell dumpsys activity service com.google.android.gms/.common.stats.GmsCoreStatsService | grep 'com\.google\.android\.gms \['
If it's older than 12.6.85, update to latest Google Play services and try again.

You can force a Google Play services update by:
1. Access the Google Settings screen:
    a) Android <= L: App Drawer > Google Settings
    b) Android >= M: Settings > Google
2. From Google Settings, go to the overflow menu → Help & feedback → overflow menu → View in Google Play Store. 
3. If you see an [UPDATE] button, click it.

**Comment by fvermeulen** [comment]
@isaisachen 
Checked it on a Huawei P9 Lite.... There is the 12.6.85 installed, Camera works, but no scanning. After deleting the playServices-data it will work. You have to do the same steps on every restart of the phone :(

On the non Huawei-decives I've tested, the barcode scanner works.

**Comment by isaisachen** [comment]
@fvermeulen Would you mind grabbing a full bug report and share to us? You can e.g. upload it to Google Drive and share by link. Thanks!

**Comment by dimsuz** [comment]
@samtstern this happens not only on Huawei devices, I have the same issue on my Nexus 5X (running android 8.1.0)

**Comment by isaisachen** [comment]
@dimsuz Are you sure you have the same issue on Nexus 5X? i.e. it could work initially and after a reboot, it stops working again. If you could never get it working, try clear Google Play services cache and see if you can put it to work again?

Also everyone FYI that we figured out the root cause for the Huawei issue and the fix will be available 100% end of the month. You can subscribe to public Beta below to get it earlier (12.8.59+):
https://developers.google.com/android/guides/beta-program

**Comment by dimsuz** [comment]
@isaisachen it looks very similar at least. I for sure have these lines in my log on Nexus 5X

```
05-28 14:14:37.061 10888-10932/com.google.firebase.samples.apps.mlkit I/Vision: Loading library libbarhopper.so
05-28 14:14:37.061 10888-10932/com.google.firebase.samples.apps.mlkit I/Vision: libbarhopper.so library load status: false
```

though it is reproduced when using mobile-vision library, but I suspect that the core is the same - i mean ndk lib loading part and all this dynamite module stuff :)

I tried clearing Play cache (as was suggested in issues linked above) and tried to reboot my phone - nothing have helped.

**Comment by isaisachen** [comment]
@dimsuz I don't think it's the same issue as Huawei then. After you clear the cache, need some API usage to trigger the download. Also, make sure you have sufficient device storage. (no download if < x% storage available)

Also, it's recommended to configure below meta-data to trigger the download upon your app installation. 
```
<application ...>
  ...
  <meta-data
      android:name="com.google.firebase.ml.vision.DEPENDENCIES"
      android:value="barcode" />
  <!-- To use multiple models: android:value="barcode,model2,model3" -->
</application>
```

See here for details.
https://firebase.google.com/docs/ml-kit/android/read-barcodes#before-you-begin

**Comment by dimsuz** [comment]
Thank you! I will try it and see if it helps!

**Comment by fvermeulen** [comment]
for me it didn't help to update to the play-services-beta version. Deleted the data from play-services restarted the app then it works, but after a restart of the phone same thing :(

**Comment by isaisachen** [comment]
Hi folks, sorry that the fix was actually only included in 12.8.62+. 

@fvermeulen which version did you get?

`adb shell dumpsys activity service com.google.android.gms/.common.stats.GmsCoreStatsService | grep 'com\.google\.android\.gms \['
`

**Comment by wbervoets** [comment]
@isaisachen has 12.8.62+ been released fully as non beta? Still 197 users impacted yesterday on our app. Why does it take so long (eg. from May 10th) to fix an important bug ?

**Comment by isaisachen** [comment]
@wbervoets No, not yet. I will update here when a fix is 100% available to end users.

**Comment by avatarerr** [comment]
In case this information helps:

My codebar reading was working smoothly on a Huawei P8 lite when, 2 days ago, stopped detecting codebars, having exactly the same error than the poster. Not only my app, also the mlkit demo i used to test it's features.

Google Play services version: 12.6.85

Then i tried on a new Huawei P8 Lite (directly from the box) and, yeah, my app and the mlkit demo works.

Google Play services version of the non updated Huawei: 11.0.55

So now i'm in panic and trying to downgrade google play services as a quick fix, while looking for a new set of excuses for my angry client :)

**Comment by wbervoets** [comment]
@isaisachen can you share the current rollout plan?

**Comment by isaisachen** [comment]
@wbervoets Sorry, I don't have any details to share. I can just say Google is actively working on the release. Thanks for your patience. I will update here when it's 100% rolled out.

**Comment by wbervoets** [comment]
Seems 12.8.72 is being rolled out since a few days. I'll check if number of users impacted by the bug now starts decreasing.

**Comment by wbervoets** [comment]
@isaisachen I assume roll out of 12.8.74 is complete for Huawei users now?

**Comment by isaisachen** [comment]
Yes, 12.8.74 is available to everyone now.

**Comment by samtstern** [comment]
Thanks @isaisachen !

**Comment by arthas1888** [comment]
gays, do you know something with this bug?
Actually my customers work with Huawei phones
