### ISSUE TITLE
Firebase Invite always failed...

### ISSUE THREAD

**Issue by vendys-sungsik** [firebase/quickstart-android#52]
I wonder why does always fail (resultCode : 3) about 'Firebase Invites' sample app.
What about others? Why does the fail occur?

**Comment by Rahulrsannidhi** [comment]
I am also getting the same Error Please help to resolve

**Comment by Karthi-R** [comment]
@vendys-sungsik @Rahulrsannidhi did you add "SHA-1 key" of your Android app in firebase console ?
If not; check Firebase App invite after updating your "SHA-1 key".

**Comment by samtstern** [comment]
Let's discuss general firebase invite failures on #38, which has a number of people with similar issues.

**Comment by JasonSheedy** [comment]
If this causes dynamic links to fail, why is adding the SHA-1 key marked as optional in the console?

**Comment by vendys-sungsik** [comment]
Yes right. i found my mistake. 
It was a problem that is not registed SHA-1 key to my console. 
Thanks every good man 👍

**Comment by samtstern** [comment]
@vendys-sungsik Glad you found your issue.

**Comment by JoCodes** [comment]
Hi , 
I m facing the same issue. Initially I was not having SHA-1 key registered in console. now added. but still I m getting the invite failed ( resultcode =3 ) can you please help

**Comment by ligi** [comment]
Also stumbling into this currently: http://stackoverflow.com/questions/40489697/firebase-appinvites-return-with-resultcode-3
