### ISSUE TITLE
Firebase Token not generating in android

### ISSUE THREAD

**Issue by harmispatel** [firebase/quickstart-android#525]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Moto E Power
  * Android OS version: 6.0
  * Google Play Services version: 4.0.0
  * Firebase/Play Services SDK version: 17.0.0
  
### Step 3: Describe the problem:

FirebaseInstanceId Service not working. onRefreshedToken method is never called even when first time app is install.
I have done all the steps for registering app on firebase. I didn't recognize the issue.
  
#### Observed Results:

  Firebase token not generating.
  
#### Expected Results:

 firebase token has to be generate at first time.

**Comment by rosariopfernandes** [comment]
I have faced a similar issue. What I did was [retrieve the current registration token](https://firebase.google.com/docs/cloud-messaging/android/client#retrieve-the-current-registration-token) when the app starts.

**Comment by samtstern** [comment]
Been a while since I asked for more info (although I should have been faster) so going to close this issue as stale.  Hope it was solved!

**Comment by HoangTri81** [comment]
Help!
I try run test get token on my device: `FirebaseApp.initializeApp(this);FirebaseInstanceId.getInstance().getInstanceId()...`
I get error: java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process com.triaxlogistic.myapplication. Make sure to call FirebaseApp.initializeApp(Context) first
How to fix it?
Note in my build.gradle, i was add `    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-messaging:18.0.0'}

apply plugin: 'com.google.gms.google-services'`
