### ISSUE TITLE
Isn't there any Authentication by email yet?

### ISSUE THREAD

**Issue by jcsla** [firebase/quickstart-android#53]
Hi

I've already checked in email authentication firebase console.

firebase console -> Auth -> email template
you can see those three menus in there.(email authentication, change password, change email address)

But I couldn't see any api in android api document.(email authentication, change email address)
(I found sending change password api)

**Comment by samtstern** [comment]
@jcsla are you looking for Email/Password authentication?  

If so you can find the documentation here:
https://firebase.google.com/docs/auth/android/password-auth

And a sample app here:
https://github.com/firebase/quickstart-android/blob/master/auth/app/src/main/java/com/google/firebase/quickstart/auth/EmailPasswordActivity.java
