### ISSUE TITLE
To save ML Kit models for face recognititon into device's persisted storage

### ISSUE THREAD

**Issue by techievbv** [firebase/quickstart-android#532]
Hi everyone,
I have just started exploring Firebase ML Kit by Google to test out face recognition capabilities. I tried official samples and it's working well.

Though, according to the official documentation, we can schedule an install time download of the ML models required using meta-data tags inside manifest, but I need a way to manually pre-install the models into the Android device's persisted storage itself, so it could be utilized in my app **in Offline scenarios(w/o internet)**. If there is one, it would be of great help for my use case.

Thanks.

**Comment by psanketi** [comment]
You need to download the models just once. Do you estimate that even that
is unlikely?

**Comment by techievbv** [comment]
@psanketi you need to read the question again. This time more carefully. Thanks.

**Comment by psanketi** [comment]
Who's your audience and how do you plan to distribute the apps to your
them? You can possibly build the app locally (during development time) and
then pass it to your audience.

**Comment by techievbv** [comment]
Can't disclose details excep that the target audience will not be installing the app via Play Store, it will be manually distributed.
The scenario to be precise here, is that, the app should work OFFLINE at all times and being able to compare duplicate images.

**Comment by psanketi** [comment]
So seems like you are going to bring your own models. In that case, it could be possible.
Let's continue our discussion on the [SO thread](https://stackoverflow.com/questions/50815020/how-to-save-ml-kit-models-for-face-recognititon-into-devices-persisted-storage/50822872) since we are having the same dialogue there.

**Comment by samtstern** [comment]
Thanks @psanketi and @techievbv for the discussion.  I agree, moving to SO or another forum is best here.
