### ISSUE TITLE
new dynamic links custom domain issue

### ISSUE THREAD

**Issue by norhan-elsawi** [firebase/quickstart-android#533]
i created dynamic link domain example.page.link
i created new dynamic link from console example ==> redirect to google.com
i add meta data image, title, description

issue
====
when i share that link in facebook no meta date appears and facebook deleted it after while as it consider it spam
 please solve this issue

**Comment by samtstern** [comment]
@norhan-elsawi this does not sound like an Android-specific issue or an issue with this repository.  I would recommend contacting Firebase support about this.
