### ISSUE TITLE
Subscription to topic does not return Task

### ISSUE THREAD

**Issue by elvisoric** [firebase/quickstart-android#535]
I was following the code and run into some issues. 
Looking at code I can see that `subscribeToTopic` should return Task but it returns void, regarding that, I can not use this part for adding completion listener to determine whether the subscription succeeded. 

```
FirebaseMessaging.getInstance().subscribeToTopic("news")
        .addOnCompleteListener(new OnCompleteListener<Void>() {
    @Override
    public void onComplete(@NonNull Task<Void> task) {
        String msg = getString(R.string.msg_subscribed);
        if (!task.isSuccessful()) {
            msg = getString(R.string.msg_subscribe_failed);
        }
        Log.d(TAG, msg);
        Toast.makeText(MainActivity.this, msg, Toast.LENGTH_SHORT).show();
    }
});
```

**Comment by powell** [comment]
Have you solved your problem yet? I have the same issue with Oreo devices, my program works fine with Android 7 and lower.

**Comment by elvisoric** [comment]
I was using wrong version of 
`Cloud Messaging | com.google.firebase:firebase-messaging`

From the release notes of Cloud Messaging version 17.0.0:
>> The methods subscribeToTopic() and unsubscribeFromTopic() on FirebaseMessaging now return a Task that can be used to see when the request has completed.
