### ISSUE TITLE
D/FirebaseInstanceId: background sync failed: INVALID_PARAMETERS

### ISSUE THREAD

**Issue by wheel1992** [firebase/quickstart-android#54]
Hi,

I've have successfully registered a device and gotten a device token. 
However, after I tried subscribing a topic, it keeps showing this error " D/FirebaseInstanceId: background sync failed: INVALID_PARAMETERS", and no topic was shown in console for past few hours.

**Comment by samtstern** [comment]
@wheel1992 can you provide some more information:

  * What is the topic name you are subscribing to?  A code snippet would be useful.
  * Are there any other errors in the logs?
  * Are you able to send a message to the topic using the HTTP API? (see example below)

HTTP sending example:
```
curl --header "Authorization: key=$API_KEY" \
       --header Content-Type:"application/json" \
       https://fcm.googleapis.com/fcm/send \
       -d "{ \"to\": \"/topics/foo\", \"notification\": { \"title\": \"Test\", \"text\": \"Hello World\" } }"
```

**Comment by wheel1992** [comment]
Hi Sam,

Thank you for your reply. I've managed to get it working by uninstalling my app on the device. It is kind of weird as Firebase does not register the device after the **first and only the first** installation from Android Studio.
