### ISSUE TITLE
Firebase Invites - sending invitations failed (resultCode=13)

### ISSUE THREAD

**Issue by nikoviljanen** [firebase/quickstart-android#540]
### Environment

  * Android device: Nokia 8
  * Android OS version: Oreo 8.1.0
  * Google Play Services version: 12.6.85
  
### The problem:
I posted this same message on StackOverflow, looking for some help with this issue. https://stackoverflow.com/questions/50900378/firebase-invites-sending-invitations-failed-resultcode-13

I am trying to get Firebase Invites to work, using the example app from here: https://github.com/firebase/quickstart-android/tree/master/invites

When sending an invite the app shows a message saying "Sending invitations failed". The `resultCode `value is **13** in `onActivityResult()`. I can not find any documentation on what this result value means.

Firebase core and invites in the gradle file:

```
implementation 'com.google.firebase:firebase-core:16.0.0'
implementation 'com.google.firebase:firebase-invites:16.0.0'
```

Dynamic links has been enabled in the Firebase console and the debug SHA-1, SHA-256 fingerprints have been added in the console and the app is using the correct google-services.json file.

Any help on this would be appreciated.

**Comment by samtstern** [comment]
@nikoviljanen unfortunately that code (13) is just `ERROR` so there's not much information:
https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes.html#ERROR

Is this issue device-specific or present on all devices?

**Comment by nikoviljanen** [comment]
@samtstern I tried this on an Honor 7 (Lollipop 5.0.2) but the same issue is present.

**Comment by nikoviljanen** [comment]
@samtstern For no apparent reason the issue disappeared yesterday, and the invites are now sent correctly. I have no clue why this is.

**Comment by samtstern** [comment]
@nikoviljanen thanks for the update ... I wish we knew what happened but let us know if it comes back!
