### ISSUE TITLE
com.google.firebase.auth not found 

### ISSUE THREAD

**Issue by munibhamza** [firebase/quickstart-android#546]
I am trying to make a user login and register panel but it was giving me an error that com.google.firebase.auth not found . 
Also when i run my app first time i registered a user and them login that user and It was successful but now it is giving me an error ..
Also attaching the screenshot of error after debugging.
Thanks in advance if anyone could help me resolving this issue 
![screen shot 2018-06-29 at 2 50 29 am](https://user-images.githubusercontent.com/38657444/42063278-4cff0018-7b4a-11e8-832c-efaeb41f28e6.png)

**Comment by samtstern** [comment]
The messages say Google Play services is out of date.  I recommend running this on a real device or an emulator that has the Play store so that you can get auto updates.
