### ISSUE TITLE
FirebaseInstanceIdService is deprecated

### ISSUE THREAD

**Issue by UttamPanchasara** [firebase/quickstart-android#548]
**I'm using : implementation 'com.google.firebase:firebase-messaging:17.1.0'**

when i have extended **FirebaseInstanceIdService** class, it showing that this is **deprecated.**

how should i get refreshed token, as this showing deprecated.

**Comment by rosariopfernandes** [comment]
Cross-posted on [StackOverflow](https://stackoverflow.com/q/51123197/5861618).

As [this answer](https://stackoverflow.com/a/51123913/5861618) suggests, you simply need to override the `onNewToken(String token)` method from the `FirebaseMessagingService` class.

**Comment by pratikbutani** [comment]
Here I wrote something :) :+1: 
[Solution of Deprecated FirebaseInstanceIdService](https://medium.com/android-school/firebaseinstanceidservice-is-deprecated-50651f17a148)

**Comment by samtstern** [comment]
See #556

**Comment by ipsjolly** [comment]
### **Here is Solution explained!** 
[http://www.freakyjolly.com/resolved-firebaseinstanceidservice-is-deprecated/](http://www.freakyjolly.com/resolved-firebaseinstanceidservice-is-deprecated/)
