### ISSUE TITLE
CONTRIBUTING.md needs update

### ISSUE THREAD

**Issue by rosariopfernandes** [firebase/quickstart-android#549]
- The [CONTRIBUTING.md](https://github.com/firebase/quickstart-android/blob/master/CONTRIBUTING.md) in this repository currently asks for browser information on the [issue template](https://github.com/firebase/quickstart-android/blob/master/CONTRIBUTING.md#submitting-an-issue). This is an Android project and does not run on a browser.
- Under [Coding Rules](https://github.com/firebase/quickstart-android/blob/master/CONTRIBUTING.md#-coding-rules) it's also mentioned to follow the [Google JavaScript style guide](http://google.github.io/styleguide/javascriptguide.xml) while this repository is written in Java and (probably) follows the [Google Java style guide](https://google.github.io/styleguide/javaguide.html) instead.

**Comment by samtstern** [comment]
@rosariopfernandes fixed, thank you!
