### ISSUE TITLE
[Firebase remote config] How to change property some fields in color.xml file or dimen.xml file

### ISSUE THREAD

**Issue by tvhieuit** [firebase/quickstart-android#554]
Hello all

I want to make my app dynamic color for all in app, So i want to change color.xml and dimen.xml but I dont know how to use.

Could you help me
```
    <color name="colorPrimary">#000</color>
    <color name="colorPrimaryDark">#000</color>
    <color name="colorAccent">#000</color>
```

Thank you so much

**Comment by anipindie** [comment]
<color name="colorPrimary">#000</color>
    <color name="colorPrimaryDark">#000</color>
    <color name="colorAccent">#000</color>

**Comment by samtstern** [comment]
@tvhieuit by default there is no connection between Remote Config and the theme of your app, you'd have to build that yourself.  Remote Config can only help you get the string values (`#000`, etc) into your code over the air.

If you need help learning how to apply themes at runtime, please ask on StackOverflow.
