### ISSUE TITLE
Firebase Storage: The upload task triggered even the previous task is completed

### ISSUE THREAD

**Issue by ArcherEmiya05** [firebase/quickstart-android#555]
My scenario is that I was uploading 2 video the first item is about 150mb+ and the second one is about 70mb+. While uploading I closed the app then removed it from Recent App. Sometimes the task gets killed thus restarting the upload task when returning to the app. The 70mb+ upload video task  is complete while the 150mb+ upload video task is still on going. Instead of downloading the 70mb+ what I did is to close the app again and remove it to Recent App. Then again I launch the app, at this point the 150mb+ upload video task was restart together with the previous completed task which is the 70mb+ video. The bottom line becomes once the tasks is complete then I will have 3 video file in my database. One is 150mb+ and a duplicate 70mb+. My idea is to mark every complete upload task so that when I return to the activity it will not try to upload a task again that is already completed.

**Comment by samtstern** [comment]
@ArcherEmiya05 this does not sound like a bug with this repository or in the Firebase Android SDK.  Please post this question to StackOverflow for help with your application logic.
