### ISSUE TITLE
Shorten link is not returning complete long URL

### ISSUE THREAD

**Issue by Yugalmodi** [firebase/quickstart-android#560]
### Describing environment
  * Android device: Any
  * Android OS version: 6+
  * Google Play Services version: 16.0.1
  * Firebase/Play Services SDK version: 16.0.1

### Describing Problem

I am passing below example long link for shorten and it's shorten successfully but while i am clicking that shorten link. It's returning only below result long link.

##**NOTE:** All below links are just dummy example link for understanding purpose. 

**Original Long Link:**  "https://play.google.com/store/apps/details?id=com.example&referrer=referral_medium%3DAndroid_App%26referral_id%3D12345"

**Shorten Link:**  "https://example.page.link/8EdwL6vuiG7SkbC57"

**Result long link after clicking shorten link:** ""https://play.google.com/store/apps/details?id=com.example.app"
  

### Sample Code

I am using below code for convert long link into short link.

        final String shortLink ;
        final String longUrl = "https://play.google.com/store/apps/details?id=com.example&"+
                               "referrer=referral_medium%3DAndroid_App%26referral_id%3D12345"

        FirebaseDynamicLinks.getInstance().createDynamicLink()
                .setLongLink(Uri.parse("https://example.page.link/?link=" +longUrl))
                .buildShortDynamicLink()
                .addOnCompleteListener(this, new OnCompleteListener<ShortDynamicLink>() {
                    @Override
                    public void onComplete(@NonNull Task<ShortDynamicLink> task) {
                        if (task.isSuccessful()) {
                            // Short link created
                            shortLink = task.getResult().getShortLink());
                        } else {
                        }
                    }
                });

**Comment by samtstern** [comment]
@Yugalmodi thanks for reporting this!  I will ask the Dynamic Links team and see what the possible explanation could be.

**Comment by samtstern** [comment]
@Yugalmodi here's the response I got, hope it helps:

> https://firebase.google.com/docs/dynamic-links/create-manually
> I think that longUrl needs to be URL encoded.
> 
> `setLongLink(Uri.parse("https://example.page.link/?link=" + URLEncoder.encode(longUrl, "UTF-8")))`
> Or use an `Uri.Builder and appendQueryParameter()`, which URL encodes automatically.

**Comment by Yugalmodi** [comment]
Thanks for the response. It is working fabulous.
