### ISSUE TITLE
Testing with a local instance of the Cloud Functions Emulator

### ISSUE THREAD

**Issue by thatfiredev** [firebase/quickstart-android#562]
The [version 16.1.0](https://firebase.google.com/support/release-notes/android#version_1610) of the Cloud Functions Client SDK now allows us to test against a local instance of the Cloud Functions Emulator by using `useFunctionsEmulator()`.

It would be nice to have a snippet showing this method's usage and maybe also include a link pointing to the [Functions Emulator Docs](https://firebase.google.com/docs/functions/local-emulator).

**Comment by samtstern** [comment]
@rosariopfernandes thanks for the suggestion!  This is definitely something we should do.

**Comment by jQrgen** [comment]
Any updates on this?

**Comment by jQrgen** [comment]
How to get logs? 📦

**Comment by jQrgen** [comment]
Thanks! works now

**Comment by deimantasa** [comment]
After building my emulator 
`firebase emulators:start --only functions`
And trying to run on Android, 
`firebaseFunctions.useFunctionsEmulator(origin: "http://10.0.2.2:5001");`
I get an issue
` Firebase Exception: [firebase_functions/unavailable] UNAVAILABLE`


If I run it via postman on `localhost:5001` - it works.

**Comment by samtstern** [comment]
@deimantasa can you try [this method](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions#useEmulator(java.lang.String,%20int))

```java
firebaseFunctions.useEmulator("10.0.2.2", 5001)
```

**Comment by deimantasa** [comment]
> @deimantasa can you try [this method](https://firebase.google.com/docs/reference/android/com/google/firebase/functions/FirebaseFunctions#useEmulator(java.lang.String,%20int))
> 
> ```java
> firebaseFunctions.useEmulator("10.0.2.2", 5001)
> ```

There is no secondary param anymore - only one `origin`.
![image](https://user-images.githubusercontent.com/12739071/106478432-c7f0e200-64db-11eb-9e44-06a35a295e70.png)


Am currently on `cloud_functions: ^0.9.0`.

**Comment by deimantasa** [comment]
There if no such method and params anymore - I suspect it was cut off for some reason.
![image](https://user-images.githubusercontent.com/12739071/106478684-08506000-64dc-11eb-847d-c76caa4245cb.png)

![image](https://user-images.githubusercontent.com/12739071/106478648-fbcc0780-64db-11eb-9f43-d6abc1b8fdf7.png)


Currently I'm on `cloud_functions: ^0.9.0`.

**Comment by samtstern** [comment]
@deimantasa looks like you're using FlutterFire?  Please file an issue on their GitHub repo, this repo is for the Android SDK quickstarts.

**Comment by Abhishek01039** [comment]
Hello @samtstern 
https://github.com/firebase/quickstart-android/issues/562#issuecomment-607819116
This is working fine in android.
what about ios stuff?
do we need to do anything in info.plist file ?

**Comment by thatfiredev** [comment]
Closing this issue as it is now well-documented here: https://firebase.google.com/docs/emulator-suite/connect_functions#android
