### ISSUE TITLE
have you plans to support rxjava2?

### ISSUE THREAD

**Issue by candrwow** [firebase/quickstart-android#572]
Hello,I use rxjava2 in my app develop,sometimes `firebaseFunctions.getHttpsCallable("queryUserInfoByUid")
                    .call()
                    .continueWith(task -> {`
code like this,I change it by wrap rxjava,this way cause some error can  capture very well,have you plans to support rxjava2?
by use getHttpsCallable I also don't understand thread switching very well,maybe it can run not switch thread manual beacuse it switch auto in code inside？I think this cause switch many times repeated by using rxjava2 wrap it.

**Comment by samtstern** [comment]
@candrwow thanks for the feedback.

We don't have specific plans for the `Tasks` library to support RxJava but we do understand the desire.

cc @aaronj1335 who would probably want to hear about this.
