### ISSUE TITLE
FirebaseRecyclerAdapter

### ISSUE THREAD

**Issue by dwlrathod** [firebase/quickstart-android#58]
Where is FirebaseRecyclerAdapter class ?

**Comment by yishai-glide** [comment]
there is no class with that name, what exactly are you trying to do?

**Comment by dwlrathod** [comment]
import com.firebase.ui.database.**FirebaseRecyclerAdapter**;

See this in 
database/fragment/**PostListFragment.java**

**Comment by yishai-glide** [comment]
it's part of this project that is in build.gradle https://github.com/firebase/quickstart-android/blob/master/database/app/build.gradle#L35

for more, here is the repo: https://github.com/firebase/FirebaseUI-Android

**Comment by dwlrathod** [comment]
Ya I know it's part of project but where it is?
It should be in 
[https://github.com/firebase/quickstart-android/tree/master/database/app/src/main/java/com/google/firebase/quickstart/database](url)

But the is not !!!

**Comment by yishai-glide** [comment]
do you know how the gradle build system works?
here is your class and it's being imported as a library via gradle
https://github.com/firebase/FirebaseUI-Android/blob/master/database/src/main/java/com/firebase/ui/database/FirebaseRecyclerAdapter.java

**Comment by dwlrathod** [comment]
Thanks !
