### ISSUE TITLE
firestore add new document performance is not very good

### ISSUE THREAD

**Issue by candrwow** [firebase/quickstart-android#580]
I use console.log(Date.now()) to watch this code:

` resolve(db.collection("Coin").add(data));`
this is nodejs javascript in Promise,this line add a new doc need 2000ms or more,always. my function spend almost all the time on this line.can you help me how to optimize the code，thank you very much.

my firestore is in test,the collection "Coin" is new and No more than 10 doc.I feel when I use add to a new UserInfo doc,is also slow,but not 2000ms,sometimes are 700ms+
![qq20180803-220151](https://user-images.githubusercontent.com/14042320/43647075-2b8301ba-9769-11e8-91bd-8589bb08e0ae.png)

**Comment by samtstern** [comment]
@candrwow this issue describes using Cloud Functions to write to Firestore.  This repo is for the Android quickstart, so it's not the right place to discuss this.

You may want to open an issue here:
https://github.com/firebase/firebase-admin-node
