### ISSUE TITLE
getHeadEulerAngleY() Always Returns Zero

### ISSUE THREAD

**Issue by skipe777** [firebase/quickstart-android#587]
Test Device:
  * Android device: Samsung Galaxy S7
  * Android OS version: 7.0
  * Google Play Services version: 49
  * Firebase/Play Services SDK version: 16.0.1
  
I am running the ML Kit Face Detection Sample project. Inside the project I modified the updateFace method of the FaceGraphic.java class to print out the orientation information from the faces. 

  ```
System.out.println("Face Orientation: " + face.getHeadEulerAngleY() + ", " + face.getHeadEulerAngleZ());
```

I am running the Live Preview mode inside the app so testing off a video stream not a still image. I have tested using the front camera and back camera with same results. getHeadEulerAngleY() always returns 0 while getHeadEulerAngleZ() works just fine.

What am I doing wrong?

Update w/Answer:

I did not catch the statement in the documentation that it needed to be set to ACCURATE mode. I was using the default (FAST) and it does not calculate Y only Z. NOTE: I actually found that information on the MobileVision wiki and it applied here as well (https://github.com/googlesamples/android-vision/issues/79)

**Comment by samtstern** [comment]
cc @isaisachen @gkaldev

**Comment by samtstern** [comment]
Thanks @isaisachen !
