### ISSUE TITLE
How to know the data sent to the database has reached successfully?

### ISSUE THREAD

**Issue by rockink** [firebase/quickstart-android#59]
mDatabase = FirebaseDatabase.getInstance().getReference();
        Task<Void> base = mDatabase.child("demo").child(id).setValue(story);

        Log.d(TAG, "getEditTextVals: This is after base");
        if(base.isComplete()){

            Log.d(TAG, "getEditTextVals: completed");

        }
        if (base.isSuccessful()){
            Log.d(TAG, "getEditTextVals: successful");
            Intent intent = new Intent(getApplication(), MainActivity.class);
            startActivity(intent);
            finish();

        }

What this doesn't do is, it doesn't call isComplete, or isSuccessful, meaning those are all `fasle`.

**Comment by samtstern** [comment]
@rockink when a method returns a `Task` that means it is an async operation.  In your code you are checking `isComplete` or `isSuccessful` immediately, so the operation has not completed yet and it will not be completed or successful.

Instead you need to attach a listener to the task, like this:
```
base.addOnCompleteListener(new OnCompleteListener<Void>() {
    @Override
    public void onComplete(@NonNull Task<Void> task) {
        if (task.isSuccessful()) {
            // Task completed successfully
        } else {
            // Task failed with an exception
            Exception exception = task.getException();
        }
    }
});
```
