### ISSUE TITLE
Quick Start Example Cloud Messaging onMessageReceived never called

### ISSUE THREAD

**Issue by mrkhanakia** [firebase/quickstart-android#590]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: Emulator Nexux
  * Android OS version: Oreo 8
  * Google Play Services version: 4.0.2
  * Firebase/Play Services SDK version: 16.0.1
  
### Step 3: Describe the problem:
I am using QUICK Start MESSAGING example everything is working as excepted but custom sendNotification function is not firing and it is not showing anything.

https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java
#### Steps to reproduce:
Just use the quick start example
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

It should log the output as mentioned in the quick start example
  
#### Relevant Code:

  ```
  public void onMessageReceived(RemoteMessage remoteMessage) {
        // [START_EXCLUDE]
        // There are two types of messages data messages and notification messages. Data messages are handled
        // here in onMessageReceived whether the app is in the foreground or background. Data messages are the type
        // traditionally used with GCM. Notification messages are only received here in onMessageReceived when the app
        // is in the foreground. When the app is in the background an automatically generated notification is displayed.
        // When the user taps on the notification they are returned to the app. Messages containing both notification
        // and data payloads are treated as notification messages. The Firebase console always sends notification
        // messages. For more see: https://firebase.google.com/docs/cloud-messaging/concept-options
        // [END_EXCLUDE]

        // TODO(developer): Handle FCM messages here.
        // Not getting messages here? See why this may be: https://goo.gl/39bRNJ
        Log.d(TAG, "From: " + remoteMessage.getFrom());



        // Check if message contains a data payload.
        if (remoteMessage.getData().size() > 0) {
            Log.d(TAG, "Message data payload: " + remoteMessage.getData());

            if (/* Check if data needs to be processed by long running job */ true) {
                // For long-running tasks (10 seconds or more) use Firebase Job Dispatcher.
                scheduleJob();
            } else {
                // Handle message within 10 seconds
                handleNow();
            }

        }

        // Check if message contains a notification payload.
        if (remoteMessage.getNotification() != null) {
            Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification().getBody());
            sendNotification("CUSTOM NOTIFICATION");
        }




        // Also if you intend on generating your own notifications as a result of a received FCM
        // message, here is where that should be initiated. See sendNotification method below.
    }
  ```

**Comment by AhmadullahSaikat** [comment]
I also faced the same problem with firebase latest dependencies.
Any solution?

**Comment by kroikie** [comment]
@mrkhanakia the custom `sendNotification` method is not called in the quickstart, it is only for demonstration purposes.

In the title you mention that onMessageReceived is not being called. Could you confirm this and also include how you are sending the message?

**Comment by mrkhanakia** [comment]
Yes i know **sendNotification** method is not called but please check above code i gave i called the method manually already under **OnMessageReceived** method

```
.... above code

 // Check if message contains a notification payload.
      if (remoteMessage.getNotification() != null) {
          Log.d(TAG, "Message Notification Body: " + remoteMessage.getNotification().getBody());
          sendNotification("CUSTOM NOTIFICATION");
      }

.......

**Comment by ahctangU** [comment]
Actually I was following the documentation. It states that a when a notification event is received while the app is in the foreground, onMessageReceived should be invoked, but it is never invoked.

Everything else works as expected but this important aspect of the quick start doesn't work. Could you please take a look at this.

**Comment by ahctangU** [comment]
I had to do the following in order for the MyFirebaseMessagingService to be invoked properly when I was using the Java Main Activity.

`
        
        <activity android:name=".java.MainActivity" />
        
            
            
            
                
            
        

        
            
                
            
        

        
        <service android:name=".java.MyFirebaseMessagingService">
            <intent-filter>
                <action android:name="com.google.firebase.MESSAGING_EVENT" />
            </intent-filter>
        </service>
        
        <service
            android:name=".java.MyJobService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.firebase.jobdispatcher.ACTION_EXECUTE" />
            </intent-filter>
        </service>
`

**Comment by samtstern** [comment]
@ahctangU thanks for that!  I clarified this issue in this commit:
https://github.com/firebase/quickstart-android/commit/af0ce4d301dcaa877ac33b654ef62e473989c963

**Comment by kroikie** [comment]
Looks like only one for the `MyFirebaseMessagingService` can be started for an incoming message. If both kotlin and java services are defined it is not predictable which one will be used for the incoming message. In my testing the first one defined in the AndroidManifest is the one that is used.

I'll update the README to ensure that to be sure the correct `MyFirebaseMessagingService` is used comment the appropriate service definition.

**Comment by samtstern** [comment]
Actually finished in #811 (the commit I referenced before had a small mistake)
