### ISSUE TITLE
.fetch() is not calling onComplete or onFailure 

### ISSUE THREAD

**Issue by basel93natour** [firebase/quickstart-android#592]
i used the firebase remote config yesterday and it was working perfectly but today i'm facing this problem that .fetch function doesnt throw any exception but at the same time i'm not getting any response 
this is my code : 

       FirebaseApp.initializeApp(context)
        var mFirebaseRemoteConfig = FirebaseRemoteConfig.getInstance()

        val configSettings = FirebaseRemoteConfigSettings.Builder()
                .setDeveloperModeEnabled(true)
                .build()
        mFirebaseRemoteConfig.setConfigSettings(configSettings)
        Handler().postDelayed({
            mFirebaseRemoteConfig.fetch(0)
                    .addOnCompleteListener(this@LoginActivity, object : OnCompleteListener<Void> {
                        override fun onComplete(task: Task<Void>) {
                            mFirebaseRemoteConfig.activateFetched()
                            val version_number = mFirebaseRemoteConfig.getString("version_number")
                            val version_code = mFirebaseRemoteConfig.getString("version_code")
                            checkforUpdates(version_number,version_code.toInt())
                        }
                    })

        },1000)

i called after 1 min based on : https://stackoverflow.com/a/37664946

and this is my log : 

08-10 11:33:39.567 13612-13612/com.datamicron.fertilizer D/FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
08-10 11:33:39.577 13612-13612/com.datamicron.fertilizer D/FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
08-10 11:33:39.597 13612-13612/com.datamicron.fertilizer I/FirebaseInitProvider: FirebaseApp initialization successful
08-10 11:33:39.647 13612-13642/com.datamicron.fertilizer I/FA: App measurement is starting up, version: 12211
    To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
    To enable faster debug mode event logging run:
      adb shell setprop debug.firebase.analytics.app com.datamicron.fertilizer
08-10 11:33:56.387 13612-13642/com.datamicron.fertilizer D/FA: Logging event (FE): screen_view(_vs), Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=LoginActivity, firebase_screen_id(_si)=5626414866587644433}]
08-10 11:33:57.917 13612-13642/com.datamicron.fertilizer V/FA: Logging event: origin=auto,name=screen_view(_vs),params=Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=LoginActivity, firebase_screen_id(_si)=5626414866587644433}]
08-10 11:33:57.937 13612-13642/com.datamicron.fertilizer V/FA: Saving event, name, data size: screen_view(_vs), 58
    Event recorded: Event{appId='com.datamicron.fertilizer', name='screen_view(_vs)', params=Bundle[{firebase_event_origin(_o)=auto, firebase_screen_class(_sc)=LoginActivity, firebase_screen_id(_si)=5626414866587644433}]}

**Comment by basel93natour** [comment]
sorry its my fault

**Comment by basel93natour** [comment]
ok i figurd out what the problem is ,the next day i was trying my application on a new device which doesnt have any google account yet so this means if the user mobile doesnt have google account the firebase wont return anything

**Comment by ppamorim** [comment]
I am getting the same error. The workaround:

https://stackoverflow.com/questions/37556144/firebase-storage-firebaseapinotavailableexception-repeatedly-in-the-log-when-off

tltd; You need to include the dependency of `firebase-auth`.
