### ISSUE TITLE
Domain is being released. Please retry in one month.

### ISSUE THREAD

**Issue by sankar-novel** [firebase/quickstart-android#595]
When i try to create a domain for my dynamic link in firebase the following error  message occurs. "Domain is being released. Please retry in one month."

**Comment by samtstern** [comment]
@sankar-novel please contact [Firebase Support](firebase.google.com/support) for issues like this.

**Comment by noway** [comment]
"Please retry in one month" - what a sick joke of an error message. Might as well find another service in that time. 

This is not acceptable DX.

**Comment by devDeejay** [comment]
Really have to wait a month to reuse a domain which i accidentaly removed? You have got to be kidding me Firebase

**Comment by ekramul-1** [comment]
Same issue as I also did the same mistake

**Comment by ethanwlo** [comment]
Same issue here...

**Comment by akillika** [comment]
Same issue and still they didn't fix it event after Nov 2021.

**Comment by kushal-panchal28** [comment]
Faced same issue..
Please put the solution if we get it from firebase

**Comment by akillika** [comment]
> Faced same issue..
> Please put the solution if we get it from firebase

I got reply from Firebase after a month stating that they have unblocked the domain! Can't believe that firebase is in this condition!

**Comment by jalvini** [comment]
Same issue. This is terrible implementation

**Comment by flavioa44** [comment]
Got the same issue!

**Comment by OE-Ahmed** [comment]
I found an alternative solution for it & fixed it.

**Comment by QuentinSc** [comment]
how? :o

**Comment by RohovDmytro** [comment]
@OE-Ahmed do you mind sharing? :)
