### ISSUE TITLE
How can I clone this project?

### ISSUE THREAD

**Issue by paragones** [firebase/quickstart-android#60]
Hi guys, 

I am sorry for being a noob at the moment. I tried to clone the whole project to try and test it out. 
But when I tried to clone it using Android Studio 2.1.2 `(Checkout From Version Control -> Github -> https://github.com/firebase/quickstart-android.git -> Create project from existing sources )`, I just got a series of folders but couldn't run it. 

I am having a problem with the Gradle if I chose 

> "Import project from external model"

 saying 

> "The project is using an unsupported version of Gradle. Please point to a supported Gradle version in the project's Gradle settings or in the project's Gradle wrapper (if applicable.)"

So I am quite at a loss on how to try cloning the project and see how this works. Hope someone with a good soul can help out. Thanks!

**Comment by samtstern** [comment]
@paragones no problem, newcomers welcome :+1: 

Try this:

  * Run `git clone https://github.com/firebase/quickstart-android` to get the project on your machine. This will create a directory called `quickstart-android` wherever you run the command.
  * In Android Studio select **File** > **Open**
    * Find the `quickstart-android` folder on your machine
    * Select the subfolder of the quickstart app you'd like to open (for instance `quickstart-android/database`)
    * Select the `build.gradle` file in that subfolder and click **OK** to import the project.

**Comment by paragones** [comment]
Got it. Thanks!
