### ISSUE TITLE
警告: 无法找到类型 'GuardedBy' 的注释方法 'value()'

### ISSUE THREAD

**Issue by LiuDongCai** [firebase/quickstart-android#601]
Kotlin compiler
w: C:\Users\10583\.gradle\caches\transforms-1\files-1.1\firebase-iid-17.0.0.aar\1b373d571bd213bb73244c09400435c8\jars\classes.jar(com/google/firebase/iid/FirebaseInstanceId.class): 警告: 无法找到类型 'GuardedBy' 的注释方法 'value()'
w: C:\Users\10583\.gradle\caches\transforms-1\files-1.1\firebase-common-16.0.1.aar\7e380ab91344a09a19543f405de9f9c5\jars\classes.jar(com/google/firebase/FirebaseApp.class): 警告: 无法找到类型 'GuardedBy' 的注释方法 'value()'
……
My Android Studio Version ： 3.1.3
Firebase Version:
implementation 'com.google.firebase:firebase-core:16.0.1'
implementation 'com.google.firebase:firebase-messaging:17.3.0'
implementation 'com.google.firebase:firebase-perf:16.1.0'

**Comment by LiuDongCai** [comment]
My build.gradle:

apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.google.firebase.firebase-perf'
apply plugin: 'bugly'
apply plugin: 'kotlin-kapt'

**Comment by samtstern** [comment]
@LiuDongCai a few things here:

- Unfortunately nobody who maintains this repo speaks Chinese so we have to ask that all issues are filed in English.
- There's not enough information here to explain what's going on, what you expected to happen, and what code is causing the problem.

Could you please file a new issue and fill out the whole issue template and keep in mind the points above?  Thank you!
