### ISSUE TITLE
Firebase invitations: SMS 20 chars longer does not send

### ISSUE THREAD

**Issue by dan-leech** [firebase/quickstart-android#602]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: ASUS_Z012DA
  * Android OS version: 8.0.0
  * Google Play Services version: 13.2.70
  * Firebase/Play Services SDK version: 16.0.1
    compile 'com.google.android.gms:play-services-auth:11.8.0'
    compile 'com.google.android.gms:play-services-identity:11.8.0'
    compile 'com.google.firebase:firebase-core:16.0.1'
    compile 'com.google.firebase:firebase-invites:16.0.1'
    compile 'com.google.firebase:firebase-dynamic-links:16.0.1'
    compile 'com.google.android.gms:play-services-tagmanager:16.0.1'
    compile 'com.google.firebase:firebase-messaging:17.3.0'
    compile 'com.google.firebase:firebase-crash:16.0.1'
    compile 'com.google.firebase:firebase-config:16.0.0'
    compile 'com.google.firebase:firebase-perf:16.1.0'
  
### Step 3: Describe the problem:
Firebase invites doesn't send long sms. Sms appears in outbox but have not been received by recipient.

#### Steps to reproduce:

  1. Intent intent = new AppInviteInvitation.IntentBuilder("Some title")
                .setMessage(""I invite you join my group \"Name of my group GroupName\" group code #12345678"")
                .setDeepLink("http://my.app?data=some_data")
                .build();
        startActivityForResult(intent, REQUEST_INVITE);
  
#### Observed Results:

 D/CordovaActivity: Incoming Result. Request code = 48
D/CordovaInterfaceImpl: Sending activity result to plugin
V/FA: Connecting to remote service
V/FA: Activity resumed, time: 4014731
D/CordovaActivity: Resumed the activity.
D/SystemWebChromeClient: file:///android_asset/www/js/15.ab18d24c.js: Line 1 : Invitation ID's: ["11504607883-a2aee0fb-bea2-4215-a487-a34e312ef77f"]
I/chromium: [INFO:CONSOLE(1)] "Invitation ID's: ["11504607883-a2aee0fb-bea2-4215-a487-a34e312ef77f"]", source: file:///android_asset/www/js/15.ab18d24c.js (1)
D/FA: Connected to remote service
V/FA: Processing queued up service tasks: 1
V/FA: Inactivity, disconnecting from the service
  
#### Expected Results:

  * I espect that recipient got the message.
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
Intent intent = new AppInviteInvitation.IntentBuilder("Some title")
                .setMessage(""I invite you join my group \"Name of my group GroupName\" group code #12345678"")
                .setDeepLink("http://my.app?data=some_data")
                .build();
        startActivityForResult(intent, REQUEST_INVITE);
  ```

**Comment by samtstern** [comment]
@dan-leech does this depend on the number you're sending it to?  Does it reliably work with 19 characters?

**Comment by dan-leech** [comment]
@samtstern
I've tested it with USA number and two Russian numbers. The problem is the same.
Yes short messages send successfully. (I noticed this message only today, and doubt a bit about exact length. I set 19 and it work well. But with long message as in example it doesn't.)

**Comment by samtstern** [comment]
Hi @dan-leech.  As of this week, Firebase Invites is deprecated.  This means we won't be fixing any bugs or making any new features.  Please see the documentation for information on how to migrate away from Invites and contact Firebase Support if this creates a problem for you:
https://firebase.google.com/docs/invites/
