### ISSUE TITLE
In App messaging won't compile with Cloud Firestore

### ISSUE THREAD

**Issue by the-dagger** [firebase/quickstart-android#608]
* Android device: Pixel 2 XL
  * Android OS version: 9.0
  * Google Play Services version: 4.0.0
  * Firebase/Play Services SDK version: 17.1.0 
  
### Describe the problem:
On adding the In-App dependency with Cloud Firestore, the project doesn't build with the following error : 
```
Error: Program type already present: com.google.a.a.a.a.zza
```

#### Steps to reproduce:

Add the dependencies for Cloud Firestore and In-App Messaging.
```
implementation 'com.google.firebase:firebase-inappmessaging-display:17.0.0'
implementation 'com.google.firebase:firebase-firestore:17.1.0'
```
  
#### Expected Results:

The project should build as expected.
  
#### Additional info: 
Firebase Plugin version : 1.1.5

**Comment by samtstern** [comment]
@the-dagger yeah this is a known issue :-/ we're working on it!  Nothing you can do besides downgrading Firestore (which may work by luck) or waiting for our next patch release.

**Comment by the-dagger** [comment]
Got it, thanks for the heads up!

**Comment by samtstern** [comment]
`17.0.1` has been released and should solve this!

**Comment by the-dagger** [comment]
Awesome!

Best,
Harshit Dwivedi
https://harshit.app
<https://mailtrack.io/trace/link/4eb378ec1ae620fd5d6f83cf2283823aced9cfd9?url=https%3A%2F%2Fharshit.app&userId=531655&signature=6dbe406ad00a4786>
