### ISSUE TITLE
Compilation fails with androidx.databinding:databinding-compiler:3.2.0-rc02

### ISSUE THREAD

**Issue by dakdroid** [firebase/quickstart-android#611]
Error: Duplicate zip entry
There's a duplicate of Absent.java from the guava library.
Enable proguard and databinding:

```
defaultConfig {
    multiDexEnabled = true
    dataBinding {
        enabled = true
    }
} 

buildTypes {
    release {
        minifyEnabled = true 
    }
}
```

I deleted unnecessary nodes here:

\--- androidx.databinding:databinding-compiler:3.2.0-rc02
     +--- androidx.databinding:databinding-compiler-common:3.2.0-rc02
     |    +--- com.google.guava:guava:23.0

+--- com.google.firebase:firebase-inappmessaging:17.0.1
|    |    +--- io.grpc:grpc-okhttp:1.12.0
|    |    |    +--- io.grpc:grpc-core:[1.12.0] -> 1.12.0
|    |    |    |    +--- com.google.guava:guava:20.0

**Comment by samtstern** [comment]
@dakdroid what happens if you add a direct dependency on `com.google.guava:guava:23.0` in your `build.gradle`.  Does that fix it?

**Comment by dakdroid** [comment]
This doesn't help and wouldn't be a fix at all.

**Comment by samtstern** [comment]
@dakdroid are you still having this issue?  Apologies for my late response.  If you are can you please paste the error message you're getting?

**Comment by dakdroid** [comment]
@samtstern 
`Warning: Exception while processing task java.io.IOException: Can't write [/Users/stefanpledl/Android/LocalCast/localCast/build/intermediates/transforms/proguard/playstore/release/0.jar] (Can't read [/Users/stefanpledl/Android/LocalCast/dynamic_feature_cloud/build/intermediates/merged-classes/release/classes.jar(;;;;;;;**.class)] (Duplicate jar entry [com/google/common/base/a.class]))`

Full log:
https://github.com/dakdroid/pastes/blob/master/inappmessaging

**Comment by samtstern** [comment]
@dakdroid closing this issue since the lack of recent responses makes me assume that you figured it out.  If that's not the case please let me know and I will re-open the discussion.
