### ISSUE TITLE
[Internal] Translate mlkit app to kotlin

### ISSUE THREAD

**Issue by samtstern** [firebase/quickstart-android#635]
See #557

**Comment by rosariopfernandes** [comment]
I'll be handling this one.

**Comment by samtstern** [comment]
I just started looking at `firestore` and I think the process I used for `inappmessaging` was probably too simple for the more complex quickstarts

**Comment by rosariopfernandes** [comment]
I understand. Do you prefer I wait for you to make this change before I start making changes?

**Comment by samtstern** [comment]
Or if you come up with something better, feel free to experiment!
