### ISSUE TITLE
Save and Deleting temporary Data from Firebase ?

### ISSUE THREAD

**Issue by shs442000** [firebase/quickstart-android#649]
simply i want to create a Tow-player questions game the first one who invites and creates the room and prepare all questions on the client side and the second will accept the invite and once the game has ended i dont need these questions anymore .. So What I supposed to do ?

Should I upload the data to RealtimeDatabase and fetch it to the other player and once the game has done the data will be deleted ? is that supposed to be heavy on the DB to load and delete data every time ??

What about Firebase Cloud functions and Messaging should them help me ?

**Comment by samtstern** [comment]
@shs442000 apologies we did not get back to you sooner.  This type of question should either be asked on StackOverflow or the firebase-talk Google Groups mailing list.  Good luck!
