### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by alexd555** [firebase/quickstart-android#650]
Hi,

I can't find the code of login.
Could you point ?
https://github.com/firebase/quickstart-android/tree/master/firestore

**Comment by samtstern** [comment]
The firestore quickstart uses the FirebaseUI library for sign in, it's called here:
https://github.com/firebase/quickstart-android/blob/master/firestore/app/src/main/java/com/google/firebase/example/fireeats/java/MainActivity.java#L267

To learn more about the library:
https://firebaseopensource.com/projects/firebase/firebaseui-android/auth/readme.md/
