### ISSUE TITLE
login with facebook

### ISSUE THREAD

**Issue by alexd555** [firebase/quickstart-android#657]
HI,

I done all configuration but I got error:
"Given URL is not allowed by the Application configuration.: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains."

I google it and I need to add platform.
When I add android platform then I need to enter hash. 
keytool -exportcert -alias YOUR_RELEASE_KEY_ALIAS -keystore YOUR_RELEASE_KEY_PATH | openssl sha1 -binary | openssl base64

Could you help ? I don't know what I need to do.
I tried to change firestore example.

Thanks,
Alex

**Comment by alexd555** [comment]
Please help me.

**Comment by samtstern** [comment]
@alexd555 looks like you're getting an error message from Facebook explaining what you need to do, so I don't think this is an issue with the quickstart.  Have you tried asking on StackOverflow?
