### ISSUE TITLE
Firebase traces not showing any trace in last 24 hours?

### ISSUE THREAD

**Issue by sudhanshugaur4** [firebase/quickstart-android#679]
Firebase trace showing no network traces in last 24 hours, but I have opened my app many times.

Does Firebase only capture traces when the app is not in debug mode?

**Comment by sudhanshugaur4** [comment]
Hii, currently when I am checking for last 24 Hours I can see my traces, but the thing is why this data was not showing when I was trying 2 hours ago? Also when I am checking for the time of the traces they are between 5-7 PM that's why they must have included 2 hours ago too? Is this a bug or normal behaviour? Thanks.

**Comment by samtstern** [comment]
@sudhanshugaur4 I apologize that nobody ever responded here!  In general when you have issues specific to your project (especially missing data) please contact Firebase support:
https://firebase.google.com/support/
