### ISSUE TITLE
Adaptive icons couldn't show in push notification on Android O

### ISSUE THREAD

**Issue by allanzhu1** [firebase/quickstart-android#685]
I use the launcher icon as the push notification large icon. On android O, I use adaptive icon, but it wouldn't show it in push notification. If I use it as the small icon, it will just show a circle with primary color.

**Comment by allanzhu1** [comment]
Update: 
I found this will help to fix notification when app is foreground. https://stackoverflow.com/questions/44447056/convert-adaptiveicondrawable-to-bitmap-in-android-o-preview

But I couldn't find any way to set the large icon when app is in background. Put <meta-data> in Manifest will only works for status icon and small icon, but not the large icon. Does any one know how to set overwrite the large icon when app is in background. thanks!

**Comment by samtstern** [comment]
cc @kroikie

**Comment by allanzhu1** [comment]
As far as I can tell, large icon can only set for data message when app is in background.

**Comment by kroikie** [comment]
@allanzhu1 you are correct. Currently if you want to use a large icon for the messages you receive from FCM then you should send data-messages then build your notification in `onMessageReceived` callback.
