### ISSUE TITLE
Firebase Auth 16.0.4 - No GoogleSignIn, GoogleSignInClient

### ISSUE THREAD

**Issue by DarrylDJohnson** [firebase/quickstart-android#692]
### Step 1: Are you in the right place?

  * For issues or feature requests related to the code **in this repository** file a Github issue.
    * If you are filing an issue about **FCM in the background** make sure to read [#4](https://github.com/firebase/quickstart-android/issues/4) and [#89](https://github.com/firebase/quickstart-android/issues/89) first!
  * For general technical questions, post a question on [StackOverflow](http://stackoverflow.com/) tagged appropriately.
  * For general Firebase discussion, use the [firebase-talk google group](https://groups.google.com/forum/#!forum/firebase-talk)
  * For help troubleshooting your application that does not fall under one of the above categories, reach out to the [personalized Firebase support channel](https://firebase.google.com/support/contact/troubleshooting/)

### Step 2: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: com.google.gms:google-services:3.2.1
  * Firebase/Play Services SDK version: com.google.firebase:firebase-auth:16.0.4
  
### Step 3: Describe the problem:

The Firebase Docs say Firebase Auth Version 16.0.4 is available, but when using this version, I guess the library couldn't find GoogleSignIn and GoogleSignInClient classes

#### Steps to reproduce:

I used the same code in the quickstart and updated the auth to version 16.0.4 
  
#### Observed Results:

  * What happened? Unresolved reference: GoogleSignInOptions, Unresolved reference: GoogleSignInClient

  
#### Expected Results:

  * What did you expect to happen? To be able to use the newest version of Firebase Auth
 
#### Relevant Code:

  ```
  // TODO(you): my code is exactly the same as the Kotlin Quickstart for Auth
  ```

**Comment by samtstern** [comment]
@DarrylDJohnson I am going to close this issue since none of the requested information was filled out.

If you're having trouble finding the `GoogleSignInClient` and other GSI-related classes, you need the `play-services-auth` library in addition to the `firebase-auth` library.
