### ISSUE TITLE
More idiomatic Kotlin code

### ISSUE THREAD

**Issue by samtstern** [firebase/quickstart-android#698]
We were right called out by the one and only SUPERCILEX for having some Java remnants hanging around:
https://twitter.com/SUPERCILEX/status/1050544888733818880

We should at a minimum fix all instances of those two issues (unnecessary `public` access modifiers and `mHungarianNotation`) but ideally we could add some sort of Kotlin style checker to find even more.

**Comment by peterpeterpeter10101** [comment]
Trying

**Comment by samtstern** [comment]
Fixed by #699
