### ISSUE TITLE
 HTTP Error: 401, Request had invalid authentication credentials.

### ISSUE THREAD

**Issue by mohamed6996** [firebase/quickstart-android#706]
I`m trying to set up firebase functions but i get an error after running firebase init 

**Error: HTTP Error: 401, Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or other valid authentication credential. See https://developers.google.com/identity/sign-in/web/devconsole-project.**

![error](https://user-images.githubusercontent.com/13904032/47214990-0ceeba00-d3a0-11e8-89d0-7610e9d089bd.JPG)

**Comment by yidah** [comment]
I have the same issue
