### ISSUE TITLE
Where is the data structure?

### ISSUE THREAD

**Issue by mnuaimi** [firebase/quickstart-android#713]
Where is the data structure?

**Comment by samtstern** [comment]
Which app are you asking about?  What would you like to know about the data structures?

**Comment by Albey8606** [comment]
I'm using  sketchware

**Comment by samtstern** [comment]
@Albey8606 @mnuaimi can you explain what you're trying to do and how you got linked to this repo?

**Comment by samtstern** [comment]
Closing this issue since there's almost no information.  Let me know if you want to keep discussing though!
