### ISSUE TITLE
CameraPreview quality dropped

### ISSUE THREAD

**Issue by sshrabah** [firebase/quickstart-android#719]
### Step 3: Describe the problem:
hi, 
I was using the classes under the common folder from a month ago for a barcode scanning. However, after updating to the new release the camera preview quality and accuracy dropped.
After some digging, I noticed that the _requestedPreviewWidth, requestedPreviewHeight_  were lower than the previous version 

 		private final int requestedPreviewWidth = 480;
  		private final int requestedPreviewHeight = 360;
 
so i tried changing that back the to the previous values

	  private final int requestedPreviewWidth = 1280;    
	  private final int requestedPreviewWidth = 480;
 
Unfortunately, that did not work and  made the camera lag. 
is there a workaround? or should I fall back to the previous release?

Thanks in advanced

**Comment by samtstern** [comment]
@gkaldev can probably explain the recent change.

**Comment by samtstern** [comment]
See discussion in #745, this is working as intended for now.
