### ISSUE TITLE
[BUG] MLKit Kotlin Sample doesn't work, camera is frozen.

### ISSUE THREAD

**Issue by XinyueZ** [firebase/quickstart-android#720]
MLKit sample Kotlin version has frozen camera, only classification works but only sometimes. 
Anyway, please check Kotlin version, it is not good as expect.

Java version works.

**Comment by rosariopfernandes** [comment]
What device are you using? Do you see any message that could be related to
this on the logcat?

**Comment by XinyueZ** [comment]
Pixel 1 and S6 of samsung

**Comment by rosariopfernandes** [comment]
Thanks @XinyueZ . I was able to reproduce the bug on my device as well (Xperia Z5). Apparently, this started after @gkaldev 's [last commit](https://github.com/firebase/quickstart-android/commit/ae28467df6ff882fc4e4e4cebad8e66d26f44c4a).

**Comment by XinyueZ** [comment]
> Thanks @XinyueZ . I was able to reproduce the bug on my device as well (Xperia Z5). Apparently, this started after @gkaldev 's [last commit](https://github.com/firebase/quickstart-android/commit/ae28467df6ff882fc4e4e4cebad8e66d26f44c4a).
> 
> **Update:** I've just noticed that last commit adds a new feature(custom model) to the java app and not to the Kotlin app, that's probably the reason why it crashes. I believe #721 should fix it.

OK, wait for update

**Comment by samtstern** [comment]
#721 has been merged, @XinyueZ @rosariopfernandes has this been fixed?

**Comment by rosariopfernandes** [comment]
@samtstern Just checked. Unfortunately, it's not been fixed.

**Comment by richgabrielli** [comment]
I have just cloned the latest build and this issue still exists.

**Comment by samtstern** [comment]
Been looking into this and I can't spot what's wrong with the Kotlin code ... maybe there's some subtle difference with the threading that I don't understand?

**Comment by the-dagger** [comment]
@samtstern Let me see if I can figure out something wrong here.
I'll look into this over the weekend

**Comment by samtstern** [comment]
Fixed by @the-dagger in #768
