### ISSUE TITLE
Event names with white spaces wont log to analytics

### ISSUE THREAD

**Issue by varunrramani** [firebase/quickstart-android#74]
Currently we are unable to log events with the event names containing white spaces, same goes for the keys in the bundle sent. Is there a way to do it or is it a planned feature for the future release?

**Comment by samtstern** [comment]
@varunrramani this is working as intended, no plans to allow spaces that I am aware of.

From: https://firebase.google.com/docs/reference/android/com/google/firebase/analytics/FirebaseAnalytics#logEvent(java.lang.String,%20android.os.Bundle)

"""
The name of the event. Should contain 1 to 32 alphanumeric characters or underscores. The name must start with an alphabetic character. Some event names are reserved. See FirebaseAnalytics.Event for the list of reserved event names. The "firebase_" prefix is reserved and should not be used. Note that event names are case-sensitive and that logging two events whose names differ only in case will result in two distinct events.
"""
