### ISSUE TITLE
[MLKIT] Is it possible to make detectInImage(..).addOnSuccessListener{} be invoked in a specific thread?

### ISSUE THREAD

**Issue by trueangle** [firebase/quickstart-android#742]
I'm trying to implement _Reactive_ wrapper over mlkit's detectInImage method and then embed into my _Rx_ chain.

The problem here: I cannot instruct `detectInImage(..).addOnSuccessListener{}` callback to be invoked in a specific thread (or thread, where detectInImage() was called), such method gets called on the main thread automatically. Therefore, it affects whole _Rx_ chain by switching all operations on the main thread as if `observeOn` was called.

For example, some _camera2_ methods accept the `Handler` as a parameter on which the listener should be invoked. Is it possible to achieve similar behavior?

**Comment by samtstern** [comment]
For any API which returns a `Task` you can specify the `Executor` that you'd like to use for the callback:
https://developers.google.com/android/guides/tasks#threading

Hope that helps!
