### ISSUE TITLE
FCM - To replace/cancel notification posted when app in background

### ISSUE THREAD

**Issue by liaowng** [firebase/quickstart-android#744]
I'm trying to handle notifications received both in foreground and background, and group(replace) existing notifications in the system tray when needed. And I think there's some clarification needed.

 * Android OS version: 9.0
 * Google Play Services version: 4.0.1
 * Firebase/Play Services SDK version: 16.0.5
 * Firebase Cloud Messaging version: 17.3.4
  
#### Steps to reproduce:

  1. When app is in background or closed, send FCM with payload as such,
```
{
 "to" : "xxx",
 "notification" : {
     "body" : "Original message",
     "tag": "myTag"
 },
 "data" : { ... }
}
```
  2. Leave the notification as it is in the system tray, and open the app
  3. While app is in foreground, receive another push with payload as such,
```
{
 "to" : "xxx",
 "notification" : {
     "body" : "Updated message",
     "tag": "myTag"
 },
 "data" : { ... }
}
```
  4. In `FirebaseMessagingService#onMessageReceived()`, create a 'notification' with body of "Updated message", then post with
  a. NotificationManager.notify("myTag", 1234, notification)
  b. NotificationManager.notify("myTag", 0, notification)

#### Observed:
In case of 4.a, a new notification is created in the system tray, and in 4.b, the system identifies it as a replacement and replaced the one posted when app was in background.

#### Question:
As the FCM doc states, "tag" is the identifier used to replace existing notifications in the notification drawer (and I believe "id" in "notification" will be ignored)
https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support
And for 'NotificationManager.notify()', its doc states "The pair (tag, id) must be unique within your application."

Based on the my observation, I would assume that when we get the push notification while the app is in background, internally a notification will be posted with the pair of ("myTag", 0). However, I don't think I find any official documentation confirming this behaviour, or if we should expect it will keep behaving this way in the future.

Similar situation when we want to cancel a notification, we would like a clearer guideline on how to identify the targeted notification .

**Comment by kroikie** [comment]
@liaowng Good question I'll dig into this and reply here.

**Comment by kroikie** [comment]
@liaowng You are correct, the ID used for the notifications from the SDK is 0. You can use the 0 ID to replace notifications from the SDK with your own.

**Comment by liaowng** [comment]
@kroikie Thanks for clarifying that

**Comment by liaowng** [comment]
@kroikie Thanks for clarifying that, any chance you could let me know where to reference to?

**Comment by kroikie** [comment]
@liaowng there is no public reference at this time. We are working on a doc update to expose this functionality.

**Comment by erlangp** [comment]
how about other notification (more than one) ?
