### ISSUE TITLE
 Firebase ML Kit: Pre-Trained Models

### ISSUE THREAD

**Issue by SubhashKsr** [firebase/quickstart-android#747]
I can see there are 3 pre-trained models included in the [assets][1] folder of the ML-Kit sample app. 

Please help me understand

 - Which of these models correspond to face detection?
 - What is the data set used to train these models?

This question can also be answered on [StackOverflow](https://stackoverflow.com/questions/53335038/firebase-ml-kit-pre-trained-models)

  [1]: https://github.com/firebase/quickstart-android/tree/master/mlkit/app/src/main/assets

**Comment by the-dagger** [comment]
Hi @SubhashKsr 
I don't think that any of these models correspond to face detection, however looking at the label.txt file, I can say that they are basic examples of a classification model.

As far as the dataset goes, I guess @gkaldev might be able to give more insights on this but you can go ahead and retrain any one of these models using a dataset available on kaggle.

**Comment by samtstern** [comment]
Thanks  @the-dagger.  That's correct, none of those models correspond to Face detection. These are meant to demonstrate using a custom model with MLKit, whereas the face detection model is built-in.
