### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException 

### ISSUE THREAD

**Issue by junelaykris** [firebase/quickstart-android#755]
After using firebase (Analytics, Cloud Messaging, Remote Config) libraries i'm having this problem on different os versions of android.

Fatal Exception: java.lang.NullPointerException
com.google.android.gms.internal.in.zzc (Unknown Source)
com.google.android.gms.internal.in.zza (Unknown Source)
com.google.android.gms.internal.abf.run (Unknown Source)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:231)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:848)

I am using Firebase v11.0.4 now.

Device:
Brand: HUAWEI
Model: Y625-U32
Orientation: Portrait
RAM free: 79.63 MB
Disk free: 97.97 MB    

Operating System
Version: 4.4.2
Orientation: Portrait
Rooted: Yes 

How to solve that firebase problem if you know plz help me.Thanks in advance!

**Comment by samtstern** [comment]
@junelaykris I believe that error was solved, but `11.0.4` is a very old version of Firebase!  Please update all your dependencies to the latest version and then report back if you're still seeing this error.
