### ISSUE TITLE
when app killed notifications not received in oppo, xiaomi, vivo like devices

### ISSUE THREAD

**Issue by crashfiredeep** [firebase/quickstart-android#758]
I have a trouble getting notifications when app is killed or swipe closed. even not getting notifications send from console also not received from custom server api using data payload.
also removed app from battery optimizer list, still not worked.

please help.

**Comment by samtstern** [comment]
@crashfiredeep there's not much we can do to help here, especially with so little information.  Please see discussions in previous issues like #4 and #89

**Comment by iulian0512** [comment]
+1
