### ISSUE TITLE
how to send data queue realtime database

### ISSUE THREAD

**Issue by Prabha10cs** [firebase/quickstart-android#763]
I get child value and update value two device  at a same time the child values are replaced

```java
 mFirebaseDatabase.child(userId).addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                  user = dataSnapshot.getValue(Noti_item.class);

                      if (user == null) {
                          System.out.println("User data is null!");
                          Log.e(TAG, "User data is null!");
                          createUser(userId, "0", "1");
                 
                          return;
                      } else {

                          System.out.println("User data is :"+userId+" - "+ user.read+" - "+ user.receive);
                          Log.e(TAG, "User data is :"+userId+" - "+ user.read+" - "+ user.receive);

                          updateUser(userId, user.read, user.receive);
                         
                          return;
                      }
               


            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.e(TAG, "Failed to read user", error.toException());
            }
        });
```

```java
private void createUser(String userId, String read, String receive) {

        Noti_item user = new Noti_item(read, receive);

        mFirebaseDatabase.child(userId).setValue(user);


    }
```

```java
    private void updateUser(String userId, String read, String receive) {
        // updating the user via child nodes
        System.out.println("user update : " + receive);
        int vall = Integer.parseInt(receive) + 1;

        receive = String.valueOf(vall);

        if (!TextUtils.isEmpty(read))
            mFirebaseDatabase.child(userId).child("read").setValue(read);

        if (!TextUtils.isEmpty(receive))
            mFirebaseDatabase.child(userId).child("receive").setValue(receive);
    }
```

**Comment by samtstern** [comment]
@Prabha10cs it's not clear what your question is, or if it has anything to do with the quickstart code in this repo.  If it's just a general question about how to use Firebase, please ask on StackOverflow.

**Comment by Prabha10cs** [comment]
@samtstern  hello sir

i am working get counts from fcm message received counts but message received same time two device  my values are replacing 
my code are following here
help to recover this problem


 mFirebaseDatabase.child(userId).addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                  user = dataSnapshot.getValue(Noti_item.class);

                      if (user == null) {
                          System.out.println("User data is null!");
                          Log.e(TAG, "User data is null!");
                          createUser(userId, "0", "1");
                 
                          return;
                      } else {

                          System.out.println("User data is :"+userId+" - "+ user.read+" - "+ user.receive);
                          Log.e(TAG, "User data is :"+userId+" - "+ user.read+" - "+ user.receive);

                          updateUser(userId, user.read, user.receive);
                         
                          return;
                      }
               


            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.e(TAG, "Failed to read user", error.toException());
            }
        });

private void createUser(String userId, String read, String receive) {

        Noti_item user = new Noti_item(read, receive);

        mFirebaseDatabase.child(userId).setValue(user);


    }

private void updateUser(String userId, String read, String receive) {
        // updating the user via child nodes
        System.out.println("user update : " + receive);
        int vall = Integer.parseInt(receive) + 1;

        receive = String.valueOf(vall);

        if (!TextUtils.isEmpty(read))
            mFirebaseDatabase.child(userId).child("read").setValue(read);

        if (!TextUtils.isEmpty(receive))
            mFirebaseDatabase.child(userId).child("receive").setValue(receive);
    }
