### ISSUE TITLE
How to handle FCM Push notification when app is in background or killed in Android Oreo?

### ISSUE THREAD

**Issue by yaramvenki** [firebase/quickstart-android#765]
### Question 1: How to handle FCM Push notification when app is in background or killed in Android?
 * I implemented FCM push notifications, i am getting data as well notification data like **remoteMessage.getNotification()**  and **remoteMessage.getData().size() > 0**. Now, i am able to get data from both when app is in foreground. How to get both/single data when app is in background?
  
### Question 2: I am getting notification when app is in background, but on click of that notification it is not launching activity? how to implement that?(Android)
    implementation 'com.google.firebase:firebase-core:16.0.6'
    implementation 'com.google.firebase:firebase-messaging:17.3.4'

```
public class HealthAppMessagingService extends FirebaseMessagingService {
    @Override
    public void onNewToken(String s) {
        super.onNewToken(s);
    }
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        super.onMessageReceived(remoteMessage);
        if (remoteMessage.getNotification() != null) {
            title = remoteMessage.getNotification().getTitle();
            messageBody = remoteMessage.getNotification().getBody();
        }
        if (remoteMessage.getData().size() > 0) {
            try{
                type = remoteMessage.getData().get("type");
                time = remoteMessage.getData().get("time");
              
                Intent resultIntent = new Intent(getApplicationContext(), MainActivity.class);
                resultIntent.putExtra("message", messageBody);
                showNotificationMessage(title, messageBody, time, resultIntent, null);
            } catch (Exception e){
                Log.e(TAG, "Exception: " + e.getMessage());
            }
        }
    }
}
```
 
How to get notification data and data when app is in background? how to implement code for that?

**Comment by tareqassi** [comment]
did you manage to get answers for your questions ?

**Comment by kroikie** [comment]
@yaramvenki 
Question 1: Data messages (messages with no notification payload) are handled the same whether the app is in the foreground or background. Notification messages (messages with a notification payload) automatically generate a visible notification (does not trigger onMessageReceived), if the user taps on the visible notification any data payload will be available in the extras of the launched intent.

Question 2: Looks like you are generating the notification yourself, after you get the `onMessageReceived` callback it is standard Android framework stuff from then on, not FCM specific. For an example of how to create a notification that launches an intent see [the sample](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/java/MyFirebaseMessagingService.java#L150).

**Comment by baderkhane** [comment]
// Handle possible data accompanying notification message.
        // [START handle_data_extras]
        if (getIntent().getExtras() != null) {
            for (String key : getIntent().getExtras().keySet()) {
                Object value = getIntent().getExtras().get(key);
                Log.d(TAG, "Key: " + key + " Value: " + value);
            }
        }
