### ISSUE TITLE
ML Kit FaceDetectionProcessor not running in background service class 

### ISSUE THREAD

**Issue by Nathiya-Smitiv** [firebase/quickstart-android#766]
Hi,

I'd like to implement face detection when app is in background. Is there a Firebase ML Kit CameraSource Builder class (Same as Like Google vision https://developers.google.com/android/reference/com/google/android/gms/vision/CameraSource.Builder) one could extend to implement the same? Any help in urgent manner would be thankful . In my app i need to use FaceDetection in both foreground and background.

**Comment by samtstern** [comment]
@Nathiya-Smitiv please provide some code and errors we can use to figure out what's going on!  This isn't really enough information.

Also I don't think apps are allowed to use the camera while in the background on Android, but I could be wrong.

**Comment by Nathiya-Smitiv** [comment]
@samtstern  Below code i have tried to run the FaceDetection in Background service class.
`public class DemoService extends Service {
private LayoutInflater inflater;
private View mView;
WindowManager wm;
CameraSourcePreview preview;
GraphicOverlay graphicOverlay;
public int onStartCommand(Intent intent, int flags, int startId) {
LayoutInflater  inflater = (LayoutInflater) getSystemService(LAYOUT_INFLATER_SERVICE);
    WindowManager wm = (WindowManager) getSystemService(WINDOW_SERVICE);

    View mView = inflater.inflate(R.layout.child_camerapreview, null);

    wm.addView(mView, params);
   graphicOverlay = (GraphicOverlay) mView.findViewById(R.id.childbgFaceOverlay);
   preview = (CameraSourcePreview) mView.findViewById(R.id.childbgCameraPreview);
    createCameraSource();
    startCameraSource();
}
private void createCameraSource() {
		try {
			// If there's no existing cameraSource, create one.
			if (cameraSource == null) {
				Log.i("TAG_FACE", "Camera Source is Null so create new one");
				cameraSource = new CameraSource(this, graphicOverlay);
				cameraSource.setFacing(CameraSource.CAMERA_FACING_FRONT);
				//  cameraSource = new CameraSource(this);
				cameraSource.setMachineLearningFrameProcessor(new FaceDetectionProcessor(this));
			}
		}catch (Exception e){
			Log.i("TAG_FACE" , " Create Camera Source Exception:" + e.getMessage());
		}
	}
private void startCameraSource() {
		if (cameraSource != null) {
			try {
				if (preview == null) {
					Log.d("TAG_FACE", "resume: Preview is null");
				}
				if (graphicOverlay == null) {
					Log.d("TAG_FACE", "resume: graphOverlay is null");
				}
				preview.start(cameraSource, graphicOverlay);
			} catch (IOException e) {
				Log.e("TAG_FACE", "Unable to start camera source.", e);
				cameraSource.release();
				cameraSource = null;
			}
		}
	}
}`
XML Layout:
`<?xml version="1.0" encoding="utf-8"?>
<RelativeLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:background="@android:color/transparent"
    >
    <RelativeLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:keepScreenOn="true"
        >
        <co.demo.facekit.common.CameraSourcePreview
            android:id="@+id/childbgCameraPreview"
            android:layout_width="match_parent"
            android:layout_height="240dp"
            android:layout_alignParentStart="true"
            android:layout_alignParentTop="true">

            <co.demo.facekit.common.GraphicOverlay
                android:id="@+id/childbgFaceOverlay"
                android:layout_width="0dp"
                android:layout_height="0dp"
                android:layout_alignParentStart="true"
                android:layout_alignParentTop="true"
                android:layout_alignParentBottom="true"/>
        </co.demo.facekit.common.CameraSourcePreview>

    </RelativeLayout>

    <ImageView
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#00000000"
        />


</RelativeLayout>`
When i run my app in foreground its working fine. But my app is in background the CameraSourcePreview UI is rendering . If i set the width and height as "0dp" for CameraSourcePreview then UI is not render in background but Face Detection is not happening.

**Comment by samtstern** [comment]
@Nathiya-Smitiv sorry for the slow response, was out of the office for the holiday break.

Right now ML Kit face detection is intended for apps running in the foreground, and face detection through a background service is not something we expect to work (or be a good idea!) you may want to take this question to StackOverflow where the community may have some other possible solutions that may work for you.

**Comment by mpaleo** [comment]
@Nathiya-Smitiv Hey!
Do you found a solution to this ?
I need to run face detection as a service too

**Comment by Nathiya-Smitiv** [comment]
@mpaleo No solution found yet. 

> @Nathiya-Smitiv Hey!
> Do you found a solution to this ?
> I need to run face detection as a service too
