### ISSUE TITLE
Even when using `FirebaseOptions` to create a `[DEFAULT] FirebaseApp`, Google Service still tries to use `google_app_id`. 

### ISSUE THREAD

**Issue by harsh0893** [firebase/quickstart-android#769]
Please someone provide a solution for this.

**Comment by samtstern** [comment]
@harsh0893 this is currently working as intended, the Analytics SDK does not allow configuration of the App ID at runtime.  However I will pass on your feedback, since this could change in the future.

P.S. please use the issue template next time!

**Comment by thatfiredev** [comment]
@OlegTarashkevich Note that those keys are not secrets, as explained in [this page](https://firebase.google.com/docs/android/learn-more#google-services-plugin-and-file).

**Comment by OlegTarashkevich** [comment]
@thatfiredev It's nice to have unique keys that anyone can extract and reuse as their own. Even SafetyNet won't help.

**Comment by thatfiredev** [comment]
SafetyNet is being deprecated anyways, so probably not a worthy mention. But maybe [PlayIntegrity](https://developer.android.com/google/play/integrity/overview)?

**Comment by OlegTarashkevich** [comment]
The Firebase team makes an amazing SDK.
But, unfortunately, "ignoring the problem" is the second name for this sdk team.

The problem can be solved with a resource wrapper in the Application class:
https://gist.github.com/electricbolt/423c03f09bc0303d0d5696b8beb392bd

```
public class App extends Application {

    private FirebaseResourcesWrapper firebaseResources;

    @Override
    public Resources getResources() {
        if (firebaseResources == null)
            firebaseResources = new FirebaseResourcesWrapper(super.getResources());
        return firebaseResources;
    }

}
```
