### ISSUE TITLE
How to set FirebaseAnalytics.setCurrentScreen in fragment？

### ISSUE THREAD

**Issue by scsfwgy** [firebase/quickstart-android#772]
### Step 3: Describe the problem:

How to set FirebaseAnalytics.setCurrentScreen in fragment？
This method just can track activity name?

**Comment by rosariopfernandes** [comment]
Although the method takes an activity as argument, it can definitely track fragments. Simply pass the activity that this fragment is attached to:
```java
Activity activity = getActivity();
if (activity != null) {
    FirebaseAnalytics.getInstance(activity).setCurrentScreen(activity, "Screen Name", null);
}
```

**Comment by scsfwgy** [comment]
@rosariopfernandes  Thank you for your reply!
Other question, How can I migrate google analytics projcet to firebase？Or I just change google analytics SDK to Firebase SDK,then associated google analytics projcet to new firebase projcet(I can't find how to associated button... ).

ref：https://firebase.google.com/support/faq/#analytics
https://firebase.google.com/docs/analytics/

**Comment by rosariopfernandes** [comment]
TBH I never did such thing, but a quick search returned [this post](https://stackoverflow.com/q/37919630/5861618).

On a side note: This is not the best channel to ask these kind of questions, please only use this issue tracker to discuss about the Quickstart-Android samples. If you have a different question, you might want to try one of the other channels listed on Step 2 of the [Official Support Page](https://firebase.google.com/support/).

**Comment by scsfwgy** [comment]
Okay...thx
