### ISSUE TITLE
FCM message handling when app is in background

### ISSUE THREAD

**Issue by AhmadNosratian** [firebase/quickstart-android#779]
Hi 
I want to show activity when FCM  received ,without clicking on notification 
i use onMessageReceived but it doenst work 
please guide me.

**Comment by samtstern** [comment]
@AhmadNosratian this looks like a better question for StackOverflow, as it doesn't relate to the code in this quickstart.  There is no built-in functionality for showing an activity automatically from an FCM message (and most users wouldn't want that anyway)
