### ISSUE TITLE
Authentication login with Google  getting handleSignInResult:false

### ISSUE THREAD

**Issue by yokei15** [firebase/quickstart-android#78]
Getting false in results success 

```
if (requestCode == RC_SIGN_IN) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            Log.d(TAG, "handleSignInResult:" + result.isSuccess());
            if (result.isSuccess()) {
                // Google Sign In was successful, authenticate with Firebase
                GoogleSignInAccount account = result.getSignInAccount();
                firebaseAuthWithGoogle(account);
            } else {
                // ...
            }
        }
    }
```

**handleSignInResult:false**

tried out many ways but cant find out the solution,there is any solution for these..
Thanks in Advance

**Comment by samtstern** [comment]
@yokei15 I need some more information to debug this.  What other output do you see in `adb logcat` and  can you try adding a statement like this for more info:
```
Log.d(TAG, "handleSignInResult:" + result.getStatus().toString());
```

It's likely an issue with your SHA1 and package name, but can't say for sure yet.

**Comment by yokei15** [comment]
@samtstern Is **SHA1** key to be update in **firebase auth as well as in google developer console**???

**Comment by samtstern** [comment]
@yokei15 you need to make sure your SHA1 and package name are listed in the [Firebase console](console.firebase.google.com).

Could you show how you're creating your GoogleSignInOptions?

**Comment by yokei15** [comment]
provided SHA! & Pakage Name correctly but same error in logcat (i.e) result is false

these was the code which i used
GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                    .requestIdToken(getString(R.string.default_web_client_id))
                    .requestEmail()
                    .build();

            mGoogleApiClient = new GoogleApiClient.Builder(this)
                    .enableAutoManage(this, this)
                    .addApi(Auth.GOOGLE_SIGN_IN_API, gso)
                    .build();
 @Override
    public void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);

        // Result returned from launching the Intent from GoogleSignInApi.getSignInIntent(...);
        if (requestCode == RC_SIGN_IN) {
            GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            Log.d(TAG, "Result:" + result.isSuccess());
            if (result.isSuccess()) {
                // Google Sign In was successful, authenticate with Firebase
                GoogleSignInAccount account = result.getSignInAccount();
                firebaseAuthWithGoogle(account);
            }
        }
    }

**Comment by mussa-ibragimov** [comment]
Any news on this issue?
I'm having the same problem with my androiddebugkey SHA1

**Comment by samtstern** [comment]
@mussa-ibragimov so you had to replace `default_web_client_id` with a web Client ID you created yourself?

**Comment by manishbutola** [comment]
I also get the same issue but adding SHA1 has solved the problem.

To Get SHA1 follow this: 
http://stackoverflow.com/questions/27609442/how-to-get-the-sha1-fingerprint-certificate-in-android-studio-for-debug-mode

**Comment by samtstern** [comment]
This issue has been inactive for a very long time, going to close it.  Please feel free to re-open if you have more relevant information.

**Comment by alihussain** [comment]
Hi,
I am having issue while calling getSignInResultFromIntent(). In  onActivityResult It receive StatusCode=9001 and ResultCode=SUCCESS. 

 GoogleSignInResult res=Auth.GoogleSignInApi.getSignInResultFromIntent(data);
            handleResult(res); 

But res.isSuccess()  return false. I dont know why??

I am using Huawie Phone and google play  version 9.8.0.

Please help.

**Comment by samtstern** [comment]
@alihussain check `res.getException()` for more information

**Comment by alihussain** [comment]
@samtstern  Android Studio was signing apk with different key then i input in google console. I configured the debug key in Android studio and now everything is fine. Thanks.

**Comment by KishanViramgama** [comment]
please add SHA-1 Key on fire base project  and try i hope solved problem

**Comment by rakeshkumar217** [comment]
I am facing same issue. But different scenario, I have created a signed apk and installed in phone and then it is working fine. But when i upload on play store & then download and then it is returning false result. Please help. Thanks.

**Comment by alihussain** [comment]
Try to add both md5 and sha1 key into the firebase signing. Make sure its corresponding release keys.

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 2, 2019 at 6:23 PM, rakeshkumar217<notifications@github.com> wrote:   
Thanks for your reply. But still not able to resolve it.

**Comment by RSReswin** [comment]
i also have same IsSuccess return false Problem!
