### ISSUE TITLE
ML Kit:: How to read text from seven segment image

### ISSUE THREAD

**Issue by pawarn** [firebase/quickstart-android#785]
I am working on the module where I want to read text from 7 segment image. E.g.Want to read HB meter values using ML kit.

And HB meter values in the form of 7 segments.

**This is working perfectly on normal images.** 

![img1](https://user-images.githubusercontent.com/32476234/51103519-050cad80-1809-11e9-912d-03c796b65625.png)

**Not working on 7 segment images.**

![img2](https://user-images.githubusercontent.com/32476234/51103524-09d16180-1809-11e9-8c7c-fb1d7bab5ad3.png)

Plz, guide me on how I can achieve this.

**Comment by samtstern** [comment]
@pawarn there is no built in model for 7 segment images other than text recognition.  You will either have to use a custom model or consider a solution other than MLKit
