### ISSUE TITLE
How to handle notification when app in background in firebase

### ISSUE THREAD

**Issue by Arun1811** [firebase/quickstart-android#79]

**Comment by yishai-glide** [comment]
1. this question should be in stackoverflow with the [firebase-cloud-messaging tag](http://stackoverflow.com/questions/tagged/firebase-cloud-messaging)

2. as written in the documentation and referenced in the [source code](https://github.com/firebase/quickstart-android/blob/master/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/MyFirebaseMessagingService.java#L43), notifications that are received from the console while the application in in background will not trigger any code to run but instead will post a notification that opens the application on click

**Comment by samtstern** [comment]
@yishai-glide thanks for the recommendation.

Closing this issue, discussion duplicated in #4.

**Comment by kkyyppp** [comment]
How about my solution try it.
ttps://stackoverflow.com/questions/48897883
