### ISSUE TITLE
get average screen time  

### ISSUE THREAD

**Issue by Maneesh528** [firebase/quickstart-android#790]
Hello Team, 

Our app is an Video Stemming Application, I am sending the data to Firebase like: (VideoTitle : VideoViewedTime) by using LogEvents. 

```java
Bundle firebaseBundle = new Bundle();
        firebaseBundle.putString(FirebaseAnalytics.Param.CONTENT_TYPE, String.valueOf(videoType));
        mFirebaseAnalytics.logEvent(FirebaseAnalytics.Event.SELECT_CONTENT, firebaseBundle);
```

And also I have used:

```
mFirebaseAnalytics.setCurrentScreen(PlayerActivity.this, String.valueOf(videoType), "PlayerActivity");
```

So finally my intention to see Total average time of Each particular video in Firebase dashboard.

Can you guys help me with this problem.

**Comment by samtstern** [comment]
Hey @Maneesh528.  When you file an issue on GitHub you're presented with a template that has a list of sections containing information we need to help you:

![image](https://user-images.githubusercontent.com/8466666/51548566-6fcb7380-1e1d-11e9-8b9c-0d024803d59c.png)

Filling out the template makes it much easier for us to dig into your issue.

**Comment by samtstern** [comment]
@Maneesh528 to answer your question, there is no way to add custom metric aggregations to your Analytics dashboard.  However you should be able to use BigQuery to analyze this data and then use something like Data Studio to make your own dashboard if you need to visualize it:
https://cloud.google.com/solutions/mobile/mobile-firebase-analytics-bigquery#working_with_firebase_analytics_data_in_bigquery

**Comment by Maneesh528** [comment]
Hello Team, Thanks for your reply, I have raised a new Ticket
<https://github.com/amzn/exoplayer-amazon-port/issues/84> Please help me to
get out of it. I am in very hurry.

Thanks
Maneesh. A
