### ISSUE TITLE
Taking photo in Storage app always returns RESULT_CANCELED (0) in onActivityResult(..)

### ISSUE THREAD

**Issue by madim** [firebase/quickstart-android#81]
### Describe your environment

  * Android device: Nexus 5
  * Android OS version: 6.0.1
  * Google Play Services version: 9.2.56
  * Firebase/Play Services SDK version: firebase-ui: 9.2.0
  
### Describe the problem:
Taking photo in Storage app always returns RESULT_CANCELED (0) in onActivityResult(..).
  
#### Observed Results:
logs: onActivityResult:101:0:Intent {  }
    
#### Relevant Code:

    @AfterPermissionGranted(RC_STORAGE_PERMS)
    private void launchCamera() {
        Log.d(LOG_TAG, "launchCamera");
        // Check that we have permission to read images from external storage.
        String perm = Manifest.permission.WRITE_EXTERNAL_STORAGE;
        if (!EasyPermissions.hasPermissions(this, perm)) {
            EasyPermissions.requestPermissions(this, getString(R.string.rationale_storage),
                    RC_STORAGE_PERMS, perm);
            return;
        }

        // Choose file storage location, must be listed in res/xml/file_paths.xml
        File externalDir = Environment.getExternalStorageDirectory();
        File file = new File(externalDir, "photos/" + UUID.randomUUID().toString() + ".jpg");

        // Create content:// URI for file, required since Android N
        // See: https://developer.android.com/reference/android/support/v4/content/FileProvider.html
        mFileUri = FileProvider.getUriForFile(this,
                "com.google.firebase.quickstart.firebasestorage.fileprovider", file);

        // Create and launch the intent
        Intent takePictureIntent = new Intent(MediaStore.ACTION_IMAGE_CAPTURE);
        takePictureIntent.putExtra(MediaStore.EXTRA_OUTPUT, mFileUri);

        startActivityForResult(takePictureIntent, RC_TAKE_PICTURE);
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        Log.d(LOG_TAG, "onActivityResult:" + requestCode + ":" + resultCode + ":" + data);
        if (requestCode == RC_TAKE_PICTURE) {
            if (resultCode == RESULT_OK) {
                if (mFileUri != null) {
                    uploadFromUri(mFileUri);
                } else {
                    Log.w(LOG_TAG, "File URI is null");
                }
            } else {
                Toast.makeText(this, "Taking picture failed.", Toast.LENGTH_SHORT).show();
            }
        }
    }

**Comment by samtstern** [comment]
@madim thanks for the report.  Is there anything else appearing in logcat that would be helpful in tracking this down?  I am having trouble reproducing.

**Comment by madim** [comment]
@samtstern thanks for the reply, the problem is solved. There was something wrong with the FileProvider, it could find the directory to locate the photo. It was solved by just changing the value of  "path" to the different location: 

`<paths>
    <external-path name="photos" path="Android/data/<package_name>/files/Pictures" />
</paths>`

**Comment by samtstern** [comment]
@madim thanks for investigating.  Let's leave this issue open so I can figure out why the initial code did not work.

**Comment by samtstern** [comment]
@madim I think this was fixed by commit 591053 so I will close this issue.  If you're still using this sample and it's not fixed for you please let me know.
