### ISSUE TITLE
Is there a way to disable the instant verification? 

### ISSUE THREAD

**Issue by jaytarub** [firebase/quickstart-android#814]
### Step 1: Describe your environment

  * Android device: Any
  * Android OS version: Any
  * Google Play Services version: 4.2.0
  * Firebase/Play Services SDK version: 16.1.0
  
### Step 2: Describe the problem:
- OTP not being sent when user logs out and logs in again due to Instant Verification.

**Comment by samtstern** [comment]
@jaytarub you can use this guide to integration test the different scenarios:
https://firebase.google.com/docs/auth/android/phone-auth#integration-testing
