### ISSUE TITLE
ML Kit Vision fails to detect QR codes on Wiko Tommy 3 running Android 8.1.0

### ISSUE THREAD

**Issue by LouisCAD** [firebase/quickstart-android#818]
Was reported for Google Vision API, but still seems to happen with Firebase ML Kit 😞 https://issuetracker.google.com/issues/80454351

How can we make it simply reliable?

**Comment by samtstern** [comment]
@LouisCAD thanks for pointing me at that issue tracker link!  I think that is still the best place to track this issue, rather than here as part of the quickstart.

I will see if I can get someone who knows more to give an update there.

**Comment by LouisCAD** [comment]
I'm looking forward updates on that ticket in Google's issue tracker, thank
you!
