### ISSUE TITLE
updateChildrenASync cannot be resolved

### ISSUE THREAD

**Issue by eleallegue** [firebase/quickstart-android#821]
Android Studio App Development

I was developing my app when I (following google firebase guide) wrote the updateChildrenAsync method which I think is great for my purpose. The thing is that when I wrote it down in my code, Android Studio tell me that it cannot resolve the method and not me, not anyone knows why.
I have reopened Android, I checked the versions of the dependencies and everything.

I have been looking all over the internet and I came here empty handed because I found nothing.
I hope you can help me with this one.

I have all of this in my code:
1. build.gradle (from the app)
```
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.firebase:firebase-database:16.0.5'
    implementation 'com.google.firebase:firebase-storage:16.0.5'
    implementation 'com.google.firebase:firebase-core:16.0.5'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
```

2. My Java class
```
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
[...]
    private FirebaseDatabase database;
    private DatabaseReference ref;
[...]
public ClassExample(){
        database = FirebaseDatabase.getInstance();
        ref = database.getReference("real");
}
[...]

protected void addNew(String idUser, String idOtherUser){
        Map<String,Boolean> realtionshipsToAdd = new HashMap<>();
        String proPath = "pro/"+idOtherUser;
        String notPath ="not/"+idUser;
        realtionshipsToAdd.put(proPath, Boolean.TRUE);
        realtionshipsToAdd.put(notPath, Boolean.TRUE);

        Task result = ref.updateChildrenAsync(relationshipsToAdd);
        [...]
}
```

3. The Structure of the database would be something like this:
```
{
  "real":{
       "pro":{
            "id1": {
                "id2": true
                "id3": true
            }
        },
        "not":{
            "id3": {
               "id1":true
            }
        }
   }
}
```

**Comment by samtstern** [comment]
@eleallegue that method does not exist in the Android SDK, maybe you are following a bad or old guide? 

However the existing `updateChildren` method is async:
https://firebase.google.com/docs/reference/android/com/google/firebase/database/DatabaseReference.html#updateChildren(java.util.Map%3Cjava.lang.String,%20java.lang.Object%3E)

So just change your `updateChildrenAsync` call to `updateChildren` and you'll be done.
