### ISSUE TITLE
onMessageRecieved not working when app is killed. Any solution?

### ISSUE THREAD

**Issue by KORuL** [firebase/quickstart-android#822]
### Step 1: Describe your environment

  * Android device:  Meizu M1 Note
  * Android OS version: 5.1
  * Google Play Services version: `com.google.gms:google-services:4.2.0`
  * Firebase/Play Services SDK version: 

```
    implementation 'com.google.firebase:firebase-core:16.0.7'
//    implementation 'com.google.firebase:firebase-iid:17.1.0'
    implementation 'com.google.firebase:firebase-messaging:17.4.0'
    implementation 'com.firebase:firebase-jobdispatcher:0.8.5'
    implementation 'com.google.firebase:firebase-functions:16.1.3'
    implementation 'com.google.firebase:firebase-auth:16.1.0'
    implementation 'com.google.firebase:firebase-database:16.0.6'
    implementation 'com.google.firebase:firebase-crash:16.2.1'
    implementation 'com.google.firebase:firebase-storage:16.0.5'
    implementation 'com.google.android.gms:play-services-auth:16.0.1'
    implementation 'com.google.gms:google-services:4.2.0'
  
```

### Step 2: Describe the problem:

Almost all phones are fine. But in some phone (Meizu M1 note):

onMessageRecieved not working when app is killed in some devices. It works perfect in foreground and in background. But when app is killed I don t receive notification in system tray, or call onMessageRecieved .

I send only DATA (to, data) notification. What I do wrong?

I read #4 , #89 , #86 , #368 , #365 , #337 , #205 , #96  , #20 , #4, #151 , #816 did not find the answer.

I get a strange error in logcat  `W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=net.korul.hbbft (has extras) }`

I made this receiver - but it did not help

```
<receiver
            android:name=".MyBroadcastReceiver"
            android:permission="com.google.android.c2dm.permission.SEND" >
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE" />
                <category android:name="net.korul.hbbft" />
            </intent-filter>
        </receiver>
```

AndroidManifest contains:

```
        <service android:name=".services.MyFirebaseMessagingService"
                 android:permission="true"
                 ndroid:stopWithTask="false">
            <intent-filter>
                <action android:name="com.google.firebase. MESSAGING_EVENT"/>
            </intent-filter>
        </service>
```

MyFirebaseMessagingService - is standart from snippset

#### Steps to reproduce:

  1. Minimize and swipe out your application
  2. Send FCM notification
  3. You can see the below log but notification doesn't trigge
  
#### Observed Results:

 W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=net.korul.hbbft (has extras) }
  
#### Expected Results:

  Should get the notification

#### Relevant Code:

I read all the branches dedicated to this issue, do not refer to them! The problem is, she is over 2 years old! Need a solution!

I also tried to send a push message with the firebase console, and it does not come - the exact same error

**Comment by samtstern** [comment]
@KORuL thank you for reading all of those other issues.  It may very well be that Meizu has device-specific behavior changes which break FCM.  Does this happen for you on other manufacturer's devices like Samsung or Google?

@kroikie do you think there is anything different going on here versus the other issues?

**Comment by KORuL** [comment]
This does not happen with Google and Samsung devices.
But how can I deal with those who do not come pusy? Do I have to hang in the form of service and put the battery? Or are there other ways? How to implement your own, for example, messenger if you don’t get it?

**Comment by jshandorov1** [comment]
Hello,
Exactly the same behaviour on my Huawei P20 Pro + Android 9. Just I have to wait ~12 hours and app gets optimized automatically. No notifications are received after this.

**Comment by EdwardQuixote** [comment]
I get the same problem on a Tecno Spark:
* Model: K7
* Android 7.0

Even worse is how, the app is in the "Recent Apps" list, but still doesn't get any push messages when it gets into Doze. Please note I'm using FCM High Priority Messages and I'm sending a `data` type of message.

I tried out other push notification services on the same device and I noticed one of the services, does restart it's notification listening service even when a user kills the App:
` W/ActivityManager: Scheduling restart of crashed service me.pushy.example/me.pushy.sdk.services.PushySocketService in 1000ms
D/ActivityManager: AMS: *** Restart service me.pushy.example/me.pushy.sdk.services.PushySocketService
D/ActivityManager: AMS: Service me.pushy.example/me.pushy.sdk.services.PushySocketService is called by self.`

Q) Is it possible to have such an implementation on FCM, regardless of the device?

**Comment by samtstern** [comment]
@EdwardQuixote just FYI the "pushy" service does not use FCM it uses its own MQTT-based push notification service so it has totally different properties.

**Comment by KORuL** [comment]
@samtstern Thank you, I will look at this library! It’s a pity that @google @samtstern doesn’t want to do anything with an obvious BAG, which has been preventing us from developing good applications for more than 2 years!

**Comment by EdwardQuixote** [comment]
@samtstern Yes it uses MQTT. I just thought maybe Google could give us something like it even if FCM uses different protocols.

**Comment by samtstern** [comment]
@EdwardQuixote that's a reasonable thing to ask, I was just saying that there's no need for us to do something like "restart the service" since FCM messages are received by Google Play services and not your app itself.  When you use something like Pushy then each app is going to keep its own connection open.  So that's where the different behavior comes from. If every app on your phone had an MQTT connection open in the background your battery would be very unhappy :-)

**Comment by KORuL** [comment]
@samtstern Why, then, Google will not fix this bug? Accepts push with google service and redirects the receiver in the application. It's good if all the push messages are handled by one service in the system, and only it keeps one connection for all. And yes, if each application opens the connection it will be bad. But what to do in this situation? Push is required when the application is closed!
I don’t like the answer of Google, from the category - we are fine on a pixel and samsung, so leave us alone! This is not an answer! Does not work on many phones!

**Comment by bsonmez** [comment]
It's bizarre. It works correctly android eight on a real device, and Android nine on a simulator, however, doesn't work on an actual device with android six unless it works on background. When the app killed by the user, doesn't receive messages.

**Comment by rayworks** [comment]
Got the same error on Nokia TA-1000 OS 9.0 with 
`com.google.gms:google-services:4.2.0`
`com.google.firebase:firebase-messaging:17.4.0`

W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg="app-pkg-name" (has extras) }

**Comment by luanrafael** [comment]
I get the same problem with: 

Xiomi Mi 9

**Comment by montaqa** [comment]
i believe this has nothing to do with FCM, it is a service at the end of the day and you need to look on how to maintain a service from being killed by the OS and you will find a lot by googling on this.

**Comment by taar1** [comment]
I was able to solve the problem. In our app we are displaying a splash screen (SplashActivity.java) before the app starts.
So when a push notification comes in and I tapped it it opened the app but loaded SplashActivity and not MainActivity. SplashActivity does nothing else than opening MainActivity with an Intent. The problem there was that it didn't forward the Extras from the Bundle and therefore there never was any payload in MainActivity. Forwarding the payload from SplashActivity to MainActivity solved the problem for me.

Here how it looks like:

```

public class SplashActivity extends AppCompatActivity {
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Intent intent = new Intent(this, MainActivity.class);

        // Forward the Payload of Push Notifications to the MainActivity here.
        if (getIntent().getExtras() != null) {
            intent.putExtras(getIntent().getExtras());
        }
        startActivity(intent);
        finish();
    }
}
```

**Comment by KORuL** [comment]
> I was able to solve the problem. In our app we are displaying a splash screen (SplashActivity.java) before the app starts.
> So when a push notification comes in and I tapped it it opened the app but loaded SplashActivity and not MainActivity. SplashActivity does nothing else than opening MainActivity with an Intent. The problem there was that it didn't forward the Extras from the Bundle and therefore there never was any payload in MainActivity. Forwarding the payload from SplashActivity to MainActivity solved the problem for me.
> 
> Here how it looks like:
> 
> ```
> 
> public class SplashActivity extends AppCompatActivity {
>     @Override
>     protected void onCreate(Bundle savedInstanceState) {
>         super.onCreate(savedInstanceState);
> 
>         Intent intent = new Intent(this, MainActivity.class);
> 
>         // Forward the Payload of Push Notifications to the MainActivity here.
>         if (getIntent().getExtras() != null) {
>             intent.putExtras(getIntent().getExtras());
>         }
>         startActivity(intent);
>         finish();
>     }
> }
> ```

Not the problem

**Comment by KORuL** [comment]
I heard that for some there is a solution with adding an application to autostart, but this requires actions from the user, maybe there is some kind of flag in the manifest?

**Comment by rayworks** [comment]
FYI. About granting auto start permission, there is a [library](https://github.com/judemanutd/AutoStarter) trying to make it for all the non-stock android phones.

**Comment by mariooooo** [comment]
Meizu M5
Android 5.1
The same problem doesn't get the message when app killed, on the emulator 5.1 all work fine

**Comment by ambr89** [comment]
Does anyone found the solution?

I've Android device and I receive the push message only if ap is in the background but not killed.

Android 8.0.0

**Comment by suseendhar** [comment]
Is there any solution found?  issue happens in samsung galaxy mobiles too

**Comment by fluidsonic** [comment]
I have the same issue. Somewhat.

- Latest Firebase libraries
- Happens on emulator for Android 10 (API 29 with Google APIs)
- Also happens on Google Pixel 2 with Android 10
- App in background = all is fine
- App removed from recent apps by swiping = no push notifications
- Background restriction status: not restricted
- Standby bucket: active

Logcat (app kill):
```
2020-04-09 21:21:00.263 2036-2058/? I/ActivityManager: Killing 898:<package>/u0a135 (adj 905): remove task
…
2020-04-09 21:21:01.088 2036-6481/? I/ActivityManager: Force stopping <package> appid=10135 user=0: from pid 1129
```

Logcat (message delivery):
```
W/GCM: broadcast intent callback: result=CANCELLED forIntent { act=com.google.android.c2dm.intent.RECEIVE pkg=<package> (has extras) }
```

`adb shell dumpsys package <package> | grep stopped`:
```
User 0: ceDataInode=-4294836147 installed=true hidden=false suspended=false stopped=true notLaunched=false enabled=0 instant=false virtual=false
```

**But:**
After some testing it looks like that `stopped=true` is only the case when I've started the app with Android Studio. If I start the app manually or using `adb shell am start -n` and *then* kill it (swipe from recents) then the state is `stopped=false` and push notifications work just fine!

**Comment by Anuradha677** [comment]
when I am publishing message in firebase, the notification message displaying in Andriod Studio logcat. But the same notification is displayed in the emulator. I am using Andriod 9.0.
Can someone please help me with this?
I have build the messaging app in Andriod Studio.

**Comment by GoldLinPan** [comment]
I also can't receive notification in System Notification Bar when App is killed by swiping remove Unless the app is set to run in the background and can start automatically in the system settings （default is auto managed by System).

    mobile phone : Huawei honor 20
    System: Magic UI  3.1.0 (based on Android 10)

**Comment by evgentset** [comment]
Same issue on Samsung Galaxy A5 with Android 8.0.0. 
I use Data Message with custom data payload.
Method onMessageReceived (from FirebaseMessagingService) is not called if the app was removed from recent app. Looks like the app was killed in this case, so FirebaseMessagingService also was stopped. 


implementation 'com.google.firebase:firebase-messaging:20.2.0'

**Comment by evgentset** [comment]
ahhh... found this on SO - https://stackoverflow.com/questions/48642423/firebase-push-notification-issue-in-android-when-app-is-closed-killed
I tested with release build and it works for me.

**Comment by katowulf** [comment]
There is nothing actionable in this thread related to the Android quickstart; this isn't the correct place to troubleshoot message delivery issues.
