### ISSUE TITLE
Android Firebase Crashlytics displays no crashes for Internal Test Track

### ISSUE THREAD

**Issue by udaysrinath** [firebase/quickstart-android#825]
### Step 1: Describe your environment 

 * Android device: Pixel XL
  * Android OS version: 9.0
  * Google Play Services version: 15.0.90
  * Firebase/Play Services SDK version: 16.0.2
  * Crashlytics SDK(com.crashlytics.sdk.android:crashlytics) version : 2.9.9
  * Crashlytics NDK (com.crashlytics.sdk.android:crashlytics-ndk) version : 2.0.5

### Step 2: Describe the problem:

How do I see the crashlytics crashes with symbols both for android and native (via NDK).
 > I am currently on the internal track for the app, as it is under development and not released yet. I also tried publishing to the alpha track and did not make any difference. The app is published as a AAB (android app bundle).
Am I missing any steps to get symbols uploaded?

I also have an issue opened on stackoverflow here : https://stackoverflow.com/questions/54836789/android-firebase-crashlytics-displays-no-crashes-for-internal-test-track

#### Steps to reproduce:

Integrate crashlytics SDK and NDK in an android app following the instructions here: https://firebase.google.com/docs/crashlytics/get-started#android

#### Observed Results:
I have firebase crashlytics integrated on a new android app and its currently deployed on internal test track only. I see the internal version tags show in crashlytics but I see no crashes for that those versions.

Are crashlytics logs not available for internal test track? Would they work for alpha (closed) test track?

#### Relevant Code:

```AndroidManifest.xml``` has 

```
<meta-data android:name="firebase_crashlytics_collection_enabled"  
 android:value="false" />
```

Initializing as:

```
Fabric.with(Fabric.Builder(this)
                    .kits(Crashlytics(), CrashlyticsNdk())
                    .build())

```

in the ```Application``` subclass.

Also added:

```implementation 'com.crashlytics.sdk.android:crashlytics-ndk:2.0.5'``` to the ```build.gradle``` for **crashlytics ndk** support. (Assuming the symbols are uploaded automatically with cmake build)

**Comment by udaysrinath** [comment]
@google-oss-bot Updated.

**Comment by samtstern** [comment]
@udaysrinath sorry for the slow response here.  Can you give more information about the "internal test track"?  Does it have the same package name?  Is it in the same Firebase project?  What are the differences in general
