### ISSUE TITLE
don't see in my facebook profile in firebase

### ISSUE THREAD

**Issue by alexd555** [firebase/quickstart-android#830]
I click on "continue with facebook" button and see my profile but I don't see in my facebook profile in firebase console.
What may be the reason ?

Thanks,
Alex

**Comment by samtstern** [comment]
@alexd555 sorry for the slow response here but as @google-oss-bot said, this issue does not contain enough information to reproduce the error and debug it.  If this is still an issue for you, please fill out the entire template and try again.
