### ISSUE TITLE
Camera quality is too low

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [firebase/quickstart-android#832]
### Step 1: Describe your environment

  * Android device: Nokia 7.1
  * Android OS version: Pie
  * Google Play Services version: _4.2.0
  * Firebase/Play Services SDK version: _ml-vision:19.0.2
  
### Step 2: Describe the problem:

Camera quality is too low...And how to implemented Camera2,, Because android.hardware.Camera is deprecated...

**Comment by samtstern** [comment]
I am going to track this along with some other issues in #832
