### ISSUE TITLE
Using FCM on the android 9 device, the prompt Detected problems with API compatibility appears, check if the undeveloped API is used to output the following log.

### ISSUE THREAD

**Issue by ayyf** [firebase/quickstart-android#835]
### Step 1: Describe your environment

  * Android device: ____android 9 device_
  * Android OS version: __android 9___
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: __27.4.0___
  
### Step 2: Describe the problem:

Using FCM on the android 9 device, the prompt Detected problems with API compatibility appears, check if the undeveloped API is used to output the following log.

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
Please fill out the issue template when filing issues!
