### ISSUE TITLE
Face detection in ml kitis too slow in samsung device....

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [firebase/quickstart-android#837]
### Step 1: Describe your environment

  * Android device: _Samsung note 7
  * Android OS version: _oero
  * Google Play Services version: _4.2.0
  * Firebase/Play Services SDK version: _17.0.2
  
### Step 2: Describe the problem:

It's too slow in samsung device. quality also too low. in Face Detection and Face contoure...

Can you please upgrade your code to latest camera.. because  all camera property are deprecated.
  ```

**Comment by samtstern** [comment]
@Priyanka-Mohanty the speed issue should not be because of Camera1 vs Camera2, but we are tracking that upgrade and other performance improvements in #842
