### ISSUE TITLE
(Text Recognition) The Preview Camera moves slowly even though I edited "requestedFps" to max

### ISSUE THREAD

**Issue by nhattv18** [firebase/quickstart-android#841]
### Step 1: Describe your environment

   * Android device: Samsung S8
  * Android OS version: 9.0
  * Google Play Services version: 4.2.0
  * Firebase/Play Services SDK version: firebase-ml-vision:18.0.2
  
### Step 2: Describe the problem:

The Preview Camera moves slowly even though I edited "requestedFps" to max. 

You can watch this video: [https://drive.google.com/open?id=158jpsnVzwClO3DSR3GU5jmAgzLf7ppG7](https://drive.google.com/open?id=158jpsnVzwClO3DSR3GU5jmAgzLf7ppG7)

Please explain help me. Thank you!

#### Steps to reproduce:

  1. Run MLKit project
  2. Select LivePreviewActivity
  3. Select Text Detection
  
#### Observed Results:

  * The Preview Camera moves slowly
  
#### Expected Results:

  * Camera moves fast
  
#### Relevant Code:
......

**Comment by samtstern** [comment]
@nhattv18 thanks for the feedback!  I am going to join this with some other related bugs in #842
