### ISSUE TITLE
Getting Tracking Id -1 in ALL_CONTOURS  

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [firebase/quickstart-android#845]
.setPerformanceMode(FirebaseVisionFaceDetectorOptions.FAST)
                .setContourMode(FirebaseVisionFaceDetectorOptions.ALL_CONTOURS)
                .setMinFaceSize(0.1f)
                .enableTracking()
                .build()
Here getting tracking id for all face -1. when i set  contour mode?
How get different tracking id for different face at time of  using contours...???

**Comment by samtstern** [comment]
@Priyanka-Mohanty are you able to reproduce this in the sample app in this repo?

**Comment by Priyanka-Mohanty** [comment]
yes,,,,

**Comment by samtstern** [comment]
I will check with the team to see if multiple-face tracking should be supported in contour mode.

**Comment by samtstern** [comment]
@Priyanka-Mohanty this is the intended behavior:

https://firebase.google.com/docs/ml-kit/android/detect-faces#1-configure-the-face-detector

> Note that when contour detection is enabled, only one face is detected, so face tracking doesn't produce useful results. For this reason, and to improve detection speed, don't enable both contour detection and face tracking.

**Comment by Priyanka-Mohanty** [comment]
Thanks @samtstern ,One Doubt i have, when i checked in demo app , speed of camera in contour is fast as compare to FaceDetection Label , If i used this following parameter , speed of camera detection in too much slow... Why ??? do you have any idea?? and how to fix it???
FirebaseVisionFaceDetectorOptions highAccuracyOpts =
        new FirebaseVisionFaceDetectorOptions.Builder()
                .setPerformanceMode(FirebaseVisionFaceDetectorOptions.ACCURATE)
                .setLandmarkMode(FirebaseVisionFaceDetectorOptions.ALL_LANDMARKS)
                .setClassificationMode(FirebaseVisionFaceDetectorOptions.ALL_CLASSIFICATIONS)
                .build();
