### ISSUE TITLE
error: package com.google.firebase.auth does not exist. How to fix ?

### ISSUE THREAD

**Issue by AmiraJaafar** [firebase/quickstart-android#846]
I try to do login/registration using Android Studio and Firebase. I want to run the application but I cant because there seem to be an error.

![Error](https://user-images.githubusercontent.com/39890229/54876056-5d34e100-4e44-11e9-88f8-1d432ae74ceb.PNG)

So, here are the dependencies I have add.

![dependencies](https://user-images.githubusercontent.com/39890229/54876096-d46a7500-4e44-11e9-8dd8-f4557e69c6fb.PNG)

![3](https://user-images.githubusercontent.com/39890229/54876097-dcc2b000-4e44-11e9-9ae6-32ff0bdc29d0.PNG)

**Comment by samtstern** [comment]
@AmiraJaafar change `androidTestImplementation` to `implementation` for the dependencies on `firebase-auth` and `firebase-core` so they will be included in your app, rather than in your tests.
