### ISSUE TITLE
Cannot create interpreter: Didn't find op for builtin opcode 'SPLIT' version '3' . Registration failed.

### ISSUE THREAD

**Issue by yizhaoyanbo** [firebase/quickstart-android#848]
### Step 1: Describe your environment

  * Android device: __honor 9___
  * Android OS version: __8.0.0___
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
### Step 2: Describe the problem:

I have transformed the .pb model to .tflite model using the following code:

![image](https://user-images.githubusercontent.com/26928415/54903177-3ba42a00-4f16-11e9-8e49-8a5be6d63d32.png)

Then I wanna to use it in mlkit custommodel and I load it from local file.
But the following error occurs:
![image](https://user-images.githubusercontent.com/26928415/54902810-490ce480-4f15-11e9-922f-38fe79ecbf62.png)

#### Steps to reproduce:

 the error occurs at following rows of code:
![image](https://user-images.githubusercontent.com/26928415/54902896-7a85b000-4f15-11e9-976c-8b160fbeb6c7.png)

  
#### Observed Results:

 The logcat outputs are following:
Cannot create interpreter: Didn't find op for builtin opcode 'SPLIT' version '3' . Registration failed.
  
#### Expected Results:

  run successfully.

**Comment by samtstern** [comment]
This looks pretty similar to an issue that @the-dagger faced in #568 and the result was this blog post:
https://heartbeat.fritz.ai/compiling-a-tensorflow-lite-build-with-custom-operations-cf6330ee30e2'

I hope that link is helpful!

**Comment by harshithdwivedi** [comment]
Hey @samtstern Harshit here (I got locked out of my old account @the-dagger because of reasons ...)

@yizhaoyanbo The link above should help, let me know in case you face any issues; I'll be happy to help!

**Comment by samtstern** [comment]
Good to know @harshithdwivedi !

I think I will close this issue as the link should be the proper solution here. @yizhaoyanbo let us know if it doesn't work.

**Comment by yizhaoyanbo** [comment]
@samtstern @harshithdwivedi  I have tried to use the method following this blog post [https://heartbeat.fritz.ai/compiling-a-tensorflow-lite-build-with-custom-operations-cf6330ee30e2](url).

I copy the split.cc  from  tensorflow/tensorflow/lite/kernels/split.cc and change it to split.h. I have done the step1-step3 following the blog post.  But this error occurs in step 4 when I wanna to Build the Custom TensorFlow Dependency.

![image](https://user-images.githubusercontent.com/26928415/55270695-15e3a000-52dd-11e9-8e51-97f7bb7864bc.png)

I am confused. How can I deal with it?   thanks for your help.

**Comment by harshithdwivedi** [comment]
Looks like the you added one of the headers twice, can you give me more info on which model you're trying to load?
I'll try to look into it

**Comment by yizhaoyanbo** [comment]
[nimaModel.zip](https://github.com/firebase/quickstart-android/files/3025288/nimaModel.zip)
I have upload my model to the attach files nimaModel.zip.  
Thanks.
@harshithdwivedi

**Comment by yizhaoyanbo** [comment]
@harshithdwivedi  Do you have any ideas with my nimaModel?   Thanks

**Comment by harshithdwivedi** [comment]
@yizhaoyanbo Can you share your `builtin_ops_jni.cc` file?
It looks like your header declarations have some problems.

It's quite possible that you've included some headers in multiple files recursively.
Can you also share a short diff of all the files that you've edited?

More explanation on the issue that you're facing here : https://stackoverflow.com/questions/30821356/multiple-definition-first-defined-here-errors
https://stackoverflow.com/questions/34614523/multiple-definition-error-c

**Comment by yizhaoyanbo** [comment]
@harshithdwivedi  
In dir /tensorflow/tensorflow/lite/java/src/main/native/,  I have added 1 file "split.h" and edited 2 files "builtin_ops_jni.cc" and "BUILD".
![image](https://user-images.githubusercontent.com/26928415/55849978-333e2700-5b85-11e9-9fd5-68a6ce9dc980.png)


1. The "split.h" file is copied from  /tensorflow/tensorflow/lite/kernels/split.cc  and I renamed it from .cc to .h
![image](https://user-images.githubusercontent.com/26928415/55850018-4f41c880-5b85-11e9-9d81-f657a2528b74.png)


2. I added  " #include "tensorflow/lite/java/src/main/native/split.h" into the file "builtin_ops_jni.cc".  Also I  added the "split.h" into BUILD->cc_library->hdrs
![image](https://user-images.githubusercontent.com/26928415/55849997-418c4300-5b85-11e9-9d0f-0b30279e29e8.png)

I uploaded the whole native dir, though I have only edited the above 3 files.  thanks.
[native.zip](https://github.com/firebase/quickstart-android/files/3061860/native.zip)

**Comment by yizhaoyanbo** [comment]
@harshithdwivedi  
![image](https://user-images.githubusercontent.com/26928415/56074193-b5765780-5de0-11e9-856d-8c75d46cc494.png)

I find that if I change split.cc to split.h directly and put it in the native dir. The above error occurs.  Because in the split.cc file,  the Register_SPLIT( ) function has been defined. Then the split.h file will also contain this function's defination. 
So as you describe in the post, may be it does not works.
