### ISSUE TITLE
How to check full face detect,,means all 32 points of face should be display, eyes points,mouths point , nose point, and eyebrows point,,, ?? Now side face also detect,, but i want only full face detection without hiding any faces  part... how to do???

### ISSUE THREAD

**Issue by Priyanka-Mohanty** [firebase/quickstart-android#849]
How to check full face detect,,means all 32 points of face should be display, eyes points,mouths point , nose point, and eyebrows point,,, ?? Now side face also detect,, but i want only full face detection without hiding any faces  part or without coming any obstacles in face... how to do???  just like in ios CIFaceDetector

**Comment by samtstern** [comment]
@Priyanka-Mohanty this issue does not follow the issue template.  If you have general questions like this, try StackOverflow or another open-ended Q&A community.
