### ISSUE TITLE
Notification badges in notification payload are not handled for FCM android

### ISSUE THREAD

**Issue by gtl-kapil-thadani** [firebase/quickstart-android#85]
FCM does not handles notification badge counts in android. 

If my app is in background, it is impossible to update badge count of the app icon!

This is because when we have "notification payload", onMessageReceived is not called when app is in background. Hence, as a general feature, FCM should itself handle badge count coming from notification payload.

It is handled for IOS but not for Android!

[https://firebase.google.com/docs/cloud-messaging/http-server-ref#notification-payload-support]

**Comment by samtstern** [comment]
@gtl-kapil-thadani Notification badges are not supported on most Android devices, they're only enabled by custom launchers.  Therefore they are not a part of FCM.

**Comment by hamedgol** [comment]
How to handle custom count badge?

**Comment by Lu1stron** [comment]
@hamedgol  Checkout [this](https://github.com/leolin310148/ShortcutBadger) 
supports badge notification like iOS in some devices, really works.
