### ISSUE TITLE
Getting 503 service unavailable - Remote config

### ISSUE THREAD

**Issue by saurabhdtu** [firebase/quickstart-android#854]
### Step 1: Describe your environment

  * Android device: Redmi Note 5 pro
  * Android OS version: Android oreo 8.1.0
  * Google Play Services version: 
  * Firebase/Play Services SDK version: firebase-config:16.4.1
  
### Step 2: Describe the problem:
```
Fetch failed! Server responded with an error.
    com.google.android.gms.internal.firebase_remote_config.zzd: 503 Service Unavailable
    {
      "code": 503,
      "errors": [
        {
          "domain": "global",
          "message": "The service is currently unavailable.",
          "reason": "backendError"
        }
      ],
      "message": "The service is currently unavailable.",
      "status": "UNAVAILABLE"
    }
```
#### Steps to reproduce:
I have firebase blaze plan and this error constantly appears. I think it started coming after upgrading to latest firebase remote config library.
#### Observed Results:
    Getting 503 service unavailable
#### Expected Results:

  * What did you expect to happen?
  The firebase remote config values to be fetched from firebase console successfully.
#### Relevant Code:
Firebase Libraries being used
  ```  implementation 'com.google.firebase:firebase-core:16.0.8'
    implementation 'com.google.firebase:firebase-config:16.4.1'
    implementation 'com.google.firebase:firebase-messaging:17.5.0'
    implementation "com.google.android.gms:play-services-auth:16.0.1"

    implementation 'com.google.firebase:firebase-storage:16.1.0'
   
  ```
```
 long cacheExpiration = 4800;
        if (firebaseRemoteConfig.getInfo().getConfigSettings().isDeveloperModeEnabled()) {
            cacheExpiration = 2;
        }
        firebaseRemoteConfig.fetch(cacheExpiration)
                .addOnCompleteListener(this, task -> {
                })
                .addOnFailureListener(e -> {
                 
                });
  ```

**Comment by always-akshat** [comment]
+1

**Comment by samtstern** [comment]
@saurabhdtu @always-akshat thank you both for reporting this!  Looks like we had a slight increase in 503 errors coming from the server overnight.  It should be resolved now and there's nothing you need to do in your code.

In general if you are experiencing a service disruption, this repo is not the right place to get help quickly.  You should:

1. First check the Firebase status dashboard to see if there is an ongoing incident: https://status.firebase.google.com/
2. Email Firebase Support (https://firebase.google.com/support/) if you need immediate assistance or if your app is broken.
