### ISSUE TITLE
Does MLKIT support NPU ?

### ISSUE THREAD

**Issue by yizhaoyanbo** [firebase/quickstart-android#860]
Does MLkit support NPU to accelerate the computation in the mobilePhone which has NPU chip?  Or it only supports CPU and GPU to do the prediction ?

**Comment by samtstern** [comment]
@yizhaoyanbo I believe this is the same question as this issue:
https://github.com/firebase/quickstart-android/issues/802

MLKit does attempt to use the Android Neural Networks API (NNAPI) when possible.
