### ISSUE TITLE
Messaging 

### ISSUE THREAD

**Issue by emailsubjekt** [firebase/quickstart-android#862]
Why isn't there a timestamp implemented here, no data models either, what's the point? More explanations about the notification service please. I can't find a single example with timestamp implemented 

### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@emailsubjekt your question is not clear, I am not sure what it means to "implement a timestamp" or even what quickstart you're referencing.  When filing issues here please use the issue template so that we can help you.
