### ISSUE TITLE
Android ML Kit Firebase FirebaseVisionText, block.getCornerPoints() always returns null value. 

### ISSUE THREAD

**Issue by androidsparkling** [firebase/quickstart-android#866]
![image](https://user-images.githubusercontent.com/22494719/56641084-24319b80-6692-11e9-89fc-aeb14bbfc40a.png)

**Comment by samtstern** [comment]
@androidsparkling a screenshot of a debugger is not enough information to help you.  It's not clear what you were trying to do, what code you wrote, and what the situation was.  It also seems like you are trying to report a bug in the Android SDK itself (not this sample), which should be done on the "firebase-android-sdk" repo.

**Comment by manzooralam** [comment]
Even in the elements return as a  `:[Landroid.graphics.Point;@9c14ebc`

**Comment by manzooralam** [comment]
Bounding Box coming   **Rect(1732, 2243 - 1899, 2318)** by using  `elements.get(k).getBoundingBox()` 

But CornerPoints coming **[Landroid.graphics.Point;@9c14ebc** by using 
 `elements.get(k).getCornerPoints()` 

**Why getCornerPoints() not works?**
