### ISSUE TITLE
React native android app was not run in pie

### ISSUE THREAD

**Issue by Resma-Raj** [firebase/quickstart-android#872]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
This doesn't sound like an issue with the quickstart, or even Firebase.  And there's no information here so I have to close the issue.
