### ISSUE TITLE
Crashlytics for android apps using CMake for native code

### ISSUE THREAD

**Issue by Consti10** [firebase/quickstart-android#875]
Feature request for android Crashlytics:

I haven't found any information regarding the use of Crashlytics with android projects that use CMake to compile c/c++ code into a native library.

After following this tutorial https://firebase.google.com/docs/crashlytics/ndk-reports and creating a  native crash in my  CMake-compiled code the information in the Firebase console still looked like this:
![CaptureZ](https://user-images.githubusercontent.com/16462285/58012820-a1b3c480-7af5-11e9-908c-b091fdd4c3b3.JPG)

Please clarify /add if crashlytics already 'supports CMake' and how to enable it - 'support' in this context would mean 'provide exact information where / why the crash happened in native code' and not that a crash happened without any more info (as in the image above).

**Comment by samtstern** [comment]
@TKBurner can you help out with this one?

@Consti10 thanks for filing this!
