### ISSUE TITLE
It makes updateUI error in java android studio 3.4

### ISSUE THREAD

**Issue by demoncoderad** [firebase/quickstart-android#879]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@demoncoderad sorry but there's not enough information here to help you.  Please use the issue template when filing issues!
