### ISSUE TITLE
Foreground Notification

### ISSUE THREAD

**Issue by mayurteraiya** [firebase/quickstart-android#885]
{"to":"dLN-4zOwcrQ:APA91bF2PMW76qodEpZm3LAw6buW4MfasLNhY6ShReAZ5qUREm49NpklMCi_6URlyFttuYNLmRCbPXHME25-u-FETMJHi3Pbbm62mbG1FSOBLFcVwt3_aW2vydFbbFCYpFNVjRcVoI48","data":{"title":"HomeDelight","body":"HomedelightGeoLoc","IsImage":0,"ImagePath":"","TypeId":2,"SubserviceId":-1,"URL":"","BookingId":-1,"SubServiceName":"","typeName":"open"}}

Above is notification data. And its notworking in few device with foreground notification.

PLEASE HELP. Thanks in advance.

**Comment by samtstern** [comment]
@mayurteraiya sorry but that's really not enough information to debug, plus it doesn't sound like this is an issue with the quickstart at all.  Please try contacting Firebase support if you're having issues with FCM in production.
