### ISSUE TITLE
Where is BaseEntryChoiceActivity?

### ISSUE THREAD

**Issue by VirRajpurohit** [firebase/quickstart-android#899]
I have downloaded the source code and tried running mlkit out of it.
I am unable to run it and ended up with several errors.
few of them.
**ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve project :internal:chooserx.**

I have commented the implementation in build.gradle file then 
bunch of errors I have recieved in EntryChoiceActivity as not finding imports for

import com.firebase.example.internal.BaseEntryChoiceActivity
import com.firebase.example.internal.Choice
import com.google.firebase.quickstart.fcm.java.MainActivity

**Comment by samtstern** [comment]
@VirRajpurohit thanks for filing this.  How are you loading the project into Android Studio did you:

1. Load the entire `quickstart-android` project and try to run the `mlkit:app` module? OR
2. Load just the `mlkit` folder and try to run the `app` module?

**Comment by samtstern** [comment]
@VirRajpurohit I think I found and fixed the issue in https://github.com/firebase/quickstart-android/commit/4c75a7c8fb37a95367e4ca3f05c094fbec1af5cd

**Comment by VirRajpurohit** [comment]
@samtstern 

I am using 2nd approach.

Changing
include ':internal:chooserx'
project(':internal:chooserx').projectDir = file('../internal/chooserx') helped to resolve most of this.

but 
yet ended up with the issue in import of below

import com.google.firebase.**quickstart**.fcm.java.MainActivity

Please assist.

**Comment by samtstern** [comment]
@VirRajpurohit that sounds like a different issue, are you trying to run the `fcm` quickstart?

**Comment by VirRajpurohit** [comment]
@samtstern 
No, I tried running MLKit only.

The issue is in EntryChoiceActivity.kt

return 
```
kotlin.collections.listOf(
                Choice(
                        "Java",
                        "Run the Firebase Cloud Messaging quickstart written in Java.",
                        Intent(this, MainActivity::class.java)),
                Choice(
                        "Kotlin",
                        "Run the Firebase Cloud Messaging written in Kotlin.",
                        Intent(this, MainActivity::class.java))
        )
```

The MainActivity in above code asks for import

`import com.google.firebase.quickstart.fcm.java.MainActivity`

**Comment by samtstern** [comment]
@VirRajpurohit I think your local state has gotten messed up.  I can see the line you're talking about but it's not in the `mlkit` quickstart:

https://github.com/firebase/quickstart-android/blob/4c75a7c8fb37a95367e4ca3f05c094fbec1af5cd/messaging/app/src/main/java/com/google/firebase/quickstart/fcm/EntryChoiceActivity.kt#L6

As you can see in MLKit there is no such line:
https://github.com/firebase/quickstart-android/blob/4c75a7c8fb37a95367e4ca3f05c094fbec1af5cd/mlkit/app/src/main/java/EntryChoiceActivity.kt#L7

I was able to run the following, which shows there is no build issue in `messaging` either:
```
cd messaging
./gradlew assembleDebug
```

I would say you should clear your local copy and `clone` again.

**Comment by VirRajpurohit** [comment]
@samtstern 
Thanks for your consistent help.

Now, while accesing StillImaheActivity and features inside.

I have some error of cloud vision API that it needs to be enabled, but I have not created any project over there.

My project is in firebase.

So does that needs to be added in google console as well?

Please asist.

**Comment by samtstern** [comment]
@VirRajpurohit yes if you want to use cloud models you will need to enable the cloud APIs on your project in the cloud console.

Also please file new issues for any more questions/bugs.

**Comment by VirRajpurohit** [comment]
@samtstern 
Perhaps, Last question in a raw

How I need to add the project on google console?

You mean separately same as I have added it on firebase?

Please assist.

**Comment by Anuradha677** [comment]
> @samtstern
> 
> I am using 2nd approach.
> 
> Changing
> include ':internal:chooserx'
> project(':internal:chooserx').projectDir = file('../internal/chooserx') helped to resolve most of this.
> 
> but
> yet ended up with the issue in import of below
> 
> import com.google.firebase.**quickstart**.fcm.java.MainActivity
> 
> Please assist.

Thanks for posting this. I was not included Internal folder due to that it was throwing the dependency errors. It is solved.
