### ISSUE TITLE
FirebaseMessagingService extended service class destroyed in android version 7.1.1 and lower

### ISSUE THREAD

**Issue by RohiniRaman31** [firebase/quickstart-android#906]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: __7.1.1 and lower___
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

I have set the broadcast receiver for my notification action buttons and register the receivers in the FirebaseMessagingService extended class onCreate() method and unregistered in OnDestroy() method  this work fine in android version 8+ devices ,but in devices with 7.1.1 and lower version the onDestroy() method called quickly after the onMessageReceived() method
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@RohiniRaman31 please use the issue template when filing issues.
