### ISSUE TITLE
ava.lang.NullPointerException  Attempt to invoke virtual method 'com.google.firebase.remoteconfig.a com.google.firebase.remoteconfig.h.a(java.lang.String)' on a null object reference

### ISSUE THREAD

**Issue by YanCorey** [firebase/quickstart-android#908]
version:  'com.google.firebase:firebase-config:18.0.0'
device:   XIAOMI REDMI NOTE 5  Android 7.1.2,level 25 arm64-v8a
I call in the application the FirebaseApp. InitializeApp (this); Because there is a crash before the Default FirebaseApp is not initialized in this process. Global callu. Android. Make sure to call FirebaseApp. InitializeApp (Context) first.
After I called in application FirebaseRemoteConfig getInstance (); This collapse Attempt to invoke virtual method '. Com. Google firebase. Remoteconfig. Com. "its firebase. Remoteconfig. H.a (Java. Lang. String) 'on a null object reference

**Comment by YanCorey** [comment]
Is there any major change in 18.0.0? FirebaseInstanceId initialization also has a null pointer. Is it wrong with me?

**Comment by re-LIFE** [comment]
i use Firebase Notification , I get Crash 7K  , before this never happen

and i get Major Report From Google Play Store

**Comment by thatfiredev** [comment]
@YanCorey Can you please update to the latest version of the Android Firebase SDK?

If the error still persists, it would be useful if you could also provide all the relevant code here.

Closing this now, but feel free to re-open if the error is still there.
