### ISSUE TITLE
"Recipient time zone" based push notifications not working

### ISSUE THREAD

**Issue by Adarshkl** [firebase/quickstart-android#911]
I have created a recurring notification, but the recipients are not receiving these notifications. The scheduling is as below:
![image](https://user-images.githubusercontent.com/16320768/61305828-27f43a80-a809-11e9-84d7-cff572c290ad.png)

**The 'Send Now' option works just fine.** 

The target is the entire userbase of the app:
![image](https://user-images.githubusercontent.com/16320768/61306341-0a73a080-a80a-11e9-9422-25bc0015e74b.png)

I have configured a default notification channel too:
![image](https://user-images.githubusercontent.com/16320768/61306184-c4b6d800-a809-11e9-9130-e40d3eedadcd.png)

Is there anything more I am expected to do from the application to get this working?

**Comment by samtstern** [comment]
@Adarshkl sorry you're having this issue!  Unfortunately this repository is not the best place to get help with console/backend related issues like this one.  Please try Firebase support:
https://firebase.google.com/support
