### ISSUE TITLE
getbitmap(contentresolver url): bitmap is deprecated in java

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [firebase/quickstart-android#912]
Hi 

I'm trying to create this onActivity method and using Bitmap. Which is deprecated in AndroidX 29Api. So let me know how to fix this problem.

getbitmap(contentresolver url): bitmap is deprecated in java 

I got an error that only Bitmap is deprecated in Java. Please help me to fix this

**Comment by samtstern** [comment]
@KanwarpartapSinghBimrah this does not seem to be a problem with this quickstart and there's not enough information in your report to help you.  Please try another forum like StackOverflow for general help like this.
