### ISSUE TITLE
NotifFirebaseMessagingService   Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by re-LIFE** [firebase/quickstart-android#914]
### Step 1:  Environment

  * Android device: Samsung ( J SERIES ) , Motorola ( G Series ) , Xiaomi , LG
  * Android OS version: Android 9 , Android 8.1 , Android 8.0 , Android 7.1
  * Google Play Services version: 11.4.0
  * Firebase/Play Services SDK version: 11.4.0
  
###  My problem:

yesterday, I used Firebase notification, then when the notification was sent I got a 7K Crash on my application's device user

before this never happened, but this incident suddenly happened

#### Steps  reproduce:

1. Fill in the Title notification

2. Fill in the notification description

3. Entering images through the url and the images displayed on the notification
  
#### Observed Results:

 ![1  Crashlitycs  Fabric.io](https://user-images.githubusercontent.com/27994247/61423495-34c47b80-a93a-11e9-8651-5b296720b5ff.png)

![crash report](https://user-images.githubusercontent.com/27994247/61423590-98e73f80-a93a-11e9-9009-84d201e8feaf.png)

![playstore 2](https://user-images.githubusercontent.com/27994247/61423781-43f7f900-a93b-11e9-8ec8-c7f9037990ad.png)

  
#### My Expected Results:

  is this because of library problems from firebase?
  
#### Relevant Code:

  Code Line 39
![LINE 39](https://user-images.githubusercontent.com/27994247/61423669-d6e46380-a93a-11e9-8641-cc2c0a94f663.png)

This Full code
![carbon](https://user-images.githubusercontent.com/27994247/61423685-e368bc00-a93a-11e9-92c4-cc8ce5e5840a.png)

**Comment by samtstern** [comment]
@re-LIFE thanks for filing this and I am sorry to hear about this crash!  However there's really nothing that can be done about this issue on our Quickstart GitHub repo.  Please file a ticket with Firebase support, they are better equipped to investigate this:
https://firebase.google.com/support
