### ISSUE TITLE
Methods deprecated in Android X

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [firebase/quickstart-android#915]
See screenshot and let me know how to solve this.
![Screenshot (27)](https://user-images.githubusercontent.com/39325207/61579970-d958e000-ab29-11e9-85e2-7ec7658b84b1.png)

**Comment by KanwarpartapSinghBimrah** [comment]
getBitmap method is deprecated in android x

**Comment by samtstern** [comment]
@KanwarpartapSinghBimrah thanks for pointing this out!  Looks like we need to update the sample to a more modern way of getting the bigmap.

**Comment by samtstern** [comment]
According to the docs:
https://developer.android.com/reference/android/provider/MediaStore.Images.Media.html#getBitmap(android.content.ContentResolver,%20android.net.Uri)

```
This method was deprecated in API level 29. loading of images should be performed through ImageDecoder#createSource(ContentResolver, Uri), which offers modern features likePostProcessor.
```

https://developer.android.com/reference/android/graphics/ImageDecoder.html#createSource(android.content.ContentResolver,%20android.net.Uri)

**Comment by KanwarpartapSinghBimrah** [comment]
Hello Sam, I know it's not urgent for you. But I do not have any ideas about it how to replace getBitmap with Postprocessor. Please help me to sort out these issues which I got in Android X. Thank you Kanwarpartap Singh
-------- Original message --------From: Sam Stern <notifications@github.com> Date: 22/07/2019  11:01 pm  (GMT+05:30) To: firebase/quickstart-android <quickstart-android@noreply.github.com> Cc: Kanwarpartap Singh <Kanwarpartapsinghbimrah@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [firebase/quickstart-android] Methods deprecated in Android X (#915) @KanwarpartapSinghBimrah thanks for pointing this out!  Looks like we need to update the sample to a more modern way of getting the bitmap.  But I don't think this is something we need to solve urgently.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/firebase/quickstart-android/issues/915?email_source=notifications\u0026email_token=AJMA4FYBKUEKT5XCNQVBQZDQAXVHRA5CNFSM4IFOZFP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2QSVNQ#issuecomment-513878710",
"url": "https://github.com/firebase/quickstart-android/issues/915?email_source=notifications\u0026email_token=AJMA4FYBKUEKT5XCNQVBQZDQAXVHRA5CNFSM4IFOZFP2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2QSVNQ#issuecomment-513878710",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by samtstern** [comment]
@KanwarpartapSinghBimrah you need to create an `ImageDecoder` and then call `decodeBitmap`.  Since this sample does not target API 29 yet there is nothing deprecated here.  If you are still confused please try StackOverflow.

**Comment by ganeshkavhar** [comment]
get ExternalStorag method ??
