### ISSUE TITLE
Notification without background color

### ISSUE THREAD

**Issue by lveigas** [firebase/quickstart-android#92]
* Android device: Samsung Galaxy S4
  * Android OS version: 5.1.1
  
Hi,

I'm using FCM to send push notifications to my app users devices on Android, but I can't set the notification background color no matter what.
The icon is correctly set, but can't set the circle background color around the icon.
Here's my message payload:

```
var fcmMessage = {
          registration_ids: device_tokens,
          time_to_live: 2419200,
          delay_while_idle : false,
          notification: {
            icon: 'notif',
            color: '#6563a4',
            sound: 'notif',
            title: title,
            body: message
          }
        };
```

Thanks in advance,
Luís

**Comment by samtstern** [comment]
@lveigas what behavior are you seeing?  The [documentation](https://firebase.google.com/docs/cloud-messaging/http-server-ref) says that the `color` attribute "Indicates color of the icon, expressed in #rrggbb format".  There is not an attribute for changing the background color around the circle so I think you are seeing the correct behavior.

**Comment by lveigas** [comment]
Hello Sam,

Thanks for the answer. I've solved the problem by replacing the
notification payload by a data payload.

**Comment by rodrigoreal** [comment]
@lveigas did you find a way to change the background color?
i'm having the same problem as you but cant find a solution for it.

**Comment by lveigas** [comment]
Hi Rodrigo,

Yes, I did. Just change the notification payload to a data payload, and use
the color attribute.
Here's an example:

var fcmMessage = {
    to: '/topics/' + req.body.language.toString(),
    priority: 'high', //If not set, notification won't be delivered on
completely closed iOS app
    data: {
        title: req.body.title.toString(),
        body: req.body.message.toString(),
        sound: 'notif',
        click_action: 'FCM_PLUGIN_ACTIVITY',  //Must be present for Android
        icon: 'fcm_push_icon',
        id: (new Date().getTime()).toString(),
        color: '#6563A4',
        action: req.body.action.toString(),
        image: req.body.image.toString()
    }
};

Hope it helps.
Regards,
    Luís Veigas
