### ISSUE TITLE
Custom notification when app is in background

### ISSUE THREAD

**Issue by pandeyVishakha** [firebase/quickstart-android#922]
Android device: for all versions
  I have problem in showing custom notification layout when app is in background.I had worked on RemoteViews. Notification is working fine in both scenario forground / background but problem with notification layout .

Forground -- custom layout shown
Background -- Default notification shown

    I know about why it is happening but want to know is there any another option to modify default notification layout as custom layout when app is in background.

**Comment by pandeyVishakha** [comment]
Which kind of information ??...I think i already provided sufficient information.

**Comment by samtstern** [comment]
@pandeyVishakha the robot was asking you to follow the format of the [Issue Template](https://github.com/firebase/quickstart-android/blob/master/ISSUE_TEMPLATE.md)

As you probably know there are two kinds of messages you can send using FCM: "data" messages and "notification" messages.

If you are using "data" messages your app can show any custom layout you want, it doesn't matter if your app is in the foreground or background.  If you are using "notification" messages you are limited to the standard layouts (although we recently added support for images).

**Comment by pandeyVishakha** [comment]
@samtstern Thanks for your suggestions!!

But am totally aware about that . What my problem is that-
I  having a  issue getting the notifications customized, i m trying to show custom layout using RemoteView instead of default view. I'm not using the console at all - only making API calls. When app is in foreground notifications get handled by my custom FirebaseMessagingService, but when app is in the background notification layout is not customized one, means that it is showing default notification tray ui.
Here is similler issue but only related to notification icon that can be managed by providing icon to notification and data payload as well but i have to design whole view instead of only icon in both foreground / background cases.
Thanks,
