### ISSUE TITLE
FirebaseVisionBarcodeDetectorOptions not detect PDF-417

### ISSUE THREAD

**Issue by jamacado** [firebase/quickstart-android#925]
I am making an application that reads barcode PDF-417 I use FirebaseVisionBarcodeDetectorOptions to pass the Formats ship, but I don't get any results, I put another format and it works. Previously I used the Barcode API of mobile Vision and it worked without problems.
Is there a bug or failure with the PDF-417?

**Comment by samtstern** [comment]
@jamacado the best thing to do would be to write in to Firebase support (https://firebase.google.com/support) and provide:

- The exact code you're running (as little as possible)
- An example of an image with PDF-417 code in it that does not scan

They should be able to help!

**Comment by zhouyiself** [comment]
@jamacado it would be also helpful to indicate which formats you specified could work.
