### ISSUE TITLE
Firebase icon doesn't show and sound not play 

### ISSUE THREAD

**Issue by paveltech** [firebase/quickstart-android#93]
I am using this code to show notification.

    private void sendNotification(String messageBody) {
        Intent intent = new Intent(this, MainActivity.class);
        intent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TOP);
        PendingIntent pendingIntent = PendingIntent.getActivity(this, 0, intent,
                PendingIntent.FLAG_ONE_SHOT);
        Bitmap b = BitmapFactory.decodeResource(getResources(), R.drawable.moviesa);
        Uri defaultSoundUri= RingtoneManager.getDefaultUri(RingtoneManager.TYPE_ALARM);
        NotificationCompat.Builder notificationBuilder = new NotificationCompat.Builder(this)
                .setLargeIcon(b)
                .setContentTitle(getResources().getString(R.string.app_name))
                .setContentText(messageBody)
                .setAutoCancel(true)
                .setSound(defaultSoundUri)
                .setContentIntent(pendingIntent);
        
        NotificationManager notificationManager =
                (NotificationManager) getSystemService(Context.NOTIFICATION_SERVICE);

        notificationManager.notify(0, notificationBuilder.build());
    }

When i run application icon doesn't show and sound not playing when my phone in sleep mode.

**Comment by kroikie** [comment]
Hi @paveltech what are you using to send the notification?

**Comment by kroikie** [comment]
Seems like you are sending notifications from the Firebase console, which will automatically generate a notification when your app is in the background. In that case your code will not be run and that is likely the reason why you are not getting the type of notification you are expecting.

From the Firebase console sound is disabled by default and there is currently a known issue about notification icons which is known and will be fixed soon.
