### ISSUE TITLE
can we use this vision API with any usb camera (UVCCamera)

### ISSUE THREAD

**Issue by vandanabpatel** [firebase/quickstart-android#938]
### Step 1: Describe your environment

  * Android device: and android device
  * Android OS version: API 28 (Oreo)
  * Google Play Services version: latest
  * Firebase/Play Services SDK version: latest
  
### Step 2: Describe the problem:
can we use this vision API with any usb camera(UVCCamera)

#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@vandanabpatel this does not seem to be a well-formed issue and it's not likely this issue is with the quickstart anyway.  If you need help connecting a USB peripheral to your Android app I would suggest trying StacvOverflow.  MLKit will accept image data from any source.
