### ISSUE TITLE
Android Firebase Storage - Imagesize too large

### ISSUE THREAD

**Issue by mrosenlund** [firebase/quickstart-android#94]
ANDROID FIREBASE STORAGE:
I setup Firebase Storage and I am unsure how to reduce the quality of the image that is uploaded. The file size is anywhere from 3mb-7mb which is far too large and I cant seem to find a way to reduce it. Also it is 4000+ x 2000+ and can't be rendered back in android.

**Comment by samtstern** [comment]
@mrosenlund this sample uploads a file from your camera at full resolution.  If you want to change the file size, you need to do that **before** interacting with Firebase Storage.  Image resizing is not a feature of Firebase Storage right now.

[This article](https://developer.android.com/training/displaying-bitmaps/load-bitmap.html) on loading large bitmaps may be useful to you.  You can load the `File` in this way, get a low-res `Bitmap`, and then pass either a `byte[]` or `InputStream` to Firebase Storage.
