### ISSUE TITLE
Where is the ML Kit Translate on-device model saved?

### ISSUE THREAD

**Issue by BlueAnthony** [firebase/quickstart-android#944]
As title, where I can find the "ML Kit Translate on-device model" in my phone?

**Comment by samtstern** [comment]
@BlueAnthony that's not something we publicly document so it could change at any time / is probably not in a place where you could easily access it.

Could you explain what you're trying to do with this information?  Maybe I can help.

**Comment by BlueAnthony** [comment]
@samtstern I want to use it to create my own translator app.

**Comment by BlueAnthony** [comment]
@samtstern I think I find it, but there are four binary files.  It seems not to be tflite file. How can I use it?

**Comment by samtstern** [comment]
@BlueAnthony sorry we don't provide information like that, I honestly don't know the answer and it's likely to change over time.  If you want to make your own translator app you can use the ML Kit API rather than the raw models, or build your own model and use that.
