### ISSUE TITLE
Error on FirebaseMessagingService class after updating com.google.firebase:firebase-messaging to 20.0.0

### ISSUE THREAD

**Issue by Gkundu1** [firebase/quickstart-android#947]
### Step 1: Describe your environment

  * Android device: RedMi
  * Android OS version: Android P
  * Google Play Services version: com.google.firebase:firebase-messaging:20.0.0
  * Firebase/Play Services SDK version: com.google.firebase:firebase-core:17.2.0
  
### Step 2: Describe the problem:

FirebaseMessagingService class
override fun onNewToken -> onNewToken override nothing
override fun onMessageReceived-> onMessageReceived override nothing
#### Steps to reproduce:

  1. Just update the existing version of the com.google.firebase:firebase-messaging to 20.0.0
  
  
#### Observed Results:

My class which extends FirebaseMessagingService now floating with lot of error after just update.

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

It supposed to work fine.

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by sonnyky** [comment]
Same here. Had to revert to 18.0.0. Any solutions yet?

**Comment by samtstern** [comment]
Can you show your code for `onNewToken` and `onMessageReceived`?  We added new nullability annotations which can be breaking changes in Kotlin.  For example some `String?` became `String` (or the other way around).

**Comment by samtstern** [comment]
See this commit for an example:
https://github.com/firebase/quickstart-android/commit/9753ac35d324440d8d06587c512ac133c7b41bca

Make sure you have:
```kotlin
// NOTE: RemoteMessage not RemoteMessage?
override fun onMessageReceived(remoteMessage: RemoteMessage)
```

```kotlin
// NOTE: String not String?
override fun onNewToken(token: String)
```
