### ISSUE TITLE
Not receiving sms using firebase android phone verification

### ISSUE THREAD

**Issue by GianhTran** [firebase/quickstart-android#949]
### Step 1: Describe your environment
Android device: Samsung Galaxy S7 edge
Android OS version: 7.0
Google Play Services version: 19.2.74(040408-265167076)
com.google.firebase:firebase-auth19.0.0
com.google.firebase:firebase-core17.2.0
com.google.android.gms:play-services-auth17.0.0
  
### Step 2: Describe the problem:
I have set up the firebase android phone verification following the official document. I double and triple check the steps. Everything seems fine, but almost of the cases, after calling `PhoneAuthProvider.verifyPhoneNumber`, the `codeSent` callback gets fired but I never received any SMS (it is OK in case of a phone number in whitelist). Tried so many times with no luck (after 5 times, firebase block my phone number). plus the onVerificationFailed callback is not called which makes me believe the problem is not from my side. I am testing from Viet Nam. 

#### Steps to reproduce:
1. get a valid phone number to verify
2. pass it to `PhoneAuthProvider.verifyPhoneNumber` along with other arguments
3. `codeSent` callback gets fired but no SMS is sent to the device
  
#### Observed Results:
The code executes with no error, but the SMS is never sent to the device even though the codeSent callback gets fired. Nothing to show from the LogCat
  
#### Expected Results:
I was expecting to receive and SMS with the verification code to complete the phone verification.
  
#### Relevant Code:

  ```
/** this function define in a fragment **/
private fun startPhoneNumberVerification() {
        btnContinueToVerifyCode.handleLoading(true)
        val phoneNumber = phoneNumberPicker.getPhoneNumber()

        PhoneAuthProvider.getInstance().verifyPhoneNumber(
            phoneNumber,
            VERIFY_PHONE_NUMBER_TIME_OUT_IN_SECOND,
            TimeUnit.SECONDS,
            requireActivity(),
            object : PhoneAuthProvider.OnVerificationStateChangedCallbacks() {
                override fun onVerificationCompleted(credential: PhoneAuthCredential) {
                    // we not using this case
                }

                override fun onVerificationFailed(e: FirebaseException) {
                    btnContinueToVerifyCode.handleLoading(false)

                    navigator.showErrorSnackbar(requireActivity(), e.message ?: getString(R.string.send_sms_error))
                }

                override fun onCodeSent(verificationId: String, token: PhoneAuthProvider.ForceResendingToken) {
                    btnContinueToVerifyCode.handleLoading(false)

                    navigator.showInformationSnackbar(requireActivity(), getString(R.string.sent_code))
                    resendToken = token

                    goToVerifyCode(verificationId)
                }
            }
        )
    }
  ```
One more thing,  I can not submit a bug report in the support page: https://firebase.google.com/support/
<img width="1232" alt="Screen Shot 2019-09-16 at 10 04 52 AM" src="https://user-images.githubusercontent.com/20894740/64932479-87061800-d869-11e9-82c1-61dcda29d6a7.png">

**Comment by PhuHoaframgia** [comment]
I have the same problem as you 😞

**Comment by samtstern** [comment]
@GianhTran @PhuHoaframgia if you're having issues with SMS please contact Firebase support:
https://firebase.google.com/support

There are many factors that can affect this (country, carrier, etc) and it's much easier for support to try and debug this, they are experts.
