### ISSUE TITLE
Hot to customise CameraSourcePreview layout? I want full screen Scanning but it shows some part only?

### ISSUE THREAD

**Issue by Pratik1827** [firebase/quickstart-android#952]
### Step 1: Describe your environment

  * Android device: _____
  * Android OS version: _____
  * Google Play Services version: _____
  * Firebase/Play Services SDK version: _____
  
#### Steps to reproduce:

  1. _____
  2. _____
  3. _____
  
#### Observed Results:

  * What happened?  This could be a description, `logcat` output, etc.
  
#### Expected Results:

  * What did you expect to happen?
  
#### Relevant Code:

  ```
  // TODO(you): code here to reproduce the problem
  ```

**Comment by samtstern** [comment]
@Pratik1827 please use the issue template when filing an issue.  You may want to try your question on StackOverflow.
