### ISSUE TITLE
I'd like to help you translate it!

### ISSUE THREAD

**Issue by ijin1322** [firebase/quickstart-android#953]
Hello. I am a college student majoring in computer engineering in Korea.
I am interested in this program so I want to help you translate Korean. Is it possible? If possible, which part should I translate? Even though my role is small, I want to contribute here!

**Comment by samtstern** [comment]
@ijin1322 hello!  Thank you for your enthusiasm and your offer.  Unfortunately we can't accept translations for this repository.  The main issues are:

1) I'd have no reasonable way to review them
2) When we make future updates we would not be able to make our own changes

I hope you understand, and good luck in school!
