### ISSUE TITLE
Too many ANR by com.google.firebase.iid.FirebaseInstanceIdReceiver

### ISSUE THREAD

**Issue by chaitendra** [firebase/quickstart-android#973]
* Android device: All
  * Android OS version: Higher then 5.0
  * Google Play Services version: 28.0.0
  * Firebase/Play Services SDK version:11.6.2

Getting too many ANR by com.google.firebase.iid.FirebaseInstanceIdReceiver in Google play console ANR & Crash logs.

Error starting with
Broadcast of Intent { act=com.google.android.c2dm.intent.RECEIVE flg=0x11000010 pkg=in.securelearning.lil.android.app.euroschool cmp=in.securelearning.lil.android.app.euroschool/com.google.firebase.iid.FirebaseInstanceIdReceiver (has extras) }

**Comment by samtstern** [comment]
@chaitendra this does not seem like it's an issue with the code in this repository.  Please file an issue on the `firebase-android-sdk` repository or contact Firebase support.  In either case, please provide more logs and information to aid with debugging.
