### ISSUE TITLE
when i connect to firebase i get this error

### ISSUE THREAD

**Issue by Mkhira** [firebase/quickstart-android#976]
Launching lib\main.dart on SM J500F in debug mode...
Initializing gradle...
Resolving dependencies...
* Error running Gradle:
ProcessException: Process "E:\flater_projects\arabete\android\gradlew.bat" exited abnormally:

FAILURE: Build failed with an exception.

* Where:
Build file 'E:\flater_projects\arabete\android\app\build.gradle' line: 24

* What went wrong:
A problem occurred evaluating project ':app'.
> ASCII

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
  Command: E:\flater_projects\arabete\android\gradlew.bat app:properties

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by kroikie** [comment]
@Mkhira since your logs are showing `lib/main.dart` I'm assuming that you are using FlutterFire in a Flutter app. If this is the case try filing an issue in the [flutterfire repo](https://github.com/FirebaseExtended/flutterfire)

**Comment by Mkhira** [comment]
For which templet should i search
