### ISSUE TITLE
Error in new code after update Build.gradle (app) file

### ISSUE THREAD

**Issue by KanwarpartapSinghBimrah** [firebase/quickstart-android#977]
Hello,

Today on 19 October 2019. I have been updated build. gradle file's dependency. But after update this I got these errors. You can check it in a screenshot and also dependency below.

```
    implementation 'com.google.firebase:firebase-ml-vision:24.0.0'
    implementation 'com.google.firebase:firebase-ml-vision-image-label-model:19.0.0'
    implementation 'com.google.firebase:firebase-ml-vision-face-model:19.0.0'
    implementation 'com.google.firebase:firebase-ml-model-interpreter:22.0.0'
    implementation 'com.google.firebase:firebase-ml-natural-language:22.0.0'
    implementation 'com.google.firebase:firebase-ml-natural-language-language-id-model:20.0.7'
    implementation 'com.google.firebase:firebase-ml-natural-language-smart-reply-model:20.0.7'
    implementation 'androidx.multidex:multidex:2.0.1'
    implementation 'com.google.firebase:firebase-ml-natural-language:22.0.0'
    implementation 'com.google.firebase:firebase-ml-natural-language-translate-model:20.0.7'
```

![Screenshot (25)](https://user-images.githubusercontent.com/39325207/67146593-540cd500-f2aa-11e9-804d-6cdcbcaa0987.png)
![Screenshot (26)](https://user-images.githubusercontent.com/39325207/67146595-540cd500-f2aa-11e9-86d1-d2cd844aed15.png)

**Comment by rosariopfernandes** [comment]
@KanwarpartapSinghBimrah the latest version of ML Kit introduced some breaking changes. These changes are documented on the [release notes](https://firebase.google.com/support/release-notes/android#mlkit-common_v22-0-0)

**Comment by KanwarpartapSinghBimrah** [comment]
@rosariopfernandes I checked the [release notes](https://firebase.google.com/support/release-notes/) and I was confused. let me know how to fix this. Have any solid example.

**Comment by rosariopfernandes** [comment]
@KanwarpartapSinghBimrah you can find the solution for TranslateViewModel on [StackOverflow](https://stackoverflow.com/a/58466167/5861618).

Now in order to fix your CustomModelActivity, you'll need to change the options you're using to create an interpreter. It would be something like this:
```kotlin
val localSource = FirebaseCustomLocalModel.Builder()
            .setAssetFilePath("my_model.tflite")
            .build()
// There's no need to register your model anymore
val options = FirebaseModelInterpreterOptions.Builder(localModel).build()
val interpreter = FirebaseModelInterpreter.getInstance(options)
```

**Comment by KanwarpartapSinghBimrah** [comment]
@rosariopfernandes I tried to sort out this error with the help of your example code. But sorry to say that I have an error in the below code. I mean only `localModel` in getting the error.

`val options = FirebaseModelInterpreterOptions.Builder(localModel).build()`

**Comment by KanwarpartapSinghBimrah** [comment]
@rosariopfernandes Hi thanks for providing the solution on this topic now its working fine.

**Comment by kikogassen** [comment]
Hi!

Does someone has an example of a AutoML LocalModel working at com.google.firebase:firebase-ml-vision v24.0.0? Only my RemoteModel is working at the moment, and I didn't find any documentation about it on v24.0.0. I also tried to read the release notes of v24.0.0 but it didn't worked

My actual code is:

        FirebaseAutoMLRemoteModel remoteModel = new FirebaseAutoMLRemoteModel.Builder(REMOTE_MODEL_NAME).build();

        FirebaseAutoMLLocalModel localModel = new FirebaseAutoMLLocalModel.Builder()
                .setAssetFilePath("automl/manifest.json")
                .build();

        FirebaseVisionOnDeviceAutoMLImageLabelerOptions.Builder optionsBuilder =
                new FirebaseVisionOnDeviceAutoMLImageLabelerOptions.Builder(remoteModel)
                        .setConfidenceThreshold(0.8f);

        detector = FirebaseVision.getInstance().getOnDeviceAutoMLImageLabeler(optionsBuilder.build());

When I pass localModel to FirebaseVisionOnDeviceAutoMLImageLabelerOptions.Builder constructor, the image isn't shown or detected
