### ISSUE TITLE
Why .getDynamicLink(intent) is required?

### ISSUE THREAD

**Issue by Ghedeon** [firebase/quickstart-android#987]
Why would you even need `FirebaseDynamicLinks.getInstance().getDynamicLink(intent)` if, at the end, the only link that hits the app is a deeplink and not the Firebase short link?

Ex:
1. The App is installed. The user clicks on a short dynamic link. The link got resolved by the browser and intent with a deep link is being thrown.
2. The App is not installed. The user clicks on a short dynamic link. Play Store flow, app is installed, the link is resolved/rethrown internally (by android `MarketDeepLinkHandlerActivity`) and your app is being opened with a deeplink again.

Did I miss anything? If app is handling deeplink anyway, why call `getDynamicLink`?

Thank you.

**Comment by samtstern** [comment]
@Ghedeon really sorry about the slow response here.  The `getDynamicLink()` method lets you examine the link that opened your app (if any).  If you're satisfied with just the app being opened to the right place then you're correct, there's nothing you need to do.

**Comment by ubuntudroid** [comment]
@samtstern sorry for digging this old thread out again, but would deeplink tracking still work without calling `Firebase.dynamicLinks.getDynamicLink(intent)`?

**Comment by ubuntudroid** [comment]
And: would the deeplink routing and tracking still work if the user didn't have the app installed when clicking on the dynamic link?

**Comment by samtstern** [comment]
@ubuntudroid as far as I know all of that will still work without calling `getDynamicLink`, but it's been a while since I played with these flows so I can't say I am 100% positive

**Comment by ubuntudroid** [comment]
@samtstern I just closely inspected the code and it looks like tracking won't work (at least not everything) when not calling `getDynamicLink()`. What I'm doing now: I call it in `onCreate()`, but don't handle it in any way and let default Android Intent handling and Navigation Components do the routing thing instead. That should do the trick.
