### ISSUE TITLE
Unable to use this service for Multiple Image upload

### ISSUE THREAD

**Issue by Xy-joe** [firebase/quickstart-android#994]
I'm using a library to load multiple images from the android device. This returns an `Arraylist<Images>` of the picture path Uri on the `OnActivityResult`. How then do I use the upload service to show something like Uploading 1 of 3 images on the backlground? Showing the progress as usual

**Comment by samtstern** [comment]
@Xy-joe sorry for general "how to" questions about writing your app please use StackOverflow or another Q&A forum.
